// Generated by scripts/megakernel/generate_v4_header.py. Do not edit.
#pragma once

#include <cstdint>

namespace deepspec::v4_generated {
inline constexpr int kPhaseCount = 94;
inline constexpr int kRootCount = 2;
inline constexpr int kStaticTaskCount = 5715;
inline constexpr uint16_t kNoStreamingConsumer = 0xFFFF;
inline constexpr int kWorkers = 152;
inline constexpr int kThreads = 256;
inline constexpr int kLocalQueueDepth = 16;
inline constexpr int kTraceCapacity = 2048;
inline constexpr int kTraceColumns = 8;
inline constexpr uint8_t kExecutionMain = 0;
inline constexpr uint8_t kExecutionEmbedding = 1;
inline constexpr uint8_t kExecutionMainKv = 2;
inline constexpr uint8_t kExecutionAttnHc = 3;
inline constexpr uint8_t kExecutionAttnProjection = 4;
inline constexpr uint8_t kExecutionSparseAttention = 5;
inline constexpr uint8_t kExecutionAttentionOutput = 6;
inline constexpr uint8_t kExecutionFfnHc = 7;
inline constexpr uint8_t kExecutionRouter = 8;
inline constexpr uint8_t kExecutionExpert = 9;
inline constexpr uint8_t kExecutionHead = 10;
inline constexpr uint8_t kExecutionTail = 11;
inline constexpr uint64_t kWorkspaceBytes = 7379456ULL;
inline constexpr uint64_t kDependencyOffset = 7352320ULL;
inline constexpr uint64_t kNextTileOffset = 7353600ULL;
inline constexpr uint64_t kCompletedTileOffset = 7354880ULL;
inline constexpr uint64_t kPublishEpochOffset = 7356160ULL;
inline constexpr uint64_t kReadyQueueOffset = 7357440ULL;
inline constexpr uint64_t kQueueStateOffset = 7367168ULL;
inline constexpr uint64_t kWorkerStateOffset = 7369728ULL;
inline constexpr int kWeightOffsetSlots = 4724;
inline constexpr int kGlobalWeightBase = 0;
inline constexpr int kLayerWeightBase = 2;
inline constexpr int kRoutedExpertWeightBase = 98;
inline constexpr int kSharedExpertWeightBase = 4706;
inline constexpr int kGlobalWeightSlots = 2;
inline constexpr int kLayerWeightSlots = 32;
inline constexpr int kExpertWeightSlots = 6;
inline constexpr int kRouterChainsPerItem = 8;
inline constexpr int kRouterRowsPerChain = 1;
inline constexpr unsigned long long kWeightArenaBytes = 14206958848ULL;
inline constexpr int kMainQuantPhase = 0;
inline constexpr int kMainProjectionPhase = 1;
inline constexpr int kMainReducePhase = 2;
inline constexpr int kMainNormPhase = 3;
inline constexpr int kEmbeddingPhase = 4;
inline constexpr int kMainProjectedQuantPhase = 5;
inline constexpr int kLayer0AttnHcProjectionPhase = 12;
inline constexpr int kLayer0AttnHcSinkhornPhase = 13;
inline constexpr int kLayer0AttnHcReduceNormPhase = 65535;
inline constexpr int kLayer0QaPhase = 14;
inline constexpr int kLayer0QaNormPhase = 15;
inline constexpr int kLayer0QbPhase = 16;
inline constexpr int kLayer0DraftKvProjectionPhase = 17;
inline constexpr int kLayer0QueryNormRopePhase = 18;
inline constexpr int kLayer0DraftKvFinalizePhase = 19;
inline constexpr int kLayer0SparseAttentionPhase = 20;
inline constexpr int kLayer0OutputAProjectionPhase = 21;
inline constexpr int kLayer0OutputBProjectionPhase = 22;
inline constexpr int kLayer0AttnPostPhase = 23;
inline constexpr int kLayer0FfnHcProjectionPhase = 24;
inline constexpr int kLayer0FfnHcSinkhornPhase = 25;
inline constexpr int kLayer0FfnHcReduceNormPhase = 65535;
inline constexpr int kLayer0RouterScorePhase = 26;
inline constexpr int kLayer0RouterTop6Phase = 27;
inline constexpr int kLayer0RoutedW13Phase = 28;
inline constexpr int kLayer0RoutedSwiGluPhase = 29;
inline constexpr int kLayer0RoutedW2Phase = 30;
inline constexpr int kLayer0SharedW13Phase = 31;
inline constexpr int kLayer0SharedSwiGluPhase = 32;
inline constexpr int kLayer0SharedW2Phase = 33;
inline constexpr int kLayer0ExpertCombinePhase = 34;
inline constexpr int kHeadReducePhase = 81;
inline constexpr int kPrefixSchedulerPhase = 65535;
inline constexpr int kExpertW1Slot = 0;
inline constexpr int kExpertW1ScaleSlot = 1;
inline constexpr int kExpertW2Slot = 2;
inline constexpr int kExpertW2ScaleSlot = 3;
inline constexpr int kExpertW3Slot = 4;
inline constexpr int kExpertW3ScaleSlot = 5;
inline constexpr int kMainProjWeightSlot = 24;
inline constexpr int kEmbeddingWeightSlot = 0;
inline constexpr int kMainProjScaleSlot = 25;
inline constexpr int kMainNormWeightSlot = 26;
inline constexpr int kLayer0AttnHcFnSlot = 2;
inline constexpr int kLayer0AttnHcBaseSlot = 3;
inline constexpr int kLayer0AttnHcScaleSlot = 4;
inline constexpr int kLayer0AttnNormWeightSlot = 8;
inline constexpr int kLayer0WqaWeightSlot = 11;
inline constexpr int kLayer0WqaScaleSlot = 12;
inline constexpr int kLayer0QaNormWeightSlot = 13;
inline constexpr int kLayer0WqbWeightSlot = 14;
inline constexpr int kLayer0WqbScaleSlot = 15;
inline constexpr int kLayer0WkvWeightSlot = 16;
inline constexpr int kLayer0WkvScaleSlot = 17;
inline constexpr int kLayer0KvNormWeightSlot = 18;
inline constexpr int kLayer0AttnSinkWeightSlot = 10;
inline constexpr int kLayer0WoaWeightSlot = 19;
inline constexpr int kLayer0WobWeightSlot = 20;
inline constexpr int kLayer0WobScaleSlot = 21;
inline constexpr int kLayer0FfnHcFnSlot = 5;
inline constexpr int kLayer0FfnHcBaseSlot = 6;
inline constexpr int kLayer0FfnHcScaleSlot = 7;
inline constexpr int kLayer0FfnNormWeightSlot = 9;
inline constexpr int kLayer0RouterWeightSlot = 22;
inline constexpr int kLayer0RouterBiasSlot = 23;
inline constexpr int kFinalNormWeightSlot = 91;
inline constexpr int kHcHeadFnWeightSlot = 92;
inline constexpr int kHcHeadBaseWeightSlot = 93;
inline constexpr int kHcHeadScaleWeightSlot = 94;
inline constexpr int kLmHeadWeightSlot = 1;
inline constexpr int kMarkovW1WeightSlot = 95;
inline constexpr int kMarkovW2WeightSlot = 96;
inline constexpr int kConfidenceWeightSlot = 97;
inline constexpr uint64_t kMainQuantizedOffset = 0ULL;
inline constexpr uint64_t kMainScaleOffset = 12288ULL;
inline constexpr uint64_t kMainPartialOffset = 12544ULL;
inline constexpr uint64_t kMainFp32Offset = 143616ULL;
inline constexpr uint64_t kMainRmsPartialOffset = 160000ULL;
inline constexpr uint64_t kMainProjectedOffset = 160256ULL;
inline constexpr uint64_t kMainProjectedQuantizedOffset = 168448ULL;
inline constexpr uint64_t kMainProjectedScaleOffset = 172544ULL;
inline constexpr uint64_t kMainKvPartialOffset = 172800ULL;
inline constexpr uint64_t kHiddenStreamsOffset = 197376ULL;
inline constexpr uint64_t kHcMixOffset = 364288ULL;
inline constexpr uint64_t kHcPreOffset = 364800ULL;
inline constexpr uint64_t kHcPostOffset = 365056ULL;
inline constexpr uint64_t kHcCombOffset = 365312ULL;
inline constexpr uint64_t kNormalizedHiddenOffset = 365824ULL;
inline constexpr uint64_t kAttnInputQuantizedOffset = 406784ULL;
inline constexpr uint64_t kAttnInputScaleOffset = 427264ULL;
inline constexpr uint64_t kQaPartialOffset = 427520ULL;
inline constexpr uint64_t kQloraOffset = 509440ULL;
inline constexpr uint64_t kQloraQuantizedOffset = 519680ULL;
inline constexpr uint64_t kQloraScaleOffset = 524800ULL;
inline constexpr uint64_t kQueryProjectionOffset = 525056ULL;
inline constexpr uint64_t kQueryInverseRmsOffset = 852736ULL;
inline constexpr uint64_t kQueriesOffset = 853504ULL;
inline constexpr uint64_t kDraftKvPartialOffset = 1181184ULL;
inline constexpr uint64_t kDraftKvOffset = 1222144ULL;
inline constexpr uint64_t kAttentionAccumulatorOffset = 1227264ULL;
inline constexpr uint64_t kAttentionRawOffset = 1882624ULL;
inline constexpr uint64_t kAttentionValuesOffset = 2210304ULL;
inline constexpr uint64_t kOutputLoraOffset = 2537984ULL;
inline constexpr uint64_t kOutputLoraQuantizedOffset = 2619904ULL;
inline constexpr uint64_t kOutputLoraScaleOffset = 2660864ULL;
inline constexpr uint64_t kAttentionOutputPartialOffset = 2661376ULL;
inline constexpr uint64_t kAttentionOutputOffset = 2989056ULL;
inline constexpr uint64_t kAttentionHiddenStreamsOffset = 3030016ULL;
inline constexpr uint64_t kFfnHcMixOffset = 3193856ULL;
inline constexpr uint64_t kFfnHcPreOffset = 3194368ULL;
inline constexpr uint64_t kFfnHcPostOffset = 3194624ULL;
inline constexpr uint64_t kFfnHcCombOffset = 3194880ULL;
inline constexpr uint64_t kFfnNormalizedHiddenOffset = 3195392ULL;
inline constexpr uint64_t kFfnInputQuantizedOffset = 3236352ULL;
inline constexpr uint64_t kFfnInputScaleOffset = 3256832ULL;
inline constexpr uint64_t kRouterScoreOffset = 3257088ULL;
inline constexpr uint64_t kRouterIndexOffset = 3262208ULL;
inline constexpr uint64_t kRouterWeightOffset = 3262464ULL;
inline constexpr uint64_t kRoutedW13Offset = 3262720ULL;
inline constexpr uint64_t kSharedW13Offset = 3508480ULL;
inline constexpr uint64_t kRoutedSwiGluOffset = 3549440ULL;
inline constexpr uint64_t kRoutedSwiGluQuantizedOffset = 3672320ULL;
inline constexpr uint64_t kRoutedSwiGluScaleOffset = 3733760ULL;
inline constexpr uint64_t kSharedSwiGluOffset = 3734272ULL;
inline constexpr uint64_t kSharedSwiGluQuantizedOffset = 3754752ULL;
inline constexpr uint64_t kSharedSwiGluScaleOffset = 3764992ULL;
inline constexpr uint64_t kRoutedOutputPartialOffset = 3765248ULL;
inline constexpr uint64_t kRoutedOutputOffset = 4011008ULL;
inline constexpr uint64_t kSharedOutputOffset = 4092928ULL;
inline constexpr uint64_t kHeadHiddenOffset = 4133888ULL;
inline constexpr uint64_t kHeadNormalizedOffset = 4174848ULL;
inline constexpr uint64_t kBaseLogitsOffset = 4215808ULL;
inline constexpr uint64_t kMarkovEmbeddingOffset = 6801408ULL;
inline constexpr uint64_t kMarkovLogitsOffset = 6803968ULL;
inline constexpr uint64_t kSoftmaxPartialMaxOffset = 7321088ULL;
inline constexpr uint64_t kSoftmaxPartialSumOffset = 7331328ULL;
inline constexpr uint64_t kSampleScanOffset = 7341568ULL;

static __device__ __constant__ uint16_t kMainKvProjectionPhases[3] = {
    6, 8, 10,
};

static __device__ __constant__ uint16_t kMainKvNormPhases[3] = {
    7, 9, 11,
};

static __device__ __constant__ uint16_t kMainKvWeightSlots[3] = {
    16, 48, 80,
};

static __device__ __constant__ uint16_t kMainKvScaleSlots[3] = {
    17, 49, 81,
};

static __device__ __constant__ uint16_t kMainKvNormWeightSlots[3] = {
    18, 50, 82,
};

static __device__ __constant__ uint16_t kAttnHcProjectionPhases[3] = {
    12, 35, 58,
};

static __device__ __constant__ uint16_t kAttnHcSinkhornPhases[3] = {
    13, 36, 59,
};

static __device__ __constant__ uint16_t kAttnHcReduceNormPhases[3] = {
    65535, 65535, 65535,
};

static __device__ __constant__ uint16_t kQaPhases[3] = {
    14, 37, 60,
};

static __device__ __constant__ uint16_t kQaNormPhases[3] = {
    15, 38, 61,
};

static __device__ __constant__ uint16_t kQbPhases[3] = {
    16, 39, 62,
};

static __device__ __constant__ uint16_t kDraftKvProjectionPhases[3] = {
    17, 40, 63,
};

static __device__ __constant__ uint16_t kQueryNormRopePhases[3] = {
    18, 41, 64,
};

static __device__ __constant__ uint16_t kDraftKvFinalizePhases[3] = {
    19, 42, 65,
};

static __device__ __constant__ uint16_t kSparseAttentionPhases[3] = {
    20, 43, 66,
};

static __device__ __constant__ uint16_t kOutputAProjectionPhases[3] = {
    21, 44, 67,
};

static __device__ __constant__ uint16_t kOutputBProjectionPhases[3] = {
    22, 45, 68,
};

static __device__ __constant__ uint16_t kAttnPostPhases[3] = {
    23, 46, 69,
};

static __device__ __constant__ uint16_t kFfnHcProjectionPhases[3] = {
    24, 47, 70,
};

static __device__ __constant__ uint16_t kFfnHcSinkhornPhases[3] = {
    25, 48, 71,
};

static __device__ __constant__ uint16_t kFfnHcReduceNormPhases[3] = {
    65535, 65535, 65535,
};

static __device__ __constant__ uint16_t kRouterScorePhases[3] = {
    26, 49, 72,
};

static __device__ __constant__ uint16_t kRouterTop6Phases[3] = {
    27, 50, 73,
};

static __device__ __constant__ uint16_t kRoutedW13Phases[3] = {
    28, 51, 74,
};

static __device__ __constant__ uint16_t kRoutedSwiGluPhases[3] = {
    29, 52, 75,
};

static __device__ __constant__ uint16_t kRoutedW2Phases[3] = {
    30, 53, 76,
};

static __device__ __constant__ uint16_t kSharedW13Phases[3] = {
    31, 54, 77,
};

static __device__ __constant__ uint16_t kSharedSwiGluPhases[3] = {
    32, 55, 78,
};

static __device__ __constant__ uint16_t kSharedW2Phases[3] = {
    33, 56, 79,
};

static __device__ __constant__ uint16_t kExpertCombinePhases[3] = {
    34, 57, 80,
};

static __device__ __constant__ uint16_t kLmRowPhases[5] = {
    82, 82, 82, 82, 82,
};

static __device__ __constant__ uint16_t kMarkovGatherPhases[5] = {
    83, 85, 87, 89, 91,
};

static __device__ __constant__ uint16_t kConfidencePhases[5] = {
    65535, 65535, 65535, 65535, 65535,
};

static __device__ __constant__ uint16_t kMarkovW2Phases[5] = {
    84, 86, 88, 90, 92,
};

static __device__ __constant__ uint16_t kCorrectLogitPhases[5] = {
    65535, 65535, 65535, 65535, 65535,
};

static __device__ __constant__ uint16_t kSoftmaxExpSumPhases[5] = {
    65535, 65535, 65535, 65535, 65535,
};

static __device__ __constant__ uint16_t kSumReducePhases[5] = {
    65535, 65535, 65535, 65535, 65535,
};

static __device__ __constant__ uint16_t kNormalizeSamplePhases[5] = {
    65535, 65535, 65535, 65535, 65535,
};

static __device__ __constant__ uint16_t kAttnHcFnSlots[3] = {
    2, 34, 66,
};

static __device__ __constant__ uint16_t kAttnHcBaseSlots[3] = {
    3, 35, 67,
};

static __device__ __constant__ uint16_t kAttnHcScaleSlots[3] = {
    4, 36, 68,
};

static __device__ __constant__ uint16_t kAttnNormWeightSlots[3] = {
    8, 40, 72,
};

static __device__ __constant__ uint16_t kWqaWeightSlots[3] = {
    11, 43, 75,
};

static __device__ __constant__ uint16_t kWqaScaleSlots[3] = {
    12, 44, 76,
};

static __device__ __constant__ uint16_t kQaNormWeightSlots[3] = {
    13, 45, 77,
};

static __device__ __constant__ uint16_t kWqbWeightSlots[3] = {
    14, 46, 78,
};

static __device__ __constant__ uint16_t kWqbScaleSlots[3] = {
    15, 47, 79,
};

static __device__ __constant__ uint16_t kDraftWkvWeightSlots[3] = {
    16, 48, 80,
};

static __device__ __constant__ uint16_t kDraftWkvScaleSlots[3] = {
    17, 49, 81,
};

static __device__ __constant__ uint16_t kDraftKvNormWeightSlots[3] = {
    18, 50, 82,
};

static __device__ __constant__ uint16_t kAttnSinkWeightSlots[3] = {
    10, 42, 74,
};

static __device__ __constant__ uint16_t kWoaWeightSlots[3] = {
    19, 51, 83,
};

static __device__ __constant__ uint16_t kWobWeightSlots[3] = {
    20, 52, 84,
};

static __device__ __constant__ uint16_t kWobScaleSlots[3] = {
    21, 53, 85,
};

static __device__ __constant__ uint16_t kFfnHcFnSlots[3] = {
    5, 37, 69,
};

static __device__ __constant__ uint16_t kFfnHcBaseSlots[3] = {
    6, 38, 70,
};

static __device__ __constant__ uint16_t kFfnHcScaleSlots[3] = {
    7, 39, 71,
};

static __device__ __constant__ uint16_t kFfnNormWeightSlots[3] = {
    9, 41, 73,
};

static __device__ __constant__ uint16_t kRouterWeightSlots[3] = {
    22, 54, 86,
};

static __device__ __constant__ uint16_t kRouterBiasSlots[3] = {
    23, 55, 87,
};

static __device__ __constant__ uint16_t kRoutedExpertWeightBases[3] = {
    98, 1634, 3170,
};

static __device__ __constant__ uint16_t kSharedExpertWeightBases[3] = {
    4706, 4712, 4718,
};

static __device__ __constant__ uint16_t kRoots[2] = {
    0, 4,
};

static __device__ __constant__ uint32_t kWorkUnits[94] = {
    96, 256, 8, 8, 160, 32, 16, 1, 16, 1, 16, 1,
    120, 5, 32, 5, 256, 16, 40, 5, 40, 64, 128, 40,
    120, 5, 160, 5, 960, 240, 960, 32, 20, 32, 160, 120,
    5, 32, 5, 256, 16, 40, 5, 40, 64, 128, 40, 120,
    5, 160, 5, 960, 240, 960, 32, 20, 32, 160, 120, 5,
    32, 5, 256, 16, 40, 5, 40, 64, 128, 40, 120, 5,
    160, 5, 960, 240, 960, 32, 20, 32, 160, 5, 1010, 1,
    1010, 1, 1010, 1, 1010, 1, 1010, 1, 1010, 1,
};

static __device__ __constant__ uint8_t kClaimChunks[94] = {
    1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 2, 1, 4, 1, 4, 1, 1, 1, 2, 1,
    1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 2, 1, 4, 1, 4, 1, 1, 1, 2, 1, 1,
    1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    2, 1, 4, 1, 4, 1, 1, 1, 2, 1, 7, 1,
    7, 1, 7, 1, 7, 1, 7, 1, 7, 1,
};

static __device__ __constant__ uint8_t kExecutionGroups[94] = {
    0, 0, 0, 0, 1, 2, 2, 2, 2, 2, 2, 2,
    3, 3, 4, 4, 4, 4, 4, 4, 5, 6, 6, 6,
    7, 7, 8, 8, 9, 9, 9, 9, 9, 9, 9, 3,
    3, 4, 4, 4, 4, 4, 4, 5, 6, 6, 6, 7,
    7, 8, 8, 9, 9, 9, 9, 9, 9, 9, 3, 3,
    4, 4, 4, 4, 4, 4, 5, 6, 6, 6, 7, 7,
    8, 8, 9, 9, 9, 9, 9, 9, 9, 10, 10, 11,
    11, 11, 11, 11, 11, 11, 11, 11, 11, 11,
};

static __device__ __constant__ uint8_t kPhaseLayers[94] = {
    255, 255, 255, 255, 255, 255, 0, 0, 1, 1, 2, 2,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
    2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
    2, 2, 2, 2, 2, 2, 2, 2, 2, 255, 255, 255,
    255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
};

static __device__ __constant__ uint16_t kStaticWorkerTaskOffsets[153] = {
    0, 74, 143, 212, 281, 350, 408, 466, 524, 582, 640, 698,
    756, 814, 870, 926, 982, 1038, 1094, 1150, 1206, 1259, 1312, 1365,
    1418, 1468, 1518, 1568, 1618, 1668, 1718, 1768, 1818, 1869, 1920, 1971,
    2022, 2073, 2124, 2175, 2226, 2268, 2310, 2352, 2394, 2436, 2478, 2520,
    2562, 2603, 2644, 2685, 2726, 2767, 2808, 2849, 2890, 2931, 2972, 3013,
    3054, 3095, 3136, 3177, 3218, 3255, 3292, 3329, 3366, 3403, 3440, 3477,
    3514, 3551, 3588, 3625, 3662, 3699, 3736, 3773, 3810, 3841, 3872, 3903,
    3934, 3965, 3996, 4027, 4058, 4089, 4120, 4151, 4182, 4213, 4244, 4275,
    4306, 4337, 4368, 4399, 4430, 4461, 4492, 4523, 4554, 4585, 4616, 4647,
    4678, 4709, 4740, 4771, 4802, 4833, 4864, 4895, 4926, 4957, 4988, 5019,
    5050, 5073, 5096, 5119, 5142, 5165, 5188, 5211, 5234, 5259, 5283, 5307,
    5331, 5355, 5377, 5399, 5421, 5443, 5465, 5487, 5509, 5531, 5553, 5575,
    5597, 5619, 5634, 5648, 5662, 5676, 5689, 5702, 5715,
};

static __device__ __constant__ uint16_t kStaticTaskPhases[5715] = {
    0, 4, 12, 12, 12, 12, 13, 14, 15, 16, 18, 20,
    21, 22, 23, 24, 25, 26, 27, 28, 28, 32, 33, 34,
    35, 36, 37, 38, 39, 41, 43, 44, 45, 46, 47, 48,
    49, 50, 51, 51, 55, 56, 57, 58, 59, 60, 61, 62,
    64, 66, 67, 68, 69, 70, 71, 72, 73, 74, 74, 78,
    79, 80, 81, 82, 84, 85, 86, 87, 88, 89, 90, 91,
    92, 93, 0, 4, 12, 12, 12, 12, 13, 14, 15, 16,
    18, 20, 21, 22, 23, 24, 25, 26, 27, 28, 28, 32,
    33, 34, 35, 36, 37, 38, 39, 41, 43, 44, 45, 46,
    47, 48, 49, 50, 51, 51, 55, 56, 57, 58, 59, 60,
    61, 62, 64, 66, 67, 68, 69, 70, 71, 72, 73, 74,
    74, 78, 79, 80, 81, 82, 84, 86, 88, 90, 92, 0,
    4, 12, 12, 12, 12, 13, 14, 15, 16, 18, 20, 21,
    22, 23, 24, 25, 26, 27, 28, 28, 32, 33, 34, 35,
    36, 37, 38, 39, 41, 43, 44, 45, 46, 47, 48, 49,
    50, 51, 51, 55, 56, 57, 58, 59, 60, 61, 62, 64,
    66, 67, 68, 69, 70, 71, 72, 73, 74, 74, 78, 79,
    80, 81, 82, 84, 86, 88, 90, 92, 0, 4, 12, 12,
    12, 12, 13, 14, 15, 16, 18, 20, 21, 22, 23, 24,
    25, 26, 27, 28, 28, 32, 33, 34, 35, 36, 37, 38,
    39, 41, 43, 44, 45, 46, 47, 48, 49, 50, 51, 51,
    55, 56, 57, 58, 59, 60, 61, 62, 64, 66, 67, 68,
    69, 70, 71, 72, 73, 74, 74, 78, 79, 80, 81, 82,
    84, 86, 88, 90, 92, 0, 4, 12, 12, 12, 12, 13,
    14, 15, 16, 18, 20, 21, 22, 23, 24, 25, 26, 27,
    28, 28, 32, 33, 34, 35, 36, 37, 38, 39, 41, 43,
    44, 45, 46, 47, 48, 49, 50, 51, 51, 55, 56, 57,
    58, 59, 60, 61, 62, 64, 66, 67, 68, 69, 70, 71,
    72, 73, 74, 74, 78, 79, 80, 81, 82, 84, 86, 88,
    90, 92, 0, 4, 12, 12, 12, 12, 2, 3, 14, 16,
    18, 20, 21, 22, 23, 24, 26, 28, 28, 32, 33, 34,
    35, 37, 39, 41, 43, 44, 45, 46, 47, 49, 51, 51,
    55, 56, 57, 58, 60, 62, 64, 66, 67, 68, 69, 70,
    72, 74, 74, 78, 79, 80, 82, 84, 86, 88, 90, 92,
    0, 4, 12, 12, 12, 12, 2, 3, 14, 16, 18, 20,
    21, 22, 23, 24, 26, 28, 28, 32, 33, 34, 35, 37,
    39, 41, 43, 44, 45, 46, 47, 49, 51, 51, 55, 56,
    57, 58, 60, 62, 64, 66, 67, 68, 69, 70, 72, 74,
    74, 78, 79, 80, 82, 84, 86, 88, 90, 92, 0, 4,
    12, 12, 12, 12, 2, 3, 14, 16, 18, 20, 21, 22,
    23, 24, 26, 28, 28, 32, 33, 34, 35, 37, 39, 41,
    43, 44, 45, 46, 47, 49, 51, 51, 55, 56, 57, 58,
    60, 62, 64, 66, 67, 68, 69, 70, 72, 74, 74, 78,
    79, 80, 82, 84, 86, 88, 90, 92, 0, 4, 12, 12,
    12, 12, 2, 3, 14, 16, 18, 20, 21, 22, 23, 24,
    26, 28, 28, 32, 33, 34, 35, 37, 39, 41, 43, 44,
    45, 46, 47, 49, 51, 51, 55, 56, 57, 58, 60, 62,
    64, 66, 67, 68, 69, 70, 72, 74, 74, 78, 79, 80,
    82, 84, 86, 88, 90, 92, 0, 4, 12, 12, 12, 12,
    2, 3, 14, 16, 18, 20, 21, 22, 23, 24, 26, 28,
    28, 32, 33, 34, 35, 37, 39, 41, 43, 44, 45, 46,
    47, 49, 51, 51, 55, 56, 57, 58, 60, 62, 64, 66,
    67, 68, 69, 70, 72, 74, 74, 78, 79, 80, 82, 84,
    86, 88, 90, 92, 0, 4, 12, 12, 12, 12, 2, 3,
    14, 16, 18, 20, 21, 22, 23, 24, 26, 28, 28, 32,
    33, 34, 35, 37, 39, 41, 43, 44, 45, 46, 47, 49,
    51, 51, 55, 56, 57, 58, 60, 62, 64, 66, 67, 68,
    69, 70, 72, 74, 74, 78, 79, 80, 82, 84, 86, 88,
    90, 92, 0, 4, 12, 12, 12, 12, 2, 3, 14, 16,
    18, 20, 21, 22, 23, 24, 26, 28, 28, 32, 33, 34,
    35, 37, 39, 41, 43, 44, 45, 46, 47, 49, 51, 51,
    55, 56, 57, 58, 60, 62, 64, 66, 67, 68, 69, 70,
    72, 74, 74, 78, 79, 80, 82, 84, 86, 88, 90, 92,
    0, 4, 12, 12, 12, 12, 2, 3, 14, 16, 18, 20,
    21, 22, 23, 24, 26, 28, 28, 32, 33, 34, 35, 37,
    39, 41, 43, 44, 45, 46, 47, 49, 51, 51, 55, 56,
    57, 58, 60, 62, 64, 66, 67, 68, 69, 70, 72, 74,
    74, 78, 79, 80, 82, 84, 86, 88, 90, 92, 0, 4,
    12, 12, 12, 12, 14, 16, 18, 20, 21, 22, 23, 24,
    26, 28, 28, 32, 33, 34, 35, 37, 39, 41, 43, 44,
    45, 46, 47, 49, 51, 51, 55, 56, 57, 58, 60, 62,
    64, 66, 67, 68, 69, 70, 72, 74, 74, 78, 79, 80,
    82, 84, 86, 88, 90, 92, 0, 4, 12, 12, 12, 12,
    14, 16, 18, 20, 21, 22, 23, 24, 26, 28, 28, 32,
    33, 34, 35, 37, 39, 41, 43, 44, 45, 46, 47, 49,
    51, 51, 55, 56, 57, 58, 60, 62, 64, 66, 67, 68,
    69, 70, 72, 74, 74, 78, 79, 80, 82, 84, 86, 88,
    90, 92, 0, 4, 12, 12, 12, 12, 14, 16, 18, 20,
    21, 22, 23, 24, 26, 28, 28, 32, 33, 34, 35, 37,
    39, 41, 43, 44, 45, 46, 47, 49, 51, 51, 55, 56,
    57, 58, 60, 62, 64, 66, 67, 68, 69, 70, 72, 74,
    74, 78, 79, 80, 82, 84, 86, 88, 90, 92, 0, 4,
    12, 12, 12, 12, 14, 16, 18, 20, 21, 22, 23, 24,
    26, 28, 28, 32, 33, 34, 35, 37, 39, 41, 43, 44,
    45, 46, 47, 49, 51, 51, 55, 56, 57, 58, 60, 62,
    64, 66, 67, 68, 69, 70, 72, 74, 74, 78, 79, 80,
    82, 84, 86, 88, 90, 92, 0, 4, 12, 12, 12, 12,
    14, 16, 18, 20, 21, 22, 23, 24, 26, 28, 28, 32,
    33, 34, 35, 37, 39, 41, 43, 44, 45, 46, 47, 49,
    51, 51, 55, 56, 57, 58, 60, 62, 64, 66, 67, 68,
    69, 70, 72, 74, 74, 78, 79, 80, 82, 84, 86, 88,
    90, 92, 0, 4, 12, 12, 12, 12, 14, 16, 18, 20,
    21, 22, 23, 24, 26, 28, 28, 32, 33, 34, 35, 37,
    39, 41, 43, 44, 45, 46, 47, 49, 51, 51, 55, 56,
    57, 58, 60, 62, 64, 66, 67, 68, 69, 70, 72, 74,
    74, 78, 79, 80, 82, 84, 86, 88, 90, 92, 0, 4,
    12, 12, 12, 12, 14, 16, 18, 20, 21, 22, 23, 24,
    26, 28, 28, 32, 33, 34, 35, 37, 39, 41, 43, 44,
    45, 46, 47, 49, 51, 51, 55, 56, 57, 58, 60, 62,
    64, 66, 67, 68, 69, 70, 72, 74, 74, 78, 79, 80,
    82, 84, 86, 88, 90, 92, 0, 4, 12, 12, 12, 12,
    14, 16, 18, 20, 21, 22, 23, 24, 26, 28, 28, 33,
    34, 35, 37, 39, 41, 43, 44, 45, 46, 47, 49, 51,
    51, 56, 57, 58, 60, 62, 64, 66, 67, 68, 69, 70,
    72, 74, 74, 79, 80, 82, 84, 86, 88, 90, 92, 0,
    4, 12, 12, 12, 12, 14, 16, 18, 20, 21, 22, 23,
    24, 26, 28, 28, 33, 34, 35, 37, 39, 41, 43, 44,
    45, 46, 47, 49, 51, 51, 56, 57, 58, 60, 62, 64,
    66, 67, 68, 69, 70, 72, 74, 74, 79, 80, 82, 84,
    86, 88, 90, 92, 0, 4, 12, 12, 12, 12, 14, 16,
    18, 20, 21, 22, 23, 24, 26, 28, 28, 33, 34, 35,
    37, 39, 41, 43, 44, 45, 46, 47, 49, 51, 51, 56,
    57, 58, 60, 62, 64, 66, 67, 68, 69, 70, 72, 74,
    74, 79, 80, 82, 84, 86, 88, 90, 92, 0, 4, 12,
    12, 12, 12, 14, 16, 18, 20, 21, 22, 23, 24, 26,
    28, 28, 33, 34, 35, 37, 39, 41, 43, 44, 45, 46,
    47, 49, 51, 51, 56, 57, 58, 60, 62, 64, 66, 67,
    68, 69, 70, 72, 74, 74, 79, 80, 82, 84, 86, 88,
    90, 92, 0, 1, 12, 14, 16, 18, 20, 21, 22, 23,
    24, 26, 28, 28, 33, 34, 35, 37, 39, 41, 43, 44,
    45, 46, 47, 49, 51, 51, 56, 57, 58, 60, 62, 64,
    66, 67, 68, 69, 70, 72, 74, 74, 79, 80, 82, 84,
    86, 88, 90, 92, 0, 1, 12, 14, 16, 18, 20, 21,
    22, 23, 24, 26, 28, 28, 33, 34, 35, 37, 39, 41,
    43, 44, 45, 46, 47, 49, 51, 51, 56, 57, 58, 60,
    62, 64, 66, 67, 68, 69, 70, 72, 74, 74, 79, 80,
    82, 84, 86, 88, 90, 92, 0, 1, 12, 14, 16, 18,
    20, 21, 22, 23, 24, 26, 28, 28, 33, 34, 35, 37,
    39, 41, 43, 44, 45, 46, 47, 49, 51, 51, 56, 57,
    58, 60, 62, 64, 66, 67, 68, 69, 70, 72, 74, 74,
    79, 80, 82, 84, 86, 88, 90, 92, 0, 1, 12, 14,
    16, 18, 20, 21, 22, 23, 24, 26, 28, 28, 33, 34,
    35, 37, 39, 41, 43, 44, 45, 46, 47, 49, 51, 51,
    56, 57, 58, 60, 62, 64, 66, 67, 68, 69, 70, 72,
    74, 74, 79, 80, 82, 84, 86, 88, 90, 92, 0, 1,
    12, 14, 16, 18, 20, 21, 22, 23, 24, 26, 28, 28,
    33, 34, 35, 37, 39, 41, 43, 44, 45, 46, 47, 49,
    51, 51, 56, 57, 58, 60, 62, 64, 66, 67, 68, 69,
    70, 72, 74, 74, 79, 80, 82, 84, 86, 88, 90, 92,
    0, 1, 12, 14, 16, 18, 20, 21, 22, 23, 24, 26,
    28, 28, 33, 34, 35, 37, 39, 41, 43, 44, 45, 46,
    47, 49, 51, 51, 56, 57, 58, 60, 62, 64, 66, 67,
    68, 69, 70, 72, 74, 74, 79, 80, 82, 84, 86, 88,
    90, 92, 0, 1, 12, 14, 16, 18, 20, 21, 22, 23,
    24, 26, 28, 28, 33, 34, 35, 37, 39, 41, 43, 44,
    45, 46, 47, 49, 51, 51, 56, 57, 58, 60, 62, 64,
    66, 67, 68, 69, 70, 72, 74, 74, 79, 80, 82, 84,
    86, 88, 90, 92, 0, 1, 12, 14, 16, 18, 20, 21,
    22, 23, 24, 26, 28, 28, 33, 34, 35, 37, 39, 41,
    43, 44, 45, 46, 47, 49, 51, 51, 56, 57, 58, 60,
    62, 64, 66, 67, 68, 69, 70, 72, 74, 74, 79, 80,
    82, 84, 86, 88, 90, 92, 0, 1, 12, 5, 16, 18,
    20, 21, 22, 23, 24, 26, 28, 28, 30, 30, 34, 35,
    39, 41, 43, 44, 45, 46, 47, 49, 51, 51, 53, 53,
    57, 58, 62, 64, 66, 67, 68, 69, 70, 72, 74, 74,
    76, 76, 80, 82, 84, 86, 88, 90, 92, 0, 1, 12,
    5, 16, 18, 20, 21, 22, 23, 24, 26, 28, 28, 30,
    30, 34, 35, 39, 41, 43, 44, 45, 46, 47, 49, 51,
    51, 53, 53, 57, 58, 62, 64, 66, 67, 68, 69, 70,
    72, 74, 74, 76, 76, 80, 82, 84, 86, 88, 90, 92,
    0, 1, 12, 5, 16, 18, 20, 21, 22, 23, 24, 26,
    28, 28, 30, 30, 34, 35, 39, 41, 43, 44, 45, 46,
    47, 49, 51, 51, 53, 53, 57, 58, 62, 64, 66, 67,
    68, 69, 70, 72, 74, 74, 76, 76, 80, 82, 84, 86,
    88, 90, 92, 0, 1, 12, 5, 16, 18, 20, 21, 22,
    23, 24, 26, 28, 28, 30, 30, 34, 35, 39, 41, 43,
    44, 45, 46, 47, 49, 51, 51, 53, 53, 57, 58, 62,
    64, 66, 67, 68, 69, 70, 72, 74, 74, 76, 76, 80,
    82, 84, 86, 88, 90, 92, 0, 1, 12, 5, 16, 18,
    20, 21, 22, 23, 24, 26, 28, 28, 30, 30, 34, 35,
    39, 41, 43, 44, 45, 46, 47, 49, 51, 51, 53, 53,
    57, 58, 62, 64, 66, 67, 68, 69, 70, 72, 74, 74,
    76, 76, 80, 82, 84, 86, 88, 90, 92, 0, 1, 12,
    5, 16, 18, 20, 21, 22, 23, 24, 26, 28, 28, 30,
    30, 34, 35, 39, 41, 43, 44, 45, 46, 47, 49, 51,
    51, 53, 53, 57, 58, 62, 64, 66, 67, 68, 69, 70,
    72, 74, 74, 76, 76, 80, 82, 84, 86, 88, 90, 92,
    0, 1, 12, 5, 16, 18, 20, 21, 22, 23, 24, 26,
    28, 28, 30, 30, 34, 35, 39, 41, 43, 44, 45, 46,
    47, 49, 51, 51, 53, 53, 57, 58, 62, 64, 66, 67,
    68, 69, 70, 72, 74, 74, 76, 76, 80, 82, 84, 86,
    88, 90, 92, 0, 1, 12, 5, 16, 18, 20, 21, 22,
    23, 24, 26, 28, 28, 30, 30, 34, 35, 39, 41, 43,
    44, 45, 46, 47, 49, 51, 51, 53, 53, 57, 58, 62,
    64, 66, 67, 68, 69, 70, 72, 74, 74, 76, 76, 80,
    82, 84, 86, 88, 90, 92, 0, 1, 12, 5, 16, 21,
    22, 24, 26, 28, 28, 30, 30, 34, 35, 39, 44, 45,
    47, 49, 51, 51, 53, 53, 57, 58, 62, 67, 68, 70,
    72, 74, 74, 76, 76, 80, 82, 84, 86, 88, 90, 92,
    0, 1, 12, 5, 16, 21, 22, 24, 26, 28, 28, 30,
    30, 34, 35, 39, 44, 45, 47, 49, 51, 51, 53, 53,
    57, 58, 62, 67, 68, 70, 72, 74, 74, 76, 76, 80,
    82, 84, 86, 88, 90, 92, 0, 1, 12, 5, 16, 21,
    22, 24, 26, 28, 28, 30, 30, 34, 35, 39, 44, 45,
    47, 49, 51, 51, 53, 53, 57, 58, 62, 67, 68, 70,
    72, 74, 74, 76, 76, 80, 82, 84, 86, 88, 90, 92,
    0, 1, 12, 5, 16, 21, 22, 24, 26, 28, 28, 30,
    30, 34, 35, 39, 44, 45, 47, 49, 51, 51, 53, 53,
    57, 58, 62, 67, 68, 70, 72, 74, 74, 76, 76, 80,
    82, 84, 86, 88, 90, 92, 0, 1, 12, 5, 16, 21,
    22, 24, 26, 28, 28, 30, 30, 34, 35, 39, 44, 45,
    47, 49, 51, 51, 53, 53, 57, 58, 62, 67, 68, 70,
    72, 74, 74, 76, 76, 80, 82, 84, 86, 88, 90, 92,
    0, 1, 12, 5, 16, 21, 22, 24, 26, 28, 28, 30,
    30, 34, 35, 39, 44, 45, 47, 49, 51, 51, 53, 53,
    57, 58, 62, 67, 68, 70, 72, 74, 74, 76, 76, 80,
    82, 84, 86, 88, 90, 92, 0, 1, 12, 5, 16, 21,
    22, 24, 26, 28, 28, 30, 30, 34, 35, 39, 44, 45,
    47, 49, 51, 51, 53, 53, 57, 58, 62, 67, 68, 70,
    72, 74, 74, 76, 76, 80, 82, 84, 86, 88, 90, 92,
    0, 1, 12, 5, 16, 21, 22, 24, 26, 28, 28, 30,
    30, 34, 35, 39, 44, 45, 47, 49, 51, 51, 53, 53,
    57, 58, 62, 67, 68, 70, 72, 74, 74, 76, 76, 80,
    82, 84, 86, 88, 90, 92, 0, 1, 5, 16, 21, 22,
    24, 26, 28, 28, 30, 30, 34, 35, 39, 44, 45, 47,
    49, 51, 51, 53, 53, 57, 58, 62, 67, 68, 70, 72,
    74, 74, 76, 76, 80, 82, 84, 86, 88, 90, 92, 0,
    1, 5, 16, 21, 22, 24, 26, 28, 28, 30, 30, 34,
    35, 39, 44, 45, 47, 49, 51, 51, 53, 53, 57, 58,
    62, 67, 68, 70, 72, 74, 74, 76, 76, 80, 82, 84,
    86, 88, 90, 92, 0, 1, 5, 16, 21, 22, 24, 26,
    28, 28, 30, 30, 34, 35, 39, 44, 45, 47, 49, 51,
    51, 53, 53, 57, 58, 62, 67, 68, 70, 72, 74, 74,
    76, 76, 80, 82, 84, 86, 88, 90, 92, 0, 1, 5,
    16, 21, 22, 24, 26, 28, 28, 30, 30, 34, 35, 39,
    44, 45, 47, 49, 51, 51, 53, 53, 57, 58, 62, 67,
    68, 70, 72, 74, 74, 76, 76, 80, 82, 84, 86, 88,
    90, 92, 0, 1, 5, 16, 21, 22, 24, 26, 28, 28,
    30, 30, 34, 35, 39, 44, 45, 47, 49, 51, 51, 53,
    53, 57, 58, 62, 67, 68, 70, 72, 74, 74, 76, 76,
    80, 82, 84, 86, 88, 90, 92, 0, 1, 5, 16, 21,
    22, 24, 26, 28, 28, 30, 30, 34, 35, 39, 44, 45,
    47, 49, 51, 51, 53, 53, 57, 58, 62, 67, 68, 70,
    72, 74, 74, 76, 76, 80, 82, 84, 86, 88, 90, 92,
    0, 1, 5, 16, 21, 22, 24, 26, 28, 28, 30, 30,
    34, 35, 39, 44, 45, 47, 49, 51, 51, 53, 53, 57,
    58, 62, 67, 68, 70, 72, 74, 74, 76, 76, 80, 82,
    84, 86, 88, 90, 92, 0, 1, 5, 16, 21, 22, 24,
    26, 28, 28, 30, 30, 34, 35, 39, 44, 45, 47, 49,
    51, 51, 53, 53, 57, 58, 62, 67, 68, 70, 72, 74,
    74, 76, 76, 80, 82, 84, 86, 88, 90, 92, 0, 1,
    5, 16, 21, 22, 24, 26, 28, 28, 30, 30, 34, 35,
    39, 44, 45, 47, 49, 51, 51, 53, 53, 57, 58, 62,
    67, 68, 70, 72, 74, 74, 76, 76, 80, 82, 84, 86,
    88, 90, 92, 0, 1, 5, 16, 21, 22, 24, 26, 28,
    28, 30, 30, 34, 35, 39, 44, 45, 47, 49, 51, 51,
    53, 53, 57, 58, 62, 67, 68, 70, 72, 74, 74, 76,
    76, 80, 82, 84, 86, 88, 90, 92, 0, 1, 5, 16,
    21, 22, 24, 26, 28, 28, 30, 30, 34, 35, 39, 44,
    45, 47, 49, 51, 51, 53, 53, 57, 58, 62, 67, 68,
    70, 72, 74, 74, 76, 76, 80, 82, 84, 86, 88, 90,
    92, 0, 1, 5, 16, 21, 22, 24, 26, 28, 28, 30,
    30, 34, 35, 39, 44, 45, 47, 49, 51, 51, 53, 53,
    57, 58, 62, 67, 68, 70, 72, 74, 74, 76, 76, 80,
    82, 84, 86, 88, 90, 92, 0, 1, 5, 16, 21, 22,
    24, 26, 28, 28, 30, 30, 34, 35, 39, 44, 45, 47,
    49, 51, 51, 53, 53, 57, 58, 62, 67, 68, 70, 72,
    74, 74, 76, 76, 80, 82, 84, 86, 88, 90, 92, 0,
    1, 5, 16, 21, 22, 24, 26, 28, 28, 30, 30, 34,
    35, 39, 44, 45, 47, 49, 51, 51, 53, 53, 57, 58,
    62, 67, 68, 70, 72, 74, 74, 76, 76, 80, 82, 84,
    86, 88, 90, 92, 0, 1, 5, 16, 21, 22, 24, 26,
    28, 28, 30, 30, 34, 35, 39, 44, 45, 47, 49, 51,
    51, 53, 53, 57, 58, 62, 67, 68, 70, 72, 74, 74,
    76, 76, 80, 82, 84, 86, 88, 90, 92, 0, 1, 5,
    16, 21, 22, 24, 26, 28, 28, 30, 30, 34, 35, 39,
    44, 45, 47, 49, 51, 51, 53, 53, 57, 58, 62, 67,
    68, 70, 72, 74, 74, 76, 76, 80, 82, 84, 86, 88,
    90, 92, 0, 1, 16, 22, 24, 26, 28, 28, 30, 30,
    34, 35, 39, 45, 47, 49, 51, 51, 53, 53, 57, 58,
    62, 68, 70, 72, 74, 74, 76, 76, 80, 82, 84, 86,
    88, 90, 92, 0, 1, 16, 22, 24, 26, 28, 28, 30,
    30, 34, 35, 39, 45, 47, 49, 51, 51, 53, 53, 57,
    58, 62, 68, 70, 72, 74, 74, 76, 76, 80, 82, 84,
    86, 88, 90, 92, 0, 1, 16, 22, 24, 26, 28, 28,
    30, 30, 34, 35, 39, 45, 47, 49, 51, 51, 53, 53,
    57, 58, 62, 68, 70, 72, 74, 74, 76, 76, 80, 82,
    84, 86, 88, 90, 92, 0, 1, 16, 22, 24, 26, 28,
    28, 30, 30, 34, 35, 39, 45, 47, 49, 51, 51, 53,
    53, 57, 58, 62, 68, 70, 72, 74, 74, 76, 76, 80,
    82, 84, 86, 88, 90, 92, 0, 1, 16, 22, 24, 26,
    28, 28, 30, 30, 34, 35, 39, 45, 47, 49, 51, 51,
    53, 53, 57, 58, 62, 68, 70, 72, 74, 74, 76, 76,
    80, 82, 84, 86, 88, 90, 92, 0, 1, 16, 22, 24,
    26, 28, 28, 30, 30, 34, 35, 39, 45, 47, 49, 51,
    51, 53, 53, 57, 58, 62, 68, 70, 72, 74, 74, 76,
    76, 80, 82, 84, 86, 88, 90, 92, 0, 1, 16, 22,
    24, 26, 28, 28, 30, 30, 34, 35, 39, 45, 47, 49,
    51, 51, 53, 53, 57, 58, 62, 68, 70, 72, 74, 74,
    76, 76, 80, 82, 84, 86, 88, 90, 92, 0, 1, 16,
    22, 24, 26, 28, 28, 30, 30, 34, 35, 39, 45, 47,
    49, 51, 51, 53, 53, 57, 58, 62, 68, 70, 72, 74,
    74, 76, 76, 80, 82, 84, 86, 88, 90, 92, 0, 1,
    16, 22, 24, 26, 28, 28, 30, 30, 34, 35, 39, 45,
    47, 49, 51, 51, 53, 53, 57, 58, 62, 68, 70, 72,
    74, 74, 76, 76, 80, 82, 84, 86, 88, 90, 92, 0,
    1, 16, 22, 24, 26, 28, 28, 30, 30, 34, 35, 39,
    45, 47, 49, 51, 51, 53, 53, 57, 58, 62, 68, 70,
    72, 74, 74, 76, 76, 80, 82, 84, 86, 88, 90, 92,
    0, 1, 16, 22, 24, 26, 28, 28, 30, 30, 34, 35,
    39, 45, 47, 49, 51, 51, 53, 53, 57, 58, 62, 68,
    70, 72, 74, 74, 76, 76, 80, 82, 84, 86, 88, 90,
    92, 0, 1, 16, 22, 24, 26, 28, 28, 30, 30, 34,
    35, 39, 45, 47, 49, 51, 51, 53, 53, 57, 58, 62,
    68, 70, 72, 74, 74, 76, 76, 80, 82, 84, 86, 88,
    90, 92, 0, 1, 16, 22, 24, 26, 28, 28, 30, 30,
    34, 35, 39, 45, 47, 49, 51, 51, 53, 53, 57, 58,
    62, 68, 70, 72, 74, 74, 76, 76, 80, 82, 84, 86,
    88, 90, 92, 0, 1, 16, 22, 24, 26, 28, 28, 30,
    30, 34, 35, 39, 45, 47, 49, 51, 51, 53, 53, 57,
    58, 62, 68, 70, 72, 74, 74, 76, 76, 80, 82, 84,
    86, 88, 90, 92, 0, 1, 16, 22, 24, 26, 28, 28,
    30, 30, 34, 35, 39, 45, 47, 49, 51, 51, 53, 53,
    57, 58, 62, 68, 70, 72, 74, 74, 76, 76, 80, 82,
    84, 86, 88, 90, 92, 0, 1, 16, 22, 24, 26, 28,
    28, 30, 30, 34, 35, 39, 45, 47, 49, 51, 51, 53,
    53, 57, 58, 62, 68, 70, 72, 74, 74, 76, 76, 80,
    82, 84, 86, 88, 90, 92, 0, 1, 16, 22, 24, 28,
    28, 30, 30, 35, 39, 45, 47, 51, 51, 53, 53, 58,
    62, 68, 70, 74, 74, 76, 76, 82, 84, 86, 88, 90,
    92, 0, 1, 16, 22, 24, 28, 28, 30, 30, 35, 39,
    45, 47, 51, 51, 53, 53, 58, 62, 68, 70, 74, 74,
    76, 76, 82, 84, 86, 88, 90, 92, 0, 1, 16, 22,
    24, 28, 28, 30, 30, 35, 39, 45, 47, 51, 51, 53,
    53, 58, 62, 68, 70, 74, 74, 76, 76, 82, 84, 86,
    88, 90, 92, 0, 1, 16, 22, 24, 28, 28, 30, 30,
    35, 39, 45, 47, 51, 51, 53, 53, 58, 62, 68, 70,
    74, 74, 76, 76, 82, 84, 86, 88, 90, 92, 0, 1,
    16, 22, 24, 28, 28, 30, 30, 35, 39, 45, 47, 51,
    51, 53, 53, 58, 62, 68, 70, 74, 74, 76, 76, 82,
    84, 86, 88, 90, 92, 0, 1, 16, 22, 24, 28, 28,
    30, 30, 35, 39, 45, 47, 51, 51, 53, 53, 58, 62,
    68, 70, 74, 74, 76, 76, 82, 84, 86, 88, 90, 92,
    0, 1, 16, 22, 24, 28, 28, 30, 30, 35, 39, 45,
    47, 51, 51, 53, 53, 58, 62, 68, 70, 74, 74, 76,
    76, 82, 84, 86, 88, 90, 92, 0, 1, 16, 22, 24,
    28, 28, 30, 30, 35, 39, 45, 47, 51, 51, 53, 53,
    58, 62, 68, 70, 74, 74, 76, 76, 82, 84, 86, 88,
    90, 92, 0, 1, 16, 22, 24, 28, 31, 30, 30, 35,
    39, 45, 47, 51, 54, 53, 53, 58, 62, 68, 70, 74,
    77, 76, 76, 82, 84, 86, 88, 90, 92, 0, 1, 16,
    22, 24, 28, 31, 30, 30, 35, 39, 45, 47, 51, 54,
    53, 53, 58, 62, 68, 70, 74, 77, 76, 76, 82, 84,
    86, 88, 90, 92, 0, 1, 16, 22, 24, 28, 31, 30,
    30, 35, 39, 45, 47, 51, 54, 53, 53, 58, 62, 68,
    70, 74, 77, 76, 76, 82, 84, 86, 88, 90, 92, 0,
    1, 16, 22, 24, 28, 31, 30, 30, 35, 39, 45, 47,
    51, 54, 53, 53, 58, 62, 68, 70, 74, 77, 76, 76,
    82, 84, 86, 88, 90, 92, 0, 1, 16, 22, 24, 28,
    31, 30, 30, 35, 39, 45, 47, 51, 54, 53, 53, 58,
    62, 68, 70, 74, 77, 76, 76, 82, 84, 86, 88, 90,
    92, 0, 1, 16, 22, 24, 28, 31, 30, 30, 35, 39,
    45, 47, 51, 54, 53, 53, 58, 62, 68, 70, 74, 77,
    76, 76, 82, 84, 86, 88, 90, 92, 0, 1, 16, 22,
    24, 28, 31, 30, 30, 35, 39, 45, 47, 51, 54, 53,
    53, 58, 62, 68, 70, 74, 77, 76, 76, 82, 84, 86,
    88, 90, 92, 0, 1, 16, 22, 24, 28, 31, 30, 30,
    35, 39, 45, 47, 51, 54, 53, 53, 58, 62, 68, 70,
    74, 77, 76, 76, 82, 84, 86, 88, 90, 92, 4, 1,
    16, 22, 24, 28, 31, 30, 30, 35, 39, 45, 47, 51,
    54, 53, 53, 58, 62, 68, 70, 74, 77, 76, 76, 82,
    84, 86, 88, 90, 92, 4, 1, 16, 22, 24, 28, 31,
    30, 30, 35, 39, 45, 47, 51, 54, 53, 53, 58, 62,
    68, 70, 74, 77, 76, 76, 82, 84, 86, 88, 90, 92,
    4, 1, 16, 22, 24, 28, 31, 30, 30, 35, 39, 45,
    47, 51, 54, 53, 53, 58, 62, 68, 70, 74, 77, 76,
    76, 82, 84, 86, 88, 90, 92, 4, 1, 16, 22, 24,
    28, 31, 30, 30, 35, 39, 45, 47, 51, 54, 53, 53,
    58, 62, 68, 70, 74, 77, 76, 76, 82, 84, 86, 88,
    90, 92, 4, 1, 16, 22, 24, 28, 31, 30, 30, 35,
    39, 45, 47, 51, 54, 53, 53, 58, 62, 68, 70, 74,
    77, 76, 76, 82, 84, 86, 88, 90, 92, 4, 1, 16,
    22, 24, 28, 31, 30, 30, 35, 39, 45, 47, 51, 54,
    53, 53, 58, 62, 68, 70, 74, 77, 76, 76, 82, 84,
    86, 88, 90, 92, 4, 1, 16, 22, 24, 28, 31, 30,
    30, 35, 39, 45, 47, 51, 54, 53, 53, 58, 62, 68,
    70, 74, 77, 76, 76, 82, 84, 86, 88, 90, 92, 4,
    1, 16, 22, 24, 28, 31, 30, 30, 35, 39, 45, 47,
    51, 54, 53, 53, 58, 62, 68, 70, 74, 77, 76, 76,
    82, 84, 86, 88, 90, 92, 4, 1, 16, 22, 24, 28,
    31, 30, 30, 35, 39, 45, 47, 51, 54, 53, 53, 58,
    62, 68, 70, 74, 77, 76, 76, 82, 84, 86, 88, 90,
    92, 4, 1, 16, 22, 24, 28, 31, 30, 30, 35, 39,
    45, 47, 51, 54, 53, 53, 58, 62, 68, 70, 74, 77,
    76, 76, 82, 84, 86, 88, 90, 92, 4, 1, 16, 22,
    24, 28, 31, 30, 30, 35, 39, 45, 47, 51, 54, 53,
    53, 58, 62, 68, 70, 74, 77, 76, 76, 82, 84, 86,
    88, 90, 92, 4, 1, 16, 22, 24, 28, 31, 30, 30,
    35, 39, 45, 47, 51, 54, 53, 53, 58, 62, 68, 70,
    74, 77, 76, 76, 82, 84, 86, 88, 90, 92, 4, 1,
    16, 22, 24, 28, 31, 30, 30, 35, 39, 45, 47, 51,
    54, 53, 53, 58, 62, 68, 70, 74, 77, 76, 76, 82,
    84, 86, 88, 90, 92, 4, 1, 16, 22, 24, 28, 31,
    30, 30, 35, 39, 45, 47, 51, 54, 53, 53, 58, 62,
    68, 70, 74, 77, 76, 76, 82, 84, 86, 88, 90, 92,
    4, 1, 16, 22, 24, 28, 31, 30, 30, 35, 39, 45,
    47, 51, 54, 53, 53, 58, 62, 68, 70, 74, 77, 76,
    76, 82, 84, 86, 88, 90, 92, 4, 1, 16, 22, 24,
    28, 31, 30, 30, 35, 39, 45, 47, 51, 54, 53, 53,
    58, 62, 68, 70, 74, 77, 76, 76, 82, 84, 86, 88,
    90, 92, 4, 1, 16, 22, 24, 28, 31, 30, 30, 35,
    39, 45, 47, 51, 54, 53, 53, 58, 62, 68, 70, 74,
    77, 76, 76, 82, 84, 86, 88, 90, 92, 4, 1, 16,
    22, 24, 28, 31, 30, 30, 35, 39, 45, 47, 51, 54,
    53, 53, 58, 62, 68, 70, 74, 77, 76, 76, 82, 84,
    86, 88, 90, 92, 4, 1, 16, 22, 24, 28, 31, 30,
    30, 35, 39, 45, 47, 51, 54, 53, 53, 58, 62, 68,
    70, 74, 77, 76, 76, 82, 84, 86, 88, 90, 92, 4,
    1, 16, 22, 24, 28, 31, 30, 30, 35, 39, 45, 47,
    51, 54, 53, 53, 58, 62, 68, 70, 74, 77, 76, 76,
    82, 84, 86, 88, 90, 92, 4, 1, 16, 22, 24, 28,
    31, 30, 30, 35, 39, 45, 47, 51, 54, 53, 53, 58,
    62, 68, 70, 74, 77, 76, 76, 82, 84, 86, 88, 90,
    92, 4, 1, 16, 22, 24, 28, 31, 30, 30, 35, 39,
    45, 47, 51, 54, 53, 53, 58, 62, 68, 70, 74, 77,
    76, 76, 82, 84, 86, 88, 90, 92, 4, 1, 16, 22,
    24, 28, 31, 30, 30, 35, 39, 45, 47, 51, 54, 53,
    53, 58, 62, 68, 70, 74, 77, 76, 76, 82, 84, 86,
    88, 90, 92, 4, 1, 16, 22, 24, 28, 31, 30, 30,
    35, 39, 45, 47, 51, 54, 53, 53, 58, 62, 68, 70,
    74, 77, 76, 76, 82, 84, 86, 88, 90, 92, 4, 1,
    16, 22, 28, 30, 30, 39, 45, 51, 53, 53, 62, 68,
    74, 76, 76, 82, 84, 86, 88, 90, 92, 4, 1, 16,
    22, 28, 30, 30, 39, 45, 51, 53, 53, 62, 68, 74,
    76, 76, 82, 84, 86, 88, 90, 92, 4, 1, 16, 22,
    28, 30, 30, 39, 45, 51, 53, 53, 62, 68, 74, 76,
    76, 82, 84, 86, 88, 90, 92, 4, 1, 16, 22, 28,
    30, 30, 39, 45, 51, 53, 53, 62, 68, 74, 76, 76,
    82, 84, 86, 88, 90, 92, 4, 1, 16, 22, 28, 30,
    30, 39, 45, 51, 53, 53, 62, 68, 74, 76, 76, 82,
    84, 86, 88, 90, 92, 4, 1, 16, 22, 28, 30, 30,
    39, 45, 51, 53, 53, 62, 68, 74, 76, 76, 82, 84,
    86, 88, 90, 92, 4, 1, 16, 22, 28, 30, 30, 39,
    45, 51, 53, 53, 62, 68, 74, 76, 76, 82, 84, 86,
    88, 90, 92, 4, 1, 16, 22, 28, 30, 30, 39, 45,
    51, 53, 53, 62, 68, 74, 76, 76, 82, 84, 86, 88,
    90, 92, 4, 1, 6, 7, 28, 30, 30, 8, 40, 42,
    51, 53, 53, 10, 63, 65, 74, 76, 76, 82, 84, 86,
    88, 90, 92, 4, 1, 6, 28, 30, 30, 8, 40, 42,
    51, 53, 53, 10, 63, 65, 74, 76, 76, 82, 84, 86,
    88, 90, 92, 4, 1, 6, 28, 30, 30, 8, 40, 42,
    51, 53, 53, 10, 63, 65, 74, 76, 76, 82, 84, 86,
    88, 90, 92, 4, 1, 6, 28, 30, 30, 8, 40, 42,
    51, 53, 53, 10, 63, 65, 74, 76, 76, 82, 84, 86,
    88, 90, 92, 4, 1, 6, 28, 30, 30, 8, 40, 42,
    51, 53, 53, 10, 63, 65, 74, 76, 76, 82, 84, 86,
    88, 90, 92, 4, 1, 6, 28, 30, 30, 8, 40, 51,
    53, 53, 10, 63, 74, 76, 76, 82, 84, 86, 88, 90,
    92, 4, 1, 6, 28, 30, 30, 8, 40, 51, 53, 53,
    10, 63, 74, 76, 76, 82, 84, 86, 88, 90, 92, 4,
    1, 6, 28, 30, 30, 8, 40, 51, 53, 53, 10, 63,
    74, 76, 76, 82, 84, 86, 88, 90, 92, 4, 1, 6,
    28, 30, 30, 8, 40, 51, 53, 53, 10, 63, 74, 76,
    76, 82, 84, 86, 88, 90, 92, 4, 1, 6, 28, 30,
    30, 8, 40, 51, 53, 53, 10, 63, 74, 76, 76, 82,
    84, 86, 88, 90, 92, 4, 1, 6, 28, 30, 30, 8,
    40, 51, 53, 53, 10, 63, 74, 76, 76, 82, 84, 86,
    88, 90, 92, 4, 1, 6, 28, 30, 30, 8, 40, 51,
    53, 53, 10, 63, 74, 76, 76, 82, 84, 86, 88, 90,
    92, 4, 1, 6, 28, 30, 30, 8, 40, 51, 53, 53,
    10, 63, 74, 76, 76, 82, 84, 86, 88, 90, 92, 4,
    1, 6, 28, 30, 30, 8, 40, 51, 53, 53, 10, 63,
    74, 76, 76, 82, 84, 86, 88, 90, 92, 4, 1, 6,
    28, 30, 30, 8, 40, 51, 53, 53, 10, 63, 74, 76,
    76, 82, 84, 86, 88, 90, 92, 4, 1, 6, 28, 30,
    30, 8, 40, 51, 53, 53, 10, 63, 74, 76, 76, 82,
    84, 86, 88, 90, 92, 4, 1, 17, 17, 19, 28, 30,
    30, 9, 51, 53, 53, 11, 74, 76, 76, 82, 84, 86,
    88, 90, 92, 4, 1, 17, 17, 19, 28, 30, 30, 51,
    53, 53, 74, 76, 76, 83, 4, 1, 17, 17, 19, 28,
    30, 30, 51, 53, 53, 74, 76, 76, 4, 1, 17, 17,
    19, 28, 30, 30, 51, 53, 53, 74, 76, 76, 4, 1,
    17, 17, 19, 28, 30, 30, 51, 53, 53, 74, 76, 76,
    4, 1, 17, 17, 28, 30, 30, 51, 53, 53, 74, 76,
    76, 4, 1, 17, 17, 28, 30, 30, 51, 53, 53, 74,
    76, 76, 4, 1, 17, 17, 28, 30, 30, 51, 53, 53,
    74, 76, 76,
};

static __device__ __constant__ uint16_t kStaticTaskClaims[5715] = {
    0, 56, 0, 24, 48, 72, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 152, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 152, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 152, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 1, 57, 1, 25, 49, 73, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 153, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 153, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    153, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2,
    58, 2, 26, 50, 74, 2, 2, 2, 2, 2, 2, 2,
    2, 2, 2, 2, 2, 2, 2, 154, 2, 2, 2, 2,
    2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
    2, 2, 154, 2, 2, 2, 2, 2, 2, 2, 2, 2,
    2, 2, 2, 2, 2, 2, 2, 2, 2, 154, 2, 2,
    2, 2, 2, 2, 2, 2, 2, 2, 3, 59, 3, 27,
    51, 75, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
    3, 3, 3, 3, 155, 3, 3, 3, 3, 3, 3, 3,
    3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 155,
    3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
    3, 3, 3, 3, 3, 3, 155, 3, 3, 3, 3, 3,
    3, 3, 3, 3, 3, 4, 60, 4, 28, 52, 76, 4,
    4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
    4, 156, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
    4, 4, 4, 4, 4, 4, 4, 4, 156, 4, 4, 4,
    4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
    4, 4, 4, 156, 4, 4, 4, 4, 4, 4, 4, 4,
    4, 4, 5, 61, 5, 29, 53, 77, 0, 0, 5, 5,
    5, 5, 5, 5, 5, 5, 5, 5, 157, 5, 5, 5,
    5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 157,
    5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
    5, 5, 157, 5, 5, 5, 5, 5, 5, 5, 5, 5,
    6, 62, 6, 30, 54, 78, 1, 1, 6, 6, 6, 6,
    6, 6, 6, 6, 6, 6, 158, 6, 6, 6, 6, 6,
    6, 6, 6, 6, 6, 6, 6, 6, 6, 158, 6, 6,
    6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
    158, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 63,
    7, 31, 55, 79, 2, 2, 7, 7, 7, 7, 7, 7,
    7, 7, 7, 7, 159, 7, 7, 7, 7, 7, 7, 7,
    7, 7, 7, 7, 7, 7, 7, 159, 7, 7, 7, 7,
    7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 159, 7,
    7, 7, 7, 7, 7, 7, 7, 7, 8, 64, 8, 32,
    56, 80, 3, 3, 8, 8, 8, 8, 8, 8, 8, 8,
    8, 8, 160, 8, 8, 8, 8, 8, 8, 8, 8, 8,
    8, 8, 8, 8, 8, 160, 8, 8, 8, 8, 8, 8,
    8, 8, 8, 8, 8, 8, 8, 8, 160, 8, 8, 8,
    8, 8, 8, 8, 8, 8, 9, 65, 9, 33, 57, 81,
    4, 4, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
    161, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
    9, 9, 9, 161, 9, 9, 9, 9, 9, 9, 9, 9,
    9, 9, 9, 9, 9, 9, 161, 9, 9, 9, 9, 9,
    9, 9, 9, 9, 10, 66, 10, 34, 58, 82, 5, 5,
    10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 162, 10,
    10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
    10, 162, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
    10, 10, 10, 10, 162, 10, 10, 10, 10, 10, 10, 10,
    10, 10, 11, 67, 11, 35, 59, 83, 6, 6, 11, 11,
    11, 11, 11, 11, 11, 11, 11, 11, 163, 11, 11, 11,
    11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 163,
    11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11,
    11, 11, 163, 11, 11, 11, 11, 11, 11, 11, 11, 11,
    12, 68, 12, 36, 60, 84, 7, 7, 12, 12, 12, 12,
    12, 12, 12, 12, 12, 12, 164, 12, 12, 12, 12, 12,
    12, 12, 12, 12, 12, 12, 12, 12, 12, 164, 12, 12,
    12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12,
    164, 12, 12, 12, 12, 12, 12, 12, 12, 12, 13, 69,
    13, 37, 61, 85, 13, 13, 13, 13, 13, 13, 13, 13,
    13, 13, 165, 13, 13, 13, 13, 13, 13, 13, 13, 13,
    13, 13, 13, 13, 13, 165, 13, 13, 13, 13, 13, 13,
    13, 13, 13, 13, 13, 13, 13, 13, 165, 13, 13, 13,
    13, 13, 13, 13, 13, 13, 14, 70, 14, 38, 62, 86,
    14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 166, 14,
    14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14,
    14, 166, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14,
    14, 14, 14, 14, 166, 14, 14, 14, 14, 14, 14, 14,
    14, 14, 15, 71, 15, 39, 63, 87, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 167, 15, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 15, 15, 167, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
    167, 15, 15, 15, 15, 15, 15, 15, 15, 15, 16, 72,
    16, 40, 64, 88, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 168, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 168, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 168, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 17, 73, 17, 41, 65, 89,
    17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 169, 17,
    17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17,
    17, 169, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17,
    17, 17, 17, 17, 169, 17, 17, 17, 17, 17, 17, 17,
    17, 17, 18, 74, 18, 42, 66, 90, 18, 18, 18, 18,
    18, 18, 18, 18, 18, 18, 170, 18, 18, 18, 18, 18,
    18, 18, 18, 18, 18, 18, 18, 18, 18, 170, 18, 18,
    18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18,
    170, 18, 18, 18, 18, 18, 18, 18, 18, 18, 19, 75,
    19, 43, 67, 91, 19, 19, 19, 19, 19, 19, 19, 19,
    19, 19, 171, 19, 19, 19, 19, 19, 19, 19, 19, 19,
    19, 19, 19, 19, 19, 171, 19, 19, 19, 19, 19, 19,
    19, 19, 19, 19, 19, 19, 19, 19, 171, 19, 19, 19,
    19, 19, 19, 19, 19, 19, 20, 76, 20, 44, 68, 92,
    20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 172, 20,
    20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
    172, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
    20, 20, 172, 20, 20, 20, 20, 20, 20, 20, 20, 21,
    77, 21, 45, 69, 93, 21, 21, 21, 21, 21, 21, 21,
    21, 21, 21, 173, 21, 21, 21, 21, 21, 21, 21, 21,
    21, 21, 21, 21, 21, 173, 21, 21, 21, 21, 21, 21,
    21, 21, 21, 21, 21, 21, 21, 173, 21, 21, 21, 21,
    21, 21, 21, 21, 22, 78, 22, 46, 70, 94, 22, 22,
    22, 22, 22, 22, 22, 22, 22, 22, 174, 22, 22, 22,
    22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 174, 22,
    22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22,
    174, 22, 22, 22, 22, 22, 22, 22, 22, 23, 79, 23,
    47, 71, 95, 23, 23, 23, 23, 23, 23, 23, 23, 23,
    23, 175, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23,
    23, 23, 23, 175, 23, 23, 23, 23, 23, 23, 23, 23,
    23, 23, 23, 23, 23, 175, 23, 23, 23, 23, 23, 23,
    23, 23, 24, 0, 96, 24, 24, 24, 24, 24, 24, 24,
    24, 24, 24, 176, 24, 24, 24, 24, 24, 24, 24, 24,
    24, 24, 24, 24, 24, 176, 24, 24, 24, 24, 24, 24,
    24, 24, 24, 24, 24, 24, 24, 176, 24, 24, 24, 24,
    24, 24, 24, 24, 25, 1, 97, 25, 25, 25, 25, 25,
    25, 25, 25, 25, 25, 177, 25, 25, 25, 25, 25, 25,
    25, 25, 25, 25, 25, 25, 25, 177, 25, 25, 25, 25,
    25, 25, 25, 25, 25, 25, 25, 25, 25, 177, 25, 25,
    25, 25, 25, 25, 25, 25, 26, 2, 98, 26, 26, 26,
    26, 26, 26, 26, 26, 26, 26, 178, 26, 26, 26, 26,
    26, 26, 26, 26, 26, 26, 26, 26, 26, 178, 26, 26,
    26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 178,
    26, 26, 26, 26, 26, 26, 26, 26, 27, 3, 99, 27,
    27, 27, 27, 27, 27, 27, 27, 27, 27, 179, 27, 27,
    27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 179,
    27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27,
    27, 179, 27, 27, 27, 27, 27, 27, 27, 27, 28, 4,
    100, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 180,
    28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28,
    28, 180, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28,
    28, 28, 28, 180, 28, 28, 28, 28, 28, 28, 28, 28,
    29, 5, 101, 29, 29, 29, 29, 29, 29, 29, 29, 29,
    29, 181, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29,
    29, 29, 29, 181, 29, 29, 29, 29, 29, 29, 29, 29,
    29, 29, 29, 29, 29, 181, 29, 29, 29, 29, 29, 29,
    29, 29, 30, 6, 102, 30, 30, 30, 30, 30, 30, 30,
    30, 30, 30, 182, 30, 30, 30, 30, 30, 30, 30, 30,
    30, 30, 30, 30, 30, 182, 30, 30, 30, 30, 30, 30,
    30, 30, 30, 30, 30, 30, 30, 182, 30, 30, 30, 30,
    30, 30, 30, 30, 31, 7, 103, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 183, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 183, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 183, 31, 31,
    31, 31, 31, 31, 31, 31, 32, 8, 104, 0, 32, 32,
    32, 32, 32, 32, 32, 32, 32, 184, 0, 120, 32, 32,
    32, 32, 32, 32, 32, 32, 32, 32, 32, 184, 0, 120,
    32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 184,
    0, 120, 32, 32, 32, 32, 32, 32, 32, 33, 9, 105,
    1, 33, 33, 33, 33, 33, 33, 33, 33, 33, 185, 1,
    121, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33,
    185, 1, 121, 33, 33, 33, 33, 33, 33, 33, 33, 33,
    33, 33, 185, 1, 121, 33, 33, 33, 33, 33, 33, 33,
    34, 10, 106, 2, 34, 34, 34, 34, 34, 34, 34, 34,
    34, 186, 2, 122, 34, 34, 34, 34, 34, 34, 34, 34,
    34, 34, 34, 186, 2, 122, 34, 34, 34, 34, 34, 34,
    34, 34, 34, 34, 34, 186, 2, 122, 34, 34, 34, 34,
    34, 34, 34, 35, 11, 107, 3, 35, 35, 35, 35, 35,
    35, 35, 35, 35, 187, 3, 123, 35, 35, 35, 35, 35,
    35, 35, 35, 35, 35, 35, 187, 3, 123, 35, 35, 35,
    35, 35, 35, 35, 35, 35, 35, 35, 187, 3, 123, 35,
    35, 35, 35, 35, 35, 35, 36, 12, 108, 4, 36, 36,
    36, 36, 36, 36, 36, 36, 36, 188, 4, 124, 36, 36,
    36, 36, 36, 36, 36, 36, 36, 36, 36, 188, 4, 124,
    36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 188,
    4, 124, 36, 36, 36, 36, 36, 36, 36, 37, 13, 109,
    5, 37, 37, 37, 37, 37, 37, 37, 37, 37, 189, 5,
    125, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37,
    189, 5, 125, 37, 37, 37, 37, 37, 37, 37, 37, 37,
    37, 37, 189, 5, 125, 37, 37, 37, 37, 37, 37, 37,
    38, 14, 110, 6, 38, 38, 38, 38, 38, 38, 38, 38,
    38, 190, 6, 126, 38, 38, 38, 38, 38, 38, 38, 38,
    38, 38, 38, 190, 6, 126, 38, 38, 38, 38, 38, 38,
    38, 38, 38, 38, 38, 190, 6, 126, 38, 38, 38, 38,
    38, 38, 38, 39, 15, 111, 7, 39, 39, 39, 39, 39,
    39, 39, 39, 39, 191, 7, 127, 39, 39, 39, 39, 39,
    39, 39, 39, 39, 39, 39, 191, 7, 127, 39, 39, 39,
    39, 39, 39, 39, 39, 39, 39, 39, 191, 7, 127, 39,
    39, 39, 39, 39, 39, 39, 40, 16, 112, 8, 40, 40,
    40, 40, 40, 40, 192, 8, 128, 40, 40, 40, 40, 40,
    40, 40, 40, 192, 8, 128, 40, 40, 40, 40, 40, 40,
    40, 40, 192, 8, 128, 40, 40, 40, 40, 40, 40, 40,
    41, 17, 113, 9, 41, 41, 41, 41, 41, 41, 193, 9,
    129, 41, 41, 41, 41, 41, 41, 41, 41, 193, 9, 129,
    41, 41, 41, 41, 41, 41, 41, 41, 193, 9, 129, 41,
    41, 41, 41, 41, 41, 41, 42, 18, 114, 10, 42, 42,
    42, 42, 42, 42, 194, 10, 130, 42, 42, 42, 42, 42,
    42, 42, 42, 194, 10, 130, 42, 42, 42, 42, 42, 42,
    42, 42, 194, 10, 130, 42, 42, 42, 42, 42, 42, 42,
    43, 19, 115, 11, 43, 43, 43, 43, 43, 43, 195, 11,
    131, 43, 43, 43, 43, 43, 43, 43, 43, 195, 11, 131,
    43, 43, 43, 43, 43, 43, 43, 43, 195, 11, 131, 43,
    43, 43, 43, 43, 43, 43, 44, 20, 116, 12, 44, 44,
    44, 44, 44, 44, 196, 12, 132, 44, 44, 44, 44, 44,
    44, 44, 44, 196, 12, 132, 44, 44, 44, 44, 44, 44,
    44, 44, 196, 12, 132, 44, 44, 44, 44, 44, 44, 44,
    45, 21, 117, 13, 45, 45, 45, 45, 45, 45, 197, 13,
    133, 45, 45, 45, 45, 45, 45, 45, 45, 197, 13, 133,
    45, 45, 45, 45, 45, 45, 45, 45, 197, 13, 133, 45,
    45, 45, 45, 45, 45, 45, 46, 22, 118, 14, 46, 46,
    46, 46, 46, 46, 198, 14, 134, 46, 46, 46, 46, 46,
    46, 46, 46, 198, 14, 134, 46, 46, 46, 46, 46, 46,
    46, 46, 198, 14, 134, 46, 46, 46, 46, 46, 46, 46,
    47, 23, 119, 15, 47, 47, 47, 47, 47, 47, 199, 15,
    135, 47, 47, 47, 47, 47, 47, 47, 47, 199, 15, 135,
    47, 47, 47, 47, 47, 47, 47, 47, 199, 15, 135, 47,
    47, 47, 47, 47, 47, 47, 48, 24, 16, 48, 48, 48,
    48, 48, 48, 200, 16, 136, 48, 48, 48, 48, 48, 48,
    48, 48, 200, 16, 136, 48, 48, 48, 48, 48, 48, 48,
    48, 200, 16, 136, 48, 48, 48, 48, 48, 48, 48, 49,
    25, 17, 49, 49, 49, 49, 49, 49, 201, 17, 137, 49,
    49, 49, 49, 49, 49, 49, 49, 201, 17, 137, 49, 49,
    49, 49, 49, 49, 49, 49, 201, 17, 137, 49, 49, 49,
    49, 49, 49, 49, 50, 26, 18, 50, 50, 50, 50, 50,
    50, 202, 18, 138, 50, 50, 50, 50, 50, 50, 50, 50,
    202, 18, 138, 50, 50, 50, 50, 50, 50, 50, 50, 202,
    18, 138, 50, 50, 50, 50, 50, 50, 50, 51, 27, 19,
    51, 51, 51, 51, 51, 51, 203, 19, 139, 51, 51, 51,
    51, 51, 51, 51, 51, 203, 19, 139, 51, 51, 51, 51,
    51, 51, 51, 51, 203, 19, 139, 51, 51, 51, 51, 51,
    51, 51, 52, 28, 20, 52, 52, 52, 52, 52, 52, 204,
    20, 140, 52, 52, 52, 52, 52, 52, 52, 52, 204, 20,
    140, 52, 52, 52, 52, 52, 52, 52, 52, 204, 20, 140,
    52, 52, 52, 52, 52, 52, 52, 53, 29, 21, 53, 53,
    53, 53, 53, 53, 205, 21, 141, 53, 53, 53, 53, 53,
    53, 53, 53, 205, 21, 141, 53, 53, 53, 53, 53, 53,
    53, 53, 205, 21, 141, 53, 53, 53, 53, 53, 53, 53,
    54, 30, 22, 54, 54, 54, 54, 54, 54, 206, 22, 142,
    54, 54, 54, 54, 54, 54, 54, 54, 206, 22, 142, 54,
    54, 54, 54, 54, 54, 54, 54, 206, 22, 142, 54, 54,
    54, 54, 54, 54, 54, 55, 31, 23, 55, 55, 55, 55,
    55, 55, 207, 23, 143, 55, 55, 55, 55, 55, 55, 55,
    55, 207, 23, 143, 55, 55, 55, 55, 55, 55, 55, 55,
    207, 23, 143, 55, 55, 55, 55, 55, 55, 55, 56, 32,
    24, 56, 56, 56, 56, 56, 56, 208, 24, 144, 56, 56,
    56, 56, 56, 56, 56, 56, 208, 24, 144, 56, 56, 56,
    56, 56, 56, 56, 56, 208, 24, 144, 56, 56, 56, 56,
    56, 56, 56, 57, 33, 25, 57, 57, 57, 57, 57, 57,
    209, 25, 145, 57, 57, 57, 57, 57, 57, 57, 57, 209,
    25, 145, 57, 57, 57, 57, 57, 57, 57, 57, 209, 25,
    145, 57, 57, 57, 57, 57, 57, 57, 58, 34, 26, 58,
    58, 58, 58, 58, 58, 210, 26, 146, 58, 58, 58, 58,
    58, 58, 58, 58, 210, 26, 146, 58, 58, 58, 58, 58,
    58, 58, 58, 210, 26, 146, 58, 58, 58, 58, 58, 58,
    58, 59, 35, 27, 59, 59, 59, 59, 59, 59, 211, 27,
    147, 59, 59, 59, 59, 59, 59, 59, 59, 211, 27, 147,
    59, 59, 59, 59, 59, 59, 59, 59, 211, 27, 147, 59,
    59, 59, 59, 59, 59, 59, 60, 36, 28, 60, 60, 60,
    60, 60, 60, 212, 28, 148, 60, 60, 60, 60, 60, 60,
    60, 60, 212, 28, 148, 60, 60, 60, 60, 60, 60, 60,
    60, 212, 28, 148, 60, 60, 60, 60, 60, 60, 60, 61,
    37, 29, 61, 61, 61, 61, 61, 61, 213, 29, 149, 61,
    61, 61, 61, 61, 61, 61, 61, 213, 29, 149, 61, 61,
    61, 61, 61, 61, 61, 61, 213, 29, 149, 61, 61, 61,
    61, 61, 61, 61, 62, 38, 30, 62, 62, 62, 62, 62,
    62, 214, 30, 150, 62, 62, 62, 62, 62, 62, 62, 62,
    214, 30, 150, 62, 62, 62, 62, 62, 62, 62, 62, 214,
    30, 150, 62, 62, 62, 62, 62, 62, 62, 63, 39, 31,
    63, 63, 63, 63, 63, 63, 215, 31, 151, 63, 63, 63,
    63, 63, 63, 63, 63, 215, 31, 151, 63, 63, 63, 63,
    63, 63, 63, 63, 215, 31, 151, 63, 63, 63, 63, 63,
    63, 63, 64, 40, 64, 64, 64, 64, 64, 216, 32, 152,
    64, 64, 64, 64, 64, 64, 64, 216, 32, 152, 64, 64,
    64, 64, 64, 64, 64, 216, 32, 152, 64, 64, 64, 64,
    64, 64, 64, 65, 41, 65, 65, 65, 65, 65, 217, 33,
    153, 65, 65, 65, 65, 65, 65, 65, 217, 33, 153, 65,
    65, 65, 65, 65, 65, 65, 217, 33, 153, 65, 65, 65,
    65, 65, 65, 65, 66, 42, 66, 66, 66, 66, 66, 218,
    34, 154, 66, 66, 66, 66, 66, 66, 66, 218, 34, 154,
    66, 66, 66, 66, 66, 66, 66, 218, 34, 154, 66, 66,
    66, 66, 66, 66, 66, 67, 43, 67, 67, 67, 67, 67,
    219, 35, 155, 67, 67, 67, 67, 67, 67, 67, 219, 35,
    155, 67, 67, 67, 67, 67, 67, 67, 219, 35, 155, 67,
    67, 67, 67, 67, 67, 67, 68, 44, 68, 68, 68, 68,
    68, 220, 36, 156, 68, 68, 68, 68, 68, 68, 68, 220,
    36, 156, 68, 68, 68, 68, 68, 68, 68, 220, 36, 156,
    68, 68, 68, 68, 68, 68, 68, 69, 45, 69, 69, 69,
    69, 69, 221, 37, 157, 69, 69, 69, 69, 69, 69, 69,
    221, 37, 157, 69, 69, 69, 69, 69, 69, 69, 221, 37,
    157, 69, 69, 69, 69, 69, 69, 69, 70, 46, 70, 70,
    70, 70, 70, 222, 38, 158, 70, 70, 70, 70, 70, 70,
    70, 222, 38, 158, 70, 70, 70, 70, 70, 70, 70, 222,
    38, 158, 70, 70, 70, 70, 70, 70, 70, 71, 47, 71,
    71, 71, 71, 71, 223, 39, 159, 71, 71, 71, 71, 71,
    71, 71, 223, 39, 159, 71, 71, 71, 71, 71, 71, 71,
    223, 39, 159, 71, 71, 71, 71, 71, 71, 71, 72, 48,
    72, 72, 72, 72, 72, 224, 40, 160, 72, 72, 72, 72,
    72, 72, 72, 224, 40, 160, 72, 72, 72, 72, 72, 72,
    72, 224, 40, 160, 72, 72, 72, 72, 72, 72, 72, 73,
    49, 73, 73, 73, 73, 73, 225, 41, 161, 73, 73, 73,
    73, 73, 73, 73, 225, 41, 161, 73, 73, 73, 73, 73,
    73, 73, 225, 41, 161, 73, 73, 73, 73, 73, 73, 73,
    74, 50, 74, 74, 74, 74, 74, 226, 42, 162, 74, 74,
    74, 74, 74, 74, 74, 226, 42, 162, 74, 74, 74, 74,
    74, 74, 74, 226, 42, 162, 74, 74, 74, 74, 74, 74,
    74, 75, 51, 75, 75, 75, 75, 75, 227, 43, 163, 75,
    75, 75, 75, 75, 75, 75, 227, 43, 163, 75, 75, 75,
    75, 75, 75, 75, 227, 43, 163, 75, 75, 75, 75, 75,
    75, 75, 76, 52, 76, 76, 76, 76, 76, 228, 44, 164,
    76, 76, 76, 76, 76, 76, 76, 228, 44, 164, 76, 76,
    76, 76, 76, 76, 76, 228, 44, 164, 76, 76, 76, 76,
    76, 76, 76, 77, 53, 77, 77, 77, 77, 77, 229, 45,
    165, 77, 77, 77, 77, 77, 77, 77, 229, 45, 165, 77,
    77, 77, 77, 77, 77, 77, 229, 45, 165, 77, 77, 77,
    77, 77, 77, 77, 78, 54, 78, 78, 78, 78, 78, 230,
    46, 166, 78, 78, 78, 78, 78, 78, 78, 230, 46, 166,
    78, 78, 78, 78, 78, 78, 78, 230, 46, 166, 78, 78,
    78, 78, 78, 78, 78, 79, 55, 79, 79, 79, 79, 79,
    231, 47, 167, 79, 79, 79, 79, 79, 79, 79, 231, 47,
    167, 79, 79, 79, 79, 79, 79, 79, 231, 47, 167, 79,
    79, 79, 79, 79, 79, 79, 80, 56, 80, 80, 80, 80,
    232, 48, 168, 80, 80, 80, 80, 80, 232, 48, 168, 80,
    80, 80, 80, 80, 232, 48, 168, 80, 80, 80, 80, 80,
    80, 81, 57, 81, 81, 81, 81, 233, 49, 169, 81, 81,
    81, 81, 81, 233, 49, 169, 81, 81, 81, 81, 81, 233,
    49, 169, 81, 81, 81, 81, 81, 81, 82, 58, 82, 82,
    82, 82, 234, 50, 170, 82, 82, 82, 82, 82, 234, 50,
    170, 82, 82, 82, 82, 82, 234, 50, 170, 82, 82, 82,
    82, 82, 82, 83, 59, 83, 83, 83, 83, 235, 51, 171,
    83, 83, 83, 83, 83, 235, 51, 171, 83, 83, 83, 83,
    83, 235, 51, 171, 83, 83, 83, 83, 83, 83, 84, 60,
    84, 84, 84, 84, 236, 52, 172, 84, 84, 84, 84, 84,
    236, 52, 172, 84, 84, 84, 84, 84, 236, 52, 172, 84,
    84, 84, 84, 84, 84, 85, 61, 85, 85, 85, 85, 237,
    53, 173, 85, 85, 85, 85, 85, 237, 53, 173, 85, 85,
    85, 85, 85, 237, 53, 173, 85, 85, 85, 85, 85, 85,
    86, 62, 86, 86, 86, 86, 238, 54, 174, 86, 86, 86,
    86, 86, 238, 54, 174, 86, 86, 86, 86, 86, 238, 54,
    174, 86, 86, 86, 86, 86, 86, 87, 63, 87, 87, 87,
    87, 239, 55, 175, 87, 87, 87, 87, 87, 239, 55, 175,
    87, 87, 87, 87, 87, 239, 55, 175, 87, 87, 87, 87,
    87, 87, 88, 64, 88, 88, 88, 88, 0, 88, 208, 88,
    88, 88, 88, 88, 0, 88, 208, 88, 88, 88, 88, 88,
    0, 88, 208, 88, 88, 88, 88, 88, 88, 89, 65, 89,
    89, 89, 89, 1, 89, 209, 89, 89, 89, 89, 89, 1,
    89, 209, 89, 89, 89, 89, 89, 1, 89, 209, 89, 89,
    89, 89, 89, 89, 90, 66, 90, 90, 90, 90, 2, 90,
    210, 90, 90, 90, 90, 90, 2, 90, 210, 90, 90, 90,
    90, 90, 2, 90, 210, 90, 90, 90, 90, 90, 90, 91,
    67, 91, 91, 91, 91, 3, 91, 211, 91, 91, 91, 91,
    91, 3, 91, 211, 91, 91, 91, 91, 91, 3, 91, 211,
    91, 91, 91, 91, 91, 91, 92, 68, 92, 92, 92, 92,
    4, 92, 212, 92, 92, 92, 92, 92, 4, 92, 212, 92,
    92, 92, 92, 92, 4, 92, 212, 92, 92, 92, 92, 92,
    92, 93, 69, 93, 93, 93, 93, 5, 93, 213, 93, 93,
    93, 93, 93, 5, 93, 213, 93, 93, 93, 93, 93, 5,
    93, 213, 93, 93, 93, 93, 93, 93, 94, 70, 94, 94,
    94, 94, 6, 94, 214, 94, 94, 94, 94, 94, 6, 94,
    214, 94, 94, 94, 94, 94, 6, 94, 214, 94, 94, 94,
    94, 94, 94, 95, 71, 95, 95, 95, 95, 7, 95, 215,
    95, 95, 95, 95, 95, 7, 95, 215, 95, 95, 95, 95,
    95, 7, 95, 215, 95, 95, 95, 95, 95, 95, 0, 72,
    96, 96, 96, 96, 8, 96, 216, 96, 96, 96, 96, 96,
    8, 96, 216, 96, 96, 96, 96, 96, 8, 96, 216, 96,
    96, 96, 96, 96, 96, 1, 73, 97, 97, 97, 97, 9,
    97, 217, 97, 97, 97, 97, 97, 9, 97, 217, 97, 97,
    97, 97, 97, 9, 97, 217, 97, 97, 97, 97, 97, 97,
    2, 74, 98, 98, 98, 98, 10, 98, 218, 98, 98, 98,
    98, 98, 10, 98, 218, 98, 98, 98, 98, 98, 10, 98,
    218, 98, 98, 98, 98, 98, 98, 3, 75, 99, 99, 99,
    99, 11, 99, 219, 99, 99, 99, 99, 99, 11, 99, 219,
    99, 99, 99, 99, 99, 11, 99, 219, 99, 99, 99, 99,
    99, 99, 4, 76, 100, 100, 100, 100, 12, 100, 220, 100,
    100, 100, 100, 100, 12, 100, 220, 100, 100, 100, 100, 100,
    12, 100, 220, 100, 100, 100, 100, 100, 100, 5, 77, 101,
    101, 101, 101, 13, 101, 221, 101, 101, 101, 101, 101, 13,
    101, 221, 101, 101, 101, 101, 101, 13, 101, 221, 101, 101,
    101, 101, 101, 101, 6, 78, 102, 102, 102, 102, 14, 102,
    222, 102, 102, 102, 102, 102, 14, 102, 222, 102, 102, 102,
    102, 102, 14, 102, 222, 102, 102, 102, 102, 102, 102, 7,
    79, 103, 103, 103, 103, 15, 103, 223, 103, 103, 103, 103,
    103, 15, 103, 223, 103, 103, 103, 103, 103, 15, 103, 223,
    103, 103, 103, 103, 103, 103, 8, 80, 104, 104, 104, 104,
    16, 104, 224, 104, 104, 104, 104, 104, 16, 104, 224, 104,
    104, 104, 104, 104, 16, 104, 224, 104, 104, 104, 104, 104,
    104, 9, 81, 105, 105, 105, 105, 17, 105, 225, 105, 105,
    105, 105, 105, 17, 105, 225, 105, 105, 105, 105, 105, 17,
    105, 225, 105, 105, 105, 105, 105, 105, 10, 82, 106, 106,
    106, 106, 18, 106, 226, 106, 106, 106, 106, 106, 18, 106,
    226, 106, 106, 106, 106, 106, 18, 106, 226, 106, 106, 106,
    106, 106, 106, 11, 83, 107, 107, 107, 107, 19, 107, 227,
    107, 107, 107, 107, 107, 19, 107, 227, 107, 107, 107, 107,
    107, 19, 107, 227, 107, 107, 107, 107, 107, 107, 12, 84,
    108, 108, 108, 108, 20, 108, 228, 108, 108, 108, 108, 108,
    20, 108, 228, 108, 108, 108, 108, 108, 20, 108, 228, 108,
    108, 108, 108, 108, 108, 13, 85, 109, 109, 109, 109, 21,
    109, 229, 109, 109, 109, 109, 109, 21, 109, 229, 109, 109,
    109, 109, 109, 21, 109, 229, 109, 109, 109, 109, 109, 109,
    14, 86, 110, 110, 110, 110, 22, 110, 230, 110, 110, 110,
    110, 110, 22, 110, 230, 110, 110, 110, 110, 110, 22, 110,
    230, 110, 110, 110, 110, 110, 110, 15, 87, 111, 111, 111,
    111, 23, 111, 231, 111, 111, 111, 111, 111, 23, 111, 231,
    111, 111, 111, 111, 111, 23, 111, 231, 111, 111, 111, 111,
    111, 111, 16, 88, 112, 112, 112, 112, 24, 112, 232, 112,
    112, 112, 112, 112, 24, 112, 232, 112, 112, 112, 112, 112,
    24, 112, 232, 112, 112, 112, 112, 112, 112, 17, 89, 113,
    113, 113, 113, 25, 113, 233, 113, 113, 113, 113, 113, 25,
    113, 233, 113, 113, 113, 113, 113, 25, 113, 233, 113, 113,
    113, 113, 113, 113, 18, 90, 114, 114, 114, 114, 26, 114,
    234, 114, 114, 114, 114, 114, 26, 114, 234, 114, 114, 114,
    114, 114, 26, 114, 234, 114, 114, 114, 114, 114, 114, 19,
    91, 115, 115, 115, 115, 27, 115, 235, 115, 115, 115, 115,
    115, 27, 115, 235, 115, 115, 115, 115, 115, 27, 115, 235,
    115, 115, 115, 115, 115, 115, 20, 92, 116, 116, 116, 116,
    28, 116, 236, 116, 116, 116, 116, 116, 28, 116, 236, 116,
    116, 116, 116, 116, 28, 116, 236, 116, 116, 116, 116, 116,
    116, 21, 93, 117, 117, 117, 117, 29, 117, 237, 117, 117,
    117, 117, 117, 29, 117, 237, 117, 117, 117, 117, 117, 29,
    117, 237, 117, 117, 117, 117, 117, 117, 22, 94, 118, 118,
    118, 118, 30, 118, 238, 118, 118, 118, 118, 118, 30, 118,
    238, 118, 118, 118, 118, 118, 30, 118, 238, 118, 118, 118,
    118, 118, 118, 23, 95, 119, 119, 119, 119, 31, 119, 239,
    119, 119, 119, 119, 119, 31, 119, 239, 119, 119, 119, 119,
    119, 31, 119, 239, 119, 119, 119, 119, 119, 119, 24, 96,
    120, 120, 120, 56, 176, 120, 120, 120, 56, 176, 120, 120,
    120, 56, 176, 120, 120, 120, 120, 120, 120, 25, 97, 121,
    121, 121, 57, 177, 121, 121, 121, 57, 177, 121, 121, 121,
    57, 177, 121, 121, 121, 121, 121, 121, 26, 98, 122, 122,
    122, 58, 178, 122, 122, 122, 58, 178, 122, 122, 122, 58,
    178, 122, 122, 122, 122, 122, 122, 27, 99, 123, 123, 123,
    59, 179, 123, 123, 123, 59, 179, 123, 123, 123, 59, 179,
    123, 123, 123, 123, 123, 123, 28, 100, 124, 124, 124, 60,
    180, 124, 124, 124, 60, 180, 124, 124, 124, 60, 180, 124,
    124, 124, 124, 124, 124, 29, 101, 125, 125, 125, 61, 181,
    125, 125, 125, 61, 181, 125, 125, 125, 61, 181, 125, 125,
    125, 125, 125, 125, 30, 102, 126, 126, 126, 62, 182, 126,
    126, 126, 62, 182, 126, 126, 126, 62, 182, 126, 126, 126,
    126, 126, 126, 31, 103, 127, 127, 127, 63, 183, 127, 127,
    127, 63, 183, 127, 127, 127, 63, 183, 127, 127, 127, 127,
    127, 127, 32, 104, 0, 0, 128, 64, 184, 0, 0, 0,
    128, 64, 184, 0, 0, 0, 128, 64, 184, 128, 128, 128,
    128, 128, 128, 33, 105, 1, 129, 65, 185, 1, 1, 1,
    129, 65, 185, 1, 1, 1, 129, 65, 185, 129, 129, 129,
    129, 129, 129, 34, 106, 2, 130, 66, 186, 2, 2, 2,
    130, 66, 186, 2, 2, 2, 130, 66, 186, 130, 130, 130,
    130, 130, 130, 35, 107, 3, 131, 67, 187, 3, 3, 3,
    131, 67, 187, 3, 3, 3, 131, 67, 187, 131, 131, 131,
    131, 131, 131, 36, 108, 4, 132, 68, 188, 4, 4, 4,
    132, 68, 188, 4, 4, 4, 132, 68, 188, 132, 132, 132,
    132, 132, 132, 37, 109, 5, 133, 69, 189, 5, 5, 133,
    69, 189, 5, 5, 133, 69, 189, 133, 133, 133, 133, 133,
    133, 38, 110, 6, 134, 70, 190, 6, 6, 134, 70, 190,
    6, 6, 134, 70, 190, 134, 134, 134, 134, 134, 134, 39,
    111, 7, 135, 71, 191, 7, 7, 135, 71, 191, 7, 7,
    135, 71, 191, 135, 135, 135, 135, 135, 135, 40, 112, 8,
    136, 72, 192, 8, 8, 136, 72, 192, 8, 8, 136, 72,
    192, 136, 136, 136, 136, 136, 136, 41, 113, 9, 137, 73,
    193, 9, 9, 137, 73, 193, 9, 9, 137, 73, 193, 137,
    137, 137, 137, 137, 137, 42, 114, 10, 138, 74, 194, 10,
    10, 138, 74, 194, 10, 10, 138, 74, 194, 138, 138, 138,
    138, 138, 138, 43, 115, 11, 139, 75, 195, 11, 11, 139,
    75, 195, 11, 11, 139, 75, 195, 139, 139, 139, 139, 139,
    139, 44, 116, 12, 140, 76, 196, 12, 12, 140, 76, 196,
    12, 12, 140, 76, 196, 140, 140, 140, 140, 140, 140, 45,
    117, 13, 141, 77, 197, 13, 13, 141, 77, 197, 13, 13,
    141, 77, 197, 141, 141, 141, 141, 141, 141, 46, 118, 14,
    142, 78, 198, 14, 14, 142, 78, 198, 14, 14, 142, 78,
    198, 142, 142, 142, 142, 142, 142, 47, 119, 15, 143, 79,
    199, 15, 15, 143, 79, 199, 15, 15, 143, 79, 199, 143,
    143, 143, 143, 143, 143, 48, 120, 0, 8, 0, 144, 80,
    200, 0, 144, 80, 200, 0, 144, 80, 200, 144, 144, 144,
    144, 144, 144, 49, 121, 1, 9, 1, 145, 81, 201, 145,
    81, 201, 145, 81, 201, 0, 50, 122, 2, 10, 2, 146,
    82, 202, 146, 82, 202, 146, 82, 202, 51, 123, 3, 11,
    3, 147, 83, 203, 147, 83, 203, 147, 83, 203, 52, 124,
    4, 12, 4, 148, 84, 204, 148, 84, 204, 148, 84, 204,
    53, 125, 5, 13, 149, 85, 205, 149, 85, 205, 149, 85,
    205, 54, 126, 6, 14, 150, 86, 206, 150, 86, 206, 150,
    86, 206, 55, 127, 7, 15, 151, 87, 207, 151, 87, 207,
    151, 87, 207,
};

static __device__ __constant__ uint16_t kStreamingConsumerForPhase[94] = {
    65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535,
    65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535,
    65535, 65535, 65535, 65535, 29, 65535, 65535, 65535, 65535, 65535, 65535, 65535,
    65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535,
    65535, 65535, 65535, 52, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535,
    65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535,
    65535, 65535, 75, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535,
    65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535,
};

static __device__ __constant__ uint8_t kDependencyCounts[94] = {
    0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 3, 1, 1, 2,
    1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 3, 1,
    1, 1, 1, 1, 1, 1, 1, 3, 1, 1, 2, 1,
    1, 1, 1, 1, 0, 1, 1, 1, 1, 3, 1, 1,
    1, 1, 1, 1, 1, 1, 3, 1, 1, 2, 1, 1,
    1, 1, 1, 0, 1, 1, 1, 1, 3, 1, 1, 1,
    2, 2, 2, 2, 2, 2, 2, 2, 2, 1,
};

static __device__ __constant__ uint8_t kRoleMasks[94] = {
    9, 15, 9, 9, 11, 9, 15, 9, 15, 9, 15, 9,
    15, 9, 15, 9, 15, 15, 9, 9, 15, 15, 15, 9,
    15, 9, 15, 9, 15, 9, 15, 15, 9, 15, 9, 15,
    9, 15, 9, 15, 15, 9, 9, 15, 15, 15, 9, 15,
    9, 15, 9, 15, 9, 15, 15, 9, 15, 9, 15, 9,
    15, 9, 15, 15, 9, 9, 15, 15, 15, 9, 15, 9,
    15, 9, 15, 9, 15, 15, 9, 15, 9, 9, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 15, 15, 1,
};

static __device__ __constant__ uint16_t kSuccessorOffsets[95] = {
    0, 1, 2, 3, 4, 5, 8, 9, 10, 11, 12, 13,
    14, 15, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
    28, 29, 32, 33, 34, 34, 35, 36, 37, 38, 39, 40,
    41, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54,
    55, 58, 59, 60, 60, 61, 62, 63, 64, 65, 66, 67,
    70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
    84, 85, 86, 86, 87, 88, 89, 90, 91, 92, 98, 103,
    104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 113,
};

static __device__ __constant__ uint16_t kSuccessors[113] = {
    1, 2, 3, 5, 12, 6, 8, 10, 7, 20, 9, 43,
    11, 66, 13, 14, 17, 23, 15, 16, 18, 19, 20, 20,
    21, 22, 23, 24, 25, 26, 31, 34, 27, 28, 30, 34,
    32, 33, 34, 35, 36, 37, 40, 46, 38, 39, 41, 42,
    43, 43, 44, 45, 46, 47, 48, 49, 54, 57, 50, 51,
    53, 57, 55, 56, 57, 58, 59, 60, 63, 69, 61, 62,
    64, 65, 66, 66, 67, 68, 69, 70, 71, 72, 77, 80,
    73, 74, 76, 80, 78, 79, 80, 81, 82, 83, 85, 87,
    89, 91, 84, 86, 88, 90, 92, 84, 85, 86, 87, 88,
    89, 90, 91, 92, 93,
};

}  // namespace deepspec::v4_generated
