// Generated by scripts/megakernel/generate_v4_header.py. Do not edit.
#pragma once

#include <cstdint>

namespace deepspec::v4_generated {
inline constexpr int kRoutedW2Workers = 128;
inline constexpr int kRoutedW2Credits = 512;
inline constexpr int kPhaseCount = 100;
inline constexpr int kRootCount = 2;
inline constexpr int kStaticTaskCount = 5793;
inline constexpr int kWorkers = 152;
inline constexpr int kThreads = 256;
inline constexpr int kLocalQueueDepth = 16;
inline constexpr int kTraceCapacity = 2048;
inline constexpr int kTraceColumns = 8;
inline constexpr uint8_t kExecutionMain = 0;
inline constexpr uint8_t kExecutionEmbedding = 1;
inline constexpr uint8_t kExecutionMainKv = 2;
inline constexpr uint8_t kExecutionAttnHc = 3;
inline constexpr uint8_t kExecutionAttnProjection = 4;
inline constexpr uint8_t kExecutionSparseAttention = 5;
inline constexpr uint8_t kExecutionAttentionOutput = 6;
inline constexpr uint8_t kExecutionFfnHc = 7;
inline constexpr uint8_t kExecutionRouter = 8;
inline constexpr uint8_t kExecutionExpert = 9;
inline constexpr uint8_t kExecutionHead = 10;
inline constexpr uint8_t kExecutionTail = 11;
inline constexpr uint64_t kWorkspaceBytes = 7379456ULL;
inline constexpr uint64_t kDependencyOffset = 7352320ULL;
inline constexpr uint64_t kNextTileOffset = 7353600ULL;
inline constexpr uint64_t kCompletedTileOffset = 7354880ULL;
inline constexpr uint64_t kPublishEpochOffset = 7356160ULL;
inline constexpr uint64_t kReadyQueueOffset = 7357440ULL;
inline constexpr uint64_t kQueueStateOffset = 7367168ULL;
inline constexpr uint64_t kWorkerStateOffset = 7369728ULL;
inline constexpr int kWeightOffsetSlots = 4724;
inline constexpr int kGlobalWeightBase = 0;
inline constexpr int kLayerWeightBase = 2;
inline constexpr int kRoutedExpertWeightBase = 98;
inline constexpr int kSharedExpertWeightBase = 4706;
inline constexpr int kGlobalWeightSlots = 2;
inline constexpr int kLayerWeightSlots = 32;
inline constexpr int kExpertWeightSlots = 6;
inline constexpr int kRouterChainsPerItem = 8;
inline constexpr int kRouterRowsPerChain = 1;
inline constexpr unsigned long long kWeightArenaBytes = 14206958848ULL;
inline constexpr int kMainQuantPhase = 0;
inline constexpr int kMainProjectionPhase = 1;
inline constexpr int kMainReducePhase = 2;
inline constexpr int kMainNormPhase = 3;
inline constexpr int kEmbeddingPhase = 4;
inline constexpr int kMainProjectedQuantPhase = 5;
inline constexpr int kLayer0AttnHcProjectionPhase = 12;
inline constexpr int kLayer0AttnHcSinkhornPhase = 13;
inline constexpr int kLayer0AttnHcReduceNormPhase = 14;
inline constexpr int kLayer0QaPhase = 15;
inline constexpr int kLayer0QaNormPhase = 16;
inline constexpr int kLayer0QbPhase = 17;
inline constexpr int kLayer0DraftKvProjectionPhase = 18;
inline constexpr int kLayer0QueryNormRopePhase = 19;
inline constexpr int kLayer0DraftKvFinalizePhase = 20;
inline constexpr int kLayer0SparseAttentionPhase = 21;
inline constexpr int kLayer0OutputAProjectionPhase = 22;
inline constexpr int kLayer0OutputBProjectionPhase = 24;
inline constexpr int kLayer0AttnPostPhase = 25;
inline constexpr int kLayer0FfnHcProjectionPhase = 26;
inline constexpr int kLayer0FfnHcSinkhornPhase = 27;
inline constexpr int kLayer0FfnHcReduceNormPhase = 28;
inline constexpr int kLayer0RouterScorePhase = 29;
inline constexpr int kLayer0RouterTop6Phase = 30;
inline constexpr int kLayer0RoutedW13Phase = 31;
inline constexpr int kLayer0RoutedSwiGluPhase = 65535;
inline constexpr int kLayer0RoutedW2Phase = 32;
inline constexpr int kLayer0SharedW13Phase = 33;
inline constexpr int kLayer0SharedSwiGluPhase = 34;
inline constexpr int kLayer0SharedW2Phase = 35;
inline constexpr int kLayer0ExpertCombinePhase = 36;
inline constexpr int kHeadReducePhase = 87;
inline constexpr int kPrefixSchedulerPhase = 65535;
inline constexpr int kExpertW1Slot = 0;
inline constexpr int kExpertW1ScaleSlot = 1;
inline constexpr int kExpertW2Slot = 2;
inline constexpr int kExpertW2ScaleSlot = 3;
inline constexpr int kExpertW3Slot = 4;
inline constexpr int kExpertW3ScaleSlot = 5;
inline constexpr int kMainProjWeightSlot = 24;
inline constexpr int kEmbeddingWeightSlot = 0;
inline constexpr int kMainProjScaleSlot = 25;
inline constexpr int kMainNormWeightSlot = 26;
inline constexpr int kLayer0AttnHcFnSlot = 2;
inline constexpr int kLayer0AttnHcBaseSlot = 3;
inline constexpr int kLayer0AttnHcScaleSlot = 4;
inline constexpr int kLayer0AttnNormWeightSlot = 8;
inline constexpr int kLayer0WqaWeightSlot = 11;
inline constexpr int kLayer0WqaScaleSlot = 12;
inline constexpr int kLayer0QaNormWeightSlot = 13;
inline constexpr int kLayer0WqbWeightSlot = 14;
inline constexpr int kLayer0WqbScaleSlot = 15;
inline constexpr int kLayer0WkvWeightSlot = 16;
inline constexpr int kLayer0WkvScaleSlot = 17;
inline constexpr int kLayer0KvNormWeightSlot = 18;
inline constexpr int kLayer0AttnSinkWeightSlot = 10;
inline constexpr int kLayer0WoaWeightSlot = 19;
inline constexpr int kLayer0WobWeightSlot = 20;
inline constexpr int kLayer0WobScaleSlot = 21;
inline constexpr int kLayer0FfnHcFnSlot = 5;
inline constexpr int kLayer0FfnHcBaseSlot = 6;
inline constexpr int kLayer0FfnHcScaleSlot = 7;
inline constexpr int kLayer0FfnNormWeightSlot = 9;
inline constexpr int kLayer0RouterWeightSlot = 22;
inline constexpr int kLayer0RouterBiasSlot = 23;
inline constexpr int kFinalNormWeightSlot = 91;
inline constexpr int kHcHeadFnWeightSlot = 92;
inline constexpr int kHcHeadBaseWeightSlot = 93;
inline constexpr int kHcHeadScaleWeightSlot = 94;
inline constexpr int kLmHeadWeightSlot = 1;
inline constexpr int kMarkovW1WeightSlot = 95;
inline constexpr int kMarkovW2WeightSlot = 96;
inline constexpr int kConfidenceWeightSlot = 97;
inline constexpr uint64_t kMainQuantizedOffset = 0ULL;
inline constexpr uint64_t kMainScaleOffset = 12288ULL;
inline constexpr uint64_t kMainPartialOffset = 12544ULL;
inline constexpr uint64_t kMainFp32Offset = 143616ULL;
inline constexpr uint64_t kMainRmsPartialOffset = 160000ULL;
inline constexpr uint64_t kMainProjectedOffset = 160256ULL;
inline constexpr uint64_t kMainProjectedQuantizedOffset = 168448ULL;
inline constexpr uint64_t kMainProjectedScaleOffset = 172544ULL;
inline constexpr uint64_t kMainKvPartialOffset = 172800ULL;
inline constexpr uint64_t kHiddenStreamsOffset = 197376ULL;
inline constexpr uint64_t kHcMixOffset = 364288ULL;
inline constexpr uint64_t kHcPreOffset = 364800ULL;
inline constexpr uint64_t kHcPostOffset = 365056ULL;
inline constexpr uint64_t kHcCombOffset = 365312ULL;
inline constexpr uint64_t kNormalizedHiddenOffset = 365824ULL;
inline constexpr uint64_t kAttnInputQuantizedOffset = 406784ULL;
inline constexpr uint64_t kAttnInputScaleOffset = 427264ULL;
inline constexpr uint64_t kQaPartialOffset = 427520ULL;
inline constexpr uint64_t kQloraOffset = 509440ULL;
inline constexpr uint64_t kQloraQuantizedOffset = 519680ULL;
inline constexpr uint64_t kQloraScaleOffset = 524800ULL;
inline constexpr uint64_t kQueryProjectionOffset = 525056ULL;
inline constexpr uint64_t kQueryInverseRmsOffset = 852736ULL;
inline constexpr uint64_t kQueriesOffset = 853504ULL;
inline constexpr uint64_t kDraftKvPartialOffset = 1181184ULL;
inline constexpr uint64_t kDraftKvOffset = 1222144ULL;
inline constexpr uint64_t kAttentionAccumulatorOffset = 1227264ULL;
inline constexpr uint64_t kAttentionRawOffset = 1882624ULL;
inline constexpr uint64_t kAttentionValuesOffset = 2210304ULL;
inline constexpr uint64_t kOutputLoraOffset = 2537984ULL;
inline constexpr uint64_t kOutputLoraQuantizedOffset = 2619904ULL;
inline constexpr uint64_t kOutputLoraScaleOffset = 2660864ULL;
inline constexpr uint64_t kAttentionOutputPartialOffset = 2661376ULL;
inline constexpr uint64_t kAttentionOutputOffset = 2989056ULL;
inline constexpr uint64_t kAttentionHiddenStreamsOffset = 3030016ULL;
inline constexpr uint64_t kFfnHcMixOffset = 3193856ULL;
inline constexpr uint64_t kFfnHcPreOffset = 3194368ULL;
inline constexpr uint64_t kFfnHcPostOffset = 3194624ULL;
inline constexpr uint64_t kFfnHcCombOffset = 3194880ULL;
inline constexpr uint64_t kFfnNormalizedHiddenOffset = 3195392ULL;
inline constexpr uint64_t kFfnInputQuantizedOffset = 3236352ULL;
inline constexpr uint64_t kFfnInputScaleOffset = 3256832ULL;
inline constexpr uint64_t kRouterScoreOffset = 3257088ULL;
inline constexpr uint64_t kRouterIndexOffset = 3262208ULL;
inline constexpr uint64_t kRouterWeightOffset = 3262464ULL;
inline constexpr uint64_t kRoutedW13Offset = 3262720ULL;
inline constexpr uint64_t kSharedW13Offset = 3508480ULL;
inline constexpr uint64_t kRoutedSwiGluOffset = 3549440ULL;
inline constexpr uint64_t kRoutedSwiGluQuantizedOffset = 3672320ULL;
inline constexpr uint64_t kRoutedSwiGluScaleOffset = 3733760ULL;
inline constexpr uint64_t kSharedSwiGluOffset = 3734272ULL;
inline constexpr uint64_t kSharedSwiGluQuantizedOffset = 3754752ULL;
inline constexpr uint64_t kSharedSwiGluScaleOffset = 3764992ULL;
inline constexpr uint64_t kRoutedOutputPartialOffset = 3765248ULL;
inline constexpr uint64_t kRoutedOutputOffset = 4011008ULL;
inline constexpr uint64_t kSharedOutputOffset = 4092928ULL;
inline constexpr uint64_t kHeadHiddenOffset = 4133888ULL;
inline constexpr uint64_t kHeadNormalizedOffset = 4174848ULL;
inline constexpr uint64_t kBaseLogitsOffset = 4215808ULL;
inline constexpr uint64_t kMarkovEmbeddingOffset = 6801408ULL;
inline constexpr uint64_t kMarkovLogitsOffset = 6803968ULL;
inline constexpr uint64_t kSoftmaxPartialMaxOffset = 7321088ULL;
inline constexpr uint64_t kSoftmaxPartialSumOffset = 7331328ULL;
inline constexpr uint64_t kSampleScanOffset = 7341568ULL;

static __device__ __constant__ uint16_t kMainKvProjectionPhases[3] = {
    6, 8, 10,
};

static __device__ __constant__ uint16_t kMainKvNormPhases[3] = {
    7, 9, 11,
};

static __device__ __constant__ uint16_t kMainKvWeightSlots[3] = {
    16, 48, 80,
};

static __device__ __constant__ uint16_t kMainKvScaleSlots[3] = {
    17, 49, 81,
};

static __device__ __constant__ uint16_t kMainKvNormWeightSlots[3] = {
    18, 50, 82,
};

static __device__ __constant__ uint16_t kAttnHcProjectionPhases[3] = {
    12, 37, 62,
};

static __device__ __constant__ uint16_t kAttnHcSinkhornPhases[3] = {
    13, 38, 63,
};

static __device__ __constant__ uint16_t kAttnHcReduceNormPhases[3] = {
    14, 39, 64,
};

static __device__ __constant__ uint16_t kQaPhases[3] = {
    15, 40, 65,
};

static __device__ __constant__ uint16_t kQaNormPhases[3] = {
    16, 41, 66,
};

static __device__ __constant__ uint16_t kQbPhases[3] = {
    17, 42, 67,
};

static __device__ __constant__ uint16_t kDraftKvProjectionPhases[3] = {
    18, 43, 68,
};

static __device__ __constant__ uint16_t kQueryNormRopePhases[3] = {
    19, 44, 69,
};

static __device__ __constant__ uint16_t kDraftKvFinalizePhases[3] = {
    20, 45, 70,
};

static __device__ __constant__ uint16_t kSparseAttentionPhases[3] = {
    21, 46, 71,
};

static __device__ __constant__ uint16_t kOutputAProjectionPhases[3] = {
    22, 47, 72,
};

static __device__ __constant__ uint16_t kOutputAReductionPhases[3] = {
    23, 48, 73,
};

static __device__ __constant__ uint16_t kOutputBProjectionPhases[3] = {
    24, 49, 74,
};

static __device__ __constant__ uint16_t kAttnPostPhases[3] = {
    25, 50, 75,
};

static __device__ __constant__ uint16_t kFfnHcProjectionPhases[3] = {
    26, 51, 76,
};

static __device__ __constant__ uint16_t kFfnHcSinkhornPhases[3] = {
    27, 52, 77,
};

static __device__ __constant__ uint16_t kFfnHcReduceNormPhases[3] = {
    28, 53, 78,
};

static __device__ __constant__ uint16_t kRouterScorePhases[3] = {
    29, 54, 79,
};

static __device__ __constant__ uint16_t kRouterTop6Phases[3] = {
    30, 55, 80,
};

static __device__ __constant__ uint16_t kRoutedW13Phases[3] = {
    31, 56, 81,
};

static __device__ __constant__ uint16_t kRoutedSwiGluPhases[3] = {
    65535, 65535, 65535,
};

static __device__ __constant__ uint16_t kRoutedW2Phases[3] = {
    32, 57, 82,
};

static __device__ __constant__ uint16_t kSharedW13Phases[3] = {
    33, 58, 83,
};

static __device__ __constant__ uint16_t kSharedSwiGluPhases[3] = {
    34, 59, 84,
};

static __device__ __constant__ uint16_t kSharedW2Phases[3] = {
    35, 60, 85,
};

static __device__ __constant__ uint16_t kExpertCombinePhases[3] = {
    36, 61, 86,
};

static __device__ __constant__ uint16_t kLmRowPhases[5] = {
    88, 88, 88, 88, 88,
};

static __device__ __constant__ uint16_t kMarkovGatherPhases[5] = {
    89, 91, 93, 95, 97,
};

static __device__ __constant__ uint16_t kConfidencePhases[5] = {
    65535, 65535, 65535, 65535, 65535,
};

static __device__ __constant__ uint16_t kMarkovW2Phases[5] = {
    90, 92, 94, 96, 98,
};

static __device__ __constant__ uint16_t kCorrectLogitPhases[5] = {
    65535, 65535, 65535, 65535, 65535,
};

static __device__ __constant__ uint16_t kSoftmaxExpSumPhases[5] = {
    65535, 65535, 65535, 65535, 65535,
};

static __device__ __constant__ uint16_t kSumReducePhases[5] = {
    65535, 65535, 65535, 65535, 65535,
};

static __device__ __constant__ uint16_t kNormalizeSamplePhases[5] = {
    65535, 65535, 65535, 65535, 65535,
};

static __device__ __constant__ uint16_t kAttnHcFnSlots[3] = {
    2, 34, 66,
};

static __device__ __constant__ uint16_t kAttnHcBaseSlots[3] = {
    3, 35, 67,
};

static __device__ __constant__ uint16_t kAttnHcScaleSlots[3] = {
    4, 36, 68,
};

static __device__ __constant__ uint16_t kAttnNormWeightSlots[3] = {
    8, 40, 72,
};

static __device__ __constant__ uint16_t kWqaWeightSlots[3] = {
    11, 43, 75,
};

static __device__ __constant__ uint16_t kWqaScaleSlots[3] = {
    12, 44, 76,
};

static __device__ __constant__ uint16_t kQaNormWeightSlots[3] = {
    13, 45, 77,
};

static __device__ __constant__ uint16_t kWqbWeightSlots[3] = {
    14, 46, 78,
};

static __device__ __constant__ uint16_t kWqbScaleSlots[3] = {
    15, 47, 79,
};

static __device__ __constant__ uint16_t kDraftWkvWeightSlots[3] = {
    16, 48, 80,
};

static __device__ __constant__ uint16_t kDraftWkvScaleSlots[3] = {
    17, 49, 81,
};

static __device__ __constant__ uint16_t kDraftKvNormWeightSlots[3] = {
    18, 50, 82,
};

static __device__ __constant__ uint16_t kAttnSinkWeightSlots[3] = {
    10, 42, 74,
};

static __device__ __constant__ uint16_t kWoaWeightSlots[3] = {
    19, 51, 83,
};

static __device__ __constant__ uint16_t kWobWeightSlots[3] = {
    20, 52, 84,
};

static __device__ __constant__ uint16_t kWobScaleSlots[3] = {
    21, 53, 85,
};

static __device__ __constant__ uint16_t kFfnHcFnSlots[3] = {
    5, 37, 69,
};

static __device__ __constant__ uint16_t kFfnHcBaseSlots[3] = {
    6, 38, 70,
};

static __device__ __constant__ uint16_t kFfnHcScaleSlots[3] = {
    7, 39, 71,
};

static __device__ __constant__ uint16_t kFfnNormWeightSlots[3] = {
    9, 41, 73,
};

static __device__ __constant__ uint16_t kRouterWeightSlots[3] = {
    22, 54, 86,
};

static __device__ __constant__ uint16_t kRouterBiasSlots[3] = {
    23, 55, 87,
};

static __device__ __constant__ uint16_t kRoutedExpertWeightBases[3] = {
    98, 1634, 3170,
};

static __device__ __constant__ uint16_t kSharedExpertWeightBases[3] = {
    4706, 4712, 4718,
};

static __device__ __constant__ uint16_t kRoots[2] = {
    0, 4,
};

static __device__ __constant__ uint32_t kWorkUnits[100] = {
    96, 256, 8, 8, 160, 32, 16, 1, 16, 1, 16, 1,
    120, 5, 5, 32, 5, 256, 16, 40, 5, 40, 128, 64,
    128, 40, 120, 5, 5, 160, 5, 960, 512, 32, 20, 32,
    160, 120, 5, 5, 32, 5, 256, 16, 40, 5, 40, 128,
    64, 128, 40, 120, 5, 5, 160, 5, 960, 512, 32, 20,
    32, 160, 120, 5, 5, 32, 5, 256, 16, 40, 5, 40,
    128, 64, 128, 40, 120, 5, 5, 160, 5, 960, 512, 32,
    20, 32, 160, 5, 1010, 1, 1010, 1, 1010, 1, 1010, 1,
    1010, 1, 1010, 1,
};

static __device__ __constant__ uint8_t kClaimChunks[100] = {
    1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 2, 1, 4, 4, 1, 1, 1,
    2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 2, 1, 4, 4, 1, 1,
    1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 2, 1, 4, 4, 1,
    1, 1, 2, 1, 7, 1, 7, 1, 7, 1, 7, 1,
    7, 1, 7, 1,
};

static __device__ __constant__ uint8_t kExecutionGroups[100] = {
    0, 0, 0, 0, 1, 2, 2, 2, 2, 2, 2, 2,
    3, 3, 3, 4, 4, 4, 4, 4, 4, 5, 6, 6,
    6, 6, 7, 7, 7, 8, 8, 9, 9, 9, 9, 9,
    9, 3, 3, 3, 4, 4, 4, 4, 4, 4, 5, 6,
    6, 6, 6, 7, 7, 7, 8, 8, 9, 9, 9, 9,
    9, 9, 3, 3, 3, 4, 4, 4, 4, 4, 4, 5,
    6, 6, 6, 6, 7, 7, 7, 8, 8, 9, 9, 9,
    9, 9, 9, 10, 10, 11, 11, 11, 11, 11, 11, 11,
    11, 11, 11, 11,
};

static __device__ __constant__ uint8_t kPhaseLayers[100] = {
    255, 255, 255, 255, 255, 255, 0, 0, 1, 1, 2, 2,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
    2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
    2, 2, 2, 255, 255, 255, 255, 255, 255, 255, 255, 255,
    255, 255, 255, 255,
};

static __device__ __constant__ uint16_t kStaticWorkerTaskOffsets[153] = {
    0, 70, 135, 200, 265, 330, 380, 430, 480, 530, 580, 636,
    692, 748, 804, 860, 916, 972, 1028, 1084, 1140, 1196, 1252, 1308,
    1364, 1420, 1473, 1526, 1579, 1632, 1685, 1738, 1791, 1844, 1897, 1950,
    2003, 2056, 2109, 2162, 2215, 2260, 2305, 2347, 2389, 2431, 2472, 2513,
    2554, 2595, 2636, 2677, 2718, 2759, 2800, 2841, 2882, 2923, 2964, 3005,
    3046, 3087, 3128, 3169, 3210, 3248, 3286, 3324, 3362, 3400, 3438, 3476,
    3514, 3552, 3590, 3628, 3666, 3704, 3742, 3780, 3818, 3853, 3888, 3923,
    3958, 3993, 4028, 4063, 4098, 4133, 4168, 4203, 4238, 4273, 4308, 4343,
    4378, 4412, 4446, 4480, 4514, 4548, 4582, 4616, 4650, 4684, 4718, 4752,
    4786, 4820, 4854, 4888, 4922, 4956, 4990, 5024, 5058, 5092, 5123, 5154,
    5185, 5213, 5241, 5269, 5297, 5325, 5350, 5375, 5400, 5423, 5446, 5469,
    5492, 5515, 5535, 5555, 5575, 5594, 5612, 5630, 5648, 5666, 5684, 5702,
    5720, 5736, 5745, 5753, 5761, 5769, 5777, 5785, 5793,
};

static __device__ __constant__ uint16_t kStaticTaskPhases[5793] = {
    0, 1, 12, 14, 15, 16, 17, 21, 22, 23, 24, 25,
    26, 28, 33, 34, 35, 31, 32, 36, 37, 39, 40, 41,
    42, 44, 46, 47, 48, 49, 50, 51, 53, 58, 59, 60,
    56, 57, 61, 62, 64, 65, 66, 67, 69, 71, 72, 73,
    74, 75, 76, 78, 83, 84, 85, 81, 82, 86, 87, 88,
    90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 0, 1,
    12, 14, 15, 16, 17, 21, 22, 23, 24, 25, 26, 28,
    33, 34, 35, 31, 32, 36, 37, 39, 40, 41, 42, 44,
    46, 47, 48, 49, 50, 51, 53, 58, 59, 60, 56, 57,
    61, 62, 64, 65, 66, 67, 69, 71, 72, 73, 74, 75,
    76, 78, 83, 84, 85, 81, 82, 86, 87, 88, 90, 92,
    94, 96, 98, 0, 1, 12, 14, 15, 16, 17, 21, 22,
    23, 24, 25, 26, 28, 33, 34, 35, 31, 32, 36, 37,
    39, 40, 41, 42, 44, 46, 47, 48, 49, 50, 51, 53,
    58, 59, 60, 56, 57, 61, 62, 64, 65, 66, 67, 69,
    71, 72, 73, 74, 75, 76, 78, 83, 84, 85, 81, 82,
    86, 87, 88, 90, 92, 94, 96, 98, 0, 1, 12, 14,
    15, 16, 17, 21, 22, 23, 24, 25, 26, 28, 33, 34,
    35, 31, 32, 36, 37, 39, 40, 41, 42, 44, 46, 47,
    48, 49, 50, 51, 53, 58, 59, 60, 56, 57, 61, 62,
    64, 65, 66, 67, 69, 71, 72, 73, 74, 75, 76, 78,
    83, 84, 85, 81, 82, 86, 87, 88, 90, 92, 94, 96,
    98, 0, 1, 12, 14, 15, 16, 17, 21, 22, 23, 24,
    25, 26, 28, 33, 34, 35, 31, 32, 36, 37, 39, 40,
    41, 42, 44, 46, 47, 48, 49, 50, 51, 53, 58, 59,
    60, 56, 57, 61, 62, 64, 65, 66, 67, 69, 71, 72,
    73, 74, 75, 76, 78, 83, 84, 85, 81, 82, 86, 87,
    88, 90, 92, 94, 96, 98, 0, 1, 12, 13, 17, 19,
    21, 22, 23, 24, 25, 26, 27, 31, 32, 36, 37, 38,
    42, 44, 46, 47, 48, 49, 50, 51, 52, 56, 57, 61,
    62, 63, 67, 69, 71, 72, 73, 74, 75, 76, 77, 81,
    82, 86, 88, 90, 92, 94, 96, 98, 0, 1, 12, 13,
    17, 19, 21, 22, 23, 24, 25, 26, 27, 31, 32, 36,
    37, 38, 42, 44, 46, 47, 48, 49, 50, 51, 52, 56,
    57, 61, 62, 63, 67, 69, 71, 72, 73, 74, 75, 76,
    77, 81, 82, 86, 88, 90, 92, 94, 96, 98, 0, 1,
    12, 13, 17, 19, 21, 22, 23, 24, 25, 26, 27, 31,
    32, 36, 37, 38, 42, 44, 46, 47, 48, 49, 50, 51,
    52, 56, 57, 61, 62, 63, 67, 69, 71, 72, 73, 74,
    75, 76, 77, 81, 82, 86, 88, 90, 92, 94, 96, 98,
    0, 1, 12, 13, 17, 19, 21, 22, 23, 24, 25, 26,
    27, 31, 32, 36, 37, 38, 42, 44, 46, 47, 48, 49,
    50, 51, 52, 56, 57, 61, 62, 63, 67, 69, 71, 72,
    73, 74, 75, 76, 77, 81, 82, 86, 88, 90, 92, 94,
    96, 98, 0, 1, 12, 13, 17, 19, 21, 22, 23, 24,
    25, 26, 27, 31, 32, 36, 37, 38, 42, 44, 46, 47,
    48, 49, 50, 51, 52, 56, 57, 61, 62, 63, 67, 69,
    71, 72, 73, 74, 75, 76, 77, 81, 82, 86, 88, 90,
    92, 94, 96, 98, 0, 1, 12, 15, 17, 19, 21, 22,
    23, 24, 25, 26, 33, 34, 35, 31, 32, 36, 37, 40,
    42, 44, 46, 47, 48, 49, 50, 51, 58, 59, 60, 56,
    57, 61, 62, 65, 67, 69, 71, 72, 73, 74, 75, 76,
    83, 84, 85, 81, 82, 86, 88, 90, 92, 94, 96, 98,
    0, 1, 12, 15, 17, 19, 21, 22, 23, 24, 25, 26,
    33, 34, 35, 31, 32, 36, 37, 40, 42, 44, 46, 47,
    48, 49, 50, 51, 58, 59, 60, 56, 57, 61, 62, 65,
    67, 69, 71, 72, 73, 74, 75, 76, 83, 84, 85, 81,
    82, 86, 88, 90, 92, 94, 96, 98, 0, 1, 12, 15,
    17, 19, 21, 22, 23, 24, 25, 26, 33, 34, 35, 31,
    32, 36, 37, 40, 42, 44, 46, 47, 48, 49, 50, 51,
    58, 59, 60, 56, 57, 61, 62, 65, 67, 69, 71, 72,
    73, 74, 75, 76, 83, 84, 85, 81, 82, 86, 88, 90,
    92, 94, 96, 98, 0, 1, 12, 15, 17, 19, 21, 22,
    23, 24, 25, 26, 33, 34, 35, 31, 32, 36, 37, 40,
    42, 44, 46, 47, 48, 49, 50, 51, 58, 59, 60, 56,
    57, 61, 62, 65, 67, 69, 71, 72, 73, 74, 75, 76,
    83, 84, 85, 81, 82, 86, 88, 90, 92, 94, 96, 98,
    0, 1, 12, 15, 17, 19, 21, 22, 23, 24, 25, 26,
    33, 34, 35, 31, 32, 36, 37, 40, 42, 44, 46, 47,
    48, 49, 50, 51, 58, 59, 60, 56, 57, 61, 62, 65,
    67, 69, 71, 72, 73, 74, 75, 76, 83, 84, 85, 81,
    82, 86, 88, 90, 92, 94, 96, 98, 0, 1, 12, 15,
    17, 19, 21, 22, 23, 24, 25, 26, 33, 34, 35, 31,
    32, 36, 37, 40, 42, 44, 46, 47, 48, 49, 50, 51,
    58, 59, 60, 56, 57, 61, 62, 65, 67, 69, 71, 72,
    73, 74, 75, 76, 83, 84, 85, 81, 82, 86, 88, 90,
    92, 94, 96, 98, 0, 1, 12, 15, 17, 19, 21, 22,
    23, 24, 25, 26, 33, 34, 35, 31, 32, 36, 37, 40,
    42, 44, 46, 47, 48, 49, 50, 51, 58, 59, 60, 56,
    57, 61, 62, 65, 67, 69, 71, 72, 73, 74, 75, 76,
    83, 84, 85, 81, 82, 86, 88, 90, 92, 94, 96, 98,
    0, 1, 12, 15, 17, 19, 21, 22, 23, 24, 25, 26,
    33, 34, 35, 31, 32, 36, 37, 40, 42, 44, 46, 47,
    48, 49, 50, 51, 58, 59, 60, 56, 57, 61, 62, 65,
    67, 69, 71, 72, 73, 74, 75, 76, 83, 84, 85, 81,
    82, 86, 88, 90, 92, 94, 96, 98, 0, 1, 12, 15,
    17, 19, 21, 22, 23, 24, 25, 26, 33, 34, 35, 31,
    32, 36, 37, 40, 42, 44, 46, 47, 48, 49, 50, 51,
    58, 59, 60, 56, 57, 61, 62, 65, 67, 69, 71, 72,
    73, 74, 75, 76, 83, 84, 85, 81, 82, 86, 88, 90,
    92, 94, 96, 98, 0, 1, 12, 15, 17, 19, 21, 22,
    23, 24, 25, 26, 33, 34, 35, 31, 32, 36, 37, 40,
    42, 44, 46, 47, 48, 49, 50, 51, 58, 59, 60, 56,
    57, 61, 62, 65, 67, 69, 71, 72, 73, 74, 75, 76,
    83, 84, 85, 81, 82, 86, 88, 90, 92, 94, 96, 98,
    0, 1, 12, 15, 17, 19, 21, 22, 23, 24, 25, 26,
    33, 34, 35, 31, 32, 36, 37, 40, 42, 44, 46, 47,
    48, 49, 50, 51, 58, 59, 60, 56, 57, 61, 62, 65,
    67, 69, 71, 72, 73, 74, 75, 76, 83, 84, 85, 81,
    82, 86, 88, 90, 92, 94, 96, 98, 0, 1, 12, 15,
    17, 19, 21, 22, 23, 24, 25, 26, 33, 34, 35, 31,
    32, 36, 37, 40, 42, 44, 46, 47, 48, 49, 50, 51,
    58, 59, 60, 56, 57, 61, 62, 65, 67, 69, 71, 72,
    73, 74, 75, 76, 83, 84, 85, 81, 82, 86, 88, 90,
    92, 94, 96, 98, 0, 1, 12, 15, 17, 19, 21, 22,
    23, 24, 25, 26, 33, 34, 35, 31, 32, 36, 37, 40,
    42, 44, 46, 47, 48, 49, 50, 51, 58, 59, 60, 56,
    57, 61, 62, 65, 67, 69, 71, 72, 73, 74, 75, 76,
    83, 84, 85, 81, 82, 86, 88, 90, 92, 94, 96, 98,
    0, 1, 12, 15, 17, 19, 21, 22, 23, 24, 25, 26,
    33, 34, 35, 31, 32, 36, 37, 40, 42, 44, 46, 47,
    48, 49, 50, 51, 58, 59, 60, 56, 57, 61, 62, 65,
    67, 69, 71, 72, 73, 74, 75, 76, 83, 84, 85, 81,
    82, 86, 88, 90, 92, 94, 96, 98, 0, 1, 12, 15,
    17, 19, 21, 22, 23, 24, 25, 26, 33, 34, 35, 31,
    32, 36, 37, 40, 42, 44, 46, 47, 48, 49, 50, 51,
    58, 59, 60, 56, 57, 61, 62, 65, 67, 69, 71, 72,
    73, 74, 75, 76, 83, 84, 85, 81, 82, 86, 88, 90,
    92, 94, 96, 98, 0, 1, 12, 15, 17, 19, 21, 22,
    23, 24, 25, 26, 33, 35, 31, 32, 36, 37, 40, 42,
    44, 46, 47, 48, 49, 50, 51, 58, 60, 56, 57, 61,
    62, 65, 67, 69, 71, 72, 73, 74, 75, 76, 83, 85,
    81, 82, 86, 88, 90, 92, 94, 96, 98, 0, 1, 12,
    15, 17, 19, 21, 22, 23, 24, 25, 26, 33, 35, 31,
    32, 36, 37, 40, 42, 44, 46, 47, 48, 49, 50, 51,
    58, 60, 56, 57, 61, 62, 65, 67, 69, 71, 72, 73,
    74, 75, 76, 83, 85, 81, 82, 86, 88, 90, 92, 94,
    96, 98, 0, 1, 12, 15, 17, 19, 21, 22, 23, 24,
    25, 26, 33, 35, 31, 32, 36, 37, 40, 42, 44, 46,
    47, 48, 49, 50, 51, 58, 60, 56, 57, 61, 62, 65,
    67, 69, 71, 72, 73, 74, 75, 76, 83, 85, 81, 82,
    86, 88, 90, 92, 94, 96, 98, 0, 1, 12, 15, 17,
    19, 21, 22, 23, 24, 25, 26, 33, 35, 31, 32, 36,
    37, 40, 42, 44, 46, 47, 48, 49, 50, 51, 58, 60,
    56, 57, 61, 62, 65, 67, 69, 71, 72, 73, 74, 75,
    76, 83, 85, 81, 82, 86, 88, 90, 92, 94, 96, 98,
    0, 1, 12, 15, 17, 19, 21, 22, 23, 24, 25, 26,
    33, 35, 31, 32, 36, 37, 40, 42, 44, 46, 47, 48,
    49, 50, 51, 58, 60, 56, 57, 61, 62, 65, 67, 69,
    71, 72, 73, 74, 75, 76, 83, 85, 81, 82, 86, 88,
    90, 92, 94, 96, 98, 0, 1, 12, 15, 17, 19, 21,
    22, 23, 24, 25, 26, 33, 35, 31, 32, 36, 37, 40,
    42, 44, 46, 47, 48, 49, 50, 51, 58, 60, 56, 57,
    61, 62, 65, 67, 69, 71, 72, 73, 74, 75, 76, 83,
    85, 81, 82, 86, 88, 90, 92, 94, 96, 98, 0, 1,
    12, 15, 17, 19, 21, 22, 23, 24, 25, 26, 33, 35,
    31, 32, 36, 37, 40, 42, 44, 46, 47, 48, 49, 50,
    51, 58, 60, 56, 57, 61, 62, 65, 67, 69, 71, 72,
    73, 74, 75, 76, 83, 85, 81, 82, 86, 88, 90, 92,
    94, 96, 98, 0, 1, 12, 15, 17, 19, 21, 22, 23,
    24, 25, 26, 33, 35, 31, 32, 36, 37, 40, 42, 44,
    46, 47, 48, 49, 50, 51, 58, 60, 56, 57, 61, 62,
    65, 67, 69, 71, 72, 73, 74, 75, 76, 83, 85, 81,
    82, 86, 88, 90, 92, 94, 96, 98, 0, 1, 12, 15,
    17, 19, 21, 22, 23, 24, 25, 26, 33, 35, 31, 32,
    36, 37, 40, 42, 44, 46, 47, 48, 49, 50, 51, 58,
    60, 56, 57, 61, 62, 65, 67, 69, 71, 72, 73, 74,
    75, 76, 83, 85, 81, 82, 86, 88, 90, 92, 94, 96,
    98, 0, 1, 12, 15, 17, 19, 21, 22, 23, 24, 25,
    26, 33, 35, 31, 32, 36, 37, 40, 42, 44, 46, 47,
    48, 49, 50, 51, 58, 60, 56, 57, 61, 62, 65, 67,
    69, 71, 72, 73, 74, 75, 76, 83, 85, 81, 82, 86,
    88, 90, 92, 94, 96, 98, 0, 1, 12, 15, 17, 19,
    21, 22, 23, 24, 25, 26, 33, 35, 31, 32, 36, 37,
    40, 42, 44, 46, 47, 48, 49, 50, 51, 58, 60, 56,
    57, 61, 62, 65, 67, 69, 71, 72, 73, 74, 75, 76,
    83, 85, 81, 82, 86, 88, 90, 92, 94, 96, 98, 0,
    1, 12, 15, 17, 19, 21, 22, 23, 24, 25, 26, 33,
    35, 31, 32, 36, 37, 40, 42, 44, 46, 47, 48, 49,
    50, 51, 58, 60, 56, 57, 61, 62, 65, 67, 69, 71,
    72, 73, 74, 75, 76, 83, 85, 81, 82, 86, 88, 90,
    92, 94, 96, 98, 0, 1, 12, 17, 19, 21, 22, 23,
    24, 25, 26, 29, 30, 31, 31, 32, 36, 37, 42, 44,
    46, 47, 48, 49, 50, 51, 54, 55, 56, 56, 57, 61,
    62, 67, 69, 71, 72, 73, 74, 75, 76, 79, 80, 81,
    81, 82, 86, 88, 90, 92, 94, 96, 98, 0, 1, 12,
    17, 19, 21, 22, 23, 24, 25, 26, 29, 30, 31, 31,
    32, 36, 37, 42, 44, 46, 47, 48, 49, 50, 51, 54,
    55, 56, 56, 57, 61, 62, 67, 69, 71, 72, 73, 74,
    75, 76, 79, 80, 81, 81, 82, 86, 88, 90, 92, 94,
    96, 98, 0, 1, 12, 17, 19, 21, 22, 23, 24, 25,
    26, 29, 30, 31, 31, 32, 36, 37, 42, 44, 46, 47,
    48, 49, 50, 51, 54, 55, 56, 56, 57, 61, 62, 67,
    69, 71, 72, 73, 74, 75, 76, 79, 80, 81, 81, 82,
    86, 88, 90, 92, 94, 96, 98, 0, 1, 12, 17, 19,
    22, 23, 24, 26, 29, 30, 31, 31, 32, 36, 37, 42,
    47, 48, 49, 51, 54, 55, 56, 56, 57, 61, 62, 67,
    72, 73, 74, 76, 79, 80, 81, 81, 82, 86, 88, 90,
    92, 94, 96, 98, 0, 1, 12, 17, 19, 22, 23, 24,
    26, 29, 30, 31, 31, 32, 36, 37, 42, 47, 48, 49,
    51, 54, 55, 56, 56, 57, 61, 62, 67, 72, 73, 74,
    76, 79, 80, 81, 81, 82, 86, 88, 90, 92, 94, 96,
    98, 0, 1, 12, 17, 19, 22, 23, 24, 26, 29, 31,
    31, 32, 36, 37, 42, 47, 48, 49, 51, 54, 56, 56,
    57, 61, 62, 67, 72, 73, 74, 76, 79, 81, 81, 82,
    86, 88, 90, 92, 94, 96, 98, 0, 1, 12, 17, 19,
    22, 23, 24, 26, 29, 31, 31, 32, 36, 37, 42, 47,
    48, 49, 51, 54, 56, 56, 57, 61, 62, 67, 72, 73,
    74, 76, 79, 81, 81, 82, 86, 88, 90, 92, 94, 96,
    98, 0, 1, 12, 17, 19, 22, 23, 24, 26, 29, 31,
    31, 32, 36, 37, 42, 47, 48, 49, 51, 54, 56, 56,
    57, 61, 62, 67, 72, 73, 74, 76, 79, 81, 81, 82,
    86, 88, 90, 92, 94, 96, 98, 0, 1, 12, 17, 22,
    23, 24, 26, 29, 31, 31, 32, 36, 37, 42, 47, 48,
    49, 51, 54, 56, 56, 57, 61, 62, 67, 72, 73, 74,
    76, 79, 81, 81, 82, 86, 88, 90, 92, 94, 96, 98,
    0, 1, 12, 17, 22, 23, 24, 26, 29, 31, 31, 32,
    36, 37, 42, 47, 48, 49, 51, 54, 56, 56, 57, 61,
    62, 67, 72, 73, 74, 76, 79, 81, 81, 82, 86, 88,
    90, 92, 94, 96, 98, 0, 1, 12, 17, 22, 23, 24,
    26, 29, 31, 31, 32, 36, 37, 42, 47, 48, 49, 51,
    54, 56, 56, 57, 61, 62, 67, 72, 73, 74, 76, 79,
    81, 81, 82, 86, 88, 90, 92, 94, 96, 98, 0, 1,
    12, 17, 22, 23, 24, 26, 29, 31, 31, 32, 36, 37,
    42, 47, 48, 49, 51, 54, 56, 56, 57, 61, 62, 67,
    72, 73, 74, 76, 79, 81, 81, 82, 86, 88, 90, 92,
    94, 96, 98, 0, 1, 12, 17, 22, 23, 24, 26, 29,
    31, 31, 32, 36, 37, 42, 47, 48, 49, 51, 54, 56,
    56, 57, 61, 62, 67, 72, 73, 74, 76, 79, 81, 81,
    82, 86, 88, 90, 92, 94, 96, 98, 0, 1, 12, 17,
    22, 23, 24, 26, 29, 31, 31, 32, 36, 37, 42, 47,
    48, 49, 51, 54, 56, 56, 57, 61, 62, 67, 72, 73,
    74, 76, 79, 81, 81, 82, 86, 88, 90, 92, 94, 96,
    98, 0, 1, 12, 17, 22, 23, 24, 26, 29, 31, 31,
    32, 36, 37, 42, 47, 48, 49, 51, 54, 56, 56, 57,
    61, 62, 67, 72, 73, 74, 76, 79, 81, 81, 82, 86,
    88, 90, 92, 94, 96, 98, 0, 1, 12, 17, 22, 23,
    24, 26, 29, 31, 31, 32, 36, 37, 42, 47, 48, 49,
    51, 54, 56, 56, 57, 61, 62, 67, 72, 73, 74, 76,
    79, 81, 81, 82, 86, 88, 90, 92, 94, 96, 98, 0,
    1, 12, 17, 22, 23, 24, 26, 29, 31, 31, 32, 36,
    37, 42, 47, 48, 49, 51, 54, 56, 56, 57, 61, 62,
    67, 72, 73, 74, 76, 79, 81, 81, 82, 86, 88, 90,
    92, 94, 96, 98, 0, 1, 12, 17, 22, 23, 24, 26,
    29, 31, 31, 32, 36, 37, 42, 47, 48, 49, 51, 54,
    56, 56, 57, 61, 62, 67, 72, 73, 74, 76, 79, 81,
    81, 82, 86, 88, 90, 92, 94, 96, 98, 0, 1, 12,
    17, 22, 23, 24, 26, 29, 31, 31, 32, 36, 37, 42,
    47, 48, 49, 51, 54, 56, 56, 57, 61, 62, 67, 72,
    73, 74, 76, 79, 81, 81, 82, 86, 88, 90, 92, 94,
    96, 98, 0, 1, 12, 17, 22, 23, 24, 26, 29, 31,
    31, 32, 36, 37, 42, 47, 48, 49, 51, 54, 56, 56,
    57, 61, 62, 67, 72, 73, 74, 76, 79, 81, 81, 82,
    86, 88, 90, 92, 94, 96, 98, 0, 1, 12, 17, 22,
    23, 24, 26, 29, 31, 31, 32, 36, 37, 42, 47, 48,
    49, 51, 54, 56, 56, 57, 61, 62, 67, 72, 73, 74,
    76, 79, 81, 81, 82, 86, 88, 90, 92, 94, 96, 98,
    0, 1, 12, 17, 22, 23, 24, 26, 29, 31, 31, 32,
    36, 37, 42, 47, 48, 49, 51, 54, 56, 56, 57, 61,
    62, 67, 72, 73, 74, 76, 79, 81, 81, 82, 86, 88,
    90, 92, 94, 96, 98, 0, 1, 12, 17, 22, 23, 24,
    26, 29, 31, 31, 32, 36, 37, 42, 47, 48, 49, 51,
    54, 56, 56, 57, 61, 62, 67, 72, 73, 74, 76, 79,
    81, 81, 82, 86, 88, 90, 92, 94, 96, 98, 0, 1,
    12, 17, 22, 23, 24, 26, 29, 31, 31, 32, 36, 37,
    42, 47, 48, 49, 51, 54, 56, 56, 57, 61, 62, 67,
    72, 73, 74, 76, 79, 81, 81, 82, 86, 88, 90, 92,
    94, 96, 98, 0, 1, 12, 17, 22, 23, 24, 26, 29,
    31, 31, 32, 36, 37, 42, 47, 48, 49, 51, 54, 56,
    56, 57, 61, 62, 67, 72, 73, 74, 76, 79, 81, 81,
    82, 86, 88, 90, 92, 94, 96, 98, 0, 1, 12, 17,
    22, 23, 24, 26, 29, 31, 31, 32, 36, 37, 42, 47,
    48, 49, 51, 54, 56, 56, 57, 61, 62, 67, 72, 73,
    74, 76, 79, 81, 81, 82, 86, 88, 90, 92, 94, 96,
    98, 0, 1, 12, 17, 22, 23, 24, 26, 29, 31, 31,
    32, 36, 37, 42, 47, 48, 49, 51, 54, 56, 56, 57,
    61, 62, 67, 72, 73, 74, 76, 79, 81, 81, 82, 86,
    88, 90, 92, 94, 96, 98, 0, 1, 12, 17, 22, 24,
    26, 29, 31, 31, 32, 36, 37, 42, 47, 49, 51, 54,
    56, 56, 57, 61, 62, 67, 72, 74, 76, 79, 81, 81,
    82, 86, 88, 90, 92, 94, 96, 98, 0, 1, 12, 17,
    22, 24, 26, 29, 31, 31, 32, 36, 37, 42, 47, 49,
    51, 54, 56, 56, 57, 61, 62, 67, 72, 74, 76, 79,
    81, 81, 82, 86, 88, 90, 92, 94, 96, 98, 0, 1,
    12, 17, 22, 24, 26, 29, 31, 31, 32, 36, 37, 42,
    47, 49, 51, 54, 56, 56, 57, 61, 62, 67, 72, 74,
    76, 79, 81, 81, 82, 86, 88, 90, 92, 94, 96, 98,
    0, 1, 12, 17, 22, 24, 26, 29, 31, 31, 32, 36,
    37, 42, 47, 49, 51, 54, 56, 56, 57, 61, 62, 67,
    72, 74, 76, 79, 81, 81, 82, 86, 88, 90, 92, 94,
    96, 98, 0, 1, 12, 17, 22, 24, 26, 29, 31, 31,
    32, 36, 37, 42, 47, 49, 51, 54, 56, 56, 57, 61,
    62, 67, 72, 74, 76, 79, 81, 81, 82, 86, 88, 90,
    92, 94, 96, 98, 0, 1, 12, 17, 22, 24, 26, 29,
    31, 31, 32, 36, 37, 42, 47, 49, 51, 54, 56, 56,
    57, 61, 62, 67, 72, 74, 76, 79, 81, 81, 82, 86,
    88, 90, 92, 94, 96, 98, 0, 1, 12, 17, 22, 24,
    26, 29, 31, 31, 32, 36, 37, 42, 47, 49, 51, 54,
    56, 56, 57, 61, 62, 67, 72, 74, 76, 79, 81, 81,
    82, 86, 88, 90, 92, 94, 96, 98, 0, 1, 12, 17,
    22, 24, 26, 29, 31, 31, 32, 36, 37, 42, 47, 49,
    51, 54, 56, 56, 57, 61, 62, 67, 72, 74, 76, 79,
    81, 81, 82, 86, 88, 90, 92, 94, 96, 98, 0, 1,
    12, 17, 22, 24, 26, 29, 31, 31, 32, 36, 37, 42,
    47, 49, 51, 54, 56, 56, 57, 61, 62, 67, 72, 74,
    76, 79, 81, 81, 82, 86, 88, 90, 92, 94, 96, 98,
    0, 1, 12, 17, 22, 24, 26, 29, 31, 31, 32, 36,
    37, 42, 47, 49, 51, 54, 56, 56, 57, 61, 62, 67,
    72, 74, 76, 79, 81, 81, 82, 86, 88, 90, 92, 94,
    96, 98, 0, 1, 12, 17, 22, 24, 26, 29, 31, 31,
    32, 36, 37, 42, 47, 49, 51, 54, 56, 56, 57, 61,
    62, 67, 72, 74, 76, 79, 81, 81, 82, 86, 88, 90,
    92, 94, 96, 98, 0, 1, 12, 17, 22, 24, 26, 29,
    31, 31, 32, 36, 37, 42, 47, 49, 51, 54, 56, 56,
    57, 61, 62, 67, 72, 74, 76, 79, 81, 81, 82, 86,
    88, 90, 92, 94, 96, 98, 0, 1, 12, 17, 22, 24,
    26, 29, 31, 31, 32, 36, 37, 42, 47, 49, 51, 54,
    56, 56, 57, 61, 62, 67, 72, 74, 76, 79, 81, 81,
    82, 86, 88, 90, 92, 94, 96, 98, 0, 1, 12, 17,
    22, 24, 26, 29, 31, 31, 32, 36, 37, 42, 47, 49,
    51, 54, 56, 56, 57, 61, 62, 67, 72, 74, 76, 79,
    81, 81, 82, 86, 88, 90, 92, 94, 96, 98, 0, 1,
    12, 17, 22, 24, 26, 29, 31, 31, 32, 36, 37, 42,
    47, 49, 51, 54, 56, 56, 57, 61, 62, 67, 72, 74,
    76, 79, 81, 81, 82, 86, 88, 90, 92, 94, 96, 98,
    0, 1, 12, 17, 22, 24, 26, 29, 31, 31, 32, 36,
    37, 42, 47, 49, 51, 54, 56, 56, 57, 61, 62, 67,
    72, 74, 76, 79, 81, 81, 82, 86, 88, 90, 92, 94,
    96, 98, 0, 1, 12, 17, 22, 24, 26, 29, 31, 31,
    32, 37, 42, 47, 49, 51, 54, 56, 56, 57, 62, 67,
    72, 74, 76, 79, 81, 81, 82, 88, 90, 92, 94, 96,
    98, 0, 1, 12, 17, 22, 24, 26, 29, 31, 31, 32,
    37, 42, 47, 49, 51, 54, 56, 56, 57, 62, 67, 72,
    74, 76, 79, 81, 81, 82, 88, 90, 92, 94, 96, 98,
    0, 1, 12, 17, 22, 24, 26, 29, 31, 31, 32, 37,
    42, 47, 49, 51, 54, 56, 56, 57, 62, 67, 72, 74,
    76, 79, 81, 81, 82, 88, 90, 92, 94, 96, 98, 0,
    1, 12, 17, 22, 24, 26, 29, 31, 31, 32, 37, 42,
    47, 49, 51, 54, 56, 56, 57, 62, 67, 72, 74, 76,
    79, 81, 81, 82, 88, 90, 92, 94, 96, 98, 0, 1,
    12, 17, 22, 24, 26, 29, 31, 31, 32, 37, 42, 47,
    49, 51, 54, 56, 56, 57, 62, 67, 72, 74, 76, 79,
    81, 81, 82, 88, 90, 92, 94, 96, 98, 0, 1, 12,
    17, 22, 24, 26, 29, 31, 31, 32, 37, 42, 47, 49,
    51, 54, 56, 56, 57, 62, 67, 72, 74, 76, 79, 81,
    81, 82, 88, 90, 92, 94, 96, 98, 0, 1, 12, 17,
    22, 24, 26, 29, 31, 31, 32, 37, 42, 47, 49, 51,
    54, 56, 56, 57, 62, 67, 72, 74, 76, 79, 81, 81,
    82, 88, 90, 92, 94, 96, 98, 0, 1, 12, 17, 22,
    24, 26, 29, 31, 31, 32, 37, 42, 47, 49, 51, 54,
    56, 56, 57, 62, 67, 72, 74, 76, 79, 81, 81, 82,
    88, 90, 92, 94, 96, 98, 0, 1, 12, 17, 22, 24,
    26, 29, 31, 31, 32, 37, 42, 47, 49, 51, 54, 56,
    56, 57, 62, 67, 72, 74, 76, 79, 81, 81, 82, 88,
    90, 92, 94, 96, 98, 0, 1, 12, 17, 22, 24, 26,
    29, 31, 31, 32, 37, 42, 47, 49, 51, 54, 56, 56,
    57, 62, 67, 72, 74, 76, 79, 81, 81, 82, 88, 90,
    92, 94, 96, 98, 0, 1, 12, 17, 22, 24, 26, 29,
    31, 31, 32, 37, 42, 47, 49, 51, 54, 56, 56, 57,
    62, 67, 72, 74, 76, 79, 81, 81, 82, 88, 90, 92,
    94, 96, 98, 0, 1, 12, 17, 22, 24, 26, 29, 31,
    31, 32, 37, 42, 47, 49, 51, 54, 56, 56, 57, 62,
    67, 72, 74, 76, 79, 81, 81, 82, 88, 90, 92, 94,
    96, 98, 0, 1, 12, 17, 22, 24, 26, 29, 31, 31,
    32, 37, 42, 47, 49, 51, 54, 56, 56, 57, 62, 67,
    72, 74, 76, 79, 81, 81, 82, 88, 90, 92, 94, 96,
    98, 0, 1, 12, 17, 22, 24, 26, 29, 31, 31, 32,
    37, 42, 47, 49, 51, 54, 56, 56, 57, 62, 67, 72,
    74, 76, 79, 81, 81, 82, 88, 90, 92, 94, 96, 98,
    0, 1, 12, 17, 22, 24, 26, 29, 31, 31, 32, 37,
    42, 47, 49, 51, 54, 56, 56, 57, 62, 67, 72, 74,
    76, 79, 81, 81, 82, 88, 90, 92, 94, 96, 98, 0,
    1, 12, 17, 22, 24, 26, 29, 31, 31, 32, 37, 42,
    47, 49, 51, 54, 56, 56, 57, 62, 67, 72, 74, 76,
    79, 81, 81, 82, 88, 90, 92, 94, 96, 98, 1, 12,
    17, 22, 24, 26, 29, 31, 31, 32, 37, 42, 47, 49,
    51, 54, 56, 56, 57, 62, 67, 72, 74, 76, 79, 81,
    81, 82, 88, 90, 92, 94, 96, 98, 1, 12, 17, 22,
    24, 26, 29, 31, 31, 32, 37, 42, 47, 49, 51, 54,
    56, 56, 57, 62, 67, 72, 74, 76, 79, 81, 81, 82,
    88, 90, 92, 94, 96, 98, 1, 12, 17, 22, 24, 26,
    29, 31, 31, 32, 37, 42, 47, 49, 51, 54, 56, 56,
    57, 62, 67, 72, 74, 76, 79, 81, 81, 82, 88, 90,
    92, 94, 96, 98, 1, 12, 17, 22, 24, 26, 29, 31,
    31, 32, 37, 42, 47, 49, 51, 54, 56, 56, 57, 62,
    67, 72, 74, 76, 79, 81, 81, 82, 88, 90, 92, 94,
    96, 98, 1, 12, 17, 22, 24, 26, 29, 31, 31, 32,
    37, 42, 47, 49, 51, 54, 56, 56, 57, 62, 67, 72,
    74, 76, 79, 81, 81, 82, 88, 90, 92, 94, 96, 98,
    1, 12, 17, 22, 24, 26, 29, 31, 31, 32, 37, 42,
    47, 49, 51, 54, 56, 56, 57, 62, 67, 72, 74, 76,
    79, 81, 81, 82, 88, 90, 92, 94, 96, 98, 1, 12,
    17, 22, 24, 26, 29, 31, 31, 32, 37, 42, 47, 49,
    51, 54, 56, 56, 57, 62, 67, 72, 74, 76, 79, 81,
    81, 82, 88, 90, 92, 94, 96, 98, 1, 12, 17, 22,
    24, 26, 29, 31, 31, 32, 37, 42, 47, 49, 51, 54,
    56, 56, 57, 62, 67, 72, 74, 76, 79, 81, 81, 82,
    88, 90, 92, 94, 96, 98, 1, 12, 17, 22, 24, 26,
    29, 31, 31, 32, 37, 42, 47, 49, 51, 54, 56, 56,
    57, 62, 67, 72, 74, 76, 79, 81, 81, 82, 88, 90,
    92, 94, 96, 98, 1, 12, 17, 22, 24, 26, 29, 31,
    31, 32, 37, 42, 47, 49, 51, 54, 56, 56, 57, 62,
    67, 72, 74, 76, 79, 81, 81, 82, 88, 90, 92, 94,
    96, 98, 1, 12, 17, 22, 24, 26, 29, 31, 31, 32,
    37, 42, 47, 49, 51, 54, 56, 56, 57, 62, 67, 72,
    74, 76, 79, 81, 81, 82, 88, 90, 92, 94, 96, 98,
    1, 12, 17, 22, 24, 26, 29, 31, 31, 32, 37, 42,
    47, 49, 51, 54, 56, 56, 57, 62, 67, 72, 74, 76,
    79, 81, 81, 82, 88, 90, 92, 94, 96, 98, 1, 12,
    17, 22, 24, 26, 29, 31, 31, 32, 37, 42, 47, 49,
    51, 54, 56, 56, 57, 62, 67, 72, 74, 76, 79, 81,
    81, 82, 88, 90, 92, 94, 96, 98, 1, 12, 17, 22,
    24, 26, 29, 31, 31, 32, 37, 42, 47, 49, 51, 54,
    56, 56, 57, 62, 67, 72, 74, 76, 79, 81, 81, 82,
    88, 90, 92, 94, 96, 98, 1, 12, 17, 22, 24, 26,
    29, 31, 31, 32, 37, 42, 47, 49, 51, 54, 56, 56,
    57, 62, 67, 72, 74, 76, 79, 81, 81, 82, 88, 90,
    92, 94, 96, 98, 1, 12, 17, 22, 24, 26, 29, 31,
    31, 32, 37, 42, 47, 49, 51, 54, 56, 56, 57, 62,
    67, 72, 74, 76, 79, 81, 81, 82, 88, 90, 92, 94,
    96, 98, 1, 12, 17, 22, 24, 26, 29, 31, 31, 32,
    37, 42, 47, 49, 51, 54, 56, 56, 57, 62, 67, 72,
    74, 76, 79, 81, 81, 82, 88, 90, 92, 94, 96, 98,
    1, 12, 17, 22, 24, 26, 29, 31, 31, 32, 37, 42,
    47, 49, 51, 54, 56, 56, 57, 62, 67, 72, 74, 76,
    79, 81, 81, 82, 88, 90, 92, 94, 96, 98, 1, 12,
    17, 22, 24, 26, 29, 31, 31, 32, 37, 42, 47, 49,
    51, 54, 56, 56, 57, 62, 67, 72, 74, 76, 79, 81,
    81, 82, 88, 90, 92, 94, 96, 98, 1, 12, 17, 22,
    24, 26, 29, 31, 31, 32, 37, 42, 47, 49, 51, 54,
    56, 56, 57, 62, 67, 72, 74, 76, 79, 81, 81, 82,
    88, 90, 92, 94, 96, 98, 1, 12, 17, 22, 24, 26,
    29, 31, 31, 32, 37, 42, 47, 49, 51, 54, 56, 56,
    57, 62, 67, 72, 74, 76, 79, 81, 81, 82, 88, 90,
    92, 94, 96, 98, 1, 12, 17, 22, 24, 26, 31, 31,
    32, 37, 42, 47, 49, 51, 56, 56, 57, 62, 67, 72,
    74, 76, 81, 81, 82, 88, 90, 92, 94, 96, 98, 1,
    12, 17, 22, 24, 26, 31, 31, 32, 37, 42, 47, 49,
    51, 56, 56, 57, 62, 67, 72, 74, 76, 81, 81, 82,
    88, 90, 92, 94, 96, 98, 1, 12, 17, 22, 24, 26,
    31, 31, 32, 37, 42, 47, 49, 51, 56, 56, 57, 62,
    67, 72, 74, 76, 81, 81, 82, 88, 90, 92, 94, 96,
    98, 1, 2, 3, 5, 17, 22, 24, 31, 31, 32, 42,
    47, 49, 56, 56, 57, 67, 72, 74, 81, 81, 82, 88,
    90, 92, 94, 96, 98, 1, 2, 3, 5, 17, 22, 24,
    31, 31, 32, 42, 47, 49, 56, 56, 57, 67, 72, 74,
    81, 81, 82, 88, 90, 92, 94, 96, 98, 1, 2, 3,
    5, 17, 22, 24, 31, 31, 32, 42, 47, 49, 56, 56,
    57, 67, 72, 74, 81, 81, 82, 88, 90, 92, 94, 96,
    98, 1, 2, 3, 5, 17, 22, 24, 31, 31, 32, 42,
    47, 49, 56, 56, 57, 67, 72, 74, 81, 81, 82, 88,
    90, 92, 94, 96, 98, 1, 2, 3, 5, 17, 22, 24,
    31, 31, 32, 42, 47, 49, 56, 56, 57, 67, 72, 74,
    81, 81, 82, 88, 90, 92, 94, 96, 98, 1, 2, 3,
    5, 17, 22, 24, 31, 32, 42, 47, 49, 56, 57, 67,
    72, 74, 81, 82, 88, 90, 92, 94, 96, 98, 1, 2,
    3, 5, 17, 22, 24, 31, 32, 42, 47, 49, 56, 57,
    67, 72, 74, 81, 82, 88, 90, 92, 94, 96, 98, 1,
    2, 3, 5, 17, 22, 24, 31, 32, 42, 47, 49, 56,
    57, 67, 72, 74, 81, 82, 88, 90, 92, 94, 96, 98,
    4, 4, 4, 4, 5, 6, 18, 20, 31, 8, 43, 45,
    56, 10, 68, 70, 81, 88, 90, 92, 94, 96, 98, 4,
    4, 4, 4, 5, 6, 18, 20, 31, 8, 43, 45, 56,
    10, 68, 70, 81, 88, 90, 92, 94, 96, 98, 4, 4,
    4, 4, 5, 6, 18, 20, 31, 8, 43, 45, 56, 10,
    68, 70, 81, 88, 90, 92, 94, 96, 98, 4, 4, 4,
    4, 5, 6, 18, 20, 31, 8, 43, 45, 56, 10, 68,
    70, 81, 88, 90, 92, 94, 96, 98, 4, 4, 4, 4,
    5, 6, 18, 20, 31, 8, 43, 45, 56, 10, 68, 70,
    81, 88, 90, 92, 94, 96, 98, 4, 4, 4, 4, 5,
    6, 18, 31, 8, 43, 56, 10, 68, 81, 88, 90, 92,
    94, 96, 98, 4, 4, 4, 4, 5, 6, 18, 31, 8,
    43, 56, 10, 68, 81, 88, 90, 92, 94, 96, 98, 4,
    4, 4, 4, 5, 6, 18, 31, 8, 43, 56, 10, 68,
    81, 88, 90, 92, 94, 96, 98, 4, 4, 4, 5, 6,
    7, 31, 8, 43, 56, 10, 68, 81, 88, 90, 92, 94,
    96, 98, 4, 4, 4, 5, 6, 31, 8, 43, 56, 10,
    68, 81, 88, 90, 92, 94, 96, 98, 4, 4, 4, 5,
    6, 31, 8, 43, 56, 10, 68, 81, 88, 90, 92, 94,
    96, 98, 4, 4, 4, 5, 6, 31, 8, 43, 56, 10,
    68, 81, 88, 90, 92, 94, 96, 98, 4, 4, 4, 5,
    6, 31, 8, 43, 56, 10, 68, 81, 88, 90, 92, 94,
    96, 98, 4, 4, 4, 5, 6, 31, 8, 43, 56, 10,
    68, 81, 88, 90, 92, 94, 96, 98, 4, 4, 4, 5,
    6, 31, 8, 43, 56, 10, 68, 81, 88, 90, 92, 94,
    96, 98, 4, 4, 4, 5, 6, 31, 8, 43, 56, 10,
    68, 81, 88, 90, 92, 94, 96, 98, 4, 4, 4, 5,
    18, 31, 9, 56, 11, 81, 88, 90, 92, 94, 96, 98,
    4, 4, 4, 5, 18, 31, 56, 81, 89, 4, 4, 4,
    5, 18, 31, 56, 81, 4, 4, 4, 5, 18, 31, 56,
    81, 4, 4, 4, 5, 18, 31, 56, 81, 4, 4, 4,
    5, 18, 31, 56, 81, 4, 4, 4, 5, 18, 31, 56,
    81, 4, 4, 4, 5, 18, 31, 56, 81,
};

static __device__ __constant__ uint16_t kStaticTaskClaims[5793] = {
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 120, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    120, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 120, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 121, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 121, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 121, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2,
    2, 2, 2, 2, 2, 2, 2, 2, 122, 2, 2, 2,
    2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
    2, 2, 2, 122, 2, 2, 2, 2, 2, 2, 2, 2,
    2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 122, 2,
    2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3,
    3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
    3, 123, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
    3, 3, 3, 3, 3, 3, 3, 3, 123, 3, 3, 3,
    3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
    3, 3, 3, 123, 3, 3, 3, 3, 3, 3, 3, 3,
    3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
    4, 4, 4, 4, 4, 4, 124, 4, 4, 4, 4, 4,
    4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
    4, 124, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
    4, 4, 4, 4, 4, 4, 4, 4, 124, 4, 4, 4,
    4, 4, 4, 4, 4, 4, 5, 5, 5, 0, 5, 0,
    5, 5, 5, 5, 5, 5, 0, 115, 5, 5, 5, 0,
    5, 5, 5, 5, 5, 5, 5, 5, 0, 115, 5, 5,
    5, 0, 5, 5, 5, 5, 5, 5, 5, 5, 0, 115,
    5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 1,
    6, 1, 6, 6, 6, 6, 6, 6, 1, 116, 6, 6,
    6, 1, 6, 6, 6, 6, 6, 6, 6, 6, 1, 116,
    6, 6, 6, 1, 6, 6, 6, 6, 6, 6, 6, 6,
    1, 116, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7,
    7, 2, 7, 2, 7, 7, 7, 7, 7, 7, 2, 117,
    7, 7, 7, 2, 7, 7, 7, 7, 7, 7, 7, 7,
    2, 117, 7, 7, 7, 2, 7, 7, 7, 7, 7, 7,
    7, 7, 2, 117, 7, 7, 7, 7, 7, 7, 7, 7,
    8, 8, 8, 3, 8, 3, 8, 8, 8, 8, 8, 8,
    3, 118, 8, 8, 8, 3, 8, 8, 8, 8, 8, 8,
    8, 8, 3, 118, 8, 8, 8, 3, 8, 8, 8, 8,
    8, 8, 8, 8, 3, 118, 8, 8, 8, 8, 8, 8,
    8, 8, 9, 9, 9, 4, 9, 4, 9, 9, 9, 9,
    9, 9, 4, 119, 9, 9, 9, 4, 9, 9, 9, 9,
    9, 9, 9, 9, 4, 119, 9, 9, 9, 4, 9, 9,
    9, 9, 9, 9, 9, 9, 4, 119, 9, 9, 9, 9,
    9, 9, 9, 9, 10, 10, 10, 5, 10, 5, 10, 10,
    10, 10, 10, 10, 5, 5, 5, 125, 10, 10, 10, 5,
    10, 10, 10, 10, 10, 10, 10, 10, 5, 5, 5, 125,
    10, 10, 10, 5, 10, 10, 10, 10, 10, 10, 10, 10,
    5, 5, 5, 125, 10, 10, 10, 10, 10, 10, 10, 10,
    11, 11, 11, 6, 11, 6, 11, 11, 11, 11, 11, 11,
    6, 6, 6, 126, 11, 11, 11, 6, 11, 11, 11, 11,
    11, 11, 11, 11, 6, 6, 6, 126, 11, 11, 11, 6,
    11, 11, 11, 11, 11, 11, 11, 11, 6, 6, 6, 126,
    11, 11, 11, 11, 11, 11, 11, 11, 12, 12, 12, 7,
    12, 7, 12, 12, 12, 12, 12, 12, 7, 7, 7, 127,
    12, 12, 12, 7, 12, 12, 12, 12, 12, 12, 12, 12,
    7, 7, 7, 127, 12, 12, 12, 7, 12, 12, 12, 12,
    12, 12, 12, 12, 7, 7, 7, 127, 12, 12, 12, 12,
    12, 12, 12, 12, 13, 13, 13, 8, 13, 8, 13, 13,
    13, 13, 13, 13, 8, 8, 8, 128, 13, 13, 13, 8,
    13, 13, 13, 13, 13, 13, 13, 13, 8, 8, 8, 128,
    13, 13, 13, 8, 13, 13, 13, 13, 13, 13, 13, 13,
    8, 8, 8, 128, 13, 13, 13, 13, 13, 13, 13, 13,
    14, 14, 14, 9, 14, 9, 14, 14, 14, 14, 14, 14,
    9, 9, 9, 129, 14, 14, 14, 9, 14, 14, 14, 14,
    14, 14, 14, 14, 9, 9, 9, 129, 14, 14, 14, 9,
    14, 14, 14, 14, 14, 14, 14, 14, 9, 9, 9, 129,
    14, 14, 14, 14, 14, 14, 14, 14, 15, 15, 15, 10,
    15, 10, 15, 15, 15, 15, 15, 15, 10, 10, 10, 130,
    15, 15, 15, 10, 15, 15, 15, 15, 15, 15, 15, 15,
    10, 10, 10, 130, 15, 15, 15, 10, 15, 15, 15, 15,
    15, 15, 15, 15, 10, 10, 10, 130, 15, 15, 15, 15,
    15, 15, 15, 15, 16, 16, 16, 11, 16, 11, 16, 16,
    16, 16, 16, 16, 11, 11, 11, 131, 16, 16, 16, 11,
    16, 16, 16, 16, 16, 16, 16, 16, 11, 11, 11, 131,
    16, 16, 16, 11, 16, 16, 16, 16, 16, 16, 16, 16,
    11, 11, 11, 131, 16, 16, 16, 16, 16, 16, 16, 16,
    17, 17, 17, 12, 17, 12, 17, 17, 17, 17, 17, 17,
    12, 12, 12, 132, 17, 17, 17, 12, 17, 17, 17, 17,
    17, 17, 17, 17, 12, 12, 12, 132, 17, 17, 17, 12,
    17, 17, 17, 17, 17, 17, 17, 17, 12, 12, 12, 132,
    17, 17, 17, 17, 17, 17, 17, 17, 18, 18, 18, 13,
    18, 13, 18, 18, 18, 18, 18, 18, 13, 13, 13, 133,
    18, 18, 18, 13, 18, 18, 18, 18, 18, 18, 18, 18,
    13, 13, 13, 133, 18, 18, 18, 13, 18, 18, 18, 18,
    18, 18, 18, 18, 13, 13, 13, 133, 18, 18, 18, 18,
    18, 18, 18, 18, 19, 19, 19, 14, 19, 14, 19, 19,
    19, 19, 19, 19, 14, 14, 14, 134, 19, 19, 19, 14,
    19, 19, 19, 19, 19, 19, 19, 19, 14, 14, 14, 134,
    19, 19, 19, 14, 19, 19, 19, 19, 19, 19, 19, 19,
    14, 14, 14, 134, 19, 19, 19, 19, 19, 19, 19, 19,
    20, 20, 20, 15, 20, 15, 20, 20, 20, 20, 20, 20,
    15, 15, 15, 135, 20, 20, 20, 15, 20, 20, 20, 20,
    20, 20, 20, 20, 15, 15, 15, 135, 20, 20, 20, 15,
    20, 20, 20, 20, 20, 20, 20, 20, 15, 15, 15, 135,
    20, 20, 20, 20, 20, 20, 20, 20, 21, 21, 21, 16,
    21, 16, 21, 21, 21, 21, 21, 21, 16, 16, 16, 136,
    21, 21, 21, 16, 21, 21, 21, 21, 21, 21, 21, 21,
    16, 16, 16, 136, 21, 21, 21, 16, 21, 21, 21, 21,
    21, 21, 21, 21, 16, 16, 16, 136, 21, 21, 21, 21,
    21, 21, 21, 21, 22, 22, 22, 17, 22, 17, 22, 22,
    22, 22, 22, 22, 17, 17, 17, 137, 22, 22, 22, 17,
    22, 22, 22, 22, 22, 22, 22, 22, 17, 17, 17, 137,
    22, 22, 22, 17, 22, 22, 22, 22, 22, 22, 22, 22,
    17, 17, 17, 137, 22, 22, 22, 22, 22, 22, 22, 22,
    23, 23, 23, 18, 23, 18, 23, 23, 23, 23, 23, 23,
    18, 18, 18, 138, 23, 23, 23, 18, 23, 23, 23, 23,
    23, 23, 23, 23, 18, 18, 18, 138, 23, 23, 23, 18,
    23, 23, 23, 23, 23, 23, 23, 23, 18, 18, 18, 138,
    23, 23, 23, 23, 23, 23, 23, 23, 24, 24, 24, 19,
    24, 19, 24, 24, 24, 24, 24, 24, 19, 19, 19, 139,
    24, 24, 24, 19, 24, 24, 24, 24, 24, 24, 24, 24,
    19, 19, 19, 139, 24, 24, 24, 19, 24, 24, 24, 24,
    24, 24, 24, 24, 19, 19, 19, 139, 24, 24, 24, 24,
    24, 24, 24, 24, 25, 25, 25, 20, 25, 20, 25, 25,
    25, 25, 25, 25, 20, 20, 140, 25, 25, 25, 20, 25,
    25, 25, 25, 25, 25, 25, 25, 20, 20, 140, 25, 25,
    25, 20, 25, 25, 25, 25, 25, 25, 25, 25, 20, 20,
    140, 25, 25, 25, 25, 25, 25, 25, 25, 26, 26, 26,
    21, 26, 21, 26, 26, 26, 26, 26, 26, 21, 21, 141,
    26, 26, 26, 21, 26, 26, 26, 26, 26, 26, 26, 26,
    21, 21, 141, 26, 26, 26, 21, 26, 26, 26, 26, 26,
    26, 26, 26, 21, 21, 141, 26, 26, 26, 26, 26, 26,
    26, 26, 27, 27, 27, 22, 27, 22, 27, 27, 27, 27,
    27, 27, 22, 22, 142, 27, 27, 27, 22, 27, 27, 27,
    27, 27, 27, 27, 27, 22, 22, 142, 27, 27, 27, 22,
    27, 27, 27, 27, 27, 27, 27, 27, 22, 22, 142, 27,
    27, 27, 27, 27, 27, 27, 27, 28, 28, 28, 23, 28,
    23, 28, 28, 28, 28, 28, 28, 23, 23, 143, 28, 28,
    28, 23, 28, 28, 28, 28, 28, 28, 28, 28, 23, 23,
    143, 28, 28, 28, 23, 28, 28, 28, 28, 28, 28, 28,
    28, 23, 23, 143, 28, 28, 28, 28, 28, 28, 28, 28,
    29, 29, 29, 24, 29, 24, 29, 29, 29, 29, 29, 29,
    24, 24, 144, 29, 29, 29, 24, 29, 29, 29, 29, 29,
    29, 29, 29, 24, 24, 144, 29, 29, 29, 24, 29, 29,
    29, 29, 29, 29, 29, 29, 24, 24, 144, 29, 29, 29,
    29, 29, 29, 29, 29, 30, 30, 30, 25, 30, 25, 30,
    30, 30, 30, 30, 30, 25, 25, 145, 30, 30, 30, 25,
    30, 30, 30, 30, 30, 30, 30, 30, 25, 25, 145, 30,
    30, 30, 25, 30, 30, 30, 30, 30, 30, 30, 30, 25,
    25, 145, 30, 30, 30, 30, 30, 30, 30, 30, 31, 31,
    31, 26, 31, 26, 31, 31, 31, 31, 31, 31, 26, 26,
    146, 31, 31, 31, 26, 31, 31, 31, 31, 31, 31, 31,
    31, 26, 26, 146, 31, 31, 31, 26, 31, 31, 31, 31,
    31, 31, 31, 31, 26, 26, 146, 31, 31, 31, 31, 31,
    31, 31, 31, 32, 32, 32, 27, 32, 27, 32, 32, 32,
    32, 32, 32, 27, 27, 147, 32, 32, 32, 27, 32, 32,
    32, 32, 32, 32, 32, 32, 27, 27, 147, 32, 32, 32,
    27, 32, 32, 32, 32, 32, 32, 32, 32, 27, 27, 147,
    32, 32, 32, 32, 32, 32, 32, 32, 33, 33, 33, 28,
    33, 28, 33, 33, 33, 33, 33, 33, 28, 28, 148, 33,
    33, 33, 28, 33, 33, 33, 33, 33, 33, 33, 33, 28,
    28, 148, 33, 33, 33, 28, 33, 33, 33, 33, 33, 33,
    33, 33, 28, 28, 148, 33, 33, 33, 33, 33, 33, 33,
    33, 34, 34, 34, 29, 34, 29, 34, 34, 34, 34, 34,
    34, 29, 29, 149, 34, 34, 34, 29, 34, 34, 34, 34,
    34, 34, 34, 34, 29, 29, 149, 34, 34, 34, 29, 34,
    34, 34, 34, 34, 34, 34, 34, 29, 29, 149, 34, 34,
    34, 34, 34, 34, 34, 34, 35, 35, 35, 30, 35, 30,
    35, 35, 35, 35, 35, 35, 30, 30, 150, 35, 35, 35,
    30, 35, 35, 35, 35, 35, 35, 35, 35, 30, 30, 150,
    35, 35, 35, 30, 35, 35, 35, 35, 35, 35, 35, 35,
    30, 30, 150, 35, 35, 35, 35, 35, 35, 35, 35, 36,
    36, 36, 31, 36, 31, 36, 36, 36, 36, 36, 36, 31,
    31, 151, 36, 36, 36, 31, 36, 36, 36, 36, 36, 36,
    36, 36, 31, 31, 151, 36, 36, 36, 31, 36, 36, 36,
    36, 36, 36, 36, 36, 31, 31, 151, 36, 36, 36, 36,
    36, 36, 36, 36, 37, 37, 37, 37, 32, 37, 37, 37,
    37, 37, 37, 0, 0, 0, 152, 37, 37, 37, 37, 37,
    37, 37, 37, 37, 37, 37, 0, 0, 0, 152, 37, 37,
    37, 37, 37, 37, 37, 37, 37, 37, 37, 0, 0, 0,
    152, 37, 37, 37, 37, 37, 37, 37, 37, 38, 38, 38,
    38, 33, 38, 38, 38, 38, 38, 38, 1, 1, 1, 153,
    38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 1,
    1, 1, 153, 38, 38, 38, 38, 38, 38, 38, 38, 38,
    38, 38, 1, 1, 1, 153, 38, 38, 38, 38, 38, 38,
    38, 38, 39, 39, 39, 39, 34, 39, 39, 39, 39, 39,
    39, 2, 2, 2, 154, 39, 39, 39, 39, 39, 39, 39,
    39, 39, 39, 39, 2, 2, 2, 154, 39, 39, 39, 39,
    39, 39, 39, 39, 39, 39, 39, 2, 2, 2, 154, 39,
    39, 39, 39, 39, 39, 39, 39, 40, 40, 40, 40, 35,
    40, 40, 40, 40, 3, 3, 3, 155, 40, 40, 40, 40,
    40, 40, 40, 40, 3, 3, 3, 155, 40, 40, 40, 40,
    40, 40, 40, 40, 3, 3, 3, 155, 40, 40, 40, 40,
    40, 40, 40, 40, 41, 41, 41, 41, 36, 41, 41, 41,
    41, 4, 4, 4, 156, 41, 41, 41, 41, 41, 41, 41,
    41, 4, 4, 4, 156, 41, 41, 41, 41, 41, 41, 41,
    41, 4, 4, 4, 156, 41, 41, 41, 41, 41, 41, 41,
    41, 42, 42, 42, 42, 37, 42, 42, 42, 42, 5, 5,
    157, 42, 42, 42, 42, 42, 42, 42, 42, 5, 5, 157,
    42, 42, 42, 42, 42, 42, 42, 42, 5, 5, 157, 42,
    42, 42, 42, 42, 42, 42, 42, 43, 43, 43, 43, 38,
    43, 43, 43, 43, 6, 6, 158, 43, 43, 43, 43, 43,
    43, 43, 43, 6, 6, 158, 43, 43, 43, 43, 43, 43,
    43, 43, 6, 6, 158, 43, 43, 43, 43, 43, 43, 43,
    43, 44, 44, 44, 44, 39, 44, 44, 44, 44, 7, 7,
    159, 44, 44, 44, 44, 44, 44, 44, 44, 7, 7, 159,
    44, 44, 44, 44, 44, 44, 44, 44, 7, 7, 159, 44,
    44, 44, 44, 44, 44, 44, 44, 45, 45, 45, 45, 45,
    45, 45, 45, 8, 8, 160, 45, 45, 45, 45, 45, 45,
    45, 45, 8, 8, 160, 45, 45, 45, 45, 45, 45, 45,
    45, 8, 8, 160, 45, 45, 45, 45, 45, 45, 45, 45,
    46, 46, 46, 46, 46, 46, 46, 46, 9, 9, 161, 46,
    46, 46, 46, 46, 46, 46, 46, 9, 9, 161, 46, 46,
    46, 46, 46, 46, 46, 46, 9, 9, 161, 46, 46, 46,
    46, 46, 46, 46, 46, 47, 47, 47, 47, 47, 47, 47,
    47, 10, 10, 162, 47, 47, 47, 47, 47, 47, 47, 47,
    10, 10, 162, 47, 47, 47, 47, 47, 47, 47, 47, 10,
    10, 162, 47, 47, 47, 47, 47, 47, 47, 47, 48, 48,
    48, 48, 48, 48, 48, 48, 11, 11, 163, 48, 48, 48,
    48, 48, 48, 48, 48, 11, 11, 163, 48, 48, 48, 48,
    48, 48, 48, 48, 11, 11, 163, 48, 48, 48, 48, 48,
    48, 48, 48, 49, 49, 49, 49, 49, 49, 49, 49, 12,
    12, 164, 49, 49, 49, 49, 49, 49, 49, 49, 12, 12,
    164, 49, 49, 49, 49, 49, 49, 49, 49, 12, 12, 164,
    49, 49, 49, 49, 49, 49, 49, 49, 50, 50, 50, 50,
    50, 50, 50, 50, 13, 13, 165, 50, 50, 50, 50, 50,
    50, 50, 50, 13, 13, 165, 50, 50, 50, 50, 50, 50,
    50, 50, 13, 13, 165, 50, 50, 50, 50, 50, 50, 50,
    50, 51, 51, 51, 51, 51, 51, 51, 51, 14, 14, 166,
    51, 51, 51, 51, 51, 51, 51, 51, 14, 14, 166, 51,
    51, 51, 51, 51, 51, 51, 51, 14, 14, 166, 51, 51,
    51, 51, 51, 51, 51, 51, 52, 52, 52, 52, 52, 52,
    52, 52, 15, 15, 167, 52, 52, 52, 52, 52, 52, 52,
    52, 15, 15, 167, 52, 52, 52, 52, 52, 52, 52, 52,
    15, 15, 167, 52, 52, 52, 52, 52, 52, 52, 52, 53,
    53, 53, 53, 53, 53, 53, 53, 16, 16, 168, 53, 53,
    53, 53, 53, 53, 53, 53, 16, 16, 168, 53, 53, 53,
    53, 53, 53, 53, 53, 16, 16, 168, 53, 53, 53, 53,
    53, 53, 53, 53, 54, 54, 54, 54, 54, 54, 54, 54,
    17, 17, 169, 54, 54, 54, 54, 54, 54, 54, 54, 17,
    17, 169, 54, 54, 54, 54, 54, 54, 54, 54, 17, 17,
    169, 54, 54, 54, 54, 54, 54, 54, 54, 55, 55, 55,
    55, 55, 55, 55, 55, 18, 18, 170, 55, 55, 55, 55,
    55, 55, 55, 55, 18, 18, 170, 55, 55, 55, 55, 55,
    55, 55, 55, 18, 18, 170, 55, 55, 55, 55, 55, 55,
    55, 55, 56, 56, 56, 56, 56, 56, 56, 56, 19, 19,
    171, 56, 56, 56, 56, 56, 56, 56, 56, 19, 19, 171,
    56, 56, 56, 56, 56, 56, 56, 56, 19, 19, 171, 56,
    56, 56, 56, 56, 56, 56, 56, 57, 57, 57, 57, 57,
    57, 57, 57, 20, 20, 172, 57, 57, 57, 57, 57, 57,
    57, 57, 20, 20, 172, 57, 57, 57, 57, 57, 57, 57,
    57, 20, 20, 172, 57, 57, 57, 57, 57, 57, 57, 57,
    58, 58, 58, 58, 58, 58, 58, 58, 21, 21, 173, 58,
    58, 58, 58, 58, 58, 58, 58, 21, 21, 173, 58, 58,
    58, 58, 58, 58, 58, 58, 21, 21, 173, 58, 58, 58,
    58, 58, 58, 58, 58, 59, 59, 59, 59, 59, 59, 59,
    59, 22, 22, 174, 59, 59, 59, 59, 59, 59, 59, 59,
    22, 22, 174, 59, 59, 59, 59, 59, 59, 59, 59, 22,
    22, 174, 59, 59, 59, 59, 59, 59, 59, 59, 60, 60,
    60, 60, 60, 60, 60, 60, 23, 23, 175, 60, 60, 60,
    60, 60, 60, 60, 60, 23, 23, 175, 60, 60, 60, 60,
    60, 60, 60, 60, 23, 23, 175, 60, 60, 60, 60, 60,
    60, 60, 60, 61, 61, 61, 61, 61, 61, 61, 61, 24,
    24, 176, 61, 61, 61, 61, 61, 61, 61, 61, 24, 24,
    176, 61, 61, 61, 61, 61, 61, 61, 61, 24, 24, 176,
    61, 61, 61, 61, 61, 61, 61, 61, 62, 62, 62, 62,
    62, 62, 62, 62, 25, 25, 177, 62, 62, 62, 62, 62,
    62, 62, 62, 25, 25, 177, 62, 62, 62, 62, 62, 62,
    62, 62, 25, 25, 177, 62, 62, 62, 62, 62, 62, 62,
    62, 63, 63, 63, 63, 63, 63, 63, 63, 26, 26, 178,
    63, 63, 63, 63, 63, 63, 63, 63, 26, 26, 178, 63,
    63, 63, 63, 63, 63, 63, 63, 26, 26, 178, 63, 63,
    63, 63, 63, 63, 63, 63, 64, 64, 64, 64, 64, 64,
    64, 27, 27, 179, 64, 64, 64, 64, 64, 64, 64, 27,
    27, 179, 64, 64, 64, 64, 64, 64, 64, 27, 27, 179,
    64, 64, 64, 64, 64, 64, 64, 64, 65, 65, 65, 65,
    65, 65, 65, 28, 28, 180, 65, 65, 65, 65, 65, 65,
    65, 28, 28, 180, 65, 65, 65, 65, 65, 65, 65, 28,
    28, 180, 65, 65, 65, 65, 65, 65, 65, 65, 66, 66,
    66, 66, 66, 66, 66, 29, 29, 181, 66, 66, 66, 66,
    66, 66, 66, 29, 29, 181, 66, 66, 66, 66, 66, 66,
    66, 29, 29, 181, 66, 66, 66, 66, 66, 66, 66, 66,
    67, 67, 67, 67, 67, 67, 67, 30, 30, 182, 67, 67,
    67, 67, 67, 67, 67, 30, 30, 182, 67, 67, 67, 67,
    67, 67, 67, 30, 30, 182, 67, 67, 67, 67, 67, 67,
    67, 67, 68, 68, 68, 68, 68, 68, 68, 31, 31, 183,
    68, 68, 68, 68, 68, 68, 68, 31, 31, 183, 68, 68,
    68, 68, 68, 68, 68, 31, 31, 183, 68, 68, 68, 68,
    68, 68, 68, 68, 69, 69, 69, 69, 69, 69, 69, 32,
    32, 184, 69, 69, 69, 69, 69, 69, 69, 32, 32, 184,
    69, 69, 69, 69, 69, 69, 69, 32, 32, 184, 69, 69,
    69, 69, 69, 69, 69, 69, 70, 70, 70, 70, 70, 70,
    70, 33, 33, 185, 70, 70, 70, 70, 70, 70, 70, 33,
    33, 185, 70, 70, 70, 70, 70, 70, 70, 33, 33, 185,
    70, 70, 70, 70, 70, 70, 70, 70, 71, 71, 71, 71,
    71, 71, 71, 34, 34, 186, 71, 71, 71, 71, 71, 71,
    71, 34, 34, 186, 71, 71, 71, 71, 71, 71, 71, 34,
    34, 186, 71, 71, 71, 71, 71, 71, 71, 71, 72, 72,
    72, 72, 72, 72, 72, 35, 35, 187, 72, 72, 72, 72,
    72, 72, 72, 35, 35, 187, 72, 72, 72, 72, 72, 72,
    72, 35, 35, 187, 72, 72, 72, 72, 72, 72, 72, 72,
    73, 73, 73, 73, 73, 73, 73, 36, 36, 188, 73, 73,
    73, 73, 73, 73, 73, 36, 36, 188, 73, 73, 73, 73,
    73, 73, 73, 36, 36, 188, 73, 73, 73, 73, 73, 73,
    73, 73, 74, 74, 74, 74, 74, 74, 74, 37, 37, 189,
    74, 74, 74, 74, 74, 74, 74, 37, 37, 189, 74, 74,
    74, 74, 74, 74, 74, 37, 37, 189, 74, 74, 74, 74,
    74, 74, 74, 74, 75, 75, 75, 75, 75, 75, 75, 38,
    38, 190, 75, 75, 75, 75, 75, 75, 75, 38, 38, 190,
    75, 75, 75, 75, 75, 75, 75, 38, 38, 190, 75, 75,
    75, 75, 75, 75, 75, 75, 76, 76, 76, 76, 76, 76,
    76, 39, 39, 191, 76, 76, 76, 76, 76, 76, 76, 39,
    39, 191, 76, 76, 76, 76, 76, 76, 76, 39, 39, 191,
    76, 76, 76, 76, 76, 76, 76, 76, 77, 77, 77, 77,
    77, 77, 77, 40, 40, 192, 77, 77, 77, 77, 77, 77,
    77, 40, 40, 192, 77, 77, 77, 77, 77, 77, 77, 40,
    40, 192, 77, 77, 77, 77, 77, 77, 77, 77, 78, 78,
    78, 78, 78, 78, 78, 41, 41, 193, 78, 78, 78, 78,
    78, 78, 78, 41, 41, 193, 78, 78, 78, 78, 78, 78,
    78, 41, 41, 193, 78, 78, 78, 78, 78, 78, 78, 78,
    79, 79, 79, 79, 79, 79, 79, 42, 42, 194, 79, 79,
    79, 79, 79, 79, 79, 42, 42, 194, 79, 79, 79, 79,
    79, 79, 79, 42, 42, 194, 79, 79, 79, 79, 79, 79,
    79, 79, 80, 80, 80, 80, 80, 80, 80, 43, 43, 195,
    80, 80, 80, 80, 80, 80, 43, 43, 195, 80, 80, 80,
    80, 80, 80, 43, 43, 195, 80, 80, 80, 80, 80, 80,
    80, 81, 81, 81, 81, 81, 81, 81, 44, 44, 196, 81,
    81, 81, 81, 81, 81, 44, 44, 196, 81, 81, 81, 81,
    81, 81, 44, 44, 196, 81, 81, 81, 81, 81, 81, 81,
    82, 82, 82, 82, 82, 82, 82, 45, 45, 197, 82, 82,
    82, 82, 82, 82, 45, 45, 197, 82, 82, 82, 82, 82,
    82, 45, 45, 197, 82, 82, 82, 82, 82, 82, 82, 83,
    83, 83, 83, 83, 83, 83, 46, 46, 198, 83, 83, 83,
    83, 83, 83, 46, 46, 198, 83, 83, 83, 83, 83, 83,
    46, 46, 198, 83, 83, 83, 83, 83, 83, 83, 84, 84,
    84, 84, 84, 84, 84, 47, 47, 199, 84, 84, 84, 84,
    84, 84, 47, 47, 199, 84, 84, 84, 84, 84, 84, 47,
    47, 199, 84, 84, 84, 84, 84, 84, 84, 85, 85, 85,
    85, 85, 85, 85, 48, 48, 200, 85, 85, 85, 85, 85,
    85, 48, 48, 200, 85, 85, 85, 85, 85, 85, 48, 48,
    200, 85, 85, 85, 85, 85, 85, 85, 86, 86, 86, 86,
    86, 86, 86, 49, 49, 201, 86, 86, 86, 86, 86, 86,
    49, 49, 201, 86, 86, 86, 86, 86, 86, 49, 49, 201,
    86, 86, 86, 86, 86, 86, 86, 87, 87, 87, 87, 87,
    87, 87, 50, 50, 202, 87, 87, 87, 87, 87, 87, 50,
    50, 202, 87, 87, 87, 87, 87, 87, 50, 50, 202, 87,
    87, 87, 87, 87, 87, 87, 88, 88, 88, 88, 88, 88,
    88, 51, 51, 203, 88, 88, 88, 88, 88, 88, 51, 51,
    203, 88, 88, 88, 88, 88, 88, 51, 51, 203, 88, 88,
    88, 88, 88, 88, 88, 89, 89, 89, 89, 89, 89, 89,
    52, 52, 204, 89, 89, 89, 89, 89, 89, 52, 52, 204,
    89, 89, 89, 89, 89, 89, 52, 52, 204, 89, 89, 89,
    89, 89, 89, 89, 90, 90, 90, 90, 90, 90, 90, 53,
    53, 205, 90, 90, 90, 90, 90, 90, 53, 53, 205, 90,
    90, 90, 90, 90, 90, 53, 53, 205, 90, 90, 90, 90,
    90, 90, 90, 91, 91, 91, 91, 91, 91, 91, 54, 54,
    206, 91, 91, 91, 91, 91, 91, 54, 54, 206, 91, 91,
    91, 91, 91, 91, 54, 54, 206, 91, 91, 91, 91, 91,
    91, 91, 92, 92, 92, 92, 92, 92, 92, 55, 55, 207,
    92, 92, 92, 92, 92, 92, 55, 55, 207, 92, 92, 92,
    92, 92, 92, 55, 55, 207, 92, 92, 92, 92, 92, 92,
    92, 93, 93, 93, 93, 93, 93, 93, 56, 56, 208, 93,
    93, 93, 93, 93, 93, 56, 56, 208, 93, 93, 93, 93,
    93, 93, 56, 56, 208, 93, 93, 93, 93, 93, 93, 93,
    94, 94, 94, 94, 94, 94, 94, 57, 57, 209, 94, 94,
    94, 94, 94, 94, 57, 57, 209, 94, 94, 94, 94, 94,
    94, 57, 57, 209, 94, 94, 94, 94, 94, 94, 94, 95,
    95, 95, 95, 95, 95, 95, 58, 58, 210, 95, 95, 95,
    95, 95, 95, 58, 58, 210, 95, 95, 95, 95, 95, 95,
    58, 58, 210, 95, 95, 95, 95, 95, 95, 95, 96, 96,
    96, 96, 96, 96, 59, 59, 211, 96, 96, 96, 96, 96,
    96, 59, 59, 211, 96, 96, 96, 96, 96, 96, 59, 59,
    211, 96, 96, 96, 96, 96, 96, 96, 97, 97, 97, 97,
    97, 97, 60, 60, 212, 97, 97, 97, 97, 97, 97, 60,
    60, 212, 97, 97, 97, 97, 97, 97, 60, 60, 212, 97,
    97, 97, 97, 97, 97, 97, 98, 98, 98, 98, 98, 98,
    61, 61, 213, 98, 98, 98, 98, 98, 98, 61, 61, 213,
    98, 98, 98, 98, 98, 98, 61, 61, 213, 98, 98, 98,
    98, 98, 98, 98, 99, 99, 99, 99, 99, 99, 62, 62,
    214, 99, 99, 99, 99, 99, 99, 62, 62, 214, 99, 99,
    99, 99, 99, 99, 62, 62, 214, 99, 99, 99, 99, 99,
    99, 99, 100, 100, 100, 100, 100, 100, 63, 63, 215, 100,
    100, 100, 100, 100, 100, 63, 63, 215, 100, 100, 100, 100,
    100, 100, 63, 63, 215, 100, 100, 100, 100, 100, 100, 100,
    101, 101, 101, 101, 101, 101, 64, 64, 216, 101, 101, 101,
    101, 101, 101, 64, 64, 216, 101, 101, 101, 101, 101, 101,
    64, 64, 216, 101, 101, 101, 101, 101, 101, 101, 102, 102,
    102, 102, 102, 102, 65, 65, 217, 102, 102, 102, 102, 102,
    102, 65, 65, 217, 102, 102, 102, 102, 102, 102, 65, 65,
    217, 102, 102, 102, 102, 102, 102, 102, 103, 103, 103, 103,
    103, 103, 66, 66, 218, 103, 103, 103, 103, 103, 103, 66,
    66, 218, 103, 103, 103, 103, 103, 103, 66, 66, 218, 103,
    103, 103, 103, 103, 103, 103, 104, 104, 104, 104, 104, 104,
    67, 67, 219, 104, 104, 104, 104, 104, 104, 67, 67, 219,
    104, 104, 104, 104, 104, 104, 67, 67, 219, 104, 104, 104,
    104, 104, 104, 104, 105, 105, 105, 105, 105, 105, 68, 68,
    220, 105, 105, 105, 105, 105, 105, 68, 68, 220, 105, 105,
    105, 105, 105, 105, 68, 68, 220, 105, 105, 105, 105, 105,
    105, 105, 106, 106, 106, 106, 106, 106, 69, 69, 221, 106,
    106, 106, 106, 106, 106, 69, 69, 221, 106, 106, 106, 106,
    106, 106, 69, 69, 221, 106, 106, 106, 106, 106, 106, 106,
    107, 107, 107, 107, 107, 107, 70, 70, 222, 107, 107, 107,
    107, 107, 107, 70, 70, 222, 107, 107, 107, 107, 107, 107,
    70, 70, 222, 107, 107, 107, 107, 107, 107, 107, 108, 108,
    108, 108, 108, 108, 71, 71, 223, 108, 108, 108, 108, 108,
    108, 71, 71, 223, 108, 108, 108, 108, 108, 108, 71, 71,
    223, 108, 108, 108, 108, 108, 108, 108, 109, 109, 109, 109,
    109, 109, 72, 72, 224, 109, 109, 109, 109, 109, 109, 72,
    72, 224, 109, 109, 109, 109, 109, 109, 72, 72, 224, 109,
    109, 109, 109, 109, 109, 109, 110, 110, 110, 110, 110, 110,
    73, 73, 225, 110, 110, 110, 110, 110, 110, 73, 73, 225,
    110, 110, 110, 110, 110, 110, 73, 73, 225, 110, 110, 110,
    110, 110, 110, 110, 111, 111, 111, 111, 111, 111, 74, 74,
    226, 111, 111, 111, 111, 111, 111, 74, 74, 226, 111, 111,
    111, 111, 111, 111, 74, 74, 226, 111, 111, 111, 111, 111,
    111, 111, 112, 112, 112, 112, 112, 112, 75, 75, 227, 112,
    112, 112, 112, 112, 112, 75, 75, 227, 112, 112, 112, 112,
    112, 112, 75, 75, 227, 112, 112, 112, 112, 112, 112, 112,
    113, 113, 113, 113, 113, 113, 76, 76, 228, 113, 113, 113,
    113, 113, 113, 76, 76, 228, 113, 113, 113, 113, 113, 113,
    76, 76, 228, 113, 113, 113, 113, 113, 113, 113, 114, 114,
    114, 114, 114, 114, 77, 77, 229, 114, 114, 114, 114, 114,
    114, 77, 77, 229, 114, 114, 114, 114, 114, 114, 77, 77,
    229, 114, 114, 114, 114, 114, 114, 114, 115, 115, 115, 115,
    115, 115, 78, 78, 230, 115, 115, 115, 115, 115, 115, 78,
    78, 230, 115, 115, 115, 115, 115, 115, 78, 78, 230, 115,
    115, 115, 115, 115, 115, 115, 116, 116, 116, 116, 116, 116,
    79, 79, 231, 116, 116, 116, 116, 116, 116, 79, 79, 231,
    116, 116, 116, 116, 116, 116, 79, 79, 231, 116, 116, 116,
    116, 116, 116, 116, 117, 117, 117, 117, 117, 117, 80, 232,
    117, 117, 117, 117, 117, 117, 80, 232, 117, 117, 117, 117,
    117, 117, 80, 232, 117, 117, 117, 117, 117, 117, 117, 118,
    118, 118, 118, 118, 118, 81, 233, 118, 118, 118, 118, 118,
    118, 81, 233, 118, 118, 118, 118, 118, 118, 81, 233, 118,
    118, 118, 118, 118, 118, 118, 119, 119, 119, 119, 119, 119,
    82, 234, 119, 119, 119, 119, 119, 119, 82, 234, 119, 119,
    119, 119, 119, 119, 82, 234, 119, 119, 119, 119, 119, 119,
    119, 120, 0, 0, 0, 120, 120, 120, 83, 235, 120, 120,
    120, 120, 83, 235, 120, 120, 120, 120, 83, 235, 120, 120,
    120, 120, 120, 120, 120, 121, 1, 1, 1, 121, 121, 121,
    84, 236, 121, 121, 121, 121, 84, 236, 121, 121, 121, 121,
    84, 236, 121, 121, 121, 121, 121, 121, 121, 122, 2, 2,
    2, 122, 122, 122, 85, 237, 122, 122, 122, 122, 85, 237,
    122, 122, 122, 122, 85, 237, 122, 122, 122, 122, 122, 122,
    122, 123, 3, 3, 3, 123, 123, 123, 86, 238, 123, 123,
    123, 123, 86, 238, 123, 123, 123, 123, 86, 238, 123, 123,
    123, 123, 123, 123, 123, 124, 4, 4, 4, 124, 124, 124,
    87, 239, 124, 124, 124, 124, 87, 239, 124, 124, 124, 124,
    87, 239, 124, 124, 124, 124, 124, 124, 124, 125, 5, 5,
    5, 125, 125, 125, 88, 125, 125, 125, 125, 88, 125, 125,
    125, 125, 88, 125, 125, 125, 125, 125, 125, 125, 126, 6,
    6, 6, 126, 126, 126, 89, 126, 126, 126, 126, 89, 126,
    126, 126, 126, 89, 126, 126, 126, 126, 126, 126, 126, 127,
    7, 7, 7, 127, 127, 127, 90, 127, 127, 127, 127, 90,
    127, 127, 127, 127, 90, 127, 127, 127, 127, 127, 127, 127,
    0, 24, 48, 72, 8, 0, 8, 0, 91, 0, 0, 0,
    91, 0, 0, 0, 91, 128, 128, 128, 128, 128, 128, 1,
    25, 49, 73, 9, 1, 9, 1, 92, 1, 1, 1, 92,
    1, 1, 1, 92, 129, 129, 129, 129, 129, 129, 2, 26,
    50, 74, 10, 2, 10, 2, 93, 2, 2, 2, 93, 2,
    2, 2, 93, 130, 130, 130, 130, 130, 130, 3, 27, 51,
    75, 11, 3, 11, 3, 94, 3, 3, 3, 94, 3, 3,
    3, 94, 131, 131, 131, 131, 131, 131, 4, 28, 52, 76,
    12, 4, 12, 4, 95, 4, 4, 4, 95, 4, 4, 4,
    95, 132, 132, 132, 132, 132, 132, 5, 29, 53, 77, 13,
    5, 13, 96, 5, 5, 96, 5, 5, 96, 133, 133, 133,
    133, 133, 133, 6, 30, 54, 78, 14, 6, 14, 97, 6,
    6, 97, 6, 6, 97, 134, 134, 134, 134, 134, 134, 7,
    31, 55, 79, 15, 7, 15, 98, 7, 7, 98, 7, 7,
    98, 135, 135, 135, 135, 135, 135, 8, 32, 56, 16, 8,
    0, 99, 8, 8, 99, 8, 8, 99, 136, 136, 136, 136,
    136, 136, 9, 33, 57, 17, 9, 100, 9, 9, 100, 9,
    9, 100, 137, 137, 137, 137, 137, 137, 10, 34, 58, 18,
    10, 101, 10, 10, 101, 10, 10, 101, 138, 138, 138, 138,
    138, 138, 11, 35, 59, 19, 11, 102, 11, 11, 102, 11,
    11, 102, 139, 139, 139, 139, 139, 139, 12, 36, 60, 20,
    12, 103, 12, 12, 103, 12, 12, 103, 140, 140, 140, 140,
    140, 140, 13, 37, 61, 21, 13, 104, 13, 13, 104, 13,
    13, 104, 141, 141, 141, 141, 141, 141, 14, 38, 62, 22,
    14, 105, 14, 14, 105, 14, 14, 105, 142, 142, 142, 142,
    142, 142, 15, 39, 63, 23, 15, 106, 15, 15, 106, 15,
    15, 106, 143, 143, 143, 143, 143, 143, 16, 40, 64, 24,
    0, 107, 0, 107, 0, 107, 144, 144, 144, 144, 144, 144,
    17, 41, 65, 25, 1, 108, 108, 108, 0, 18, 42, 66,
    26, 2, 109, 109, 109, 19, 43, 67, 27, 3, 110, 110,
    110, 20, 44, 68, 28, 4, 111, 111, 111, 21, 45, 69,
    29, 5, 112, 112, 112, 22, 46, 70, 30, 6, 113, 113,
    113, 23, 47, 71, 31, 7, 114, 114, 114,
};

static __device__ __constant__ uint8_t kDependencyCounts[100] = {
    0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1, 1,
    1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1,
    1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3,
    1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 3, 1, 1, 1, 2, 2, 2, 2, 2, 2,
    2, 2, 2, 1,
};

static __device__ __constant__ uint8_t kRoleMasks[100] = {
    9, 15, 9, 9, 11, 9, 15, 9, 15, 9, 15, 9,
    15, 9, 9, 15, 9, 15, 15, 9, 9, 15, 15, 9,
    15, 9, 15, 9, 9, 15, 9, 15, 15, 15, 9, 15,
    9, 15, 9, 9, 15, 9, 15, 15, 9, 9, 15, 15,
    9, 15, 9, 15, 9, 9, 15, 9, 15, 15, 15, 9,
    15, 9, 15, 9, 9, 15, 9, 15, 15, 9, 9, 15,
    15, 9, 15, 9, 15, 9, 9, 15, 9, 15, 15, 15,
    9, 15, 9, 9, 15, 15, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 1,
};

static __device__ __constant__ uint16_t kSuccessorOffsets[101] = {
    0, 1, 2, 3, 4, 5, 8, 9, 10, 11, 12, 13,
    14, 16, 17, 19, 20, 21, 22, 23, 24, 25, 26, 27,
    28, 29, 30, 32, 33, 35, 36, 37, 38, 39, 40, 41,
    42, 43, 45, 46, 48, 49, 50, 51, 52, 53, 54, 55,
    56, 57, 58, 59, 61, 62, 64, 65, 66, 67, 68, 69,
    70, 71, 72, 74, 75, 77, 78, 79, 80, 81, 82, 83,
    84, 85, 86, 87, 88, 90, 91, 93, 94, 95, 96, 97,
    98, 99, 100, 101, 107, 112, 113, 114, 115, 116, 117, 118,
    119, 120, 121, 122, 122,
};

static __device__ __constant__ uint16_t kSuccessors[122] = {
    1, 2, 3, 5, 12, 6, 8, 10, 7, 21, 9, 46,
    11, 71, 13, 14, 25, 15, 18, 16, 17, 19, 20, 21,
    21, 22, 23, 24, 25, 26, 27, 28, 36, 29, 33, 30,
    31, 32, 36, 34, 35, 36, 37, 38, 39, 50, 40, 43,
    41, 42, 44, 45, 46, 46, 47, 48, 49, 50, 51, 52,
    53, 61, 54, 58, 55, 56, 57, 61, 59, 60, 61, 62,
    63, 64, 75, 65, 68, 66, 67, 69, 70, 71, 71, 72,
    73, 74, 75, 76, 77, 78, 86, 79, 83, 80, 81, 82,
    86, 84, 85, 86, 87, 88, 89, 91, 93, 95, 97, 90,
    92, 94, 96, 98, 90, 91, 92, 93, 94, 95, 96, 97,
    98, 99,
};

static __device__ __constant__ uint16_t kPredecessorOffsets[101] = {
    0, 0, 1, 2, 3, 3, 4, 5, 6, 7, 8, 9,
    10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 22, 23,
    24, 25, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
    37, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 52,
    53, 54, 55, 57, 58, 59, 60, 61, 62, 63, 64, 65,
    66, 67, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79,
    82, 83, 84, 85, 87, 88, 89, 90, 91, 92, 93, 94,
    95, 96, 97, 100, 101, 102, 103, 105, 107, 109, 111, 113,
    115, 117, 119, 121, 122,
};

static __device__ __constant__ uint16_t kPredecessors[122] = {
    0, 1, 2, 3, 5, 6, 5, 8, 5, 10, 4, 12,
    12, 14, 15, 16, 14, 17, 18, 19, 20, 7, 21, 22,
    23, 24, 13, 25, 26, 26, 28, 29, 30, 31, 28, 33,
    34, 32, 35, 27, 36, 37, 37, 39, 40, 41, 39, 42,
    43, 44, 45, 9, 46, 47, 48, 49, 38, 50, 51, 51,
    53, 54, 55, 56, 53, 58, 59, 57, 60, 52, 61, 62,
    62, 64, 65, 66, 64, 67, 68, 69, 70, 11, 71, 72,
    73, 74, 63, 75, 76, 76, 78, 79, 80, 81, 78, 83,
    84, 82, 85, 77, 86, 87, 87, 89, 88, 90, 87, 91,
    88, 92, 87, 93, 88, 94, 87, 95, 88, 96, 87, 97,
    88, 98,
};

}  // namespace deepspec::v4_generated
