// Generated by scripts/megakernel/generate_v4_header.py. Do not edit.
#pragma once

#include <cstdint>

namespace deepspec::v4_generated {
inline constexpr int kPhaseCount = 94;
inline constexpr int kRootCount = 2;
inline constexpr int kStaticTaskCount = 6979;
inline constexpr int kWorkers = 152;
inline constexpr int kThreads = 256;
inline constexpr int kLocalQueueDepth = 16;
inline constexpr int kTraceCapacity = 2048;
inline constexpr int kTraceColumns = 8;
inline constexpr uint8_t kExecutionMain = 0;
inline constexpr uint8_t kExecutionEmbedding = 1;
inline constexpr uint8_t kExecutionMainKv = 2;
inline constexpr uint8_t kExecutionAttnHc = 3;
inline constexpr uint8_t kExecutionAttnProjection = 4;
inline constexpr uint8_t kExecutionSparseAttention = 5;
inline constexpr uint8_t kExecutionAttentionOutput = 6;
inline constexpr uint8_t kExecutionFfnHc = 7;
inline constexpr uint8_t kExecutionRouter = 8;
inline constexpr uint8_t kExecutionExpert = 9;
inline constexpr uint8_t kExecutionHead = 10;
inline constexpr uint8_t kExecutionTail = 11;
inline constexpr uint64_t kWorkspaceBytes = 14727424ULL;
inline constexpr uint64_t kDependencyOffset = 14700288ULL;
inline constexpr uint64_t kNextTileOffset = 14701568ULL;
inline constexpr uint64_t kCompletedTileOffset = 14702848ULL;
inline constexpr uint64_t kPublishEpochOffset = 14704128ULL;
inline constexpr uint64_t kReadyQueueOffset = 14705408ULL;
inline constexpr uint64_t kQueueStateOffset = 14715136ULL;
inline constexpr uint64_t kWorkerStateOffset = 14717696ULL;
inline constexpr int kWeightOffsetSlots = 4724;
inline constexpr int kGlobalWeightBase = 0;
inline constexpr int kLayerWeightBase = 2;
inline constexpr int kRoutedExpertWeightBase = 98;
inline constexpr int kSharedExpertWeightBase = 4706;
inline constexpr int kGlobalWeightSlots = 2;
inline constexpr int kLayerWeightSlots = 32;
inline constexpr int kExpertWeightSlots = 6;
inline constexpr int kRouterChainsPerItem = 8;
inline constexpr int kRouterRowsPerChain = 1;
inline constexpr unsigned long long kWeightArenaBytes = 14206958848ULL;
inline constexpr int kMainQuantPhase = 0;
inline constexpr int kMainProjectionPhase = 1;
inline constexpr int kMainReducePhase = 2;
inline constexpr int kMainNormPhase = 3;
inline constexpr int kEmbeddingPhase = 4;
inline constexpr int kMainProjectedQuantPhase = 5;
inline constexpr int kLayer0AttnHcProjectionPhase = 12;
inline constexpr int kLayer0AttnHcSinkhornPhase = 13;
inline constexpr int kLayer0AttnHcReduceNormPhase = 65535;
inline constexpr int kLayer0QaPhase = 14;
inline constexpr int kLayer0QaNormPhase = 15;
inline constexpr int kLayer0QbPhase = 16;
inline constexpr int kLayer0DraftKvProjectionPhase = 17;
inline constexpr int kLayer0QueryNormRopePhase = 18;
inline constexpr int kLayer0DraftKvFinalizePhase = 19;
inline constexpr int kLayer0SparseAttentionPhase = 20;
inline constexpr int kLayer0OutputAProjectionPhase = 21;
inline constexpr int kLayer0OutputBProjectionPhase = 22;
inline constexpr int kLayer0AttnPostPhase = 23;
inline constexpr int kLayer0FfnHcProjectionPhase = 24;
inline constexpr int kLayer0FfnHcSinkhornPhase = 25;
inline constexpr int kLayer0FfnHcReduceNormPhase = 65535;
inline constexpr int kLayer0RouterScorePhase = 26;
inline constexpr int kLayer0RouterTop6Phase = 27;
inline constexpr int kLayer0RoutedW13Phase = 28;
inline constexpr int kLayer0RoutedSwiGluPhase = 29;
inline constexpr int kLayer0RoutedW2Phase = 30;
inline constexpr int kLayer0SharedW13Phase = 31;
inline constexpr int kLayer0SharedSwiGluPhase = 32;
inline constexpr int kLayer0SharedW2Phase = 33;
inline constexpr int kLayer0ExpertCombinePhase = 34;
inline constexpr int kHeadReducePhase = 81;
inline constexpr int kPrefixSchedulerPhase = 65535;
inline constexpr int kExpertW1Slot = 0;
inline constexpr int kExpertW1ScaleSlot = 1;
inline constexpr int kExpertW2Slot = 2;
inline constexpr int kExpertW2ScaleSlot = 3;
inline constexpr int kExpertW3Slot = 4;
inline constexpr int kExpertW3ScaleSlot = 5;
inline constexpr int kMainProjWeightSlot = 24;
inline constexpr int kEmbeddingWeightSlot = 0;
inline constexpr int kMainProjScaleSlot = 25;
inline constexpr int kMainNormWeightSlot = 26;
inline constexpr int kLayer0AttnHcFnSlot = 2;
inline constexpr int kLayer0AttnHcBaseSlot = 3;
inline constexpr int kLayer0AttnHcScaleSlot = 4;
inline constexpr int kLayer0AttnNormWeightSlot = 8;
inline constexpr int kLayer0WqaWeightSlot = 11;
inline constexpr int kLayer0WqaScaleSlot = 12;
inline constexpr int kLayer0QaNormWeightSlot = 13;
inline constexpr int kLayer0WqbWeightSlot = 14;
inline constexpr int kLayer0WqbScaleSlot = 15;
inline constexpr int kLayer0WkvWeightSlot = 16;
inline constexpr int kLayer0WkvScaleSlot = 17;
inline constexpr int kLayer0KvNormWeightSlot = 18;
inline constexpr int kLayer0AttnSinkWeightSlot = 10;
inline constexpr int kLayer0WoaWeightSlot = 19;
inline constexpr int kLayer0WobWeightSlot = 20;
inline constexpr int kLayer0WobScaleSlot = 21;
inline constexpr int kLayer0FfnHcFnSlot = 5;
inline constexpr int kLayer0FfnHcBaseSlot = 6;
inline constexpr int kLayer0FfnHcScaleSlot = 7;
inline constexpr int kLayer0FfnNormWeightSlot = 9;
inline constexpr int kLayer0RouterWeightSlot = 22;
inline constexpr int kLayer0RouterBiasSlot = 23;
inline constexpr int kFinalNormWeightSlot = 91;
inline constexpr int kHcHeadFnWeightSlot = 92;
inline constexpr int kHcHeadBaseWeightSlot = 93;
inline constexpr int kHcHeadScaleWeightSlot = 94;
inline constexpr int kLmHeadWeightSlot = 1;
inline constexpr int kMarkovW1WeightSlot = 95;
inline constexpr int kMarkovW2WeightSlot = 96;
inline constexpr int kConfidenceWeightSlot = 97;
inline constexpr uint64_t kMainQuantizedOffset = 0ULL;
inline constexpr uint64_t kMainScaleOffset = 24576ULL;
inline constexpr uint64_t kMainPartialOffset = 24832ULL;
inline constexpr uint64_t kMainFp32Offset = 286976ULL;
inline constexpr uint64_t kMainRmsPartialOffset = 319744ULL;
inline constexpr uint64_t kMainProjectedOffset = 320000ULL;
inline constexpr uint64_t kMainProjectedQuantizedOffset = 336384ULL;
inline constexpr uint64_t kMainProjectedScaleOffset = 344576ULL;
inline constexpr uint64_t kMainKvPartialOffset = 344832ULL;
inline constexpr uint64_t kHiddenStreamsOffset = 393984ULL;
inline constexpr uint64_t kHcMixOffset = 727808ULL;
inline constexpr uint64_t kHcPreOffset = 728832ULL;
inline constexpr uint64_t kHcPostOffset = 729088ULL;
inline constexpr uint64_t kHcCombOffset = 729344ULL;
inline constexpr uint64_t kNormalizedHiddenOffset = 730112ULL;
inline constexpr uint64_t kAttnInputQuantizedOffset = 812032ULL;
inline constexpr uint64_t kAttnInputScaleOffset = 852992ULL;
inline constexpr uint64_t kQaPartialOffset = 853504ULL;
inline constexpr uint64_t kQloraOffset = 1017344ULL;
inline constexpr uint64_t kQloraQuantizedOffset = 1037824ULL;
inline constexpr uint64_t kQloraScaleOffset = 1048064ULL;
inline constexpr uint64_t kQueryProjectionOffset = 1048320ULL;
inline constexpr uint64_t kQueryInverseRmsOffset = 1703680ULL;
inline constexpr uint64_t kQueriesOffset = 1704960ULL;
inline constexpr uint64_t kDraftKvPartialOffset = 2360320ULL;
inline constexpr uint64_t kDraftKvOffset = 2442240ULL;
inline constexpr uint64_t kAttentionAccumulatorOffset = 2452480ULL;
inline constexpr uint64_t kAttentionRawOffset = 3763200ULL;
inline constexpr uint64_t kAttentionValuesOffset = 4418560ULL;
inline constexpr uint64_t kOutputLoraOffset = 5073920ULL;
inline constexpr uint64_t kOutputLoraQuantizedOffset = 5237760ULL;
inline constexpr uint64_t kOutputLoraScaleOffset = 5319680ULL;
inline constexpr uint64_t kAttentionOutputPartialOffset = 5320448ULL;
inline constexpr uint64_t kAttentionOutputOffset = 5975808ULL;
inline constexpr uint64_t kAttentionHiddenStreamsOffset = 6057728ULL;
inline constexpr uint64_t kFfnHcMixOffset = 6385408ULL;
inline constexpr uint64_t kFfnHcPreOffset = 6386432ULL;
inline constexpr uint64_t kFfnHcPostOffset = 6386688ULL;
inline constexpr uint64_t kFfnHcCombOffset = 6386944ULL;
inline constexpr uint64_t kFfnNormalizedHiddenOffset = 6387712ULL;
inline constexpr uint64_t kFfnInputQuantizedOffset = 6469632ULL;
inline constexpr uint64_t kFfnInputScaleOffset = 6510592ULL;
inline constexpr uint64_t kRouterScoreOffset = 6511104ULL;
inline constexpr uint64_t kRouterIndexOffset = 6521344ULL;
inline constexpr uint64_t kRouterWeightOffset = 6521600ULL;
inline constexpr uint64_t kRoutedW13Offset = 6521856ULL;
inline constexpr uint64_t kSharedW13Offset = 7013376ULL;
inline constexpr uint64_t kRoutedSwiGluOffset = 7095296ULL;
inline constexpr uint64_t kRoutedSwiGluQuantizedOffset = 7341056ULL;
inline constexpr uint64_t kRoutedSwiGluScaleOffset = 7463936ULL;
inline constexpr uint64_t kSharedSwiGluOffset = 7464960ULL;
inline constexpr uint64_t kSharedSwiGluQuantizedOffset = 7505920ULL;
inline constexpr uint64_t kSharedSwiGluScaleOffset = 7526400ULL;
inline constexpr uint64_t kRoutedOutputPartialOffset = 7526656ULL;
inline constexpr uint64_t kRoutedOutputOffset = 8018176ULL;
inline constexpr uint64_t kSharedOutputOffset = 8182016ULL;
inline constexpr uint64_t kHeadHiddenOffset = 8263936ULL;
inline constexpr uint64_t kHeadNormalizedOffset = 8345856ULL;
inline constexpr uint64_t kBaseLogitsOffset = 8427776ULL;
inline constexpr uint64_t kMarkovEmbeddingOffset = 13598976ULL;
inline constexpr uint64_t kMarkovLogitsOffset = 13604096ULL;
inline constexpr uint64_t kSoftmaxPartialMaxOffset = 14638336ULL;
inline constexpr uint64_t kSoftmaxPartialSumOffset = 14658816ULL;
inline constexpr uint64_t kSampleScanOffset = 14679296ULL;

static __device__ __constant__ uint16_t kMainKvProjectionPhases[3] = {
    6, 8, 10,
};

static __device__ __constant__ uint16_t kMainKvNormPhases[3] = {
    7, 9, 11,
};

static __device__ __constant__ uint16_t kMainKvWeightSlots[3] = {
    16, 48, 80,
};

static __device__ __constant__ uint16_t kMainKvScaleSlots[3] = {
    17, 49, 81,
};

static __device__ __constant__ uint16_t kMainKvNormWeightSlots[3] = {
    18, 50, 82,
};

static __device__ __constant__ uint16_t kAttnHcProjectionPhases[3] = {
    12, 35, 58,
};

static __device__ __constant__ uint16_t kAttnHcSinkhornPhases[3] = {
    13, 36, 59,
};

static __device__ __constant__ uint16_t kAttnHcReduceNormPhases[3] = {
    65535, 65535, 65535,
};

static __device__ __constant__ uint16_t kQaPhases[3] = {
    14, 37, 60,
};

static __device__ __constant__ uint16_t kQaNormPhases[3] = {
    15, 38, 61,
};

static __device__ __constant__ uint16_t kQbPhases[3] = {
    16, 39, 62,
};

static __device__ __constant__ uint16_t kDraftKvProjectionPhases[3] = {
    17, 40, 63,
};

static __device__ __constant__ uint16_t kQueryNormRopePhases[3] = {
    18, 41, 64,
};

static __device__ __constant__ uint16_t kDraftKvFinalizePhases[3] = {
    19, 42, 65,
};

static __device__ __constant__ uint16_t kSparseAttentionPhases[3] = {
    20, 43, 66,
};

static __device__ __constant__ uint16_t kOutputAProjectionPhases[3] = {
    21, 44, 67,
};

static __device__ __constant__ uint16_t kOutputBProjectionPhases[3] = {
    22, 45, 68,
};

static __device__ __constant__ uint16_t kAttnPostPhases[3] = {
    23, 46, 69,
};

static __device__ __constant__ uint16_t kFfnHcProjectionPhases[3] = {
    24, 47, 70,
};

static __device__ __constant__ uint16_t kFfnHcSinkhornPhases[3] = {
    25, 48, 71,
};

static __device__ __constant__ uint16_t kFfnHcReduceNormPhases[3] = {
    65535, 65535, 65535,
};

static __device__ __constant__ uint16_t kRouterScorePhases[3] = {
    26, 49, 72,
};

static __device__ __constant__ uint16_t kRouterTop6Phases[3] = {
    27, 50, 73,
};

static __device__ __constant__ uint16_t kRoutedW13Phases[3] = {
    28, 51, 74,
};

static __device__ __constant__ uint16_t kRoutedSwiGluPhases[3] = {
    29, 52, 75,
};

static __device__ __constant__ uint16_t kRoutedW2Phases[3] = {
    30, 53, 76,
};

static __device__ __constant__ uint16_t kSharedW13Phases[3] = {
    31, 54, 77,
};

static __device__ __constant__ uint16_t kSharedSwiGluPhases[3] = {
    32, 55, 78,
};

static __device__ __constant__ uint16_t kSharedW2Phases[3] = {
    33, 56, 79,
};

static __device__ __constant__ uint16_t kExpertCombinePhases[3] = {
    34, 57, 80,
};

static __device__ __constant__ uint16_t kLmRowPhases[5] = {
    82, 82, 82, 82, 82,
};

static __device__ __constant__ uint16_t kMarkovGatherPhases[5] = {
    83, 85, 87, 89, 91,
};

static __device__ __constant__ uint16_t kConfidencePhases[5] = {
    65535, 65535, 65535, 65535, 65535,
};

static __device__ __constant__ uint16_t kMarkovW2Phases[5] = {
    84, 86, 88, 90, 92,
};

static __device__ __constant__ uint16_t kCorrectLogitPhases[5] = {
    65535, 65535, 65535, 65535, 65535,
};

static __device__ __constant__ uint16_t kSoftmaxExpSumPhases[5] = {
    65535, 65535, 65535, 65535, 65535,
};

static __device__ __constant__ uint16_t kSumReducePhases[5] = {
    65535, 65535, 65535, 65535, 65535,
};

static __device__ __constant__ uint16_t kNormalizeSamplePhases[5] = {
    65535, 65535, 65535, 65535, 65535,
};

static __device__ __constant__ uint16_t kAttnHcFnSlots[3] = {
    2, 34, 66,
};

static __device__ __constant__ uint16_t kAttnHcBaseSlots[3] = {
    3, 35, 67,
};

static __device__ __constant__ uint16_t kAttnHcScaleSlots[3] = {
    4, 36, 68,
};

static __device__ __constant__ uint16_t kAttnNormWeightSlots[3] = {
    8, 40, 72,
};

static __device__ __constant__ uint16_t kWqaWeightSlots[3] = {
    11, 43, 75,
};

static __device__ __constant__ uint16_t kWqaScaleSlots[3] = {
    12, 44, 76,
};

static __device__ __constant__ uint16_t kQaNormWeightSlots[3] = {
    13, 45, 77,
};

static __device__ __constant__ uint16_t kWqbWeightSlots[3] = {
    14, 46, 78,
};

static __device__ __constant__ uint16_t kWqbScaleSlots[3] = {
    15, 47, 79,
};

static __device__ __constant__ uint16_t kDraftWkvWeightSlots[3] = {
    16, 48, 80,
};

static __device__ __constant__ uint16_t kDraftWkvScaleSlots[3] = {
    17, 49, 81,
};

static __device__ __constant__ uint16_t kDraftKvNormWeightSlots[3] = {
    18, 50, 82,
};

static __device__ __constant__ uint16_t kAttnSinkWeightSlots[3] = {
    10, 42, 74,
};

static __device__ __constant__ uint16_t kWoaWeightSlots[3] = {
    19, 51, 83,
};

static __device__ __constant__ uint16_t kWobWeightSlots[3] = {
    20, 52, 84,
};

static __device__ __constant__ uint16_t kWobScaleSlots[3] = {
    21, 53, 85,
};

static __device__ __constant__ uint16_t kFfnHcFnSlots[3] = {
    5, 37, 69,
};

static __device__ __constant__ uint16_t kFfnHcBaseSlots[3] = {
    6, 38, 70,
};

static __device__ __constant__ uint16_t kFfnHcScaleSlots[3] = {
    7, 39, 71,
};

static __device__ __constant__ uint16_t kFfnNormWeightSlots[3] = {
    9, 41, 73,
};

static __device__ __constant__ uint16_t kRouterWeightSlots[3] = {
    22, 54, 86,
};

static __device__ __constant__ uint16_t kRouterBiasSlots[3] = {
    23, 55, 87,
};

static __device__ __constant__ uint16_t kRoutedExpertWeightBases[3] = {
    98, 1634, 3170,
};

static __device__ __constant__ uint16_t kSharedExpertWeightBases[3] = {
    4706, 4712, 4718,
};

static __device__ __constant__ uint16_t kRoots[2] = {
    0, 4,
};

static __device__ __constant__ uint32_t kWorkUnits[94] = {
    192, 256, 16, 16, 320, 64, 16, 2, 16, 2, 16, 2,
    240, 10, 32, 10, 256, 16, 80, 10, 80, 64, 128, 80,
    240, 10, 320, 10, 1920, 240, 1920, 32, 40, 32, 320, 240,
    10, 32, 10, 256, 16, 80, 10, 80, 64, 128, 80, 240,
    10, 320, 10, 1920, 240, 1920, 32, 40, 32, 320, 240, 10,
    32, 10, 256, 16, 80, 10, 80, 64, 128, 80, 240, 10,
    320, 10, 1920, 240, 1920, 32, 40, 32, 320, 10, 1010, 2,
    1010, 2, 1010, 2, 1010, 2, 1010, 2, 1010, 1,
};

static __device__ __constant__ uint8_t kClaimChunks[94] = {
    2, 2, 1, 1, 3, 1, 1, 1, 1, 1, 1, 1,
    2, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1,
    2, 1, 3, 1, 8, 2, 8, 1, 1, 1, 2, 2,
    1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2,
    1, 3, 1, 8, 2, 8, 1, 1, 1, 2, 2, 1,
    1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1,
    3, 1, 8, 2, 8, 1, 1, 1, 2, 1, 7, 1,
    7, 1, 7, 1, 7, 1, 7, 1, 7, 1,
};

static __device__ __constant__ uint8_t kExecutionGroups[94] = {
    0, 0, 0, 0, 1, 2, 2, 2, 2, 2, 2, 2,
    3, 3, 4, 4, 4, 4, 4, 4, 5, 6, 6, 6,
    7, 7, 8, 8, 9, 9, 9, 9, 9, 9, 9, 3,
    3, 4, 4, 4, 4, 4, 4, 5, 6, 6, 6, 7,
    7, 8, 8, 9, 9, 9, 9, 9, 9, 9, 3, 3,
    4, 4, 4, 4, 4, 4, 5, 6, 6, 6, 7, 7,
    8, 8, 9, 9, 9, 9, 9, 9, 9, 10, 10, 11,
    11, 11, 11, 11, 11, 11, 11, 11, 11, 11,
};

static __device__ __constant__ uint8_t kPhaseLayers[94] = {
    255, 255, 255, 255, 255, 255, 0, 0, 1, 1, 2, 2,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
    2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
    2, 2, 2, 2, 2, 2, 2, 2, 2, 255, 255, 255,
    255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
};

static __device__ __constant__ uint16_t kStaticWorkerTaskOffsets[153] = {
    0, 75, 149, 219, 289, 359, 429, 499, 569, 636, 703, 758,
    813, 868, 923, 978, 1033, 1086, 1139, 1192, 1245, 1298, 1351, 1404,
    1457, 1510, 1563, 1616, 1673, 1730, 1787, 1844, 1901, 1955, 2009, 2063,
    2117, 2171, 2225, 2279, 2333, 2396, 2459, 2522, 2585, 2648, 2711, 2774,
    2837, 2897, 2957, 3017, 3074, 3131, 3188, 3245, 3302, 3359, 3416, 3473,
    3530, 3587, 3644, 3701, 3758, 3812, 3866, 3920, 3974, 4028, 4082, 4136,
    4190, 4244, 4298, 4352, 4405, 4458, 4511, 4564, 4617, 4658, 4699, 4740,
    4781, 4822, 4863, 4904, 4945, 4983, 5021, 5059, 5097, 5135, 5173, 5211,
    5249, 5287, 5325, 5363, 5401, 5439, 5476, 5513, 5550, 5587, 5624, 5661,
    5695, 5729, 5763, 5797, 5831, 5865, 5899, 5933, 5967, 6001, 6035, 6069,
    6103, 6132, 6161, 6190, 6219, 6248, 6277, 6306, 6335, 6366, 6397, 6427,
    6457, 6487, 6517, 6547, 6577, 6607, 6637, 6665, 6693, 6721, 6749, 6777,
    6805, 6834, 6858, 6879, 6899, 6919, 6939, 6959, 6979,
};

static __device__ __constant__ uint16_t kStaticTaskPhases[6979] = {
    0, 4, 1, 2, 3, 14, 15, 16, 18, 20, 21, 22,
    23, 24, 25, 26, 27, 28, 28, 32, 33, 34, 34, 35,
    36, 37, 38, 39, 41, 43, 44, 45, 46, 47, 48, 49,
    50, 51, 51, 55, 56, 57, 57, 58, 59, 60, 61, 62,
    64, 66, 67, 68, 69, 70, 71, 72, 73, 74, 74, 78,
    79, 80, 80, 81, 82, 84, 85, 86, 87, 88, 89, 90,
    91, 92, 93, 0, 4, 1, 2, 3, 14, 15, 16, 18,
    20, 21, 22, 23, 24, 25, 26, 27, 28, 28, 32, 33,
    34, 34, 35, 36, 37, 38, 39, 41, 43, 44, 45, 46,
    47, 48, 49, 50, 51, 51, 55, 56, 57, 57, 58, 59,
    60, 61, 62, 64, 66, 67, 68, 69, 70, 71, 72, 73,
    74, 74, 78, 79, 80, 80, 81, 82, 84, 85, 86, 87,
    88, 89, 90, 91, 92, 0, 4, 1, 2, 3, 14, 15,
    16, 18, 20, 21, 22, 23, 24, 25, 26, 27, 28, 28,
    32, 33, 34, 34, 35, 36, 37, 38, 39, 41, 43, 44,
    45, 46, 47, 48, 49, 50, 51, 51, 55, 56, 57, 57,
    58, 59, 60, 61, 62, 64, 66, 67, 68, 69, 70, 71,
    72, 73, 74, 74, 78, 79, 80, 80, 81, 82, 84, 86,
    88, 90, 92, 0, 4, 1, 2, 3, 14, 15, 16, 18,
    20, 21, 22, 23, 24, 25, 26, 27, 28, 28, 32, 33,
    34, 34, 35, 36, 37, 38, 39, 41, 43, 44, 45, 46,
    47, 48, 49, 50, 51, 51, 55, 56, 57, 57, 58, 59,
    60, 61, 62, 64, 66, 67, 68, 69, 70, 71, 72, 73,
    74, 74, 78, 79, 80, 80, 81, 82, 84, 86, 88, 90,
    92, 0, 4, 1, 2, 3, 14, 15, 16, 18, 20, 21,
    22, 23, 24, 25, 26, 27, 28, 28, 32, 33, 34, 34,
    35, 36, 37, 38, 39, 41, 43, 44, 45, 46, 47, 48,
    49, 50, 51, 51, 55, 56, 57, 57, 58, 59, 60, 61,
    62, 64, 66, 67, 68, 69, 70, 71, 72, 73, 74, 74,
    78, 79, 80, 80, 81, 82, 84, 86, 88, 90, 92, 0,
    4, 1, 2, 3, 14, 15, 16, 18, 20, 21, 22, 23,
    24, 25, 26, 27, 28, 28, 32, 33, 34, 34, 35, 36,
    37, 38, 39, 41, 43, 44, 45, 46, 47, 48, 49, 50,
    51, 51, 55, 56, 57, 57, 58, 59, 60, 61, 62, 64,
    66, 67, 68, 69, 70, 71, 72, 73, 74, 74, 78, 79,
    80, 80, 81, 82, 84, 86, 88, 90, 92, 0, 4, 1,
    2, 3, 14, 15, 16, 18, 20, 21, 22, 23, 24, 25,
    26, 27, 28, 28, 32, 33, 34, 34, 35, 36, 37, 38,
    39, 41, 43, 44, 45, 46, 47, 48, 49, 50, 51, 51,
    55, 56, 57, 57, 58, 59, 60, 61, 62, 64, 66, 67,
    68, 69, 70, 71, 72, 73, 74, 74, 78, 79, 80, 80,
    81, 82, 84, 86, 88, 90, 92, 0, 4, 1, 2, 3,
    14, 15, 16, 18, 20, 21, 22, 23, 24, 25, 26, 27,
    28, 28, 32, 33, 34, 34, 35, 36, 37, 38, 39, 41,
    43, 44, 45, 46, 47, 48, 49, 50, 51, 51, 55, 56,
    57, 57, 58, 59, 60, 61, 62, 64, 66, 67, 68, 69,
    70, 71, 72, 73, 74, 74, 78, 79, 80, 80, 81, 82,
    84, 86, 88, 90, 92, 0, 4, 1, 2, 3, 14, 15,
    16, 18, 20, 21, 22, 23, 24, 25, 26, 27, 28, 28,
    32, 33, 34, 35, 36, 37, 38, 39, 41, 43, 44, 45,
    46, 47, 48, 49, 50, 51, 51, 55, 56, 57, 58, 59,
    60, 61, 62, 64, 66, 67, 68, 69, 70, 71, 72, 73,
    74, 74, 78, 79, 80, 81, 82, 84, 86, 88, 90, 92,
    0, 4, 1, 2, 3, 14, 15, 16, 18, 20, 21, 22,
    23, 24, 25, 26, 27, 28, 28, 32, 33, 34, 35, 36,
    37, 38, 39, 41, 43, 44, 45, 46, 47, 48, 49, 50,
    51, 51, 55, 56, 57, 58, 59, 60, 61, 62, 64, 66,
    67, 68, 69, 70, 71, 72, 73, 74, 74, 78, 79, 80,
    81, 82, 84, 86, 88, 90, 92, 0, 4, 1, 2, 3,
    14, 16, 18, 20, 21, 22, 23, 24, 26, 28, 28, 32,
    33, 34, 35, 37, 39, 41, 43, 44, 45, 46, 47, 49,
    51, 51, 55, 56, 57, 58, 60, 62, 64, 66, 67, 68,
    69, 70, 72, 74, 74, 78, 79, 80, 82, 84, 86, 88,
    90, 92, 0, 4, 1, 2, 3, 14, 16, 18, 20, 21,
    22, 23, 24, 26, 28, 28, 32, 33, 34, 35, 37, 39,
    41, 43, 44, 45, 46, 47, 49, 51, 51, 55, 56, 57,
    58, 60, 62, 64, 66, 67, 68, 69, 70, 72, 74, 74,
    78, 79, 80, 82, 84, 86, 88, 90, 92, 0, 4, 1,
    2, 3, 14, 16, 18, 20, 21, 22, 23, 24, 26, 28,
    28, 32, 33, 34, 35, 37, 39, 41, 43, 44, 45, 46,
    47, 49, 51, 51, 55, 56, 57, 58, 60, 62, 64, 66,
    67, 68, 69, 70, 72, 74, 74, 78, 79, 80, 82, 84,
    86, 88, 90, 92, 0, 4, 1, 2, 3, 14, 16, 18,
    20, 21, 22, 23, 24, 26, 28, 28, 32, 33, 34, 35,
    37, 39, 41, 43, 44, 45, 46, 47, 49, 51, 51, 55,
    56, 57, 58, 60, 62, 64, 66, 67, 68, 69, 70, 72,
    74, 74, 78, 79, 80, 82, 84, 86, 88, 90, 92, 0,
    4, 1, 2, 3, 14, 16, 18, 20, 21, 22, 23, 24,
    26, 28, 28, 32, 33, 34, 35, 37, 39, 41, 43, 44,
    45, 46, 47, 49, 51, 51, 55, 56, 57, 58, 60, 62,
    64, 66, 67, 68, 69, 70, 72, 74, 74, 78, 79, 80,
    82, 84, 86, 88, 90, 92, 0, 4, 1, 2, 3, 14,
    16, 18, 20, 21, 22, 23, 24, 26, 28, 28, 32, 33,
    34, 35, 37, 39, 41, 43, 44, 45, 46, 47, 49, 51,
    51, 55, 56, 57, 58, 60, 62, 64, 66, 67, 68, 69,
    70, 72, 74, 74, 78, 79, 80, 82, 84, 86, 88, 90,
    92, 0, 4, 1, 14, 16, 18, 20, 21, 22, 23, 24,
    26, 28, 28, 32, 33, 34, 35, 37, 39, 41, 43, 44,
    45, 46, 47, 49, 51, 51, 55, 56, 57, 58, 60, 62,
    64, 66, 67, 68, 69, 70, 72, 74, 74, 78, 79, 80,
    82, 84, 86, 88, 90, 92, 0, 4, 1, 14, 16, 18,
    20, 21, 22, 23, 24, 26, 28, 28, 32, 33, 34, 35,
    37, 39, 41, 43, 44, 45, 46, 47, 49, 51, 51, 55,
    56, 57, 58, 60, 62, 64, 66, 67, 68, 69, 70, 72,
    74, 74, 78, 79, 80, 82, 84, 86, 88, 90, 92, 0,
    4, 1, 14, 16, 18, 20, 21, 22, 23, 24, 26, 28,
    28, 32, 33, 34, 35, 37, 39, 41, 43, 44, 45, 46,
    47, 49, 51, 51, 55, 56, 57, 58, 60, 62, 64, 66,
    67, 68, 69, 70, 72, 74, 74, 78, 79, 80, 82, 84,
    86, 88, 90, 92, 0, 4, 1, 14, 16, 18, 20, 21,
    22, 23, 24, 26, 28, 28, 32, 33, 34, 35, 37, 39,
    41, 43, 44, 45, 46, 47, 49, 51, 51, 55, 56, 57,
    58, 60, 62, 64, 66, 67, 68, 69, 70, 72, 74, 74,
    78, 79, 80, 82, 84, 86, 88, 90, 92, 0, 4, 1,
    14, 16, 18, 20, 21, 22, 23, 24, 26, 28, 28, 32,
    33, 34, 35, 37, 39, 41, 43, 44, 45, 46, 47, 49,
    51, 51, 55, 56, 57, 58, 60, 62, 64, 66, 67, 68,
    69, 70, 72, 74, 74, 78, 79, 80, 82, 84, 86, 88,
    90, 92, 0, 4, 1, 14, 16, 18, 20, 21, 22, 23,
    24, 26, 28, 28, 32, 33, 34, 35, 37, 39, 41, 43,
    44, 45, 46, 47, 49, 51, 51, 55, 56, 57, 58, 60,
    62, 64, 66, 67, 68, 69, 70, 72, 74, 74, 78, 79,
    80, 82, 84, 86, 88, 90, 92, 0, 4, 1, 14, 16,
    18, 20, 21, 22, 23, 24, 26, 28, 28, 32, 33, 34,
    35, 37, 39, 41, 43, 44, 45, 46, 47, 49, 51, 51,
    55, 56, 57, 58, 60, 62, 64, 66, 67, 68, 69, 70,
    72, 74, 74, 78, 79, 80, 82, 84, 86, 88, 90, 92,
    0, 4, 1, 14, 16, 18, 20, 21, 22, 23, 24, 26,
    28, 28, 32, 33, 34, 35, 37, 39, 41, 43, 44, 45,
    46, 47, 49, 51, 51, 55, 56, 57, 58, 60, 62, 64,
    66, 67, 68, 69, 70, 72, 74, 74, 78, 79, 80, 82,
    84, 86, 88, 90, 92, 0, 4, 1, 14, 16, 18, 20,
    21, 22, 23, 24, 26, 28, 28, 32, 33, 34, 35, 37,
    39, 41, 43, 44, 45, 46, 47, 49, 51, 51, 55, 56,
    57, 58, 60, 62, 64, 66, 67, 68, 69, 70, 72, 74,
    74, 78, 79, 80, 82, 84, 86, 88, 90, 92, 0, 4,
    1, 14, 16, 18, 20, 21, 22, 23, 24, 26, 28, 28,
    32, 33, 34, 35, 37, 39, 41, 43, 44, 45, 46, 47,
    49, 51, 51, 55, 56, 57, 58, 60, 62, 64, 66, 67,
    68, 69, 70, 72, 74, 74, 78, 79, 80, 82, 84, 86,
    88, 90, 92, 0, 4, 1, 14, 16, 18, 20, 21, 22,
    23, 24, 26, 28, 28, 32, 33, 34, 35, 37, 39, 41,
    43, 44, 45, 46, 47, 49, 51, 51, 55, 56, 57, 58,
    60, 62, 64, 66, 67, 68, 69, 70, 72, 74, 74, 78,
    79, 80, 82, 84, 86, 88, 90, 92, 0, 4, 12, 12,
    12, 12, 13, 14, 16, 18, 20, 21, 22, 23, 24, 26,
    28, 28, 32, 33, 34, 35, 37, 39, 41, 43, 44, 45,
    46, 47, 49, 51, 51, 55, 56, 57, 58, 60, 62, 64,
    66, 67, 68, 69, 70, 72, 74, 74, 78, 79, 80, 82,
    84, 86, 88, 90, 92, 0, 4, 12, 12, 12, 12, 13,
    14, 16, 18, 20, 21, 22, 23, 24, 26, 28, 28, 32,
    33, 34, 35, 37, 39, 41, 43, 44, 45, 46, 47, 49,
    51, 51, 55, 56, 57, 58, 60, 62, 64, 66, 67, 68,
    69, 70, 72, 74, 74, 78, 79, 80, 82, 84, 86, 88,
    90, 92, 0, 4, 12, 12, 12, 12, 13, 14, 16, 18,
    20, 21, 22, 23, 24, 26, 28, 28, 32, 33, 34, 35,
    37, 39, 41, 43, 44, 45, 46, 47, 49, 51, 51, 55,
    56, 57, 58, 60, 62, 64, 66, 67, 68, 69, 70, 72,
    74, 74, 78, 79, 80, 82, 84, 86, 88, 90, 92, 0,
    4, 12, 12, 12, 12, 13, 14, 16, 18, 20, 21, 22,
    23, 24, 26, 28, 28, 32, 33, 34, 35, 37, 39, 41,
    43, 44, 45, 46, 47, 49, 51, 51, 55, 56, 57, 58,
    60, 62, 64, 66, 67, 68, 69, 70, 72, 74, 74, 78,
    79, 80, 82, 84, 86, 88, 90, 92, 0, 4, 12, 12,
    12, 12, 13, 14, 16, 18, 20, 21, 22, 23, 24, 26,
    28, 28, 32, 33, 34, 35, 37, 39, 41, 43, 44, 45,
    46, 47, 49, 51, 51, 55, 56, 57, 58, 60, 62, 64,
    66, 67, 68, 69, 70, 72, 74, 74, 78, 79, 80, 82,
    84, 86, 88, 90, 92, 0, 4, 12, 12, 12, 12, 13,
    16, 18, 20, 21, 22, 23, 24, 26, 28, 28, 32, 30,
    34, 35, 39, 41, 43, 44, 45, 46, 47, 49, 51, 51,
    55, 53, 57, 58, 62, 64, 66, 67, 68, 69, 70, 72,
    74, 74, 78, 76, 80, 82, 84, 86, 88, 90, 92, 0,
    4, 12, 12, 12, 12, 13, 16, 18, 20, 21, 22, 23,
    24, 26, 28, 28, 32, 30, 34, 35, 39, 41, 43, 44,
    45, 46, 47, 49, 51, 51, 55, 53, 57, 58, 62, 64,
    66, 67, 68, 69, 70, 72, 74, 74, 78, 76, 80, 82,
    84, 86, 88, 90, 92, 0, 4, 12, 12, 12, 12, 13,
    16, 18, 20, 21, 22, 23, 24, 26, 28, 28, 32, 30,
    34, 35, 39, 41, 43, 44, 45, 46, 47, 49, 51, 51,
    55, 53, 57, 58, 62, 64, 66, 67, 68, 69, 70, 72,
    74, 74, 78, 76, 80, 82, 84, 86, 88, 90, 92, 0,
    4, 12, 12, 12, 12, 13, 16, 18, 20, 21, 22, 23,
    24, 26, 28, 28, 32, 30, 34, 35, 39, 41, 43, 44,
    45, 46, 47, 49, 51, 51, 55, 53, 57, 58, 62, 64,
    66, 67, 68, 69, 70, 72, 74, 74, 78, 76, 80, 82,
    84, 86, 88, 90, 92, 0, 4, 12, 12, 12, 12, 13,
    16, 18, 20, 21, 22, 23, 24, 26, 28, 28, 32, 30,
    34, 35, 39, 41, 43, 44, 45, 46, 47, 49, 51, 51,
    55, 53, 57, 58, 62, 64, 66, 67, 68, 69, 70, 72,
    74, 74, 78, 76, 80, 82, 84, 86, 88, 90, 92, 0,
    4, 12, 12, 12, 12, 5, 16, 18, 20, 21, 22, 23,
    24, 26, 28, 28, 32, 30, 34, 35, 39, 41, 43, 44,
    45, 46, 47, 49, 51, 51, 55, 53, 57, 58, 62, 64,
    66, 67, 68, 69, 70, 72, 74, 74, 78, 76, 80, 82,
    84, 86, 88, 90, 92, 0, 4, 12, 12, 12, 12, 5,
    16, 18, 20, 21, 22, 23, 24, 26, 28, 28, 32, 30,
    34, 35, 39, 41, 43, 44, 45, 46, 47, 49, 51, 51,
    55, 53, 57, 58, 62, 64, 66, 67, 68, 69, 70, 72,
    74, 74, 78, 76, 80, 82, 84, 86, 88, 90, 92, 0,
    4, 12, 12, 12, 12, 5, 16, 18, 20, 21, 22, 23,
    24, 26, 28, 28, 32, 30, 34, 35, 39, 41, 43, 44,
    45, 46, 47, 49, 51, 51, 55, 53, 57, 58, 62, 64,
    66, 67, 68, 69, 70, 72, 74, 74, 78, 76, 80, 82,
    84, 86, 88, 90, 92, 0, 4, 12, 12, 12, 12, 5,
    16, 18, 20, 21, 22, 23, 24, 26, 28, 28, 29, 29,
    30, 30, 30, 34, 35, 39, 41, 43, 44, 45, 46, 47,
    49, 51, 51, 52, 52, 53, 53, 53, 57, 58, 62, 64,
    66, 67, 68, 69, 70, 72, 74, 74, 75, 75, 76, 76,
    76, 80, 82, 84, 86, 88, 90, 92, 0, 4, 12, 12,
    12, 12, 5, 16, 18, 20, 21, 22, 23, 24, 26, 28,
    28, 29, 29, 30, 30, 30, 34, 35, 39, 41, 43, 44,
    45, 46, 47, 49, 51, 51, 52, 52, 53, 53, 53, 57,
    58, 62, 64, 66, 67, 68, 69, 70, 72, 74, 74, 75,
    75, 76, 76, 76, 80, 82, 84, 86, 88, 90, 92, 0,
    4, 12, 12, 12, 12, 5, 16, 18, 20, 21, 22, 23,
    24, 26, 28, 28, 29, 29, 30, 30, 30, 34, 35, 39,
    41, 43, 44, 45, 46, 47, 49, 51, 51, 52, 52, 53,
    53, 53, 57, 58, 62, 64, 66, 67, 68, 69, 70, 72,
    74, 74, 75, 75, 76, 76, 76, 80, 82, 84, 86, 88,
    90, 92, 0, 4, 12, 12, 12, 12, 5, 16, 18, 20,
    21, 22, 23, 24, 26, 28, 28, 29, 29, 30, 30, 30,
    34, 35, 39, 41, 43, 44, 45, 46, 47, 49, 51, 51,
    52, 52, 53, 53, 53, 57, 58, 62, 64, 66, 67, 68,
    69, 70, 72, 74, 74, 75, 75, 76, 76, 76, 80, 82,
    84, 86, 88, 90, 92, 0, 4, 12, 12, 12, 12, 5,
    16, 18, 20, 21, 22, 23, 24, 26, 28, 28, 29, 29,
    30, 30, 30, 34, 35, 39, 41, 43, 44, 45, 46, 47,
    49, 51, 51, 52, 52, 53, 53, 53, 57, 58, 62, 64,
    66, 67, 68, 69, 70, 72, 74, 74, 75, 75, 76, 76,
    76, 80, 82, 84, 86, 88, 90, 92, 0, 4, 12, 12,
    12, 12, 5, 16, 18, 20, 21, 22, 23, 24, 26, 28,
    28, 29, 29, 30, 30, 30, 34, 35, 39, 41, 43, 44,
    45, 46, 47, 49, 51, 51, 52, 52, 53, 53, 53, 57,
    58, 62, 64, 66, 67, 68, 69, 70, 72, 74, 74, 75,
    75, 76, 76, 76, 80, 82, 84, 86, 88, 90, 92, 0,
    4, 12, 12, 12, 12, 5, 16, 18, 20, 21, 22, 23,
    24, 26, 28, 28, 29, 29, 30, 30, 30, 34, 35, 39,
    41, 43, 44, 45, 46, 47, 49, 51, 51, 52, 52, 53,
    53, 53, 57, 58, 62, 64, 66, 67, 68, 69, 70, 72,
    74, 74, 75, 75, 76, 76, 76, 80, 82, 84, 86, 88,
    90, 92, 0, 4, 12, 12, 12, 12, 5, 16, 18, 20,
    21, 22, 23, 24, 26, 28, 28, 29, 29, 30, 30, 30,
    34, 35, 39, 41, 43, 44, 45, 46, 47, 49, 51, 51,
    52, 52, 53, 53, 53, 57, 58, 62, 64, 66, 67, 68,
    69, 70, 72, 74, 74, 75, 75, 76, 76, 76, 80, 82,
    84, 86, 88, 90, 92, 0, 4, 12, 12, 12, 12, 5,
    16, 18, 20, 21, 22, 23, 24, 26, 28, 28, 29, 29,
    30, 30, 34, 35, 39, 41, 43, 44, 45, 46, 47, 49,
    51, 51, 52, 52, 53, 53, 57, 58, 62, 64, 66, 67,
    68, 69, 70, 72, 74, 74, 75, 75, 76, 76, 80, 82,
    84, 86, 88, 90, 92, 0, 4, 12, 12, 12, 12, 5,
    16, 18, 20, 21, 22, 23, 24, 26, 28, 28, 29, 29,
    30, 30, 34, 35, 39, 41, 43, 44, 45, 46, 47, 49,
    51, 51, 52, 52, 53, 53, 57, 58, 62, 64, 66, 67,
    68, 69, 70, 72, 74, 74, 75, 75, 76, 76, 80, 82,
    84, 86, 88, 90, 92, 0, 4, 12, 12, 12, 12, 5,
    16, 18, 20, 21, 22, 23, 24, 26, 28, 28, 29, 29,
    30, 30, 34, 35, 39, 41, 43, 44, 45, 46, 47, 49,
    51, 51, 52, 52, 53, 53, 57, 58, 62, 64, 66, 67,
    68, 69, 70, 72, 74, 74, 75, 75, 76, 76, 80, 82,
    84, 86, 88, 90, 92, 0, 1, 12, 5, 16, 18, 20,
    21, 22, 23, 24, 26, 28, 28, 29, 29, 30, 30, 34,
    35, 39, 41, 43, 44, 45, 46, 47, 49, 51, 51, 52,
    52, 53, 53, 57, 58, 62, 64, 66, 67, 68, 69, 70,
    72, 74, 74, 75, 75, 76, 76, 80, 82, 84, 86, 88,
    90, 92, 0, 1, 12, 5, 16, 18, 20, 21, 22, 23,
    24, 26, 28, 28, 29, 29, 30, 30, 34, 35, 39, 41,
    43, 44, 45, 46, 47, 49, 51, 51, 52, 52, 53, 53,
    57, 58, 62, 64, 66, 67, 68, 69, 70, 72, 74, 74,
    75, 75, 76, 76, 80, 82, 84, 86, 88, 90, 92, 0,
    1, 12, 5, 16, 18, 20, 21, 22, 23, 24, 26, 28,
    28, 29, 29, 30, 30, 34, 35, 39, 41, 43, 44, 45,
    46, 47, 49, 51, 51, 52, 52, 53, 53, 57, 58, 62,
    64, 66, 67, 68, 69, 70, 72, 74, 74, 75, 75, 76,
    76, 80, 82, 84, 86, 88, 90, 92, 0, 1, 12, 5,
    16, 18, 20, 21, 22, 23, 24, 26, 28, 28, 29, 29,
    30, 30, 34, 35, 39, 41, 43, 44, 45, 46, 47, 49,
    51, 51, 52, 52, 53, 53, 57, 58, 62, 64, 66, 67,
    68, 69, 70, 72, 74, 74, 75, 75, 76, 76, 80, 82,
    84, 86, 88, 90, 92, 0, 1, 12, 5, 16, 18, 20,
    21, 22, 23, 24, 26, 28, 28, 29, 29, 30, 30, 34,
    35, 39, 41, 43, 44, 45, 46, 47, 49, 51, 51, 52,
    52, 53, 53, 57, 58, 62, 64, 66, 67, 68, 69, 70,
    72, 74, 74, 75, 75, 76, 76, 80, 82, 84, 86, 88,
    90, 92, 0, 1, 12, 5, 16, 18, 20, 21, 22, 23,
    24, 26, 28, 28, 29, 29, 30, 30, 34, 35, 39, 41,
    43, 44, 45, 46, 47, 49, 51, 51, 52, 52, 53, 53,
    57, 58, 62, 64, 66, 67, 68, 69, 70, 72, 74, 74,
    75, 75, 76, 76, 80, 82, 84, 86, 88, 90, 92, 0,
    1, 12, 5, 16, 18, 20, 21, 22, 23, 24, 26, 28,
    28, 29, 29, 30, 30, 34, 35, 39, 41, 43, 44, 45,
    46, 47, 49, 51, 51, 52, 52, 53, 53, 57, 58, 62,
    64, 66, 67, 68, 69, 70, 72, 74, 74, 75, 75, 76,
    76, 80, 82, 84, 86, 88, 90, 92, 0, 1, 12, 5,
    16, 18, 20, 21, 22, 23, 24, 26, 28, 28, 29, 29,
    30, 30, 34, 35, 39, 41, 43, 44, 45, 46, 47, 49,
    51, 51, 52, 52, 53, 53, 57, 58, 62, 64, 66, 67,
    68, 69, 70, 72, 74, 74, 75, 75, 76, 76, 80, 82,
    84, 86, 88, 90, 92, 0, 1, 12, 5, 16, 18, 20,
    21, 22, 23, 24, 26, 28, 28, 29, 29, 30, 30, 34,
    35, 39, 41, 43, 44, 45, 46, 47, 49, 51, 51, 52,
    52, 53, 53, 57, 58, 62, 64, 66, 67, 68, 69, 70,
    72, 74, 74, 75, 75, 76, 76, 80, 82, 84, 86, 88,
    90, 92, 0, 1, 12, 5, 16, 18, 20, 21, 22, 23,
    24, 26, 28, 28, 29, 29, 30, 30, 34, 35, 39, 41,
    43, 44, 45, 46, 47, 49, 51, 51, 52, 52, 53, 53,
    57, 58, 62, 64, 66, 67, 68, 69, 70, 72, 74, 74,
    75, 75, 76, 76, 80, 82, 84, 86, 88, 90, 92, 0,
    1, 12, 5, 16, 18, 20, 21, 22, 23, 24, 26, 28,
    28, 29, 29, 30, 30, 34, 35, 39, 41, 43, 44, 45,
    46, 47, 49, 51, 51, 52, 52, 53, 53, 57, 58, 62,
    64, 66, 67, 68, 69, 70, 72, 74, 74, 75, 75, 76,
    76, 80, 82, 84, 86, 88, 90, 92, 0, 1, 12, 5,
    16, 18, 20, 21, 22, 23, 24, 26, 28, 28, 29, 29,
    30, 30, 34, 35, 39, 41, 43, 44, 45, 46, 47, 49,
    51, 51, 52, 52, 53, 53, 57, 58, 62, 64, 66, 67,
    68, 69, 70, 72, 74, 74, 75, 75, 76, 76, 80, 82,
    84, 86, 88, 90, 92, 0, 1, 12, 5, 16, 18, 20,
    21, 22, 23, 24, 26, 28, 28, 29, 29, 30, 30, 34,
    35, 39, 41, 43, 44, 45, 46, 47, 49, 51, 51, 52,
    52, 53, 53, 57, 58, 62, 64, 66, 67, 68, 69, 70,
    72, 74, 74, 75, 75, 76, 76, 80, 82, 84, 86, 88,
    90, 92, 0, 1, 12, 5, 16, 18, 20, 22, 23, 24,
    26, 28, 28, 29, 29, 30, 30, 34, 35, 39, 41, 43,
    45, 46, 47, 49, 51, 51, 52, 52, 53, 53, 57, 58,
    62, 64, 66, 68, 69, 70, 72, 74, 74, 75, 75, 76,
    76, 80, 82, 84, 86, 88, 90, 92, 0, 1, 12, 5,
    16, 18, 20, 22, 23, 24, 26, 28, 28, 29, 29, 30,
    30, 34, 35, 39, 41, 43, 45, 46, 47, 49, 51, 51,
    52, 52, 53, 53, 57, 58, 62, 64, 66, 68, 69, 70,
    72, 74, 74, 75, 75, 76, 76, 80, 82, 84, 86, 88,
    90, 92, 0, 1, 12, 5, 16, 18, 20, 22, 23, 24,
    26, 28, 28, 29, 29, 30, 30, 34, 35, 39, 41, 43,
    45, 46, 47, 49, 51, 51, 52, 52, 53, 53, 57, 58,
    62, 64, 66, 68, 69, 70, 72, 74, 74, 75, 75, 76,
    76, 80, 82, 84, 86, 88, 90, 92, 0, 1, 12, 5,
    16, 18, 20, 22, 23, 24, 26, 28, 28, 29, 29, 30,
    30, 34, 35, 39, 41, 43, 45, 46, 47, 49, 51, 51,
    52, 52, 53, 53, 57, 58, 62, 64, 66, 68, 69, 70,
    72, 74, 74, 75, 75, 76, 76, 80, 82, 84, 86, 88,
    90, 92, 0, 1, 12, 5, 16, 18, 20, 22, 23, 24,
    26, 28, 28, 29, 29, 30, 30, 34, 35, 39, 41, 43,
    45, 46, 47, 49, 51, 51, 52, 52, 53, 53, 57, 58,
    62, 64, 66, 68, 69, 70, 72, 74, 74, 75, 75, 76,
    76, 80, 82, 84, 86, 88, 90, 92, 0, 1, 12, 5,
    16, 18, 20, 22, 23, 24, 26, 28, 28, 29, 29, 30,
    30, 34, 35, 39, 41, 43, 45, 46, 47, 49, 51, 51,
    52, 52, 53, 53, 57, 58, 62, 64, 66, 68, 69, 70,
    72, 74, 74, 75, 75, 76, 76, 80, 82, 84, 86, 88,
    90, 92, 0, 1, 12, 5, 16, 18, 20, 22, 23, 24,
    26, 28, 28, 29, 29, 30, 30, 34, 35, 39, 41, 43,
    45, 46, 47, 49, 51, 51, 52, 52, 53, 53, 57, 58,
    62, 64, 66, 68, 69, 70, 72, 74, 74, 75, 75, 76,
    76, 80, 82, 84, 86, 88, 90, 92, 0, 1, 12, 5,
    16, 18, 20, 22, 23, 24, 26, 28, 28, 29, 29, 30,
    30, 34, 35, 39, 41, 43, 45, 46, 47, 49, 51, 51,
    52, 52, 53, 53, 57, 58, 62, 64, 66, 68, 69, 70,
    72, 74, 74, 75, 75, 76, 76, 80, 82, 84, 86, 88,
    90, 92, 0, 1, 12, 5, 16, 18, 20, 22, 23, 24,
    26, 28, 28, 29, 29, 30, 30, 34, 35, 39, 41, 43,
    45, 46, 47, 49, 51, 51, 52, 52, 53, 53, 57, 58,
    62, 64, 66, 68, 69, 70, 72, 74, 74, 75, 75, 76,
    76, 80, 82, 84, 86, 88, 90, 92, 0, 1, 12, 5,
    16, 18, 20, 22, 23, 24, 26, 28, 28, 29, 29, 30,
    30, 34, 35, 39, 41, 43, 45, 46, 47, 49, 51, 51,
    52, 52, 53, 53, 57, 58, 62, 64, 66, 68, 69, 70,
    72, 74, 74, 75, 75, 76, 76, 80, 82, 84, 86, 88,
    90, 92, 0, 1, 12, 5, 16, 18, 20, 22, 23, 24,
    26, 28, 28, 29, 29, 30, 30, 34, 35, 39, 41, 43,
    45, 46, 47, 49, 51, 51, 52, 52, 53, 53, 57, 58,
    62, 64, 66, 68, 69, 70, 72, 74, 74, 75, 75, 76,
    76, 80, 82, 84, 86, 88, 90, 92, 0, 1, 5, 16,
    18, 20, 22, 23, 24, 26, 28, 28, 29, 29, 30, 30,
    34, 35, 39, 41, 43, 45, 46, 47, 49, 51, 51, 52,
    52, 53, 53, 57, 58, 62, 64, 66, 68, 69, 70, 72,
    74, 74, 75, 75, 76, 76, 80, 82, 84, 86, 88, 90,
    92, 0, 1, 5, 16, 18, 20, 22, 23, 24, 26, 28,
    28, 29, 29, 30, 30, 34, 35, 39, 41, 43, 45, 46,
    47, 49, 51, 51, 52, 52, 53, 53, 57, 58, 62, 64,
    66, 68, 69, 70, 72, 74, 74, 75, 75, 76, 76, 80,
    82, 84, 86, 88, 90, 92, 0, 1, 5, 16, 18, 20,
    22, 23, 24, 26, 28, 28, 29, 29, 30, 30, 34, 35,
    39, 41, 43, 45, 46, 47, 49, 51, 51, 52, 52, 53,
    53, 57, 58, 62, 64, 66, 68, 69, 70, 72, 74, 74,
    75, 75, 76, 76, 80, 82, 84, 86, 88, 90, 92, 0,
    1, 5, 16, 18, 20, 22, 23, 24, 26, 28, 28, 29,
    29, 30, 30, 34, 35, 39, 41, 43, 45, 46, 47, 49,
    51, 51, 52, 52, 53, 53, 57, 58, 62, 64, 66, 68,
    69, 70, 72, 74, 74, 75, 75, 76, 76, 80, 82, 84,
    86, 88, 90, 92, 0, 1, 5, 16, 18, 20, 22, 23,
    24, 26, 28, 28, 29, 29, 30, 30, 34, 35, 39, 41,
    43, 45, 46, 47, 49, 51, 51, 52, 52, 53, 53, 57,
    58, 62, 64, 66, 68, 69, 70, 72, 74, 74, 75, 75,
    76, 76, 80, 82, 84, 86, 88, 90, 92, 0, 1, 5,
    16, 22, 24, 26, 28, 28, 29, 30, 30, 34, 35, 39,
    45, 47, 49, 51, 51, 52, 53, 53, 57, 58, 62, 68,
    70, 72, 74, 74, 75, 76, 76, 80, 82, 84, 86, 88,
    90, 92, 0, 1, 5, 16, 22, 24, 26, 28, 28, 29,
    30, 30, 34, 35, 39, 45, 47, 49, 51, 51, 52, 53,
    53, 57, 58, 62, 68, 70, 72, 74, 74, 75, 76, 76,
    80, 82, 84, 86, 88, 90, 92, 0, 1, 5, 16, 22,
    24, 26, 28, 28, 29, 30, 30, 34, 35, 39, 45, 47,
    49, 51, 51, 52, 53, 53, 57, 58, 62, 68, 70, 72,
    74, 74, 75, 76, 76, 80, 82, 84, 86, 88, 90, 92,
    0, 1, 5, 16, 22, 24, 26, 28, 28, 29, 30, 30,
    34, 35, 39, 45, 47, 49, 51, 51, 52, 53, 53, 57,
    58, 62, 68, 70, 72, 74, 74, 75, 76, 76, 80, 82,
    84, 86, 88, 90, 92, 0, 1, 5, 16, 22, 24, 26,
    28, 28, 29, 30, 30, 34, 35, 39, 45, 47, 49, 51,
    51, 52, 53, 53, 57, 58, 62, 68, 70, 72, 74, 74,
    75, 76, 76, 80, 82, 84, 86, 88, 90, 92, 0, 1,
    5, 16, 22, 24, 26, 28, 28, 29, 30, 30, 34, 35,
    39, 45, 47, 49, 51, 51, 52, 53, 53, 57, 58, 62,
    68, 70, 72, 74, 74, 75, 76, 76, 80, 82, 84, 86,
    88, 90, 92, 0, 1, 5, 16, 22, 24, 26, 28, 28,
    29, 30, 30, 34, 35, 39, 45, 47, 49, 51, 51, 52,
    53, 53, 57, 58, 62, 68, 70, 72, 74, 74, 75, 76,
    76, 80, 82, 84, 86, 88, 90, 92, 0, 1, 5, 16,
    22, 24, 26, 28, 28, 29, 30, 30, 34, 35, 39, 45,
    47, 49, 51, 51, 52, 53, 53, 57, 58, 62, 68, 70,
    72, 74, 74, 75, 76, 76, 80, 82, 84, 86, 88, 90,
    92, 0, 1, 5, 16, 22, 24, 26, 28, 31, 30, 30,
    34, 35, 39, 45, 47, 49, 51, 54, 53, 53, 57, 58,
    62, 68, 70, 72, 74, 77, 76, 76, 80, 82, 84, 86,
    88, 90, 92, 0, 1, 5, 16, 22, 24, 26, 28, 31,
    30, 30, 34, 35, 39, 45, 47, 49, 51, 54, 53, 53,
    57, 58, 62, 68, 70, 72, 74, 77, 76, 76, 80, 82,
    84, 86, 88, 90, 92, 0, 1, 5, 16, 22, 24, 26,
    28, 31, 30, 30, 34, 35, 39, 45, 47, 49, 51, 54,
    53, 53, 57, 58, 62, 68, 70, 72, 74, 77, 76, 76,
    80, 82, 84, 86, 88, 90, 92, 0, 1, 5, 16, 22,
    24, 26, 28, 31, 30, 30, 34, 35, 39, 45, 47, 49,
    51, 54, 53, 53, 57, 58, 62, 68, 70, 72, 74, 77,
    76, 76, 80, 82, 84, 86, 88, 90, 92, 0, 1, 5,
    16, 22, 24, 26, 28, 31, 30, 30, 34, 35, 39, 45,
    47, 49, 51, 54, 53, 53, 57, 58, 62, 68, 70, 72,
    74, 77, 76, 76, 80, 82, 84, 86, 88, 90, 92, 0,
    1, 5, 16, 22, 24, 26, 28, 31, 30, 30, 34, 35,
    39, 45, 47, 49, 51, 54, 53, 53, 57, 58, 62, 68,
    70, 72, 74, 77, 76, 76, 80, 82, 84, 86, 88, 90,
    92, 0, 1, 5, 16, 22, 24, 26, 28, 31, 30, 30,
    34, 35, 39, 45, 47, 49, 51, 54, 53, 53, 57, 58,
    62, 68, 70, 72, 74, 77, 76, 76, 80, 82, 84, 86,
    88, 90, 92, 0, 1, 5, 16, 22, 24, 26, 28, 31,
    30, 30, 34, 35, 39, 45, 47, 49, 51, 54, 53, 53,
    57, 58, 62, 68, 70, 72, 74, 77, 76, 76, 80, 82,
    84, 86, 88, 90, 92, 4, 1, 5, 16, 22, 24, 26,
    28, 31, 30, 30, 34, 35, 39, 45, 47, 49, 51, 54,
    53, 53, 57, 58, 62, 68, 70, 72, 74, 77, 76, 76,
    80, 82, 84, 86, 88, 90, 92, 4, 1, 5, 16, 22,
    24, 26, 28, 31, 30, 30, 34, 35, 39, 45, 47, 49,
    51, 54, 53, 53, 57, 58, 62, 68, 70, 72, 74, 77,
    76, 76, 80, 82, 84, 86, 88, 90, 92, 4, 1, 5,
    16, 22, 24, 26, 28, 31, 30, 30, 34, 35, 39, 45,
    47, 49, 51, 54, 53, 53, 57, 58, 62, 68, 70, 72,
    74, 77, 76, 76, 80, 82, 84, 86, 88, 90, 92, 4,
    1, 5, 16, 22, 24, 26, 28, 31, 30, 30, 34, 35,
    39, 45, 47, 49, 51, 54, 53, 53, 57, 58, 62, 68,
    70, 72, 74, 77, 76, 76, 80, 82, 84, 86, 88, 90,
    92, 4, 1, 5, 16, 22, 24, 26, 28, 31, 30, 30,
    34, 35, 39, 45, 47, 49, 51, 54, 53, 53, 57, 58,
    62, 68, 70, 72, 74, 77, 76, 76, 80, 82, 84, 86,
    88, 90, 92, 4, 1, 16, 22, 24, 26, 28, 31, 30,
    30, 34, 35, 39, 45, 47, 49, 51, 54, 53, 53, 57,
    58, 62, 68, 70, 72, 74, 77, 76, 76, 80, 82, 84,
    86, 88, 90, 92, 4, 1, 16, 22, 24, 26, 28, 31,
    30, 30, 34, 35, 39, 45, 47, 49, 51, 54, 53, 53,
    57, 58, 62, 68, 70, 72, 74, 77, 76, 76, 80, 82,
    84, 86, 88, 90, 92, 4, 1, 16, 22, 24, 26, 28,
    31, 30, 30, 34, 35, 39, 45, 47, 49, 51, 54, 53,
    53, 57, 58, 62, 68, 70, 72, 74, 77, 76, 76, 80,
    82, 84, 86, 88, 90, 92, 4, 1, 16, 22, 24, 26,
    28, 31, 30, 30, 34, 35, 39, 45, 47, 49, 51, 54,
    53, 53, 57, 58, 62, 68, 70, 72, 74, 77, 76, 76,
    80, 82, 84, 86, 88, 90, 92, 4, 1, 16, 22, 24,
    26, 28, 31, 30, 30, 34, 35, 39, 45, 47, 49, 51,
    54, 53, 53, 57, 58, 62, 68, 70, 72, 74, 77, 76,
    76, 80, 82, 84, 86, 88, 90, 92, 4, 1, 16, 22,
    24, 26, 28, 31, 30, 30, 34, 35, 39, 45, 47, 49,
    51, 54, 53, 53, 57, 58, 62, 68, 70, 72, 74, 77,
    76, 76, 80, 82, 84, 86, 88, 90, 92, 4, 1, 16,
    22, 24, 28, 31, 30, 30, 34, 35, 39, 45, 47, 51,
    54, 53, 53, 57, 58, 62, 68, 70, 74, 77, 76, 76,
    80, 82, 84, 86, 88, 90, 92, 4, 1, 16, 22, 24,
    28, 31, 30, 30, 34, 35, 39, 45, 47, 51, 54, 53,
    53, 57, 58, 62, 68, 70, 74, 77, 76, 76, 80, 82,
    84, 86, 88, 90, 92, 4, 1, 16, 22, 24, 28, 31,
    30, 30, 34, 35, 39, 45, 47, 51, 54, 53, 53, 57,
    58, 62, 68, 70, 74, 77, 76, 76, 80, 82, 84, 86,
    88, 90, 92, 4, 1, 16, 22, 24, 28, 31, 30, 30,
    34, 35, 39, 45, 47, 51, 54, 53, 53, 57, 58, 62,
    68, 70, 74, 77, 76, 76, 80, 82, 84, 86, 88, 90,
    92, 4, 1, 16, 22, 24, 28, 31, 30, 30, 34, 35,
    39, 45, 47, 51, 54, 53, 53, 57, 58, 62, 68, 70,
    74, 77, 76, 76, 80, 82, 84, 86, 88, 90, 92, 4,
    1, 16, 22, 24, 28, 31, 30, 30, 34, 35, 39, 45,
    47, 51, 54, 53, 53, 57, 58, 62, 68, 70, 74, 77,
    76, 76, 80, 82, 84, 86, 88, 90, 92, 4, 1, 16,
    22, 24, 28, 31, 30, 30, 34, 35, 39, 45, 47, 51,
    54, 53, 53, 57, 58, 62, 68, 70, 74, 77, 76, 76,
    80, 82, 84, 86, 88, 90, 92, 4, 1, 16, 22, 24,
    28, 31, 30, 30, 34, 35, 39, 45, 47, 51, 54, 53,
    53, 57, 58, 62, 68, 70, 74, 77, 76, 76, 80, 82,
    84, 86, 88, 90, 92, 4, 1, 16, 22, 24, 28, 31,
    30, 30, 34, 35, 39, 45, 47, 51, 54, 53, 53, 57,
    58, 62, 68, 70, 74, 77, 76, 76, 80, 82, 84, 86,
    88, 90, 92, 4, 1, 16, 22, 24, 28, 31, 30, 30,
    34, 35, 39, 45, 47, 51, 54, 53, 53, 57, 58, 62,
    68, 70, 74, 77, 76, 76, 80, 82, 84, 86, 88, 90,
    92, 4, 1, 16, 22, 24, 28, 31, 30, 30, 34, 35,
    39, 45, 47, 51, 54, 53, 53, 57, 58, 62, 68, 70,
    74, 77, 76, 76, 80, 82, 84, 86, 88, 90, 92, 4,
    1, 16, 22, 24, 28, 31, 30, 30, 34, 35, 39, 45,
    47, 51, 54, 53, 53, 57, 58, 62, 68, 70, 74, 77,
    76, 76, 80, 82, 84, 86, 88, 90, 92, 4, 1, 16,
    22, 24, 28, 31, 30, 30, 34, 35, 39, 45, 47, 51,
    54, 53, 53, 57, 58, 62, 68, 70, 74, 77, 76, 76,
    80, 82, 84, 86, 88, 90, 92, 4, 1, 16, 22, 28,
    29, 30, 30, 34, 39, 45, 51, 52, 53, 53, 57, 62,
    68, 74, 75, 76, 76, 80, 82, 84, 86, 88, 90, 92,
    4, 1, 16, 22, 28, 29, 30, 30, 34, 39, 45, 51,
    52, 53, 53, 57, 62, 68, 74, 75, 76, 76, 80, 82,
    84, 86, 88, 90, 92, 4, 1, 16, 22, 28, 29, 30,
    30, 34, 39, 45, 51, 52, 53, 53, 57, 62, 68, 74,
    75, 76, 76, 80, 82, 84, 86, 88, 90, 92, 4, 1,
    16, 22, 28, 29, 30, 30, 34, 39, 45, 51, 52, 53,
    53, 57, 62, 68, 74, 75, 76, 76, 80, 82, 84, 86,
    88, 90, 92, 4, 1, 16, 22, 28, 29, 30, 30, 34,
    39, 45, 51, 52, 53, 53, 57, 62, 68, 74, 75, 76,
    76, 80, 82, 84, 86, 88, 90, 92, 4, 1, 16, 22,
    28, 29, 30, 30, 34, 39, 45, 51, 52, 53, 53, 57,
    62, 68, 74, 75, 76, 76, 80, 82, 84, 86, 88, 90,
    92, 4, 1, 16, 22, 28, 29, 30, 30, 34, 39, 45,
    51, 52, 53, 53, 57, 62, 68, 74, 75, 76, 76, 80,
    82, 84, 86, 88, 90, 92, 4, 1, 16, 22, 28, 29,
    30, 30, 34, 39, 45, 51, 52, 53, 53, 57, 62, 68,
    74, 75, 76, 76, 80, 82, 84, 86, 88, 90, 92, 4,
    1, 6, 7, 28, 29, 30, 30, 34, 8, 40, 42, 51,
    52, 53, 53, 57, 10, 63, 65, 74, 75, 76, 76, 80,
    82, 84, 86, 88, 90, 92, 4, 1, 6, 7, 28, 29,
    30, 30, 34, 8, 40, 42, 51, 52, 53, 53, 57, 10,
    63, 65, 74, 75, 76, 76, 80, 82, 84, 86, 88, 90,
    92, 4, 1, 6, 28, 29, 30, 30, 34, 8, 40, 42,
    51, 52, 53, 53, 57, 10, 63, 65, 74, 75, 76, 76,
    80, 82, 84, 86, 88, 90, 92, 4, 1, 6, 28, 29,
    30, 30, 34, 8, 40, 42, 51, 52, 53, 53, 57, 10,
    63, 65, 74, 75, 76, 76, 80, 82, 84, 86, 88, 90,
    92, 4, 1, 6, 28, 29, 30, 30, 34, 8, 40, 42,
    51, 52, 53, 53, 57, 10, 63, 65, 74, 75, 76, 76,
    80, 82, 84, 86, 88, 90, 92, 4, 1, 6, 28, 29,
    30, 30, 34, 8, 40, 42, 51, 52, 53, 53, 57, 10,
    63, 65, 74, 75, 76, 76, 80, 82, 84, 86, 88, 90,
    92, 4, 1, 6, 28, 29, 30, 30, 34, 8, 40, 42,
    51, 52, 53, 53, 57, 10, 63, 65, 74, 75, 76, 76,
    80, 82, 84, 86, 88, 90, 92, 4, 1, 6, 28, 29,
    30, 30, 34, 8, 40, 42, 51, 52, 53, 53, 57, 10,
    63, 65, 74, 75, 76, 76, 80, 82, 84, 86, 88, 90,
    92, 4, 1, 6, 28, 29, 30, 30, 34, 8, 40, 42,
    51, 52, 53, 53, 57, 10, 63, 65, 74, 75, 76, 76,
    80, 82, 84, 86, 88, 90, 92, 4, 1, 6, 28, 29,
    30, 30, 34, 8, 40, 42, 51, 52, 53, 53, 57, 10,
    63, 65, 74, 75, 76, 76, 80, 82, 84, 86, 88, 90,
    92, 4, 1, 6, 28, 29, 30, 30, 34, 8, 40, 51,
    52, 53, 53, 57, 10, 63, 74, 75, 76, 76, 80, 82,
    84, 86, 88, 90, 92, 4, 1, 6, 28, 29, 30, 30,
    34, 8, 40, 51, 52, 53, 53, 57, 10, 63, 74, 75,
    76, 76, 80, 82, 84, 86, 88, 90, 92, 4, 1, 6,
    28, 29, 30, 30, 34, 8, 40, 51, 52, 53, 53, 57,
    10, 63, 74, 75, 76, 76, 80, 82, 84, 86, 88, 90,
    92, 4, 1, 6, 28, 29, 30, 30, 34, 8, 40, 51,
    52, 53, 53, 57, 10, 63, 74, 75, 76, 76, 80, 82,
    84, 86, 88, 90, 92, 4, 1, 6, 28, 29, 30, 30,
    34, 8, 40, 51, 52, 53, 53, 57, 10, 63, 74, 75,
    76, 76, 80, 82, 84, 86, 88, 90, 92, 4, 1, 6,
    28, 29, 30, 30, 34, 8, 40, 51, 52, 53, 53, 57,
    10, 63, 74, 75, 76, 76, 80, 82, 84, 86, 88, 90,
    92, 4, 1, 17, 17, 19, 19, 28, 29, 30, 30, 34,
    9, 51, 52, 53, 53, 57, 11, 74, 75, 76, 76, 80,
    82, 84, 86, 88, 90, 92, 4, 1, 17, 17, 19, 19,
    28, 29, 30, 30, 34, 9, 51, 52, 53, 53, 57, 11,
    74, 75, 76, 76, 80, 83, 4, 1, 17, 17, 19, 28,
    29, 30, 30, 34, 51, 52, 53, 53, 57, 74, 75, 76,
    76, 80, 83, 4, 1, 17, 17, 19, 28, 29, 30, 30,
    34, 51, 52, 53, 53, 57, 74, 75, 76, 76, 80, 4,
    1, 17, 17, 19, 28, 29, 30, 30, 34, 51, 52, 53,
    53, 57, 74, 75, 76, 76, 80, 4, 1, 17, 17, 19,
    28, 29, 30, 30, 34, 51, 52, 53, 53, 57, 74, 75,
    76, 76, 80, 4, 1, 17, 17, 19, 28, 29, 30, 30,
    34, 51, 52, 53, 53, 57, 74, 75, 76, 76, 80, 4,
    1, 17, 17, 19, 28, 29, 30, 30, 34, 51, 52, 53,
    53, 57, 74, 75, 76, 76, 80,
};

static __device__ __constant__ uint16_t kStaticTaskClaims[6979] = {
    0, 56, 101, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 152, 0, 0, 0, 152, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 152, 0, 0, 0, 152, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 152, 0,
    0, 0, 152, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 1, 57, 102, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 153, 1, 1,
    1, 153, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 153, 1, 1, 1, 153, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 153, 1, 1, 1, 153, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 2, 58, 103, 2, 2, 2, 2,
    2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 154,
    2, 2, 2, 154, 2, 2, 2, 2, 2, 2, 2, 2,
    2, 2, 2, 2, 2, 2, 2, 154, 2, 2, 2, 154,
    2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
    2, 2, 2, 154, 2, 2, 2, 154, 2, 2, 2, 2,
    2, 2, 2, 3, 59, 104, 3, 3, 3, 3, 3, 3,
    3, 3, 3, 3, 3, 3, 3, 3, 3, 155, 3, 3,
    3, 155, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
    3, 3, 3, 3, 3, 155, 3, 3, 3, 155, 3, 3,
    3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
    3, 155, 3, 3, 3, 155, 3, 3, 3, 3, 3, 3,
    3, 4, 60, 105, 4, 4, 4, 4, 4, 4, 4, 4,
    4, 4, 4, 4, 4, 4, 4, 156, 4, 4, 4, 156,
    4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
    4, 4, 4, 156, 4, 4, 4, 156, 4, 4, 4, 4,
    4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 156,
    4, 4, 4, 156, 4, 4, 4, 4, 4, 4, 4, 5,
    61, 106, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
    5, 5, 5, 5, 5, 157, 5, 5, 5, 157, 5, 5,
    5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
    5, 157, 5, 5, 5, 157, 5, 5, 5, 5, 5, 5,
    5, 5, 5, 5, 5, 5, 5, 5, 5, 157, 5, 5,
    5, 157, 5, 5, 5, 5, 5, 5, 5, 6, 62, 107,
    6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
    6, 6, 6, 158, 6, 6, 6, 158, 6, 6, 6, 6,
    6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 158,
    6, 6, 6, 158, 6, 6, 6, 6, 6, 6, 6, 6,
    6, 6, 6, 6, 6, 6, 6, 158, 6, 6, 6, 158,
    6, 6, 6, 6, 6, 6, 6, 7, 63, 108, 7, 7,
    7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
    7, 159, 7, 7, 7, 159, 7, 7, 7, 7, 7, 7,
    7, 7, 7, 7, 7, 7, 7, 7, 7, 159, 7, 7,
    7, 159, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
    7, 7, 7, 7, 7, 159, 7, 7, 7, 159, 7, 7,
    7, 7, 7, 7, 7, 8, 64, 109, 8, 8, 8, 8,
    8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 160,
    8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
    8, 8, 8, 8, 8, 8, 160, 8, 8, 8, 8, 8,
    8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
    8, 160, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
    9, 65, 110, 9, 9, 9, 9, 9, 9, 9, 9, 9,
    9, 9, 9, 9, 9, 9, 161, 9, 9, 9, 9, 9,
    9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
    9, 161, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
    9, 9, 9, 9, 9, 9, 9, 9, 161, 9, 9, 9,
    9, 9, 9, 9, 9, 9, 9, 10, 66, 111, 10, 10,
    10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 162, 10,
    10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
    10, 162, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
    10, 10, 10, 10, 162, 10, 10, 10, 10, 10, 10, 10,
    10, 10, 11, 67, 112, 11, 11, 11, 11, 11, 11, 11,
    11, 11, 11, 11, 11, 163, 11, 11, 11, 11, 11, 11,
    11, 11, 11, 11, 11, 11, 11, 11, 163, 11, 11, 11,
    11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 163,
    11, 11, 11, 11, 11, 11, 11, 11, 11, 12, 68, 113,
    12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12,
    164, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12,
    12, 12, 12, 164, 12, 12, 12, 12, 12, 12, 12, 12,
    12, 12, 12, 12, 12, 12, 164, 12, 12, 12, 12, 12,
    12, 12, 12, 12, 13, 69, 114, 13, 13, 13, 13, 13,
    13, 13, 13, 13, 13, 13, 13, 165, 13, 13, 13, 13,
    13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 165, 13,
    13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13,
    13, 165, 13, 13, 13, 13, 13, 13, 13, 13, 13, 14,
    70, 115, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14,
    14, 14, 166, 14, 14, 14, 14, 14, 14, 14, 14, 14,
    14, 14, 14, 14, 14, 166, 14, 14, 14, 14, 14, 14,
    14, 14, 14, 14, 14, 14, 14, 14, 166, 14, 14, 14,
    14, 14, 14, 14, 14, 14, 15, 71, 116, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 15, 15, 167, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
    167, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 167, 15, 15, 15, 15, 15, 15, 15, 15,
    15, 16, 72, 117, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 168, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 168, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 168, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 17, 73, 118, 17, 17, 17,
    17, 17, 17, 17, 17, 17, 17, 169, 17, 17, 17, 17,
    17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 169, 17,
    17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17,
    17, 169, 17, 17, 17, 17, 17, 17, 17, 17, 17, 18,
    74, 119, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18,
    170, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18,
    18, 18, 18, 170, 18, 18, 18, 18, 18, 18, 18, 18,
    18, 18, 18, 18, 18, 18, 170, 18, 18, 18, 18, 18,
    18, 18, 18, 18, 19, 75, 120, 19, 19, 19, 19, 19,
    19, 19, 19, 19, 19, 171, 19, 19, 19, 19, 19, 19,
    19, 19, 19, 19, 19, 19, 19, 19, 171, 19, 19, 19,
    19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 171,
    19, 19, 19, 19, 19, 19, 19, 19, 19, 20, 76, 121,
    20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 172, 20,
    20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
    20, 172, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
    20, 20, 20, 20, 172, 20, 20, 20, 20, 20, 20, 20,
    20, 20, 21, 77, 122, 21, 21, 21, 21, 21, 21, 21,
    21, 21, 21, 173, 21, 21, 21, 21, 21, 21, 21, 21,
    21, 21, 21, 21, 21, 21, 173, 21, 21, 21, 21, 21,
    21, 21, 21, 21, 21, 21, 21, 21, 21, 173, 21, 21,
    21, 21, 21, 21, 21, 21, 21, 22, 78, 123, 22, 22,
    22, 22, 22, 22, 22, 22, 22, 22, 174, 22, 22, 22,
    22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 174,
    22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22,
    22, 22, 174, 22, 22, 22, 22, 22, 22, 22, 22, 22,
    23, 79, 124, 23, 23, 23, 23, 23, 23, 23, 23, 23,
    23, 175, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23,
    23, 23, 23, 23, 175, 23, 23, 23, 23, 23, 23, 23,
    23, 23, 23, 23, 23, 23, 23, 175, 23, 23, 23, 23,
    23, 23, 23, 23, 23, 24, 80, 125, 24, 24, 24, 24,
    24, 24, 24, 24, 24, 24, 176, 24, 24, 24, 24, 24,
    24, 24, 24, 24, 24, 24, 24, 24, 24, 176, 24, 24,
    24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24,
    176, 24, 24, 24, 24, 24, 24, 24, 24, 24, 25, 81,
    126, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 177,
    25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
    25, 25, 177, 25, 25, 25, 25, 25, 25, 25, 25, 25,
    25, 25, 25, 25, 25, 177, 25, 25, 25, 25, 25, 25,
    25, 25, 25, 26, 82, 127, 26, 26, 26, 26, 26, 26,
    26, 26, 26, 26, 178, 26, 26, 26, 26, 26, 26, 26,
    26, 26, 26, 26, 26, 26, 26, 178, 26, 26, 26, 26,
    26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 178, 26,
    26, 26, 26, 26, 26, 26, 26, 26, 27, 83, 0, 24,
    48, 72, 0, 27, 27, 27, 27, 27, 27, 27, 27, 27,
    27, 179, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27,
    27, 27, 27, 27, 179, 27, 27, 27, 27, 27, 27, 27,
    27, 27, 27, 27, 27, 27, 27, 179, 27, 27, 27, 27,
    27, 27, 27, 27, 27, 28, 84, 1, 25, 49, 73, 1,
    28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 180, 28,
    28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28,
    28, 180, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28,
    28, 28, 28, 28, 180, 28, 28, 28, 28, 28, 28, 28,
    28, 28, 29, 85, 2, 26, 50, 74, 2, 29, 29, 29,
    29, 29, 29, 29, 29, 29, 29, 181, 29, 29, 29, 29,
    29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 181, 29,
    29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29,
    29, 181, 29, 29, 29, 29, 29, 29, 29, 29, 29, 30,
    86, 3, 27, 51, 75, 3, 30, 30, 30, 30, 30, 30,
    30, 30, 30, 30, 182, 30, 30, 30, 30, 30, 30, 30,
    30, 30, 30, 30, 30, 30, 30, 182, 30, 30, 30, 30,
    30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 182, 30,
    30, 30, 30, 30, 30, 30, 30, 30, 31, 87, 4, 28,
    52, 76, 4, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 183, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 183, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 183, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 32, 88, 5, 29, 53, 77, 5,
    32, 32, 32, 32, 32, 32, 32, 32, 32, 184, 32, 224,
    32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 184,
    32, 224, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32,
    32, 184, 32, 224, 32, 32, 32, 32, 32, 32, 32, 33,
    89, 6, 30, 54, 78, 6, 33, 33, 33, 33, 33, 33,
    33, 33, 33, 185, 33, 225, 33, 33, 33, 33, 33, 33,
    33, 33, 33, 33, 33, 185, 33, 225, 33, 33, 33, 33,
    33, 33, 33, 33, 33, 33, 33, 185, 33, 225, 33, 33,
    33, 33, 33, 33, 33, 34, 90, 7, 31, 55, 79, 7,
    34, 34, 34, 34, 34, 34, 34, 34, 34, 186, 34, 226,
    34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 186,
    34, 226, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34,
    34, 186, 34, 226, 34, 34, 34, 34, 34, 34, 34, 35,
    91, 8, 32, 56, 80, 8, 35, 35, 35, 35, 35, 35,
    35, 35, 35, 187, 35, 227, 35, 35, 35, 35, 35, 35,
    35, 35, 35, 35, 35, 187, 35, 227, 35, 35, 35, 35,
    35, 35, 35, 35, 35, 35, 35, 187, 35, 227, 35, 35,
    35, 35, 35, 35, 35, 36, 92, 9, 33, 57, 81, 9,
    36, 36, 36, 36, 36, 36, 36, 36, 36, 188, 36, 228,
    36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 188,
    36, 228, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36,
    36, 188, 36, 228, 36, 36, 36, 36, 36, 36, 36, 37,
    93, 10, 34, 58, 82, 0, 37, 37, 37, 37, 37, 37,
    37, 37, 37, 189, 37, 229, 37, 37, 37, 37, 37, 37,
    37, 37, 37, 37, 37, 189, 37, 229, 37, 37, 37, 37,
    37, 37, 37, 37, 37, 37, 37, 189, 37, 229, 37, 37,
    37, 37, 37, 37, 37, 38, 94, 11, 35, 59, 83, 1,
    38, 38, 38, 38, 38, 38, 38, 38, 38, 190, 38, 230,
    38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 190,
    38, 230, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38,
    38, 190, 38, 230, 38, 38, 38, 38, 38, 38, 38, 39,
    95, 12, 36, 60, 84, 2, 39, 39, 39, 39, 39, 39,
    39, 39, 39, 191, 39, 231, 39, 39, 39, 39, 39, 39,
    39, 39, 39, 39, 39, 191, 39, 231, 39, 39, 39, 39,
    39, 39, 39, 39, 39, 39, 39, 191, 39, 231, 39, 39,
    39, 39, 39, 39, 39, 40, 96, 13, 37, 61, 85, 3,
    40, 40, 40, 40, 40, 40, 40, 40, 40, 192, 0, 80,
    0, 112, 232, 40, 40, 40, 40, 40, 40, 40, 40, 40,
    40, 40, 192, 0, 80, 0, 112, 232, 40, 40, 40, 40,
    40, 40, 40, 40, 40, 40, 40, 192, 0, 80, 0, 112,
    232, 40, 40, 40, 40, 40, 40, 40, 41, 97, 14, 38,
    62, 86, 4, 41, 41, 41, 41, 41, 41, 41, 41, 41,
    193, 1, 81, 1, 113, 233, 41, 41, 41, 41, 41, 41,
    41, 41, 41, 41, 41, 193, 1, 81, 1, 113, 233, 41,
    41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 193, 1,
    81, 1, 113, 233, 41, 41, 41, 41, 41, 41, 41, 42,
    98, 15, 39, 63, 87, 5, 42, 42, 42, 42, 42, 42,
    42, 42, 42, 194, 2, 82, 2, 114, 234, 42, 42, 42,
    42, 42, 42, 42, 42, 42, 42, 42, 194, 2, 82, 2,
    114, 234, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42,
    42, 194, 2, 82, 2, 114, 234, 42, 42, 42, 42, 42,
    42, 42, 43, 99, 16, 40, 64, 88, 6, 43, 43, 43,
    43, 43, 43, 43, 43, 43, 195, 3, 83, 3, 115, 235,
    43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 195,
    3, 83, 3, 115, 235, 43, 43, 43, 43, 43, 43, 43,
    43, 43, 43, 43, 195, 3, 83, 3, 115, 235, 43, 43,
    43, 43, 43, 43, 43, 44, 100, 17, 41, 65, 89, 7,
    44, 44, 44, 44, 44, 44, 44, 44, 44, 196, 4, 84,
    4, 116, 236, 44, 44, 44, 44, 44, 44, 44, 44, 44,
    44, 44, 196, 4, 84, 4, 116, 236, 44, 44, 44, 44,
    44, 44, 44, 44, 44, 44, 44, 196, 4, 84, 4, 116,
    236, 44, 44, 44, 44, 44, 44, 44, 45, 101, 18, 42,
    66, 90, 8, 45, 45, 45, 45, 45, 45, 45, 45, 45,
    197, 5, 85, 5, 117, 237, 45, 45, 45, 45, 45, 45,
    45, 45, 45, 45, 45, 197, 5, 85, 5, 117, 237, 45,
    45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 197, 5,
    85, 5, 117, 237, 45, 45, 45, 45, 45, 45, 45, 46,
    102, 19, 43, 67, 91, 9, 46, 46, 46, 46, 46, 46,
    46, 46, 46, 198, 6, 86, 6, 118, 238, 46, 46, 46,
    46, 46, 46, 46, 46, 46, 46, 46, 198, 6, 86, 6,
    118, 238, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46,
    46, 198, 6, 86, 6, 118, 238, 46, 46, 46, 46, 46,
    46, 46, 47, 103, 20, 44, 68, 92, 10, 47, 47, 47,
    47, 47, 47, 47, 47, 47, 199, 7, 87, 7, 119, 239,
    47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 199,
    7, 87, 7, 119, 239, 47, 47, 47, 47, 47, 47, 47,
    47, 47, 47, 47, 199, 7, 87, 7, 119, 239, 47, 47,
    47, 47, 47, 47, 47, 48, 104, 21, 45, 69, 93, 11,
    48, 48, 48, 48, 48, 48, 48, 48, 48, 200, 8, 88,
    8, 120, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48,
    48, 200, 8, 88, 8, 120, 48, 48, 48, 48, 48, 48,
    48, 48, 48, 48, 48, 200, 8, 88, 8, 120, 48, 48,
    48, 48, 48, 48, 48, 49, 105, 22, 46, 70, 94, 12,
    49, 49, 49, 49, 49, 49, 49, 49, 49, 201, 9, 89,
    9, 121, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49,
    49, 201, 9, 89, 9, 121, 49, 49, 49, 49, 49, 49,
    49, 49, 49, 49, 49, 201, 9, 89, 9, 121, 49, 49,
    49, 49, 49, 49, 49, 50, 106, 23, 47, 71, 95, 13,
    50, 50, 50, 50, 50, 50, 50, 50, 50, 202, 10, 90,
    10, 122, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50,
    50, 202, 10, 90, 10, 122, 50, 50, 50, 50, 50, 50,
    50, 50, 50, 50, 50, 202, 10, 90, 10, 122, 50, 50,
    50, 50, 50, 50, 50, 51, 0, 96, 14, 51, 51, 51,
    51, 51, 51, 51, 51, 51, 203, 11, 91, 11, 123, 51,
    51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 203, 11,
    91, 11, 123, 51, 51, 51, 51, 51, 51, 51, 51, 51,
    51, 51, 203, 11, 91, 11, 123, 51, 51, 51, 51, 51,
    51, 51, 52, 1, 97, 15, 52, 52, 52, 52, 52, 52,
    52, 52, 52, 204, 12, 92, 12, 124, 52, 52, 52, 52,
    52, 52, 52, 52, 52, 52, 52, 204, 12, 92, 12, 124,
    52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 204,
    12, 92, 12, 124, 52, 52, 52, 52, 52, 52, 52, 53,
    2, 98, 16, 53, 53, 53, 53, 53, 53, 53, 53, 53,
    205, 13, 93, 13, 125, 53, 53, 53, 53, 53, 53, 53,
    53, 53, 53, 53, 205, 13, 93, 13, 125, 53, 53, 53,
    53, 53, 53, 53, 53, 53, 53, 53, 205, 13, 93, 13,
    125, 53, 53, 53, 53, 53, 53, 53, 54, 3, 99, 17,
    54, 54, 54, 54, 54, 54, 54, 54, 54, 206, 14, 94,
    14, 126, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54,
    54, 206, 14, 94, 14, 126, 54, 54, 54, 54, 54, 54,
    54, 54, 54, 54, 54, 206, 14, 94, 14, 126, 54, 54,
    54, 54, 54, 54, 54, 55, 4, 100, 18, 55, 55, 55,
    55, 55, 55, 55, 55, 55, 207, 15, 95, 15, 127, 55,
    55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 207, 15,
    95, 15, 127, 55, 55, 55, 55, 55, 55, 55, 55, 55,
    55, 55, 207, 15, 95, 15, 127, 55, 55, 55, 55, 55,
    55, 55, 56, 5, 101, 19, 56, 56, 56, 56, 56, 56,
    56, 56, 56, 208, 16, 96, 16, 128, 56, 56, 56, 56,
    56, 56, 56, 56, 56, 56, 56, 208, 16, 96, 16, 128,
    56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 208,
    16, 96, 16, 128, 56, 56, 56, 56, 56, 56, 56, 57,
    6, 102, 20, 57, 57, 57, 57, 57, 57, 57, 57, 57,
    209, 17, 97, 17, 129, 57, 57, 57, 57, 57, 57, 57,
    57, 57, 57, 57, 209, 17, 97, 17, 129, 57, 57, 57,
    57, 57, 57, 57, 57, 57, 57, 57, 209, 17, 97, 17,
    129, 57, 57, 57, 57, 57, 57, 57, 58, 7, 103, 21,
    58, 58, 58, 58, 58, 58, 58, 58, 58, 210, 18, 98,
    18, 130, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58,
    58, 210, 18, 98, 18, 130, 58, 58, 58, 58, 58, 58,
    58, 58, 58, 58, 58, 210, 18, 98, 18, 130, 58, 58,
    58, 58, 58, 58, 58, 59, 8, 104, 22, 59, 59, 59,
    59, 59, 59, 59, 59, 59, 211, 19, 99, 19, 131, 59,
    59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 211, 19,
    99, 19, 131, 59, 59, 59, 59, 59, 59, 59, 59, 59,
    59, 59, 211, 19, 99, 19, 131, 59, 59, 59, 59, 59,
    59, 59, 60, 9, 105, 23, 60, 60, 60, 60, 60, 60,
    60, 60, 60, 212, 20, 100, 20, 132, 60, 60, 60, 60,
    60, 60, 60, 60, 60, 60, 60, 212, 20, 100, 20, 132,
    60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 212,
    20, 100, 20, 132, 60, 60, 60, 60, 60, 60, 60, 61,
    10, 106, 24, 61, 61, 61, 61, 61, 61, 61, 61, 61,
    213, 21, 101, 21, 133, 61, 61, 61, 61, 61, 61, 61,
    61, 61, 61, 61, 213, 21, 101, 21, 133, 61, 61, 61,
    61, 61, 61, 61, 61, 61, 61, 61, 213, 21, 101, 21,
    133, 61, 61, 61, 61, 61, 61, 61, 62, 11, 107, 25,
    62, 62, 62, 62, 62, 62, 62, 62, 62, 214, 22, 102,
    22, 134, 62, 62, 62, 62, 62, 62, 62, 62, 62, 62,
    62, 214, 22, 102, 22, 134, 62, 62, 62, 62, 62, 62,
    62, 62, 62, 62, 62, 214, 22, 102, 22, 134, 62, 62,
    62, 62, 62, 62, 62, 63, 12, 108, 26, 63, 63, 63,
    63, 63, 63, 63, 63, 63, 215, 23, 103, 23, 135, 63,
    63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 215, 23,
    103, 23, 135, 63, 63, 63, 63, 63, 63, 63, 63, 63,
    63, 63, 215, 23, 103, 23, 135, 63, 63, 63, 63, 63,
    63, 63, 64, 13, 109, 27, 64, 64, 64, 64, 64, 64,
    64, 64, 216, 24, 104, 24, 136, 64, 64, 64, 64, 64,
    64, 64, 64, 64, 64, 216, 24, 104, 24, 136, 64, 64,
    64, 64, 64, 64, 64, 64, 64, 64, 216, 24, 104, 24,
    136, 64, 64, 64, 64, 64, 64, 64, 65, 14, 110, 28,
    65, 65, 65, 65, 65, 65, 65, 65, 217, 25, 105, 25,
    137, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 217,
    25, 105, 25, 137, 65, 65, 65, 65, 65, 65, 65, 65,
    65, 65, 217, 25, 105, 25, 137, 65, 65, 65, 65, 65,
    65, 65, 66, 15, 111, 29, 66, 66, 66, 66, 66, 66,
    66, 66, 218, 26, 106, 26, 138, 66, 66, 66, 66, 66,
    66, 66, 66, 66, 66, 218, 26, 106, 26, 138, 66, 66,
    66, 66, 66, 66, 66, 66, 66, 66, 218, 26, 106, 26,
    138, 66, 66, 66, 66, 66, 66, 66, 67, 16, 112, 30,
    67, 67, 67, 67, 67, 67, 67, 67, 219, 27, 107, 27,
    139, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 219,
    27, 107, 27, 139, 67, 67, 67, 67, 67, 67, 67, 67,
    67, 67, 219, 27, 107, 27, 139, 67, 67, 67, 67, 67,
    67, 67, 68, 17, 113, 31, 68, 68, 68, 68, 68, 68,
    68, 68, 220, 28, 108, 28, 140, 68, 68, 68, 68, 68,
    68, 68, 68, 68, 68, 220, 28, 108, 28, 140, 68, 68,
    68, 68, 68, 68, 68, 68, 68, 68, 220, 28, 108, 28,
    140, 68, 68, 68, 68, 68, 68, 68, 69, 18, 114, 32,
    69, 69, 69, 69, 69, 69, 69, 69, 221, 29, 109, 29,
    141, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 221,
    29, 109, 29, 141, 69, 69, 69, 69, 69, 69, 69, 69,
    69, 69, 221, 29, 109, 29, 141, 69, 69, 69, 69, 69,
    69, 69, 70, 19, 115, 33, 70, 70, 70, 70, 70, 70,
    70, 70, 222, 30, 110, 30, 142, 70, 70, 70, 70, 70,
    70, 70, 70, 70, 70, 222, 30, 110, 30, 142, 70, 70,
    70, 70, 70, 70, 70, 70, 70, 70, 222, 30, 110, 30,
    142, 70, 70, 70, 70, 70, 70, 70, 71, 20, 116, 34,
    71, 71, 71, 71, 71, 71, 71, 71, 223, 31, 111, 31,
    143, 71, 71, 71, 71, 71, 71, 71, 71, 71, 71, 223,
    31, 111, 31, 143, 71, 71, 71, 71, 71, 71, 71, 71,
    71, 71, 223, 31, 111, 31, 143, 71, 71, 71, 71, 71,
    71, 71, 72, 21, 117, 35, 72, 72, 72, 72, 72, 72,
    72, 72, 224, 32, 112, 32, 144, 72, 72, 72, 72, 72,
    72, 72, 72, 72, 72, 224, 32, 112, 32, 144, 72, 72,
    72, 72, 72, 72, 72, 72, 72, 72, 224, 32, 112, 32,
    144, 72, 72, 72, 72, 72, 72, 72, 73, 22, 118, 36,
    73, 73, 73, 73, 73, 73, 73, 73, 225, 33, 113, 33,
    145, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 225,
    33, 113, 33, 145, 73, 73, 73, 73, 73, 73, 73, 73,
    73, 73, 225, 33, 113, 33, 145, 73, 73, 73, 73, 73,
    73, 73, 74, 23, 119, 37, 74, 74, 74, 74, 74, 74,
    74, 74, 226, 34, 114, 34, 146, 74, 74, 74, 74, 74,
    74, 74, 74, 74, 74, 226, 34, 114, 34, 146, 74, 74,
    74, 74, 74, 74, 74, 74, 74, 74, 226, 34, 114, 34,
    146, 74, 74, 74, 74, 74, 74, 74, 75, 24, 38, 75,
    75, 75, 75, 75, 75, 75, 75, 227, 35, 115, 35, 147,
    75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 227, 35,
    115, 35, 147, 75, 75, 75, 75, 75, 75, 75, 75, 75,
    75, 227, 35, 115, 35, 147, 75, 75, 75, 75, 75, 75,
    75, 76, 25, 39, 76, 76, 76, 76, 76, 76, 76, 76,
    228, 36, 116, 36, 148, 76, 76, 76, 76, 76, 76, 76,
    76, 76, 76, 228, 36, 116, 36, 148, 76, 76, 76, 76,
    76, 76, 76, 76, 76, 76, 228, 36, 116, 36, 148, 76,
    76, 76, 76, 76, 76, 76, 77, 26, 40, 77, 77, 77,
    77, 77, 77, 77, 77, 229, 37, 117, 37, 149, 77, 77,
    77, 77, 77, 77, 77, 77, 77, 77, 229, 37, 117, 37,
    149, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 229,
    37, 117, 37, 149, 77, 77, 77, 77, 77, 77, 77, 78,
    27, 41, 78, 78, 78, 78, 78, 78, 78, 78, 230, 38,
    118, 38, 150, 78, 78, 78, 78, 78, 78, 78, 78, 78,
    78, 230, 38, 118, 38, 150, 78, 78, 78, 78, 78, 78,
    78, 78, 78, 78, 230, 38, 118, 38, 150, 78, 78, 78,
    78, 78, 78, 78, 79, 28, 42, 79, 79, 79, 79, 79,
    79, 79, 79, 231, 39, 119, 39, 151, 79, 79, 79, 79,
    79, 79, 79, 79, 79, 79, 231, 39, 119, 39, 151, 79,
    79, 79, 79, 79, 79, 79, 79, 79, 79, 231, 39, 119,
    39, 151, 79, 79, 79, 79, 79, 79, 79, 80, 29, 43,
    80, 80, 80, 80, 80, 232, 40, 40, 152, 80, 80, 80,
    80, 80, 80, 80, 232, 40, 40, 152, 80, 80, 80, 80,
    80, 80, 80, 232, 40, 40, 152, 80, 80, 80, 80, 80,
    80, 80, 81, 30, 44, 81, 81, 81, 81, 81, 233, 41,
    41, 153, 81, 81, 81, 81, 81, 81, 81, 233, 41, 41,
    153, 81, 81, 81, 81, 81, 81, 81, 233, 41, 41, 153,
    81, 81, 81, 81, 81, 81, 81, 82, 31, 45, 82, 82,
    82, 82, 82, 234, 42, 42, 154, 82, 82, 82, 82, 82,
    82, 82, 234, 42, 42, 154, 82, 82, 82, 82, 82, 82,
    82, 234, 42, 42, 154, 82, 82, 82, 82, 82, 82, 82,
    83, 32, 46, 83, 83, 83, 83, 83, 235, 43, 43, 155,
    83, 83, 83, 83, 83, 83, 83, 235, 43, 43, 155, 83,
    83, 83, 83, 83, 83, 83, 235, 43, 43, 155, 83, 83,
    83, 83, 83, 83, 83, 84, 33, 47, 84, 84, 84, 84,
    84, 236, 44, 44, 156, 84, 84, 84, 84, 84, 84, 84,
    236, 44, 44, 156, 84, 84, 84, 84, 84, 84, 84, 236,
    44, 44, 156, 84, 84, 84, 84, 84, 84, 84, 85, 34,
    48, 85, 85, 85, 85, 85, 237, 45, 45, 157, 85, 85,
    85, 85, 85, 85, 85, 237, 45, 45, 157, 85, 85, 85,
    85, 85, 85, 85, 237, 45, 45, 157, 85, 85, 85, 85,
    85, 85, 85, 86, 35, 49, 86, 86, 86, 86, 86, 238,
    46, 46, 158, 86, 86, 86, 86, 86, 86, 86, 238, 46,
    46, 158, 86, 86, 86, 86, 86, 86, 86, 238, 46, 46,
    158, 86, 86, 86, 86, 86, 86, 86, 87, 36, 50, 87,
    87, 87, 87, 87, 239, 47, 47, 159, 87, 87, 87, 87,
    87, 87, 87, 239, 47, 47, 159, 87, 87, 87, 87, 87,
    87, 87, 239, 47, 47, 159, 87, 87, 87, 87, 87, 87,
    87, 88, 37, 51, 88, 88, 88, 88, 88, 0, 80, 192,
    88, 88, 88, 88, 88, 88, 88, 0, 80, 192, 88, 88,
    88, 88, 88, 88, 88, 0, 80, 192, 88, 88, 88, 88,
    88, 88, 88, 89, 38, 52, 89, 89, 89, 89, 89, 1,
    81, 193, 89, 89, 89, 89, 89, 89, 89, 1, 81, 193,
    89, 89, 89, 89, 89, 89, 89, 1, 81, 193, 89, 89,
    89, 89, 89, 89, 89, 90, 39, 53, 90, 90, 90, 90,
    90, 2, 82, 194, 90, 90, 90, 90, 90, 90, 90, 2,
    82, 194, 90, 90, 90, 90, 90, 90, 90, 2, 82, 194,
    90, 90, 90, 90, 90, 90, 90, 91, 40, 54, 91, 91,
    91, 91, 91, 3, 83, 195, 91, 91, 91, 91, 91, 91,
    91, 3, 83, 195, 91, 91, 91, 91, 91, 91, 91, 3,
    83, 195, 91, 91, 91, 91, 91, 91, 91, 92, 41, 55,
    92, 92, 92, 92, 92, 4, 84, 196, 92, 92, 92, 92,
    92, 92, 92, 4, 84, 196, 92, 92, 92, 92, 92, 92,
    92, 4, 84, 196, 92, 92, 92, 92, 92, 92, 92, 93,
    42, 56, 93, 93, 93, 93, 93, 5, 85, 197, 93, 93,
    93, 93, 93, 93, 93, 5, 85, 197, 93, 93, 93, 93,
    93, 93, 93, 5, 85, 197, 93, 93, 93, 93, 93, 93,
    93, 94, 43, 57, 94, 94, 94, 94, 94, 6, 86, 198,
    94, 94, 94, 94, 94, 94, 94, 6, 86, 198, 94, 94,
    94, 94, 94, 94, 94, 6, 86, 198, 94, 94, 94, 94,
    94, 94, 94, 95, 44, 58, 95, 95, 95, 95, 95, 7,
    87, 199, 95, 95, 95, 95, 95, 95, 95, 7, 87, 199,
    95, 95, 95, 95, 95, 95, 95, 7, 87, 199, 95, 95,
    95, 95, 95, 95, 95, 0, 45, 59, 96, 96, 96, 96,
    96, 8, 88, 200, 96, 96, 96, 96, 96, 96, 96, 8,
    88, 200, 96, 96, 96, 96, 96, 96, 96, 8, 88, 200,
    96, 96, 96, 96, 96, 96, 96, 1, 46, 60, 97, 97,
    97, 97, 97, 9, 89, 201, 97, 97, 97, 97, 97, 97,
    97, 9, 89, 201, 97, 97, 97, 97, 97, 97, 97, 9,
    89, 201, 97, 97, 97, 97, 97, 97, 97, 2, 47, 61,
    98, 98, 98, 98, 98, 10, 90, 202, 98, 98, 98, 98,
    98, 98, 98, 10, 90, 202, 98, 98, 98, 98, 98, 98,
    98, 10, 90, 202, 98, 98, 98, 98, 98, 98, 98, 3,
    48, 62, 99, 99, 99, 99, 99, 11, 91, 203, 99, 99,
    99, 99, 99, 99, 99, 11, 91, 203, 99, 99, 99, 99,
    99, 99, 99, 11, 91, 203, 99, 99, 99, 99, 99, 99,
    99, 4, 49, 63, 100, 100, 100, 100, 100, 12, 92, 204,
    100, 100, 100, 100, 100, 100, 100, 12, 92, 204, 100, 100,
    100, 100, 100, 100, 100, 12, 92, 204, 100, 100, 100, 100,
    100, 100, 100, 5, 50, 101, 101, 101, 101, 101, 13, 93,
    205, 101, 101, 101, 101, 101, 101, 101, 13, 93, 205, 101,
    101, 101, 101, 101, 101, 101, 13, 93, 205, 101, 101, 101,
    101, 101, 101, 101, 6, 51, 102, 102, 102, 102, 102, 14,
    94, 206, 102, 102, 102, 102, 102, 102, 102, 14, 94, 206,
    102, 102, 102, 102, 102, 102, 102, 14, 94, 206, 102, 102,
    102, 102, 102, 102, 102, 7, 52, 103, 103, 103, 103, 103,
    15, 95, 207, 103, 103, 103, 103, 103, 103, 103, 15, 95,
    207, 103, 103, 103, 103, 103, 103, 103, 15, 95, 207, 103,
    103, 103, 103, 103, 103, 103, 8, 53, 104, 104, 104, 104,
    104, 16, 96, 208, 104, 104, 104, 104, 104, 104, 104, 16,
    96, 208, 104, 104, 104, 104, 104, 104, 104, 16, 96, 208,
    104, 104, 104, 104, 104, 104, 104, 9, 54, 105, 105, 105,
    105, 105, 17, 97, 209, 105, 105, 105, 105, 105, 105, 105,
    17, 97, 209, 105, 105, 105, 105, 105, 105, 105, 17, 97,
    209, 105, 105, 105, 105, 105, 105, 105, 10, 55, 106, 106,
    106, 106, 106, 18, 98, 210, 106, 106, 106, 106, 106, 106,
    106, 18, 98, 210, 106, 106, 106, 106, 106, 106, 106, 18,
    98, 210, 106, 106, 106, 106, 106, 106, 106, 11, 56, 107,
    107, 107, 107, 19, 99, 211, 107, 107, 107, 107, 107, 107,
    19, 99, 211, 107, 107, 107, 107, 107, 107, 19, 99, 211,
    107, 107, 107, 107, 107, 107, 107, 12, 57, 108, 108, 108,
    108, 20, 100, 212, 108, 108, 108, 108, 108, 108, 20, 100,
    212, 108, 108, 108, 108, 108, 108, 20, 100, 212, 108, 108,
    108, 108, 108, 108, 108, 13, 58, 109, 109, 109, 109, 21,
    101, 213, 109, 109, 109, 109, 109, 109, 21, 101, 213, 109,
    109, 109, 109, 109, 109, 21, 101, 213, 109, 109, 109, 109,
    109, 109, 109, 14, 59, 110, 110, 110, 110, 22, 102, 214,
    110, 110, 110, 110, 110, 110, 22, 102, 214, 110, 110, 110,
    110, 110, 110, 22, 102, 214, 110, 110, 110, 110, 110, 110,
    110, 15, 60, 111, 111, 111, 111, 23, 103, 215, 111, 111,
    111, 111, 111, 111, 23, 103, 215, 111, 111, 111, 111, 111,
    111, 23, 103, 215, 111, 111, 111, 111, 111, 111, 111, 16,
    61, 112, 112, 112, 112, 24, 104, 216, 112, 112, 112, 112,
    112, 112, 24, 104, 216, 112, 112, 112, 112, 112, 112, 24,
    104, 216, 112, 112, 112, 112, 112, 112, 112, 17, 62, 113,
    113, 113, 113, 25, 105, 217, 113, 113, 113, 113, 113, 113,
    25, 105, 217, 113, 113, 113, 113, 113, 113, 25, 105, 217,
    113, 113, 113, 113, 113, 113, 113, 18, 63, 114, 114, 114,
    114, 26, 106, 218, 114, 114, 114, 114, 114, 114, 26, 106,
    218, 114, 114, 114, 114, 114, 114, 26, 106, 218, 114, 114,
    114, 114, 114, 114, 114, 19, 64, 115, 115, 115, 115, 27,
    107, 219, 115, 115, 115, 115, 115, 115, 27, 107, 219, 115,
    115, 115, 115, 115, 115, 27, 107, 219, 115, 115, 115, 115,
    115, 115, 115, 20, 65, 116, 116, 116, 116, 28, 108, 220,
    116, 116, 116, 116, 116, 116, 28, 108, 220, 116, 116, 116,
    116, 116, 116, 28, 108, 220, 116, 116, 116, 116, 116, 116,
    116, 21, 66, 117, 117, 117, 117, 29, 109, 221, 117, 117,
    117, 117, 117, 117, 29, 109, 221, 117, 117, 117, 117, 117,
    117, 29, 109, 221, 117, 117, 117, 117, 117, 117, 117, 22,
    67, 118, 118, 118, 118, 30, 110, 222, 118, 118, 118, 118,
    118, 118, 30, 110, 222, 118, 118, 118, 118, 118, 118, 30,
    110, 222, 118, 118, 118, 118, 118, 118, 118, 23, 68, 119,
    119, 119, 119, 31, 111, 223, 119, 119, 119, 119, 119, 119,
    31, 111, 223, 119, 119, 119, 119, 119, 119, 31, 111, 223,
    119, 119, 119, 119, 119, 119, 119, 24, 69, 120, 120, 120,
    48, 48, 160, 120, 120, 120, 120, 48, 48, 160, 120, 120,
    120, 120, 48, 48, 160, 120, 120, 120, 120, 120, 120, 120,
    25, 70, 121, 121, 121, 49, 49, 161, 121, 121, 121, 121,
    49, 49, 161, 121, 121, 121, 121, 49, 49, 161, 121, 121,
    121, 121, 121, 121, 121, 26, 71, 122, 122, 122, 50, 50,
    162, 122, 122, 122, 122, 50, 50, 162, 122, 122, 122, 122,
    50, 50, 162, 122, 122, 122, 122, 122, 122, 122, 27, 72,
    123, 123, 123, 51, 51, 163, 123, 123, 123, 123, 51, 51,
    163, 123, 123, 123, 123, 51, 51, 163, 123, 123, 123, 123,
    123, 123, 123, 28, 73, 124, 124, 124, 52, 52, 164, 124,
    124, 124, 124, 52, 52, 164, 124, 124, 124, 124, 52, 52,
    164, 124, 124, 124, 124, 124, 124, 124, 29, 74, 125, 125,
    125, 53, 53, 165, 125, 125, 125, 125, 53, 53, 165, 125,
    125, 125, 125, 53, 53, 165, 125, 125, 125, 125, 125, 125,
    125, 30, 75, 126, 126, 126, 54, 54, 166, 126, 126, 126,
    126, 54, 54, 166, 126, 126, 126, 126, 54, 54, 166, 126,
    126, 126, 126, 126, 126, 126, 31, 76, 127, 127, 127, 55,
    55, 167, 127, 127, 127, 127, 55, 55, 167, 127, 127, 127,
    127, 55, 55, 167, 127, 127, 127, 127, 127, 127, 127, 32,
    77, 0, 0, 128, 56, 56, 168, 128, 0, 0, 0, 128,
    56, 56, 168, 128, 0, 0, 0, 128, 56, 56, 168, 128,
    128, 128, 128, 128, 128, 128, 33, 78, 1, 1, 129, 57,
    57, 169, 129, 1, 1, 1, 129, 57, 57, 169, 129, 1,
    1, 1, 129, 57, 57, 169, 129, 129, 129, 129, 129, 129,
    129, 34, 79, 2, 130, 58, 58, 170, 130, 2, 2, 2,
    130, 58, 58, 170, 130, 2, 2, 2, 130, 58, 58, 170,
    130, 130, 130, 130, 130, 130, 130, 35, 80, 3, 131, 59,
    59, 171, 131, 3, 3, 3, 131, 59, 59, 171, 131, 3,
    3, 3, 131, 59, 59, 171, 131, 131, 131, 131, 131, 131,
    131, 36, 81, 4, 132, 60, 60, 172, 132, 4, 4, 4,
    132, 60, 60, 172, 132, 4, 4, 4, 132, 60, 60, 172,
    132, 132, 132, 132, 132, 132, 132, 37, 82, 5, 133, 61,
    61, 173, 133, 5, 5, 5, 133, 61, 61, 173, 133, 5,
    5, 5, 133, 61, 61, 173, 133, 133, 133, 133, 133, 133,
    133, 38, 83, 6, 134, 62, 62, 174, 134, 6, 6, 6,
    134, 62, 62, 174, 134, 6, 6, 6, 134, 62, 62, 174,
    134, 134, 134, 134, 134, 134, 134, 39, 84, 7, 135, 63,
    63, 175, 135, 7, 7, 7, 135, 63, 63, 175, 135, 7,
    7, 7, 135, 63, 63, 175, 135, 135, 135, 135, 135, 135,
    135, 40, 85, 8, 136, 64, 64, 176, 136, 8, 8, 8,
    136, 64, 64, 176, 136, 8, 8, 8, 136, 64, 64, 176,
    136, 136, 136, 136, 136, 136, 136, 41, 86, 9, 137, 65,
    65, 177, 137, 9, 9, 9, 137, 65, 65, 177, 137, 9,
    9, 9, 137, 65, 65, 177, 137, 137, 137, 137, 137, 137,
    137, 42, 87, 10, 138, 66, 66, 178, 138, 10, 10, 138,
    66, 66, 178, 138, 10, 10, 138, 66, 66, 178, 138, 138,
    138, 138, 138, 138, 138, 43, 88, 11, 139, 67, 67, 179,
    139, 11, 11, 139, 67, 67, 179, 139, 11, 11, 139, 67,
    67, 179, 139, 139, 139, 139, 139, 139, 139, 44, 89, 12,
    140, 68, 68, 180, 140, 12, 12, 140, 68, 68, 180, 140,
    12, 12, 140, 68, 68, 180, 140, 140, 140, 140, 140, 140,
    140, 45, 90, 13, 141, 69, 69, 181, 141, 13, 13, 141,
    69, 69, 181, 141, 13, 13, 141, 69, 69, 181, 141, 141,
    141, 141, 141, 141, 141, 46, 91, 14, 142, 70, 70, 182,
    142, 14, 14, 142, 70, 70, 182, 142, 14, 14, 142, 70,
    70, 182, 142, 142, 142, 142, 142, 142, 142, 47, 92, 15,
    143, 71, 71, 183, 143, 15, 15, 143, 71, 71, 183, 143,
    15, 15, 143, 71, 71, 183, 143, 143, 143, 143, 143, 143,
    143, 48, 93, 0, 8, 0, 8, 144, 72, 72, 184, 144,
    0, 144, 72, 72, 184, 144, 0, 144, 72, 72, 184, 144,
    144, 144, 144, 144, 144, 144, 49, 94, 1, 9, 1, 9,
    145, 73, 73, 185, 145, 1, 145, 73, 73, 185, 145, 1,
    145, 73, 73, 185, 145, 0, 50, 95, 2, 10, 2, 146,
    74, 74, 186, 146, 146, 74, 74, 186, 146, 146, 74, 74,
    186, 146, 1, 51, 96, 3, 11, 3, 147, 75, 75, 187,
    147, 147, 75, 75, 187, 147, 147, 75, 75, 187, 147, 52,
    97, 4, 12, 4, 148, 76, 76, 188, 148, 148, 76, 76,
    188, 148, 148, 76, 76, 188, 148, 53, 98, 5, 13, 5,
    149, 77, 77, 189, 149, 149, 77, 77, 189, 149, 149, 77,
    77, 189, 149, 54, 99, 6, 14, 6, 150, 78, 78, 190,
    150, 150, 78, 78, 190, 150, 150, 78, 78, 190, 150, 55,
    100, 7, 15, 7, 151, 79, 79, 191, 151, 151, 79, 79,
    191, 151, 151, 79, 79, 191, 151,
};

static __device__ __constant__ uint8_t kDependencyCounts[94] = {
    0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 3, 1, 1, 2,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1,
    1, 1, 1, 1, 1, 1, 1, 3, 1, 1, 2, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1, 1,
    1, 1, 1, 1, 1, 1, 3, 1, 1, 2, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 3, 1, 1, 1,
    2, 2, 2, 2, 2, 2, 2, 2, 2, 1,
};

static __device__ __constant__ uint8_t kRoleMasks[94] = {
    9, 15, 9, 9, 11, 9, 15, 9, 15, 9, 15, 9,
    15, 9, 15, 9, 15, 15, 9, 9, 15, 15, 15, 9,
    15, 9, 15, 9, 15, 9, 15, 15, 9, 15, 9, 15,
    9, 15, 9, 15, 15, 9, 9, 15, 15, 15, 9, 15,
    9, 15, 9, 15, 9, 15, 15, 9, 15, 9, 15, 9,
    15, 9, 15, 15, 9, 9, 15, 15, 15, 9, 15, 9,
    15, 9, 15, 9, 15, 15, 9, 15, 9, 9, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 15, 15, 1,
};

static __device__ __constant__ uint16_t kSuccessorOffsets[95] = {
    0, 1, 2, 3, 4, 5, 8, 9, 10, 11, 12, 13,
    14, 15, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
    28, 29, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
    42, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
    56, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69,
    72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
    86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 101, 106,
    107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 116,
};

static __device__ __constant__ uint16_t kSuccessors[116] = {
    1, 2, 3, 5, 12, 6, 8, 10, 7, 20, 9, 43,
    11, 66, 13, 14, 17, 23, 15, 16, 18, 19, 20, 20,
    21, 22, 23, 24, 25, 26, 31, 34, 27, 28, 29, 30,
    34, 32, 33, 34, 35, 36, 37, 40, 46, 38, 39, 41,
    42, 43, 43, 44, 45, 46, 47, 48, 49, 54, 57, 50,
    51, 52, 53, 57, 55, 56, 57, 58, 59, 60, 63, 69,
    61, 62, 64, 65, 66, 66, 67, 68, 69, 70, 71, 72,
    77, 80, 73, 74, 75, 76, 80, 78, 79, 80, 81, 82,
    83, 85, 87, 89, 91, 84, 86, 88, 90, 92, 84, 85,
    86, 87, 88, 89, 90, 91, 92, 93,
};

}  // namespace deepspec::v4_generated
