// Generated by scripts/megakernel/generate_v4_header.py. Do not edit.
#pragma once

#include <cstdint>

namespace deepspec::v4_generated {
inline constexpr int kPhaseCount = 130;
inline constexpr int kRootCount = 3;
inline constexpr int kStaticTaskCount = 8491;
inline constexpr int kWorkers = 152;
inline constexpr int kThreads = 256;
inline constexpr int kLocalQueueDepth = 16;
inline constexpr int kTraceCapacity = 2048;
inline constexpr int kTraceColumns = 8;
inline constexpr uint8_t kExecutionMain = 0;
inline constexpr uint8_t kExecutionEmbedding = 1;
inline constexpr uint8_t kExecutionMainKv = 2;
inline constexpr uint8_t kExecutionAttnHc = 3;
inline constexpr uint8_t kExecutionAttnProjection = 4;
inline constexpr uint8_t kExecutionSparseAttention = 5;
inline constexpr uint8_t kExecutionAttentionOutput = 6;
inline constexpr uint8_t kExecutionFfnHc = 7;
inline constexpr uint8_t kExecutionRouter = 8;
inline constexpr uint8_t kExecutionExpert = 9;
inline constexpr uint8_t kExecutionHead = 10;
inline constexpr uint8_t kExecutionTail = 11;
inline constexpr uint64_t kWorkspaceBytes = 7379456ULL;
inline constexpr uint64_t kDependencyOffset = 7352320ULL;
inline constexpr uint64_t kNextTileOffset = 7353600ULL;
inline constexpr uint64_t kCompletedTileOffset = 7354880ULL;
inline constexpr uint64_t kPublishEpochOffset = 7356160ULL;
inline constexpr uint64_t kReadyQueueOffset = 7357440ULL;
inline constexpr uint64_t kQueueStateOffset = 7367168ULL;
inline constexpr uint64_t kWorkerStateOffset = 7369728ULL;
inline constexpr int kWeightOffsetSlots = 4724;
inline constexpr int kGlobalWeightBase = 0;
inline constexpr int kLayerWeightBase = 2;
inline constexpr int kRoutedExpertWeightBase = 98;
inline constexpr int kSharedExpertWeightBase = 4706;
inline constexpr int kGlobalWeightSlots = 2;
inline constexpr int kLayerWeightSlots = 32;
inline constexpr int kExpertWeightSlots = 6;
inline constexpr unsigned long long kWeightArenaBytes = 14206958848ULL;
inline constexpr int kMainQuantPhase = 0;
inline constexpr int kMainProjectionPhase = 1;
inline constexpr int kMainReducePhase = 2;
inline constexpr int kMainNormPhase = 3;
inline constexpr int kEmbeddingPhase = 4;
inline constexpr int kMainProjectedQuantPhase = 5;
inline constexpr int kLayer0AttnHcProjectionPhase = 12;
inline constexpr int kLayer0AttnHcSinkhornPhase = 13;
inline constexpr int kLayer0AttnHcReduceNormPhase = 14;
inline constexpr int kLayer0QaPhase = 15;
inline constexpr int kLayer0QaNormPhase = 16;
inline constexpr int kLayer0QbPhase = 17;
inline constexpr int kLayer0DraftKvProjectionPhase = 18;
inline constexpr int kLayer0QueryNormRopePhase = 19;
inline constexpr int kLayer0DraftKvFinalizePhase = 20;
inline constexpr int kLayer0SparseAttentionPhase = 21;
inline constexpr int kLayer0OutputAProjectionPhase = 22;
inline constexpr int kLayer0OutputBProjectionPhase = 23;
inline constexpr int kLayer0AttnPostPhase = 24;
inline constexpr int kLayer0FfnHcProjectionPhase = 25;
inline constexpr int kLayer0FfnHcSinkhornPhase = 26;
inline constexpr int kLayer0FfnHcReduceNormPhase = 27;
inline constexpr int kLayer0RouterScorePhase = 28;
inline constexpr int kLayer0RouterTop6Phase = 29;
inline constexpr int kLayer0RoutedW13Phase = 30;
inline constexpr int kLayer0RoutedSwiGluPhase = 31;
inline constexpr int kLayer0RoutedW2Phase = 32;
inline constexpr int kLayer0SharedW13Phase = 33;
inline constexpr int kLayer0SharedSwiGluPhase = 34;
inline constexpr int kLayer0SharedW2Phase = 35;
inline constexpr int kLayer0ExpertCombinePhase = 36;
inline constexpr int kHeadReducePhase = 87;
inline constexpr int kPrefixSchedulerPhase = 128;
inline constexpr int kExpertW1Slot = 0;
inline constexpr int kExpertW1ScaleSlot = 1;
inline constexpr int kExpertW2Slot = 2;
inline constexpr int kExpertW2ScaleSlot = 3;
inline constexpr int kExpertW3Slot = 4;
inline constexpr int kExpertW3ScaleSlot = 5;
inline constexpr int kMainProjWeightSlot = 24;
inline constexpr int kEmbeddingWeightSlot = 0;
inline constexpr int kMainProjScaleSlot = 25;
inline constexpr int kMainNormWeightSlot = 26;
inline constexpr int kLayer0AttnHcFnSlot = 2;
inline constexpr int kLayer0AttnHcBaseSlot = 3;
inline constexpr int kLayer0AttnHcScaleSlot = 4;
inline constexpr int kLayer0AttnNormWeightSlot = 8;
inline constexpr int kLayer0WqaWeightSlot = 11;
inline constexpr int kLayer0WqaScaleSlot = 12;
inline constexpr int kLayer0QaNormWeightSlot = 13;
inline constexpr int kLayer0WqbWeightSlot = 14;
inline constexpr int kLayer0WqbScaleSlot = 15;
inline constexpr int kLayer0WkvWeightSlot = 16;
inline constexpr int kLayer0WkvScaleSlot = 17;
inline constexpr int kLayer0KvNormWeightSlot = 18;
inline constexpr int kLayer0AttnSinkWeightSlot = 10;
inline constexpr int kLayer0WoaWeightSlot = 19;
inline constexpr int kLayer0WobWeightSlot = 20;
inline constexpr int kLayer0WobScaleSlot = 21;
inline constexpr int kLayer0FfnHcFnSlot = 5;
inline constexpr int kLayer0FfnHcBaseSlot = 6;
inline constexpr int kLayer0FfnHcScaleSlot = 7;
inline constexpr int kLayer0FfnNormWeightSlot = 9;
inline constexpr int kLayer0RouterWeightSlot = 22;
inline constexpr int kLayer0RouterBiasSlot = 23;
inline constexpr int kFinalNormWeightSlot = 91;
inline constexpr int kHcHeadFnWeightSlot = 92;
inline constexpr int kHcHeadBaseWeightSlot = 93;
inline constexpr int kHcHeadScaleWeightSlot = 94;
inline constexpr int kLmHeadWeightSlot = 1;
inline constexpr int kMarkovW1WeightSlot = 95;
inline constexpr int kMarkovW2WeightSlot = 96;
inline constexpr int kConfidenceWeightSlot = 97;
inline constexpr uint64_t kMainQuantizedOffset = 0ULL;
inline constexpr uint64_t kMainScaleOffset = 12288ULL;
inline constexpr uint64_t kMainPartialOffset = 12544ULL;
inline constexpr uint64_t kMainFp32Offset = 143616ULL;
inline constexpr uint64_t kMainRmsPartialOffset = 160000ULL;
inline constexpr uint64_t kMainProjectedOffset = 160256ULL;
inline constexpr uint64_t kMainProjectedQuantizedOffset = 168448ULL;
inline constexpr uint64_t kMainProjectedScaleOffset = 172544ULL;
inline constexpr uint64_t kMainKvPartialOffset = 172800ULL;
inline constexpr uint64_t kHiddenStreamsOffset = 197376ULL;
inline constexpr uint64_t kHcMixOffset = 364288ULL;
inline constexpr uint64_t kHcPreOffset = 364800ULL;
inline constexpr uint64_t kHcPostOffset = 365056ULL;
inline constexpr uint64_t kHcCombOffset = 365312ULL;
inline constexpr uint64_t kNormalizedHiddenOffset = 365824ULL;
inline constexpr uint64_t kAttnInputQuantizedOffset = 406784ULL;
inline constexpr uint64_t kAttnInputScaleOffset = 427264ULL;
inline constexpr uint64_t kQaPartialOffset = 427520ULL;
inline constexpr uint64_t kQloraOffset = 509440ULL;
inline constexpr uint64_t kQloraQuantizedOffset = 519680ULL;
inline constexpr uint64_t kQloraScaleOffset = 524800ULL;
inline constexpr uint64_t kQueryProjectionOffset = 525056ULL;
inline constexpr uint64_t kQueryInverseRmsOffset = 852736ULL;
inline constexpr uint64_t kQueriesOffset = 853504ULL;
inline constexpr uint64_t kDraftKvPartialOffset = 1181184ULL;
inline constexpr uint64_t kDraftKvOffset = 1222144ULL;
inline constexpr uint64_t kAttentionAccumulatorOffset = 1227264ULL;
inline constexpr uint64_t kAttentionRawOffset = 1882624ULL;
inline constexpr uint64_t kAttentionValuesOffset = 2210304ULL;
inline constexpr uint64_t kOutputLoraOffset = 2537984ULL;
inline constexpr uint64_t kOutputLoraQuantizedOffset = 2619904ULL;
inline constexpr uint64_t kOutputLoraScaleOffset = 2660864ULL;
inline constexpr uint64_t kAttentionOutputPartialOffset = 2661376ULL;
inline constexpr uint64_t kAttentionOutputOffset = 2989056ULL;
inline constexpr uint64_t kAttentionHiddenStreamsOffset = 3030016ULL;
inline constexpr uint64_t kFfnHcMixOffset = 3193856ULL;
inline constexpr uint64_t kFfnHcPreOffset = 3194368ULL;
inline constexpr uint64_t kFfnHcPostOffset = 3194624ULL;
inline constexpr uint64_t kFfnHcCombOffset = 3194880ULL;
inline constexpr uint64_t kFfnNormalizedHiddenOffset = 3195392ULL;
inline constexpr uint64_t kFfnInputQuantizedOffset = 3236352ULL;
inline constexpr uint64_t kFfnInputScaleOffset = 3256832ULL;
inline constexpr uint64_t kRouterScoreOffset = 3257088ULL;
inline constexpr uint64_t kRouterIndexOffset = 3262208ULL;
inline constexpr uint64_t kRouterWeightOffset = 3262464ULL;
inline constexpr uint64_t kRoutedW13Offset = 3262720ULL;
inline constexpr uint64_t kSharedW13Offset = 3508480ULL;
inline constexpr uint64_t kRoutedSwiGluOffset = 3549440ULL;
inline constexpr uint64_t kRoutedSwiGluQuantizedOffset = 3672320ULL;
inline constexpr uint64_t kRoutedSwiGluScaleOffset = 3733760ULL;
inline constexpr uint64_t kSharedSwiGluOffset = 3734272ULL;
inline constexpr uint64_t kSharedSwiGluQuantizedOffset = 3754752ULL;
inline constexpr uint64_t kSharedSwiGluScaleOffset = 3764992ULL;
inline constexpr uint64_t kRoutedOutputPartialOffset = 3765248ULL;
inline constexpr uint64_t kRoutedOutputOffset = 4011008ULL;
inline constexpr uint64_t kSharedOutputOffset = 4092928ULL;
inline constexpr uint64_t kHeadHiddenOffset = 4133888ULL;
inline constexpr uint64_t kHeadNormalizedOffset = 4174848ULL;
inline constexpr uint64_t kBaseLogitsOffset = 4215808ULL;
inline constexpr uint64_t kMarkovEmbeddingOffset = 6801408ULL;
inline constexpr uint64_t kMarkovLogitsOffset = 6803968ULL;
inline constexpr uint64_t kSoftmaxPartialMaxOffset = 7321088ULL;
inline constexpr uint64_t kSoftmaxPartialSumOffset = 7331328ULL;
inline constexpr uint64_t kSampleScanOffset = 7341568ULL;

static __device__ __constant__ uint16_t kMainKvProjectionPhases[3] = {
    6, 8, 10,
};

static __device__ __constant__ uint16_t kMainKvNormPhases[3] = {
    7, 9, 11,
};

static __device__ __constant__ uint16_t kMainKvWeightSlots[3] = {
    16, 48, 80,
};

static __device__ __constant__ uint16_t kMainKvScaleSlots[3] = {
    17, 49, 81,
};

static __device__ __constant__ uint16_t kMainKvNormWeightSlots[3] = {
    18, 50, 82,
};

static __device__ __constant__ uint16_t kAttnHcProjectionPhases[3] = {
    12, 37, 62,
};

static __device__ __constant__ uint16_t kAttnHcSinkhornPhases[3] = {
    13, 38, 63,
};

static __device__ __constant__ uint16_t kAttnHcReduceNormPhases[3] = {
    14, 39, 64,
};

static __device__ __constant__ uint16_t kQaPhases[3] = {
    15, 40, 65,
};

static __device__ __constant__ uint16_t kQaNormPhases[3] = {
    16, 41, 66,
};

static __device__ __constant__ uint16_t kQbPhases[3] = {
    17, 42, 67,
};

static __device__ __constant__ uint16_t kDraftKvProjectionPhases[3] = {
    18, 43, 68,
};

static __device__ __constant__ uint16_t kQueryNormRopePhases[3] = {
    19, 44, 69,
};

static __device__ __constant__ uint16_t kDraftKvFinalizePhases[3] = {
    20, 45, 70,
};

static __device__ __constant__ uint16_t kSparseAttentionPhases[3] = {
    21, 46, 71,
};

static __device__ __constant__ uint16_t kOutputAProjectionPhases[3] = {
    22, 47, 72,
};

static __device__ __constant__ uint16_t kOutputBProjectionPhases[3] = {
    23, 48, 73,
};

static __device__ __constant__ uint16_t kAttnPostPhases[3] = {
    24, 49, 74,
};

static __device__ __constant__ uint16_t kFfnHcProjectionPhases[3] = {
    25, 50, 75,
};

static __device__ __constant__ uint16_t kFfnHcSinkhornPhases[3] = {
    26, 51, 76,
};

static __device__ __constant__ uint16_t kFfnHcReduceNormPhases[3] = {
    27, 52, 77,
};

static __device__ __constant__ uint16_t kRouterScorePhases[3] = {
    28, 53, 78,
};

static __device__ __constant__ uint16_t kRouterTop6Phases[3] = {
    29, 54, 79,
};

static __device__ __constant__ uint16_t kRoutedW13Phases[3] = {
    30, 55, 80,
};

static __device__ __constant__ uint16_t kRoutedSwiGluPhases[3] = {
    31, 56, 81,
};

static __device__ __constant__ uint16_t kRoutedW2Phases[3] = {
    32, 57, 82,
};

static __device__ __constant__ uint16_t kSharedW13Phases[3] = {
    33, 58, 83,
};

static __device__ __constant__ uint16_t kSharedSwiGluPhases[3] = {
    34, 59, 84,
};

static __device__ __constant__ uint16_t kSharedW2Phases[3] = {
    35, 60, 85,
};

static __device__ __constant__ uint16_t kExpertCombinePhases[3] = {
    36, 61, 86,
};

static __device__ __constant__ uint16_t kLmRowPhases[5] = {
    88, 89, 90, 91, 92,
};

static __device__ __constant__ uint16_t kMarkovGatherPhases[5] = {
    93, 100, 107, 114, 121,
};

static __device__ __constant__ uint16_t kConfidencePhases[5] = {
    94, 101, 108, 115, 122,
};

static __device__ __constant__ uint16_t kMarkovW2Phases[5] = {
    95, 102, 109, 116, 123,
};

static __device__ __constant__ uint16_t kCorrectLogitPhases[5] = {
    96, 103, 110, 117, 124,
};

static __device__ __constant__ uint16_t kSoftmaxExpSumPhases[5] = {
    97, 104, 111, 118, 125,
};

static __device__ __constant__ uint16_t kSumReducePhases[5] = {
    98, 105, 112, 119, 126,
};

static __device__ __constant__ uint16_t kNormalizeSamplePhases[5] = {
    99, 106, 113, 120, 127,
};

static __device__ __constant__ uint16_t kAttnHcFnSlots[3] = {
    2, 34, 66,
};

static __device__ __constant__ uint16_t kAttnHcBaseSlots[3] = {
    3, 35, 67,
};

static __device__ __constant__ uint16_t kAttnHcScaleSlots[3] = {
    4, 36, 68,
};

static __device__ __constant__ uint16_t kAttnNormWeightSlots[3] = {
    8, 40, 72,
};

static __device__ __constant__ uint16_t kWqaWeightSlots[3] = {
    11, 43, 75,
};

static __device__ __constant__ uint16_t kWqaScaleSlots[3] = {
    12, 44, 76,
};

static __device__ __constant__ uint16_t kQaNormWeightSlots[3] = {
    13, 45, 77,
};

static __device__ __constant__ uint16_t kWqbWeightSlots[3] = {
    14, 46, 78,
};

static __device__ __constant__ uint16_t kWqbScaleSlots[3] = {
    15, 47, 79,
};

static __device__ __constant__ uint16_t kDraftWkvWeightSlots[3] = {
    16, 48, 80,
};

static __device__ __constant__ uint16_t kDraftWkvScaleSlots[3] = {
    17, 49, 81,
};

static __device__ __constant__ uint16_t kDraftKvNormWeightSlots[3] = {
    18, 50, 82,
};

static __device__ __constant__ uint16_t kAttnSinkWeightSlots[3] = {
    10, 42, 74,
};

static __device__ __constant__ uint16_t kWoaWeightSlots[3] = {
    19, 51, 83,
};

static __device__ __constant__ uint16_t kWobWeightSlots[3] = {
    20, 52, 84,
};

static __device__ __constant__ uint16_t kWobScaleSlots[3] = {
    21, 53, 85,
};

static __device__ __constant__ uint16_t kFfnHcFnSlots[3] = {
    5, 37, 69,
};

static __device__ __constant__ uint16_t kFfnHcBaseSlots[3] = {
    6, 38, 70,
};

static __device__ __constant__ uint16_t kFfnHcScaleSlots[3] = {
    7, 39, 71,
};

static __device__ __constant__ uint16_t kFfnNormWeightSlots[3] = {
    9, 41, 73,
};

static __device__ __constant__ uint16_t kRouterWeightSlots[3] = {
    22, 54, 86,
};

static __device__ __constant__ uint16_t kRouterBiasSlots[3] = {
    23, 55, 87,
};

static __device__ __constant__ uint16_t kRoutedExpertWeightBases[3] = {
    98, 1634, 3170,
};

static __device__ __constant__ uint16_t kSharedExpertWeightBases[3] = {
    4706, 4712, 4718,
};

static __device__ __constant__ uint16_t kRoots[3] = {
    0, 4, 93,
};

static __device__ __constant__ uint32_t kWorkUnits[130] = {
    96, 256, 8, 8, 160, 32, 16, 1, 16, 1, 16, 1,
    120, 5, 5, 32, 5, 256, 16, 320, 5, 320, 320, 128,
    40, 120, 5, 5, 32, 5, 960, 120, 960, 32, 20, 32,
    160, 120, 5, 5, 32, 5, 256, 16, 320, 5, 320, 320,
    128, 40, 120, 5, 5, 32, 5, 960, 120, 960, 32, 20,
    32, 160, 120, 5, 5, 32, 5, 256, 16, 320, 5, 320,
    320, 128, 40, 120, 5, 5, 32, 5, 960, 120, 960, 32,
    20, 32, 160, 160, 1010, 1, 1, 1, 1, 1, 1, 1010,
    253, 253, 1, 253, 1, 1, 1010, 253, 253, 1, 253, 1,
    1, 1010, 253, 253, 1, 253, 1, 1, 1010, 253, 253, 1,
    253, 1, 1, 1010, 253, 253, 1, 253, 5, 1,
};

static __device__ __constant__ uint8_t kClaimChunks[130] = {
    1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 2, 1, 3, 1, 3, 3, 1,
    1, 1, 1, 1, 1, 1, 4, 1, 4, 1, 1, 1,
    2, 1, 1, 1, 1, 1, 2, 1, 3, 1, 3, 3,
    1, 1, 1, 1, 1, 1, 1, 4, 1, 4, 1, 1,
    1, 2, 1, 1, 1, 1, 1, 2, 1, 3, 1, 3,
    3, 1, 1, 1, 1, 1, 1, 1, 4, 1, 4, 1,
    1, 1, 2, 2, 7, 1, 1, 1, 1, 1, 1, 7,
    2, 2, 1, 2, 1, 1, 7, 2, 2, 1, 2, 1,
    1, 7, 2, 2, 1, 2, 1, 1, 7, 2, 2, 1,
    2, 1, 1, 7, 2, 2, 1, 2, 1, 1,
};

static __device__ __constant__ uint8_t kExecutionGroups[130] = {
    0, 0, 0, 0, 1, 2, 2, 2, 2, 2, 2, 2,
    3, 3, 3, 4, 4, 4, 4, 4, 4, 5, 6, 6,
    6, 7, 7, 7, 8, 8, 9, 9, 9, 9, 9, 9,
    9, 3, 3, 3, 4, 4, 4, 4, 4, 4, 5, 6,
    6, 6, 7, 7, 7, 8, 8, 9, 9, 9, 9, 9,
    9, 9, 3, 3, 3, 4, 4, 4, 4, 4, 4, 5,
    6, 6, 6, 7, 7, 7, 8, 8, 9, 9, 9, 9,
    9, 9, 9, 10, 10, 10, 10, 10, 10, 11, 11, 11,
    11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11,
    11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11,
    11, 11, 11, 11, 11, 11, 11, 11, 11, 11,
};

static __device__ __constant__ uint8_t kPhaseLayers[130] = {
    255, 255, 255, 255, 255, 255, 0, 0, 1, 1, 2, 2,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
    2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
    2, 2, 2, 255, 255, 255, 255, 255, 255, 255, 255, 255,
    255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
    255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
    255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
};

static __device__ __constant__ uint16_t kStaticWorkerTaskOffsets[153] = {
    0, 90, 172, 254, 342, 428, 498, 568, 638, 707, 776, 845,
    914, 983, 1051, 1119, 1187, 1255, 1323, 1391, 1459, 1530, 1601, 1668,
    1738, 1808, 1878, 1948, 2018, 2088, 2158, 2228, 2298, 2366, 2434, 2502,
    2570, 2638, 2706, 2774, 2842, 2904, 2966, 3028, 3090, 3152, 3214, 3276,
    3338, 3400, 3462, 3524, 3586, 3648, 3710, 3772, 3834, 3896, 3958, 4020,
    4082, 4144, 4206, 4268, 4330, 4391, 4452, 4513, 4574, 4635, 4696, 4757,
    4818, 4879, 4940, 5001, 5062, 5123, 5184, 5245, 5306, 5364, 5422, 5480,
    5538, 5596, 5654, 5712, 5770, 5825, 5880, 5935, 5990, 6045, 6100, 6155,
    6210, 6265, 6320, 6375, 6430, 6485, 6540, 6595, 6650, 6704, 6758, 6812,
    6857, 6902, 6947, 6992, 7037, 7082, 7127, 7172, 7217, 7262, 7307, 7352,
    7397, 7437, 7477, 7517, 7557, 7597, 7637, 7677, 7705, 7740, 7774, 7808,
    7839, 7870, 7898, 7926, 7954, 7982, 8010, 8038, 8066, 8094, 8122, 8150,
    8178, 8206, 8251, 8292, 8333, 8374, 8415, 8453, 8491,
};

static __device__ __constant__ uint16_t kStaticTaskPhases[8491] = {
    4, 1, 2, 14, 15, 16, 17, 19, 21, 22, 23, 24,
    25, 26, 27, 28, 29, 30, 30, 34, 35, 36, 37, 38,
    39, 40, 41, 42, 44, 46, 47, 48, 49, 50, 51, 52,
    53, 54, 55, 55, 59, 60, 61, 62, 63, 64, 65, 66,
    67, 69, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,
    80, 84, 85, 86, 87, 88, 89, 103, 104, 105, 106, 107,
    109, 110, 111, 112, 113, 114, 116, 117, 118, 119, 120, 121,
    123, 124, 125, 126, 127, 129, 4, 1, 2, 14, 15, 16,
    17, 19, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30,
    30, 34, 35, 36, 37, 38, 39, 40, 41, 42, 44, 46,
    47, 48, 49, 50, 51, 52, 53, 54, 55, 55, 59, 60,
    61, 62, 63, 64, 65, 66, 67, 69, 71, 72, 73, 74,
    75, 76, 77, 78, 79, 80, 80, 84, 85, 86, 87, 88,
    90, 103, 104, 106, 109, 110, 111, 113, 116, 117, 118, 120,
    123, 124, 125, 127, 4, 1, 2, 14, 15, 16, 17, 19,
    21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 30, 34,
    35, 36, 37, 38, 39, 40, 41, 42, 44, 46, 47, 48,
    49, 50, 51, 52, 53, 54, 55, 55, 59, 60, 61, 62,
    63, 64, 65, 66, 67, 69, 71, 72, 73, 74, 75, 76,
    77, 78, 79, 80, 80, 84, 85, 86, 87, 88, 91, 103,
    104, 106, 109, 110, 111, 113, 116, 117, 118, 120, 123, 124,
    125, 127, 4, 1, 2, 14, 15, 16, 17, 19, 21, 22,
    23, 24, 25, 26, 27, 28, 29, 30, 30, 34, 35, 36,
    37, 38, 39, 40, 41, 42, 44, 46, 47, 48, 49, 50,
    51, 52, 53, 54, 55, 55, 59, 60, 61, 62, 63, 64,
    65, 66, 67, 69, 71, 72, 73, 74, 75, 76, 77, 78,
    79, 80, 80, 84, 85, 86, 87, 88, 95, 96, 97, 98,
    99, 100, 102, 103, 104, 106, 109, 110, 111, 113, 116, 117,
    118, 120, 123, 124, 125, 127, 4, 1, 2, 14, 15, 16,
    17, 19, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30,
    30, 34, 35, 36, 37, 38, 39, 40, 41, 42, 44, 46,
    47, 48, 49, 50, 51, 52, 53, 54, 55, 55, 59, 60,
    61, 62, 63, 64, 65, 66, 67, 69, 71, 72, 73, 74,
    75, 76, 77, 78, 79, 80, 80, 84, 85, 86, 87, 88,
    95, 96, 97, 99, 102, 103, 104, 106, 109, 110, 111, 113,
    116, 117, 118, 120, 123, 124, 125, 127, 4, 1, 2, 3,
    15, 17, 19, 21, 22, 23, 24, 25, 28, 30, 30, 34,
    35, 36, 37, 40, 42, 44, 46, 47, 48, 49, 50, 53,
    55, 55, 59, 60, 61, 62, 65, 67, 69, 71, 72, 73,
    74, 75, 78, 80, 80, 84, 85, 86, 87, 88, 95, 96,
    97, 99, 102, 103, 104, 106, 109, 110, 111, 113, 116, 117,
    118, 120, 123, 124, 125, 127, 4, 1, 2, 3, 15, 17,
    19, 21, 22, 23, 24, 25, 28, 30, 30, 34, 35, 36,
    37, 40, 42, 44, 46, 47, 48, 49, 50, 53, 55, 55,
    59, 60, 61, 62, 65, 67, 69, 71, 72, 73, 74, 75,
    78, 80, 80, 84, 85, 86, 87, 88, 95, 96, 97, 99,
    102, 103, 104, 106, 109, 110, 111, 113, 116, 117, 118, 120,
    123, 124, 125, 127, 4, 1, 2, 3, 15, 17, 19, 21,
    22, 23, 24, 25, 28, 30, 30, 34, 35, 36, 37, 40,
    42, 44, 46, 47, 48, 49, 50, 53, 55, 55, 59, 60,
    61, 62, 65, 67, 69, 71, 72, 73, 74, 75, 78, 80,
    80, 84, 85, 86, 87, 88, 95, 96, 97, 99, 102, 103,
    104, 106, 109, 110, 111, 113, 116, 117, 118, 120, 123, 124,
    125, 127, 4, 1, 3, 15, 17, 19, 21, 22, 23, 24,
    25, 28, 30, 30, 34, 35, 36, 37, 40, 42, 44, 46,
    47, 48, 49, 50, 53, 55, 55, 59, 60, 61, 62, 65,
    67, 69, 71, 72, 73, 74, 75, 78, 80, 80, 84, 85,
    86, 87, 88, 95, 96, 97, 99, 102, 103, 104, 106, 109,
    110, 111, 113, 116, 117, 118, 120, 123, 124, 125, 127, 4,
    1, 3, 15, 17, 19, 21, 22, 23, 24, 25, 28, 30,
    30, 34, 35, 36, 37, 40, 42, 44, 46, 47, 48, 49,
    50, 53, 55, 55, 59, 60, 61, 62, 65, 67, 69, 71,
    72, 73, 74, 75, 78, 80, 80, 84, 85, 86, 87, 88,
    95, 96, 97, 99, 102, 103, 104, 106, 109, 110, 111, 113,
    116, 117, 118, 120, 123, 124, 125, 127, 4, 1, 3, 15,
    17, 19, 21, 22, 23, 24, 25, 28, 30, 30, 34, 35,
    36, 37, 40, 42, 44, 46, 47, 48, 49, 50, 53, 55,
    55, 59, 60, 61, 62, 65, 67, 69, 71, 72, 73, 74,
    75, 78, 80, 80, 84, 85, 86, 87, 88, 95, 96, 97,
    99, 102, 103, 104, 106, 109, 110, 111, 113, 116, 117, 118,
    120, 123, 124, 125, 127, 4, 1, 3, 15, 17, 19, 21,
    22, 23, 24, 25, 28, 30, 30, 34, 35, 36, 37, 40,
    42, 44, 46, 47, 48, 49, 50, 53, 55, 55, 59, 60,
    61, 62, 65, 67, 69, 71, 72, 73, 74, 75, 78, 80,
    80, 84, 85, 86, 87, 88, 95, 96, 97, 99, 102, 103,
    104, 106, 109, 110, 111, 113, 116, 117, 118, 120, 123, 124,
    125, 127, 4, 1, 3, 15, 17, 19, 21, 22, 23, 24,
    25, 28, 30, 30, 34, 35, 36, 37, 40, 42, 44, 46,
    47, 48, 49, 50, 53, 55, 55, 59, 60, 61, 62, 65,
    67, 69, 71, 72, 73, 74, 75, 78, 80, 80, 84, 85,
    86, 87, 88, 95, 96, 97, 99, 102, 103, 104, 106, 109,
    110, 111, 113, 116, 117, 118, 120, 123, 124, 125, 127, 4,
    1, 15, 17, 19, 21, 22, 23, 24, 25, 28, 30, 30,
    34, 35, 36, 37, 40, 42, 44, 46, 47, 48, 49, 50,
    53, 55, 55, 59, 60, 61, 62, 65, 67, 69, 71, 72,
    73, 74, 75, 78, 80, 80, 84, 85, 86, 87, 88, 95,
    96, 97, 99, 102, 103, 104, 106, 109, 110, 111, 113, 116,
    117, 118, 120, 123, 124, 125, 127, 4, 1, 15, 17, 19,
    21, 22, 23, 24, 25, 28, 30, 30, 34, 35, 36, 37,
    40, 42, 44, 46, 47, 48, 49, 50, 53, 55, 55, 59,
    60, 61, 62, 65, 67, 69, 71, 72, 73, 74, 75, 78,
    80, 80, 84, 85, 86, 87, 88, 95, 96, 97, 99, 102,
    103, 104, 106, 109, 110, 111, 113, 116, 117, 118, 120, 123,
    124, 125, 127, 4, 1, 15, 17, 19, 21, 22, 23, 24,
    25, 28, 30, 30, 34, 35, 36, 37, 40, 42, 44, 46,
    47, 48, 49, 50, 53, 55, 55, 59, 60, 61, 62, 65,
    67, 69, 71, 72, 73, 74, 75, 78, 80, 80, 84, 85,
    86, 87, 88, 95, 96, 97, 99, 102, 103, 104, 106, 109,
    110, 111, 113, 116, 117, 118, 120, 123, 124, 125, 127, 4,
    1, 15, 17, 19, 21, 22, 23, 24, 25, 28, 30, 30,
    34, 35, 36, 37, 40, 42, 44, 46, 47, 48, 49, 50,
    53, 55, 55, 59, 60, 61, 62, 65, 67, 69, 71, 72,
    73, 74, 75, 78, 80, 80, 84, 85, 86, 87, 88, 95,
    96, 97, 99, 102, 103, 104, 106, 109, 110, 111, 113, 116,
    117, 118, 120, 123, 124, 125, 127, 4, 1, 15, 17, 19,
    21, 22, 23, 24, 25, 28, 30, 30, 34, 35, 36, 37,
    40, 42, 44, 46, 47, 48, 49, 50, 53, 55, 55, 59,
    60, 61, 62, 65, 67, 69, 71, 72, 73, 74, 75, 78,
    80, 80, 84, 85, 86, 87, 88, 95, 96, 97, 99, 102,
    103, 104, 106, 109, 110, 111, 113, 116, 117, 118, 120, 123,
    124, 125, 127, 4, 1, 15, 17, 19, 21, 22, 23, 24,
    25, 28, 30, 30, 34, 35, 36, 37, 40, 42, 44, 46,
    47, 48, 49, 50, 53, 55, 55, 59, 60, 61, 62, 65,
    67, 69, 71, 72, 73, 74, 75, 78, 80, 80, 84, 85,
    86, 87, 88, 95, 96, 97, 99, 102, 103, 104, 106, 109,
    110, 111, 113, 116, 117, 118, 120, 123, 124, 125, 127, 4,
    1, 15, 17, 19, 21, 22, 23, 24, 25, 28, 30, 30,
    34, 35, 36, 37, 40, 42, 44, 46, 47, 48, 49, 50,
    53, 55, 55, 59, 60, 61, 62, 65, 67, 69, 71, 72,
    73, 74, 75, 78, 80, 80, 84, 85, 86, 87, 88, 95,
    96, 97, 99, 102, 103, 104, 106, 109, 110, 111, 113, 116,
    117, 118, 120, 123, 124, 125, 127, 4, 1, 15, 17, 19,
    21, 22, 23, 24, 25, 28, 30, 30, 31, 31, 35, 36,
    37, 40, 42, 44, 46, 47, 48, 49, 50, 53, 55, 55,
    56, 56, 60, 61, 62, 65, 67, 69, 71, 72, 73, 74,
    75, 78, 80, 80, 81, 81, 85, 86, 87, 88, 95, 96,
    97, 99, 102, 103, 104, 106, 109, 110, 111, 113, 116, 117,
    118, 120, 123, 124, 125, 127, 4, 1, 15, 17, 19, 21,
    22, 23, 24, 25, 28, 30, 30, 31, 31, 35, 36, 37,
    40, 42, 44, 46, 47, 48, 49, 50, 53, 55, 55, 56,
    56, 60, 61, 62, 65, 67, 69, 71, 72, 73, 74, 75,
    78, 80, 80, 81, 81, 85, 86, 87, 88, 95, 96, 97,
    99, 102, 103, 104, 106, 109, 110, 111, 113, 116, 117, 118,
    120, 123, 124, 125, 127, 4, 1, 15, 17, 19, 21, 22,
    23, 24, 25, 28, 30, 30, 31, 31, 35, 36, 37, 40,
    42, 44, 46, 47, 48, 49, 50, 53, 55, 55, 56, 56,
    60, 61, 62, 65, 67, 69, 71, 72, 73, 74, 75, 78,
    80, 80, 81, 81, 85, 86, 87, 88, 92, 103, 104, 106,
    109, 110, 111, 113, 116, 117, 118, 120, 123, 124, 125, 127,
    4, 1, 15, 17, 19, 21, 22, 23, 24, 25, 28, 30,
    30, 31, 31, 35, 36, 37, 40, 42, 44, 46, 47, 48,
    49, 50, 53, 55, 55, 56, 56, 60, 61, 62, 65, 67,
    69, 71, 72, 73, 74, 75, 78, 80, 80, 81, 81, 85,
    86, 87, 88, 96, 97, 99, 102, 103, 104, 106, 109, 110,
    111, 113, 116, 117, 118, 120, 123, 124, 125, 127, 4, 1,
    15, 17, 19, 21, 22, 23, 24, 25, 28, 30, 30, 31,
    31, 35, 36, 37, 40, 42, 44, 46, 47, 48, 49, 50,
    53, 55, 55, 56, 56, 60, 61, 62, 65, 67, 69, 71,
    72, 73, 74, 75, 78, 80, 80, 81, 81, 85, 86, 87,
    88, 96, 97, 99, 102, 103, 104, 106, 109, 110, 111, 113,
    116, 117, 118, 120, 123, 124, 125, 127, 4, 1, 15, 17,
    19, 21, 22, 23, 24, 25, 28, 30, 30, 31, 31, 35,
    36, 37, 40, 42, 44, 46, 47, 48, 49, 50, 53, 55,
    55, 56, 56, 60, 61, 62, 65, 67, 69, 71, 72, 73,
    74, 75, 78, 80, 80, 81, 81, 85, 86, 87, 88, 96,
    97, 99, 102, 103, 104, 106, 109, 110, 111, 113, 116, 117,
    118, 120, 123, 124, 125, 127, 4, 1, 15, 17, 19, 21,
    22, 23, 24, 25, 28, 30, 30, 31, 31, 35, 36, 37,
    40, 42, 44, 46, 47, 48, 49, 50, 53, 55, 55, 56,
    56, 60, 61, 62, 65, 67, 69, 71, 72, 73, 74, 75,
    78, 80, 80, 81, 81, 85, 86, 87, 88, 96, 97, 99,
    102, 103, 104, 106, 109, 110, 111, 113, 116, 117, 118, 120,
    123, 124, 125, 127, 4, 1, 15, 17, 19, 21, 22, 23,
    24, 25, 28, 30, 30, 31, 31, 35, 36, 37, 40, 42,
    44, 46, 47, 48, 49, 50, 53, 55, 55, 56, 56, 60,
    61, 62, 65, 67, 69, 71, 72, 73, 74, 75, 78, 80,
    80, 81, 81, 85, 86, 87, 88, 96, 97, 99, 102, 103,
    104, 106, 109, 110, 111, 113, 116, 117, 118, 120, 123, 124,
    125, 127, 4, 1, 15, 17, 19, 21, 22, 23, 24, 25,
    28, 30, 30, 31, 31, 35, 36, 37, 40, 42, 44, 46,
    47, 48, 49, 50, 53, 55, 55, 56, 56, 60, 61, 62,
    65, 67, 69, 71, 72, 73, 74, 75, 78, 80, 80, 81,
    81, 85, 86, 87, 88, 96, 97, 99, 102, 103, 104, 106,
    109, 110, 111, 113, 116, 117, 118, 120, 123, 124, 125, 127,
    4, 1, 15, 17, 19, 21, 22, 23, 24, 25, 28, 30,
    30, 31, 31, 35, 36, 37, 40, 42, 44, 46, 47, 48,
    49, 50, 53, 55, 55, 56, 56, 60, 61, 62, 65, 67,
    69, 71, 72, 73, 74, 75, 78, 80, 80, 81, 81, 85,
    86, 87, 88, 96, 97, 99, 102, 103, 104, 106, 109, 110,
    111, 113, 116, 117, 118, 120, 123, 124, 125, 127, 4, 1,
    15, 17, 19, 21, 22, 23, 24, 25, 28, 30, 30, 31,
    31, 35, 36, 37, 40, 42, 44, 46, 47, 48, 49, 50,
    53, 55, 55, 56, 56, 60, 61, 62, 65, 67, 69, 71,
    72, 73, 74, 75, 78, 80, 80, 81, 81, 85, 86, 87,
    88, 96, 97, 99, 102, 103, 104, 106, 109, 110, 111, 113,
    116, 117, 118, 120, 123, 124, 125, 127, 4, 1, 15, 17,
    19, 21, 22, 23, 24, 25, 28, 30, 30, 31, 31, 35,
    36, 37, 40, 42, 44, 46, 47, 48, 49, 50, 53, 55,
    55, 56, 56, 60, 61, 62, 65, 67, 69, 71, 72, 73,
    74, 75, 78, 80, 80, 81, 81, 85, 86, 87, 88, 96,
    97, 99, 102, 103, 104, 106, 109, 110, 111, 113, 116, 117,
    118, 120, 123, 124, 125, 127, 4, 1, 5, 17, 19, 21,
    22, 23, 24, 25, 30, 30, 31, 31, 32, 32, 36, 37,
    42, 44, 46, 47, 48, 49, 50, 55, 55, 56, 56, 57,
    57, 61, 62, 67, 69, 71, 72, 73, 74, 75, 80, 80,
    81, 81, 82, 82, 86, 87, 88, 96, 97, 99, 102, 103,
    104, 106, 109, 110, 111, 113, 116, 117, 118, 120, 123, 124,
    125, 127, 4, 1, 5, 17, 19, 21, 22, 23, 24, 25,
    30, 30, 31, 31, 32, 32, 36, 37, 42, 44, 46, 47,
    48, 49, 50, 55, 55, 56, 56, 57, 57, 61, 62, 67,
    69, 71, 72, 73, 74, 75, 80, 80, 81, 81, 82, 82,
    86, 87, 88, 96, 97, 99, 102, 103, 104, 106, 109, 110,
    111, 113, 116, 117, 118, 120, 123, 124, 125, 127, 4, 1,
    5, 17, 19, 21, 22, 23, 24, 25, 30, 30, 31, 31,
    32, 32, 36, 37, 42, 44, 46, 47, 48, 49, 50, 55,
    55, 56, 56, 57, 57, 61, 62, 67, 69, 71, 72, 73,
    74, 75, 80, 80, 81, 81, 82, 82, 86, 87, 88, 96,
    97, 99, 102, 103, 104, 106, 109, 110, 111, 113, 116, 117,
    118, 120, 123, 124, 125, 127, 4, 1, 5, 17, 19, 21,
    22, 23, 24, 25, 30, 30, 31, 31, 32, 32, 36, 37,
    42, 44, 46, 47, 48, 49, 50, 55, 55, 56, 56, 57,
    57, 61, 62, 67, 69, 71, 72, 73, 74, 75, 80, 80,
    81, 81, 82, 82, 86, 87, 88, 96, 97, 99, 102, 103,
    104, 106, 109, 110, 111, 113, 116, 117, 118, 120, 123, 124,
    125, 127, 4, 1, 5, 17, 19, 21, 22, 23, 24, 25,
    30, 30, 31, 31, 32, 32, 36, 37, 42, 44, 46, 47,
    48, 49, 50, 55, 55, 56, 56, 57, 57, 61, 62, 67,
    69, 71, 72, 73, 74, 75, 80, 80, 81, 81, 82, 82,
    86, 87, 88, 96, 97, 99, 102, 103, 104, 106, 109, 110,
    111, 113, 116, 117, 118, 120, 123, 124, 125, 127, 4, 1,
    5, 17, 19, 21, 22, 23, 24, 25, 30, 30, 31, 31,
    32, 32, 36, 37, 42, 44, 46, 47, 48, 49, 50, 55,
    55, 56, 56, 57, 57, 61, 62, 67, 69, 71, 72, 73,
    74, 75, 80, 80, 81, 81, 82, 82, 86, 87, 88, 96,
    97, 99, 102, 103, 104, 106, 109, 110, 111, 113, 116, 117,
    118, 120, 123, 124, 125, 127, 4, 1, 5, 17, 19, 21,
    22, 23, 24, 25, 30, 30, 31, 31, 32, 32, 36, 37,
    42, 44, 46, 47, 48, 49, 50, 55, 55, 56, 56, 57,
    57, 61, 62, 67, 69, 71, 72, 73, 74, 75, 80, 80,
    81, 81, 82, 82, 86, 87, 88, 96, 97, 99, 102, 103,
    104, 106, 109, 110, 111, 113, 116, 117, 118, 120, 123, 124,
    125, 127, 4, 1, 5, 17, 19, 21, 22, 23, 24, 25,
    30, 30, 31, 31, 32, 32, 36, 37, 42, 44, 46, 47,
    48, 49, 50, 55, 55, 56, 56, 57, 57, 61, 62, 67,
    69, 71, 72, 73, 74, 75, 80, 80, 81, 81, 82, 82,
    86, 87, 88, 96, 97, 99, 102, 103, 104, 106, 109, 110,
    111, 113, 116, 117, 118, 120, 123, 124, 125, 127, 4, 1,
    5, 17, 19, 21, 22, 23, 25, 30, 30, 31, 32, 32,
    36, 37, 42, 44, 46, 47, 48, 50, 55, 55, 56, 57,
    57, 61, 62, 67, 69, 71, 72, 73, 75, 80, 80, 81,
    82, 82, 86, 87, 88, 96, 97, 99, 102, 103, 104, 106,
    109, 110, 111, 113, 116, 117, 118, 120, 123, 124, 125, 127,
    4, 1, 5, 17, 19, 21, 22, 23, 25, 30, 30, 31,
    32, 32, 36, 37, 42, 44, 46, 47, 48, 50, 55, 55,
    56, 57, 57, 61, 62, 67, 69, 71, 72, 73, 75, 80,
    80, 81, 82, 82, 86, 87, 88, 96, 97, 99, 102, 103,
    104, 106, 109, 110, 111, 113, 116, 117, 118, 120, 123, 124,
    125, 127, 4, 1, 5, 17, 19, 21, 22, 23, 25, 30,
    30, 31, 32, 32, 36, 37, 42, 44, 46, 47, 48, 50,
    55, 55, 56, 57, 57, 61, 62, 67, 69, 71, 72, 73,
    75, 80, 80, 81, 82, 82, 86, 87, 88, 96, 97, 99,
    102, 103, 104, 106, 109, 110, 111, 113, 116, 117, 118, 120,
    123, 124, 125, 127, 4, 1, 5, 17, 19, 21, 22, 23,
    25, 30, 30, 31, 32, 32, 36, 37, 42, 44, 46, 47,
    48, 50, 55, 55, 56, 57, 57, 61, 62, 67, 69, 71,
    72, 73, 75, 80, 80, 81, 82, 82, 86, 87, 88, 96,
    97, 99, 102, 103, 104, 106, 109, 110, 111, 113, 116, 117,
    118, 120, 123, 124, 125, 127, 4, 1, 5, 17, 19, 21,
    22, 23, 25, 30, 30, 31, 32, 32, 36, 37, 42, 44,
    46, 47, 48, 50, 55, 55, 56, 57, 57, 61, 62, 67,
    69, 71, 72, 73, 75, 80, 80, 81, 82, 82, 86, 87,
    88, 96, 97, 99, 102, 103, 104, 106, 109, 110, 111, 113,
    116, 117, 118, 120, 123, 124, 125, 127, 4, 1, 5, 17,
    19, 21, 22, 23, 25, 30, 30, 31, 32, 32, 36, 37,
    42, 44, 46, 47, 48, 50, 55, 55, 56, 57, 57, 61,
    62, 67, 69, 71, 72, 73, 75, 80, 80, 81, 82, 82,
    86, 87, 88, 96, 97, 99, 102, 103, 104, 106, 109, 110,
    111, 113, 116, 117, 118, 120, 123, 124, 125, 127, 4, 1,
    5, 17, 19, 21, 22, 23, 25, 30, 30, 31, 32, 32,
    36, 37, 42, 44, 46, 47, 48, 50, 55, 55, 56, 57,
    57, 61, 62, 67, 69, 71, 72, 73, 75, 80, 80, 81,
    82, 82, 86, 87, 88, 96, 97, 99, 102, 103, 104, 106,
    109, 110, 111, 113, 116, 117, 118, 120, 123, 124, 125, 127,
    4, 1, 5, 17, 19, 21, 22, 23, 25, 30, 30, 31,
    32, 32, 36, 37, 42, 44, 46, 47, 48, 50, 55, 55,
    56, 57, 57, 61, 62, 67, 69, 71, 72, 73, 75, 80,
    80, 81, 82, 82, 86, 87, 88, 96, 97, 99, 102, 103,
    104, 106, 109, 110, 111, 113, 116, 117, 118, 120, 123, 124,
    125, 127, 4, 1, 5, 17, 19, 21, 22, 23, 25, 30,
    30, 31, 32, 32, 36, 37, 42, 44, 46, 47, 48, 50,
    55, 55, 56, 57, 57, 61, 62, 67, 69, 71, 72, 73,
    75, 80, 80, 81, 82, 82, 86, 87, 88, 96, 97, 99,
    102, 103, 104, 106, 109, 110, 111, 113, 116, 117, 118, 120,
    123, 124, 125, 127, 4, 1, 5, 17, 19, 21, 22, 23,
    25, 30, 30, 31, 32, 32, 36, 37, 42, 44, 46, 47,
    48, 50, 55, 55, 56, 57, 57, 61, 62, 67, 69, 71,
    72, 73, 75, 80, 80, 81, 82, 82, 86, 87, 88, 96,
    97, 99, 102, 103, 104, 106, 109, 110, 111, 113, 116, 117,
    118, 120, 123, 124, 125, 127, 4, 1, 5, 17, 19, 21,
    22, 23, 25, 30, 30, 31, 32, 32, 36, 37, 42, 44,
    46, 47, 48, 50, 55, 55, 56, 57, 57, 61, 62, 67,
    69, 71, 72, 73, 75, 80, 80, 81, 82, 82, 86, 87,
    88, 96, 97, 99, 102, 103, 104, 106, 109, 110, 111, 113,
    116, 117, 118, 120, 123, 124, 125, 127, 4, 1, 5, 17,
    19, 21, 22, 23, 25, 30, 30, 31, 32, 32, 36, 37,
    42, 44, 46, 47, 48, 50, 55, 55, 56, 57, 57, 61,
    62, 67, 69, 71, 72, 73, 75, 80, 80, 81, 82, 82,
    86, 87, 88, 96, 97, 99, 102, 103, 104, 106, 109, 110,
    111, 113, 116, 117, 118, 120, 123, 124, 125, 127, 4, 1,
    5, 17, 19, 21, 22, 23, 25, 30, 30, 31, 32, 32,
    36, 37, 42, 44, 46, 47, 48, 50, 55, 55, 56, 57,
    57, 61, 62, 67, 69, 71, 72, 73, 75, 80, 80, 81,
    82, 82, 86, 87, 88, 96, 97, 99, 102, 103, 104, 106,
    109, 110, 111, 113, 116, 117, 118, 120, 123, 124, 125, 127,
    4, 1, 5, 17, 19, 21, 22, 23, 25, 30, 30, 31,
    32, 32, 36, 37, 42, 44, 46, 47, 48, 50, 55, 55,
    56, 57, 57, 61, 62, 67, 69, 71, 72, 73, 75, 80,
    80, 81, 82, 82, 86, 87, 88, 96, 97, 99, 102, 103,
    104, 106, 109, 110, 111, 113, 116, 117, 118, 120, 123, 124,
    125, 127, 4, 1, 5, 17, 19, 21, 22, 23, 25, 30,
    30, 31, 32, 32, 36, 37, 42, 44, 46, 47, 48, 50,
    55, 55, 56, 57, 57, 61, 62, 67, 69, 71, 72, 73,
    75, 80, 80, 81, 82, 82, 86, 87, 88, 96, 97, 99,
    102, 103, 104, 106, 109, 110, 111, 113, 116, 117, 118, 120,
    123, 124, 125, 127, 4, 1, 5, 17, 19, 21, 22, 23,
    25, 30, 30, 31, 32, 32, 36, 37, 42, 44, 46, 47,
    48, 50, 55, 55, 56, 57, 57, 61, 62, 67, 69, 71,
    72, 73, 75, 80, 80, 81, 82, 82, 86, 87, 88, 96,
    97, 99, 102, 103, 104, 106, 109, 110, 111, 113, 116, 117,
    118, 120, 123, 124, 125, 127, 4, 1, 5, 17, 19, 21,
    22, 23, 25, 30, 30, 31, 32, 32, 36, 37, 42, 44,
    46, 47, 48, 50, 55, 55, 56, 57, 57, 61, 62, 67,
    69, 71, 72, 73, 75, 80, 80, 81, 82, 82, 86, 87,
    88, 96, 97, 99, 102, 103, 104, 106, 109, 110, 111, 113,
    116, 117, 118, 120, 123, 124, 125, 127, 4, 1, 5, 17,
    19, 21, 22, 23, 25, 30, 30, 31, 32, 32, 36, 37,
    42, 44, 46, 47, 48, 50, 55, 55, 56, 57, 57, 61,
    62, 67, 69, 71, 72, 73, 75, 80, 80, 81, 82, 82,
    86, 87, 88, 96, 97, 99, 102, 103, 104, 106, 109, 110,
    111, 113, 116, 117, 118, 120, 123, 124, 125, 127, 4, 1,
    5, 17, 19, 21, 22, 23, 25, 30, 30, 31, 32, 32,
    36, 37, 42, 44, 46, 47, 48, 50, 55, 55, 56, 57,
    57, 61, 62, 67, 69, 71, 72, 73, 75, 80, 80, 81,
    82, 82, 86, 87, 88, 96, 97, 99, 102, 103, 104, 106,
    109, 110, 111, 113, 116, 117, 118, 120, 123, 124, 125, 127,
    4, 1, 5, 17, 19, 21, 22, 23, 25, 30, 30, 31,
    32, 32, 36, 37, 42, 44, 46, 47, 48, 50, 55, 55,
    56, 57, 57, 61, 62, 67, 69, 71, 72, 73, 75, 80,
    80, 81, 82, 82, 86, 87, 88, 96, 97, 99, 102, 103,
    104, 106, 109, 110, 111, 113, 116, 117, 118, 120, 123, 124,
    125, 127, 4, 1, 5, 17, 19, 21, 22, 23, 25, 30,
    30, 31, 32, 32, 36, 37, 42, 44, 46, 47, 48, 50,
    55, 55, 56, 57, 57, 61, 62, 67, 69, 71, 72, 73,
    75, 80, 80, 81, 82, 82, 86, 87, 88, 96, 97, 99,
    102, 103, 104, 106, 109, 110, 111, 113, 116, 117, 118, 120,
    123, 124, 125, 127, 4, 1, 5, 17, 19, 21, 22, 23,
    25, 30, 30, 31, 32, 32, 36, 37, 42, 44, 46, 47,
    48, 50, 55, 55, 56, 57, 57, 61, 62, 67, 69, 71,
    72, 73, 75, 80, 80, 81, 82, 82, 86, 87, 88, 96,
    97, 99, 102, 103, 104, 106, 109, 110, 111, 113, 116, 117,
    118, 120, 123, 124, 125, 127, 4, 1, 5, 17, 19, 21,
    22, 23, 25, 30, 30, 31, 32, 32, 36, 37, 42, 44,
    46, 47, 48, 50, 55, 55, 56, 57, 57, 61, 62, 67,
    69, 71, 72, 73, 75, 80, 80, 81, 82, 82, 86, 87,
    88, 96, 97, 99, 102, 103, 104, 106, 109, 110, 111, 113,
    116, 117, 118, 120, 123, 124, 125, 127, 4, 1, 5, 17,
    19, 21, 22, 23, 25, 30, 30, 31, 32, 32, 36, 37,
    42, 44, 46, 47, 48, 50, 55, 55, 56, 57, 57, 61,
    62, 67, 69, 71, 72, 73, 75, 80, 80, 81, 82, 82,
    86, 87, 88, 96, 97, 99, 102, 103, 104, 106, 109, 110,
    111, 113, 116, 117, 118, 120, 123, 124, 125, 127, 4, 1,
    17, 19, 21, 22, 23, 25, 30, 30, 31, 32, 32, 36,
    37, 42, 44, 46, 47, 48, 50, 55, 55, 56, 57, 57,
    61, 62, 67, 69, 71, 72, 73, 75, 80, 80, 81, 82,
    82, 86, 87, 88, 96, 97, 99, 102, 103, 104, 106, 109,
    110, 111, 113, 116, 117, 118, 120, 123, 124, 125, 127, 4,
    1, 17, 19, 21, 22, 23, 25, 30, 30, 31, 32, 32,
    36, 37, 42, 44, 46, 47, 48, 50, 55, 55, 56, 57,
    57, 61, 62, 67, 69, 71, 72, 73, 75, 80, 80, 81,
    82, 82, 86, 87, 88, 96, 97, 99, 102, 103, 104, 106,
    109, 110, 111, 113, 116, 117, 118, 120, 123, 124, 125, 127,
    4, 1, 17, 19, 21, 22, 23, 25, 30, 30, 31, 32,
    32, 36, 37, 42, 44, 46, 47, 48, 50, 55, 55, 56,
    57, 57, 61, 62, 67, 69, 71, 72, 73, 75, 80, 80,
    81, 82, 82, 86, 87, 88, 96, 97, 99, 102, 103, 104,
    106, 109, 110, 111, 113, 116, 117, 118, 120, 123, 124, 125,
    127, 4, 1, 17, 19, 21, 22, 23, 25, 30, 30, 31,
    32, 32, 36, 37, 42, 44, 46, 47, 48, 50, 55, 55,
    56, 57, 57, 61, 62, 67, 69, 71, 72, 73, 75, 80,
    80, 81, 82, 82, 86, 87, 88, 96, 97, 99, 102, 103,
    104, 106, 109, 110, 111, 113, 116, 117, 118, 120, 123, 124,
    125, 127, 4, 1, 17, 19, 21, 22, 23, 25, 30, 30,
    31, 32, 32, 36, 37, 42, 44, 46, 47, 48, 50, 55,
    55, 56, 57, 57, 61, 62, 67, 69, 71, 72, 73, 75,
    80, 80, 81, 82, 82, 86, 87, 88, 96, 97, 99, 102,
    103, 104, 106, 109, 110, 111, 113, 116, 117, 118, 120, 123,
    124, 125, 127, 4, 1, 17, 19, 21, 22, 23, 25, 30,
    30, 31, 32, 32, 36, 37, 42, 44, 46, 47, 48, 50,
    55, 55, 56, 57, 57, 61, 62, 67, 69, 71, 72, 73,
    75, 80, 80, 81, 82, 82, 86, 87, 88, 96, 97, 99,
    102, 103, 104, 106, 109, 110, 111, 113, 116, 117, 118, 120,
    123, 124, 125, 127, 4, 1, 17, 19, 21, 22, 23, 25,
    30, 30, 31, 32, 32, 36, 37, 42, 44, 46, 47, 48,
    50, 55, 55, 56, 57, 57, 61, 62, 67, 69, 71, 72,
    73, 75, 80, 80, 81, 82, 82, 86, 87, 88, 96, 97,
    99, 102, 103, 104, 106, 109, 110, 111, 113, 116, 117, 118,
    120, 123, 124, 125, 127, 4, 1, 17, 19, 21, 22, 23,
    25, 30, 30, 31, 32, 32, 36, 37, 42, 44, 46, 47,
    48, 50, 55, 55, 56, 57, 57, 61, 62, 67, 69, 71,
    72, 73, 75, 80, 80, 81, 82, 82, 86, 87, 88, 96,
    97, 99, 102, 103, 104, 106, 109, 110, 111, 113, 116, 117,
    118, 120, 123, 124, 125, 127, 4, 1, 17, 19, 21, 22,
    23, 25, 30, 30, 31, 32, 32, 36, 37, 42, 44, 46,
    47, 48, 50, 55, 55, 56, 57, 57, 61, 62, 67, 69,
    71, 72, 73, 75, 80, 80, 81, 82, 82, 86, 87, 88,
    96, 97, 99, 102, 103, 104, 106, 109, 110, 111, 113, 116,
    117, 118, 120, 123, 124, 125, 127, 4, 1, 17, 19, 21,
    22, 23, 25, 30, 30, 31, 32, 32, 36, 37, 42, 44,
    46, 47, 48, 50, 55, 55, 56, 57, 57, 61, 62, 67,
    69, 71, 72, 73, 75, 80, 80, 81, 82, 82, 86, 87,
    88, 96, 97, 99, 102, 103, 104, 106, 109, 110, 111, 113,
    116, 117, 118, 120, 123, 124, 125, 127, 4, 1, 17, 19,
    21, 22, 23, 25, 30, 30, 31, 32, 32, 36, 37, 42,
    44, 46, 47, 48, 50, 55, 55, 56, 57, 57, 61, 62,
    67, 69, 71, 72, 73, 75, 80, 80, 81, 82, 82, 86,
    87, 88, 96, 97, 99, 102, 103, 104, 106, 109, 110, 111,
    113, 116, 117, 118, 120, 123, 124, 125, 127, 4, 1, 17,
    19, 21, 22, 23, 25, 30, 30, 31, 32, 32, 36, 37,
    42, 44, 46, 47, 48, 50, 55, 55, 56, 57, 57, 61,
    62, 67, 69, 71, 72, 73, 75, 80, 80, 81, 82, 82,
    86, 87, 88, 96, 97, 99, 102, 103, 104, 106, 109, 110,
    111, 113, 116, 117, 118, 120, 123, 124, 125, 127, 4, 1,
    17, 19, 21, 22, 23, 25, 30, 30, 31, 32, 32, 36,
    37, 42, 44, 46, 47, 48, 50, 55, 55, 56, 57, 57,
    61, 62, 67, 69, 71, 72, 73, 75, 80, 80, 81, 82,
    82, 86, 87, 88, 96, 97, 99, 102, 103, 104, 106, 109,
    110, 111, 113, 116, 117, 118, 120, 123, 124, 125, 127, 4,
    1, 17, 19, 21, 22, 23, 25, 30, 30, 31, 32, 32,
    36, 37, 42, 44, 46, 47, 48, 50, 55, 55, 56, 57,
    57, 61, 62, 67, 69, 71, 72, 73, 75, 80, 80, 81,
    82, 82, 86, 87, 88, 96, 97, 99, 102, 103, 104, 106,
    109, 110, 111, 113, 116, 117, 118, 120, 123, 124, 125, 127,
    4, 1, 17, 19, 21, 22, 23, 25, 30, 30, 31, 32,
    32, 36, 37, 42, 44, 46, 47, 48, 50, 55, 55, 56,
    57, 57, 61, 62, 67, 69, 71, 72, 73, 75, 80, 80,
    81, 82, 82, 86, 87, 88, 96, 97, 99, 102, 103, 104,
    106, 109, 110, 111, 113, 116, 117, 118, 120, 123, 124, 125,
    127, 4, 1, 17, 19, 21, 22, 23, 25, 30, 30, 31,
    32, 32, 36, 37, 42, 44, 46, 47, 48, 50, 55, 55,
    56, 57, 57, 61, 62, 67, 69, 71, 72, 73, 75, 80,
    80, 81, 82, 82, 86, 87, 88, 96, 97, 99, 102, 103,
    104, 106, 109, 110, 111, 113, 116, 117, 118, 120, 123, 124,
    125, 127, 0, 0, 1, 17, 19, 21, 22, 23, 25, 30,
    30, 31, 32, 32, 37, 42, 44, 46, 47, 48, 50, 55,
    55, 56, 57, 57, 62, 67, 69, 71, 72, 73, 75, 80,
    80, 81, 82, 82, 88, 96, 97, 99, 102, 103, 104, 106,
    109, 110, 111, 113, 116, 117, 118, 120, 123, 124, 125, 127,
    0, 0, 1, 17, 19, 21, 22, 23, 25, 30, 30, 31,
    32, 32, 37, 42, 44, 46, 47, 48, 50, 55, 55, 56,
    57, 57, 62, 67, 69, 71, 72, 73, 75, 80, 80, 81,
    82, 82, 88, 96, 97, 99, 102, 103, 104, 106, 109, 110,
    111, 113, 116, 117, 118, 120, 123, 124, 125, 127, 0, 0,
    1, 17, 19, 21, 22, 23, 25, 30, 30, 31, 32, 32,
    37, 42, 44, 46, 47, 48, 50, 55, 55, 56, 57, 57,
    62, 67, 69, 71, 72, 73, 75, 80, 80, 81, 82, 82,
    88, 96, 97, 99, 102, 103, 104, 106, 109, 110, 111, 113,
    116, 117, 118, 120, 123, 124, 125, 127, 0, 0, 1, 17,
    19, 21, 22, 23, 25, 30, 30, 31, 32, 32, 37, 42,
    44, 46, 47, 48, 50, 55, 55, 56, 57, 57, 62, 67,
    69, 71, 72, 73, 75, 80, 80, 81, 82, 82, 88, 96,
    97, 99, 102, 103, 104, 106, 109, 110, 111, 113, 116, 117,
    118, 120, 123, 124, 125, 127, 0, 0, 1, 17, 19, 21,
    22, 23, 25, 30, 30, 31, 32, 32, 37, 42, 44, 46,
    47, 48, 50, 55, 55, 56, 57, 57, 62, 67, 69, 71,
    72, 73, 75, 80, 80, 81, 82, 82, 88, 96, 97, 99,
    102, 103, 104, 106, 109, 110, 111, 113, 116, 117, 118, 120,
    123, 124, 125, 127, 0, 0, 1, 17, 19, 21, 22, 23,
    25, 30, 30, 31, 32, 32, 37, 42, 44, 46, 47, 48,
    50, 55, 55, 56, 57, 57, 62, 67, 69, 71, 72, 73,
    75, 80, 80, 81, 82, 82, 88, 96, 97, 99, 102, 103,
    104, 106, 109, 110, 111, 113, 116, 117, 118, 120, 123, 124,
    125, 127, 0, 0, 1, 17, 19, 21, 22, 23, 25, 30,
    30, 31, 32, 32, 37, 42, 44, 46, 47, 48, 50, 55,
    55, 56, 57, 57, 62, 67, 69, 71, 72, 73, 75, 80,
    80, 81, 82, 82, 88, 96, 97, 99, 102, 103, 104, 106,
    109, 110, 111, 113, 116, 117, 118, 120, 123, 124, 125, 127,
    0, 0, 1, 17, 19, 21, 22, 23, 25, 30, 30, 31,
    32, 32, 37, 42, 44, 46, 47, 48, 50, 55, 55, 56,
    57, 57, 62, 67, 69, 71, 72, 73, 75, 80, 80, 81,
    82, 82, 88, 96, 97, 99, 102, 103, 104, 106, 109, 110,
    111, 113, 116, 117, 118, 120, 123, 124, 125, 127, 0, 0,
    1, 17, 19, 21, 22, 23, 25, 30, 33, 32, 32, 37,
    42, 44, 46, 47, 48, 50, 55, 58, 57, 57, 62, 67,
    69, 71, 72, 73, 75, 80, 83, 82, 82, 88, 96, 97,
    99, 102, 103, 104, 106, 109, 110, 111, 113, 116, 117, 118,
    120, 123, 124, 125, 127, 0, 0, 1, 17, 19, 21, 22,
    23, 25, 30, 33, 32, 32, 37, 42, 44, 46, 47, 48,
    50, 55, 58, 57, 57, 62, 67, 69, 71, 72, 73, 75,
    80, 83, 82, 82, 88, 96, 97, 99, 102, 103, 104, 106,
    109, 110, 111, 113, 116, 117, 118, 120, 123, 124, 125, 127,
    0, 0, 1, 17, 19, 21, 22, 23, 25, 30, 33, 32,
    32, 37, 42, 44, 46, 47, 48, 50, 55, 58, 57, 57,
    62, 67, 69, 71, 72, 73, 75, 80, 83, 82, 82, 88,
    96, 97, 99, 102, 103, 104, 106, 109, 110, 111, 113, 116,
    117, 118, 120, 123, 124, 125, 127, 0, 0, 1, 17, 19,
    21, 22, 23, 25, 30, 33, 32, 32, 37, 42, 44, 46,
    47, 48, 50, 55, 58, 57, 57, 62, 67, 69, 71, 72,
    73, 75, 80, 83, 82, 82, 88, 96, 97, 99, 102, 103,
    104, 106, 109, 110, 111, 113, 116, 117, 118, 120, 123, 124,
    125, 127, 0, 0, 1, 17, 19, 21, 22, 23, 25, 30,
    33, 32, 32, 37, 42, 44, 46, 47, 48, 50, 55, 58,
    57, 57, 62, 67, 69, 71, 72, 73, 75, 80, 83, 82,
    82, 88, 96, 97, 99, 102, 103, 104, 106, 109, 110, 111,
    113, 116, 117, 118, 120, 123, 124, 125, 127, 0, 0, 1,
    17, 19, 21, 22, 23, 25, 30, 33, 32, 32, 37, 42,
    44, 46, 47, 48, 50, 55, 58, 57, 57, 62, 67, 69,
    71, 72, 73, 75, 80, 83, 82, 82, 88, 96, 97, 99,
    102, 103, 104, 106, 109, 110, 111, 113, 116, 117, 118, 120,
    123, 124, 125, 127, 0, 0, 1, 17, 19, 21, 22, 23,
    25, 30, 33, 32, 32, 37, 42, 44, 46, 47, 48, 50,
    55, 58, 57, 57, 62, 67, 69, 71, 72, 73, 75, 80,
    83, 82, 82, 88, 96, 97, 99, 102, 103, 104, 106, 109,
    110, 111, 113, 116, 117, 118, 120, 123, 124, 125, 127, 0,
    0, 1, 17, 19, 21, 22, 23, 25, 30, 33, 32, 32,
    37, 42, 44, 46, 47, 48, 50, 55, 58, 57, 57, 62,
    67, 69, 71, 72, 73, 75, 80, 83, 82, 82, 88, 96,
    97, 99, 102, 103, 104, 106, 109, 110, 111, 113, 116, 117,
    118, 120, 123, 124, 125, 127, 0, 0, 1, 17, 19, 21,
    22, 23, 25, 30, 33, 32, 32, 37, 42, 44, 46, 47,
    48, 50, 55, 58, 57, 57, 62, 67, 69, 71, 72, 73,
    75, 80, 83, 82, 82, 88, 96, 97, 99, 102, 103, 104,
    106, 109, 110, 111, 113, 116, 117, 118, 120, 123, 124, 125,
    127, 0, 0, 1, 17, 19, 21, 22, 23, 25, 30, 33,
    32, 32, 37, 42, 44, 46, 47, 48, 50, 55, 58, 57,
    57, 62, 67, 69, 71, 72, 73, 75, 80, 83, 82, 82,
    88, 96, 97, 99, 102, 103, 104, 106, 109, 110, 111, 113,
    116, 117, 118, 120, 123, 124, 125, 127, 0, 0, 1, 17,
    19, 21, 22, 23, 25, 30, 33, 32, 32, 37, 42, 44,
    46, 47, 48, 50, 55, 58, 57, 57, 62, 67, 69, 71,
    72, 73, 75, 80, 83, 82, 82, 88, 96, 97, 99, 102,
    103, 104, 106, 109, 110, 111, 113, 116, 117, 118, 120, 123,
    124, 125, 127, 0, 0, 1, 17, 19, 21, 22, 23, 25,
    30, 33, 32, 32, 37, 42, 44, 46, 47, 48, 50, 55,
    58, 57, 57, 62, 67, 69, 71, 72, 73, 75, 80, 83,
    82, 82, 88, 96, 97, 99, 102, 103, 104, 106, 109, 110,
    111, 113, 116, 117, 118, 120, 123, 124, 125, 127, 0, 0,
    1, 17, 19, 21, 22, 23, 25, 30, 33, 32, 32, 37,
    42, 44, 46, 47, 48, 50, 55, 58, 57, 57, 62, 67,
    69, 71, 72, 73, 75, 80, 83, 82, 82, 88, 96, 97,
    99, 102, 103, 104, 106, 109, 110, 111, 113, 116, 117, 118,
    120, 123, 124, 125, 127, 0, 0, 1, 17, 19, 21, 22,
    23, 25, 30, 33, 32, 32, 37, 42, 44, 46, 47, 48,
    50, 55, 58, 57, 57, 62, 67, 69, 71, 72, 73, 75,
    80, 83, 82, 82, 88, 96, 97, 99, 102, 103, 104, 106,
    109, 110, 111, 113, 116, 117, 118, 120, 123, 124, 125, 127,
    0, 0, 1, 17, 19, 21, 22, 23, 25, 30, 33, 32,
    32, 37, 42, 44, 46, 47, 48, 50, 55, 58, 57, 57,
    62, 67, 69, 71, 72, 73, 75, 80, 83, 82, 82, 88,
    96, 97, 99, 102, 103, 104, 106, 109, 110, 111, 113, 116,
    117, 118, 120, 123, 124, 125, 127, 0, 0, 1, 17, 19,
    21, 22, 23, 25, 30, 33, 32, 32, 37, 42, 44, 46,
    47, 48, 50, 55, 58, 57, 57, 62, 67, 69, 71, 72,
    73, 75, 80, 83, 82, 82, 88, 96, 97, 99, 102, 103,
    104, 106, 109, 110, 111, 113, 116, 117, 118, 120, 123, 124,
    125, 127, 0, 1, 17, 19, 21, 22, 23, 25, 30, 33,
    32, 32, 37, 42, 44, 46, 47, 48, 50, 55, 58, 57,
    57, 62, 67, 69, 71, 72, 73, 75, 80, 83, 82, 82,
    88, 96, 97, 99, 102, 103, 104, 106, 109, 110, 111, 113,
    116, 117, 118, 120, 123, 124, 125, 127, 0, 1, 17, 19,
    21, 22, 23, 25, 30, 33, 32, 32, 37, 42, 44, 46,
    47, 48, 50, 55, 58, 57, 57, 62, 67, 69, 71, 72,
    73, 75, 80, 83, 82, 82, 88, 96, 97, 99, 102, 103,
    104, 106, 109, 110, 111, 113, 116, 117, 118, 120, 123, 124,
    125, 127, 0, 1, 17, 19, 21, 22, 23, 25, 30, 33,
    32, 32, 37, 42, 44, 46, 47, 48, 50, 55, 58, 57,
    57, 62, 67, 69, 71, 72, 73, 75, 80, 83, 82, 82,
    88, 96, 97, 99, 102, 103, 104, 106, 109, 110, 111, 113,
    116, 117, 118, 120, 123, 124, 125, 127, 0, 1, 17, 23,
    25, 30, 33, 32, 32, 37, 42, 48, 50, 55, 58, 57,
    57, 62, 67, 73, 75, 80, 83, 82, 82, 88, 96, 97,
    99, 102, 103, 104, 106, 109, 110, 111, 113, 116, 117, 118,
    120, 123, 124, 125, 127, 0, 1, 17, 23, 25, 30, 33,
    32, 32, 37, 42, 48, 50, 55, 58, 57, 57, 62, 67,
    73, 75, 80, 83, 82, 82, 88, 96, 97, 99, 102, 103,
    104, 106, 109, 110, 111, 113, 116, 117, 118, 120, 123, 124,
    125, 127, 0, 1, 17, 23, 25, 30, 33, 32, 32, 37,
    42, 48, 50, 55, 58, 57, 57, 62, 67, 73, 75, 80,
    83, 82, 82, 88, 96, 97, 99, 102, 103, 104, 106, 109,
    110, 111, 113, 116, 117, 118, 120, 123, 124, 125, 127, 0,
    1, 17, 23, 25, 30, 33, 32, 32, 37, 42, 48, 50,
    55, 58, 57, 57, 62, 67, 73, 75, 80, 83, 82, 82,
    88, 96, 97, 99, 102, 103, 104, 106, 109, 110, 111, 113,
    116, 117, 118, 120, 123, 124, 125, 127, 0, 1, 17, 23,
    25, 30, 33, 32, 32, 37, 42, 48, 50, 55, 58, 57,
    57, 62, 67, 73, 75, 80, 83, 82, 82, 88, 96, 97,
    99, 102, 103, 104, 106, 109, 110, 111, 113, 116, 117, 118,
    120, 123, 124, 125, 127, 0, 1, 17, 23, 25, 30, 33,
    32, 32, 37, 42, 48, 50, 55, 58, 57, 57, 62, 67,
    73, 75, 80, 83, 82, 82, 88, 96, 97, 99, 102, 103,
    104, 106, 109, 110, 111, 113, 116, 117, 118, 120, 123, 124,
    125, 127, 0, 1, 17, 23, 25, 30, 33, 32, 32, 37,
    42, 48, 50, 55, 58, 57, 57, 62, 67, 73, 75, 80,
    83, 82, 82, 88, 96, 97, 99, 102, 103, 104, 106, 109,
    110, 111, 113, 116, 117, 118, 120, 123, 124, 125, 127, 0,
    1, 17, 23, 25, 30, 33, 32, 32, 37, 42, 48, 50,
    55, 58, 57, 57, 62, 67, 73, 75, 80, 83, 82, 82,
    88, 96, 97, 99, 102, 103, 104, 106, 109, 110, 111, 113,
    116, 117, 118, 120, 123, 124, 125, 127, 0, 1, 17, 23,
    25, 30, 33, 32, 32, 37, 42, 48, 50, 55, 58, 57,
    57, 62, 67, 73, 75, 80, 83, 82, 82, 88, 96, 97,
    99, 102, 103, 104, 106, 109, 110, 111, 113, 116, 117, 118,
    120, 123, 124, 125, 127, 0, 1, 17, 23, 25, 30, 33,
    32, 32, 37, 42, 48, 50, 55, 58, 57, 57, 62, 67,
    73, 75, 80, 83, 82, 82, 88, 96, 97, 99, 102, 103,
    104, 106, 109, 110, 111, 113, 116, 117, 118, 120, 123, 124,
    125, 127, 0, 1, 17, 23, 25, 30, 33, 32, 32, 37,
    42, 48, 50, 55, 58, 57, 57, 62, 67, 73, 75, 80,
    83, 82, 82, 88, 96, 97, 99, 102, 103, 104, 106, 109,
    110, 111, 113, 116, 117, 118, 120, 123, 124, 125, 127, 0,
    1, 17, 23, 25, 30, 33, 32, 32, 37, 42, 48, 50,
    55, 58, 57, 57, 62, 67, 73, 75, 80, 83, 82, 82,
    88, 96, 97, 99, 102, 103, 104, 106, 109, 110, 111, 113,
    116, 117, 118, 120, 123, 124, 125, 127, 0, 1, 17, 23,
    25, 30, 33, 32, 32, 37, 42, 48, 50, 55, 58, 57,
    57, 62, 67, 73, 75, 80, 83, 82, 82, 88, 96, 97,
    99, 102, 103, 104, 106, 109, 110, 111, 113, 116, 117, 118,
    120, 123, 124, 125, 127, 0, 1, 17, 23, 30, 31, 32,
    32, 42, 48, 55, 56, 57, 57, 67, 73, 80, 81, 82,
    82, 88, 96, 97, 99, 102, 103, 104, 106, 109, 110, 111,
    113, 116, 117, 118, 120, 123, 124, 125, 127, 0, 1, 17,
    23, 30, 31, 32, 32, 42, 48, 55, 56, 57, 57, 67,
    73, 80, 81, 82, 82, 88, 96, 97, 99, 102, 103, 104,
    106, 109, 110, 111, 113, 116, 117, 118, 120, 123, 124, 125,
    127, 0, 1, 17, 23, 30, 31, 32, 32, 42, 48, 55,
    56, 57, 57, 67, 73, 80, 81, 82, 82, 88, 96, 97,
    99, 102, 103, 104, 106, 109, 110, 111, 113, 116, 117, 118,
    120, 123, 124, 125, 127, 0, 1, 17, 23, 30, 31, 32,
    32, 42, 48, 55, 56, 57, 57, 67, 73, 80, 81, 82,
    82, 88, 96, 97, 99, 102, 103, 104, 106, 109, 110, 111,
    113, 116, 117, 118, 120, 123, 124, 125, 127, 0, 1, 17,
    23, 30, 31, 32, 32, 42, 48, 55, 56, 57, 57, 67,
    73, 80, 81, 82, 82, 88, 96, 97, 99, 102, 103, 104,
    106, 109, 110, 111, 113, 116, 117, 118, 120, 123, 124, 125,
    127, 0, 1, 17, 23, 30, 31, 32, 32, 42, 48, 55,
    56, 57, 57, 67, 73, 80, 81, 82, 82, 88, 96, 97,
    99, 102, 103, 104, 106, 109, 110, 111, 113, 116, 117, 118,
    120, 123, 124, 125, 127, 0, 1, 17, 23, 30, 31, 32,
    32, 42, 48, 55, 56, 57, 57, 67, 73, 80, 81, 82,
    82, 88, 96, 97, 99, 102, 103, 104, 106, 109, 110, 111,
    113, 116, 117, 118, 120, 123, 124, 125, 127, 0, 1, 17,
    23, 30, 31, 32, 32, 42, 48, 55, 56, 57, 57, 67,
    73, 80, 81, 82, 82, 88, 96, 97, 99, 102, 109, 116,
    123, 0, 12, 12, 12, 12, 12, 13, 6, 7, 30, 31,
    32, 32, 8, 43, 45, 55, 56, 57, 57, 10, 68, 70,
    80, 81, 82, 82, 88, 96, 97, 99, 102, 109, 116, 123,
    0, 12, 12, 12, 12, 12, 13, 6, 30, 31, 32, 32,
    8, 43, 45, 55, 56, 57, 57, 10, 68, 70, 80, 81,
    82, 82, 88, 96, 97, 99, 102, 109, 116, 123, 0, 12,
    12, 12, 12, 12, 13, 6, 30, 31, 32, 32, 8, 43,
    45, 55, 56, 57, 57, 10, 68, 70, 80, 81, 82, 82,
    88, 96, 97, 99, 102, 109, 116, 123, 0, 12, 12, 12,
    12, 12, 13, 6, 30, 31, 32, 32, 8, 43, 45, 55,
    56, 57, 57, 10, 68, 70, 80, 81, 82, 82, 88, 102,
    109, 116, 123, 0, 12, 12, 12, 12, 12, 13, 6, 30,
    31, 32, 32, 8, 43, 45, 55, 56, 57, 57, 10, 68,
    70, 80, 81, 82, 82, 88, 102, 109, 116, 123, 0, 12,
    12, 12, 12, 12, 6, 30, 31, 32, 32, 8, 43, 55,
    56, 57, 57, 10, 68, 80, 81, 82, 82, 88, 102, 109,
    116, 123, 0, 12, 12, 12, 12, 12, 6, 30, 31, 32,
    32, 8, 43, 55, 56, 57, 57, 10, 68, 80, 81, 82,
    82, 88, 102, 109, 116, 123, 0, 12, 12, 12, 12, 12,
    6, 30, 31, 32, 32, 8, 43, 55, 56, 57, 57, 10,
    68, 80, 81, 82, 82, 88, 102, 109, 116, 123, 0, 12,
    12, 12, 12, 12, 6, 30, 31, 32, 32, 8, 43, 55,
    56, 57, 57, 10, 68, 80, 81, 82, 82, 88, 102, 109,
    116, 123, 0, 12, 12, 12, 12, 12, 6, 30, 31, 32,
    32, 8, 43, 55, 56, 57, 57, 10, 68, 80, 81, 82,
    82, 88, 102, 109, 116, 123, 0, 12, 12, 12, 12, 12,
    6, 30, 31, 32, 32, 8, 43, 55, 56, 57, 57, 10,
    68, 80, 81, 82, 82, 88, 102, 109, 116, 123, 0, 12,
    12, 12, 12, 12, 6, 30, 31, 32, 32, 8, 43, 55,
    56, 57, 57, 10, 68, 80, 81, 82, 82, 88, 102, 109,
    116, 123, 0, 12, 12, 12, 12, 12, 6, 30, 31, 32,
    32, 8, 43, 55, 56, 57, 57, 10, 68, 80, 81, 82,
    82, 88, 102, 109, 116, 123, 0, 12, 12, 12, 12, 12,
    6, 30, 31, 32, 32, 8, 43, 55, 56, 57, 57, 10,
    68, 80, 81, 82, 82, 88, 102, 109, 116, 123, 0, 12,
    12, 12, 12, 12, 6, 30, 31, 32, 32, 8, 43, 55,
    56, 57, 57, 10, 68, 80, 81, 82, 82, 88, 102, 109,
    116, 123, 0, 12, 12, 12, 12, 12, 6, 30, 31, 32,
    32, 8, 43, 55, 56, 57, 57, 10, 68, 80, 81, 82,
    82, 88, 102, 109, 116, 123, 0, 12, 12, 12, 12, 12,
    18, 18, 20, 30, 31, 32, 32, 9, 55, 56, 57, 57,
    11, 80, 81, 82, 82, 88, 102, 109, 116, 123, 0, 12,
    12, 12, 12, 12, 18, 18, 20, 30, 31, 32, 32, 55,
    56, 57, 57, 80, 81, 82, 82, 93, 95, 95, 95, 95,
    95, 95, 95, 95, 95, 95, 95, 95, 95, 95, 95, 95,
    95, 95, 102, 108, 115, 122, 128, 0, 12, 12, 12, 12,
    12, 18, 18, 20, 30, 31, 32, 32, 55, 56, 57, 57,
    80, 81, 82, 82, 95, 95, 95, 95, 95, 95, 95, 95,
    95, 95, 95, 95, 95, 95, 95, 95, 95, 95, 102, 128,
    0, 12, 12, 12, 12, 12, 18, 18, 20, 30, 31, 32,
    32, 55, 56, 57, 57, 80, 81, 82, 82, 95, 95, 95,
    95, 95, 95, 95, 95, 95, 95, 95, 95, 95, 95, 95,
    95, 95, 95, 102, 128, 0, 12, 12, 12, 12, 12, 18,
    18, 20, 30, 31, 32, 32, 55, 56, 57, 57, 80, 81,
    82, 82, 95, 95, 95, 95, 95, 95, 95, 95, 95, 95,
    95, 95, 95, 95, 95, 95, 95, 95, 102, 128, 0, 12,
    12, 12, 12, 12, 18, 18, 30, 31, 32, 32, 55, 56,
    57, 57, 80, 81, 82, 82, 95, 95, 95, 95, 95, 95,
    95, 95, 95, 95, 95, 95, 95, 95, 95, 95, 95, 95,
    94, 101, 128, 0, 12, 12, 12, 12, 12, 18, 18, 30,
    31, 32, 32, 55, 56, 57, 57, 80, 81, 82, 82, 95,
    95, 95, 95, 95, 95, 95, 95, 95, 95, 95, 95, 95,
    95, 95, 95, 95, 95, 0, 12, 12, 12, 12, 12, 18,
    18, 30, 31, 32, 32, 55, 56, 57, 57, 80, 81, 82,
    82, 95, 95, 95, 95, 95, 95, 95, 95, 95, 95, 95,
    95, 95, 95, 95, 95, 95, 95,
};

static __device__ __constant__ uint16_t kStaticTaskClaims[8491] = {
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 152, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 152, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    152, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    153, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 153, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 153, 1, 1, 1, 1, 1,
    0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
    2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 154, 2,
    2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
    2, 2, 2, 2, 2, 2, 2, 154, 2, 2, 2, 2,
    2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
    2, 2, 2, 2, 154, 2, 2, 2, 2, 2, 0, 2,
    2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
    2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
    3, 3, 3, 3, 3, 3, 3, 3, 155, 3, 3, 3,
    3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
    3, 3, 3, 3, 3, 155, 3, 3, 3, 3, 3, 3,
    3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
    3, 3, 155, 3, 3, 3, 3, 3, 126, 0, 0, 0,
    0, 0, 0, 3, 3, 3, 3, 3, 3, 3, 3, 3,
    3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4,
    4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
    156, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
    4, 4, 4, 4, 4, 4, 4, 4, 4, 156, 4, 4,
    4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
    4, 4, 4, 4, 4, 4, 156, 4, 4, 4, 4, 4,
    127, 1, 1, 1, 1, 4, 4, 4, 4, 4, 4, 4,
    4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 0,
    5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 157, 5,
    5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
    5, 157, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
    5, 5, 5, 5, 157, 5, 5, 5, 5, 5, 128, 2,
    2, 2, 2, 5, 5, 5, 5, 5, 5, 5, 5, 5,
    5, 5, 5, 5, 5, 5, 6, 6, 6, 1, 6, 6,
    6, 6, 6, 6, 6, 6, 6, 6, 158, 6, 6, 6,
    6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 158,
    6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
    6, 6, 158, 6, 6, 6, 6, 6, 129, 3, 3, 3,
    3, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
    6, 6, 6, 6, 7, 7, 7, 2, 7, 7, 7, 7,
    7, 7, 7, 7, 7, 7, 159, 7, 7, 7, 7, 7,
    7, 7, 7, 7, 7, 7, 7, 7, 7, 159, 7, 7,
    7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
    159, 7, 7, 7, 7, 7, 130, 4, 4, 4, 4, 7,
    7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
    7, 7, 8, 8, 3, 8, 8, 8, 8, 8, 8, 8,
    8, 8, 8, 160, 8, 8, 8, 8, 8, 8, 8, 8,
    8, 8, 8, 8, 8, 8, 160, 8, 8, 8, 8, 8,
    8, 8, 8, 8, 8, 8, 8, 8, 8, 160, 8, 8,
    8, 8, 8, 131, 5, 5, 5, 5, 8, 8, 8, 8,
    8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 9,
    9, 4, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
    161, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
    9, 9, 9, 161, 9, 9, 9, 9, 9, 9, 9, 9,
    9, 9, 9, 9, 9, 9, 161, 9, 9, 9, 9, 9,
    132, 6, 6, 6, 6, 9, 9, 9, 9, 9, 9, 9,
    9, 9, 9, 9, 9, 9, 9, 9, 10, 10, 5, 10,
    10, 10, 10, 10, 10, 10, 10, 10, 10, 162, 10, 10,
    10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
    162, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
    10, 10, 10, 162, 10, 10, 10, 10, 10, 133, 7, 7,
    7, 7, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
    10, 10, 10, 10, 10, 11, 11, 6, 11, 11, 11, 11,
    11, 11, 11, 11, 11, 11, 163, 11, 11, 11, 11, 11,
    11, 11, 11, 11, 11, 11, 11, 11, 11, 163, 11, 11,
    11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11,
    163, 11, 11, 11, 11, 11, 134, 8, 8, 8, 8, 11,
    11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11,
    11, 11, 12, 12, 7, 12, 12, 12, 12, 12, 12, 12,
    12, 12, 12, 164, 12, 12, 12, 12, 12, 12, 12, 12,
    12, 12, 12, 12, 12, 12, 164, 12, 12, 12, 12, 12,
    12, 12, 12, 12, 12, 12, 12, 12, 12, 164, 12, 12,
    12, 12, 12, 135, 9, 9, 9, 9, 12, 12, 12, 12,
    12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 13,
    13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 165,
    13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13,
    13, 13, 165, 13, 13, 13, 13, 13, 13, 13, 13, 13,
    13, 13, 13, 13, 13, 165, 13, 13, 13, 13, 13, 136,
    10, 10, 10, 10, 13, 13, 13, 13, 13, 13, 13, 13,
    13, 13, 13, 13, 13, 13, 13, 14, 14, 14, 14, 14,
    14, 14, 14, 14, 14, 14, 14, 166, 14, 14, 14, 14,
    14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 166, 14,
    14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14,
    14, 166, 14, 14, 14, 14, 14, 137, 11, 11, 11, 11,
    14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14,
    14, 14, 14, 15, 15, 15, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 167, 15, 15, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 167, 15, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 15, 15, 167, 15, 15,
    15, 15, 15, 138, 12, 12, 12, 12, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 168,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 168, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 168, 16, 16, 16, 16, 16, 139,
    13, 13, 13, 13, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 17, 17, 17, 17, 17,
    17, 17, 17, 17, 17, 17, 17, 169, 17, 17, 17, 17,
    17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 169, 17,
    17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17,
    17, 169, 17, 17, 17, 17, 17, 140, 14, 14, 14, 14,
    17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17,
    17, 17, 17, 18, 18, 18, 18, 18, 18, 18, 18, 18,
    18, 18, 18, 170, 18, 18, 18, 18, 18, 18, 18, 18,
    18, 18, 18, 18, 18, 18, 170, 18, 18, 18, 18, 18,
    18, 18, 18, 18, 18, 18, 18, 18, 18, 170, 18, 18,
    18, 18, 18, 141, 15, 15, 15, 15, 18, 18, 18, 18,
    18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 19,
    19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 171,
    19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19,
    19, 19, 171, 19, 19, 19, 19, 19, 19, 19, 19, 19,
    19, 19, 19, 19, 19, 171, 19, 19, 19, 19, 19, 142,
    16, 16, 16, 16, 19, 19, 19, 19, 19, 19, 19, 19,
    19, 19, 19, 19, 19, 19, 19, 20, 20, 20, 20, 20,
    20, 20, 20, 20, 20, 20, 20, 172, 0, 100, 20, 20,
    20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 172,
    0, 100, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
    20, 20, 20, 172, 0, 100, 20, 20, 20, 20, 143, 17,
    17, 17, 17, 20, 20, 20, 20, 20, 20, 20, 20, 20,
    20, 20, 20, 20, 20, 20, 21, 21, 21, 21, 21, 21,
    21, 21, 21, 21, 21, 21, 173, 1, 101, 21, 21, 21,
    21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 173, 1,
    101, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21,
    21, 21, 173, 1, 101, 21, 21, 21, 21, 144, 18, 18,
    18, 18, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21,
    21, 21, 21, 21, 21, 22, 22, 22, 22, 22, 22, 22,
    22, 22, 22, 22, 22, 174, 2, 102, 22, 22, 22, 22,
    22, 22, 22, 22, 22, 22, 22, 22, 22, 174, 2, 102,
    22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22,
    22, 174, 2, 102, 22, 22, 22, 22, 0, 22, 22, 22,
    22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22,
    23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23,
    175, 3, 103, 23, 23, 23, 23, 23, 23, 23, 23, 23,
    23, 23, 23, 23, 175, 3, 103, 23, 23, 23, 23, 23,
    23, 23, 23, 23, 23, 23, 23, 23, 175, 3, 103, 23,
    23, 23, 23, 19, 19, 19, 19, 23, 23, 23, 23, 23,
    23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 24, 24,
    24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 176, 4,
    104, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24,
    24, 24, 176, 4, 104, 24, 24, 24, 24, 24, 24, 24,
    24, 24, 24, 24, 24, 24, 176, 4, 104, 24, 24, 24,
    24, 20, 20, 20, 20, 24, 24, 24, 24, 24, 24, 24,
    24, 24, 24, 24, 24, 24, 24, 24, 25, 25, 25, 25,
    25, 25, 25, 25, 25, 25, 25, 25, 177, 5, 105, 25,
    25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
    177, 5, 105, 25, 25, 25, 25, 25, 25, 25, 25, 25,
    25, 25, 25, 25, 177, 5, 105, 25, 25, 25, 25, 21,
    21, 21, 21, 25, 25, 25, 25, 25, 25, 25, 25, 25,
    25, 25, 25, 25, 25, 25, 26, 26, 26, 26, 26, 26,
    26, 26, 26, 26, 26, 26, 178, 6, 106, 26, 26, 26,
    26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 178, 6,
    106, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26,
    26, 26, 178, 6, 106, 26, 26, 26, 26, 22, 22, 22,
    22, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26,
    26, 26, 26, 26, 27, 27, 27, 27, 27, 27, 27, 27,
    27, 27, 27, 27, 179, 7, 107, 27, 27, 27, 27, 27,
    27, 27, 27, 27, 27, 27, 27, 27, 179, 7, 107, 27,
    27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27,
    179, 7, 107, 27, 27, 27, 27, 23, 23, 23, 23, 27,
    27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27,
    27, 27, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28,
    28, 28, 180, 8, 108, 28, 28, 28, 28, 28, 28, 28,
    28, 28, 28, 28, 28, 28, 180, 8, 108, 28, 28, 28,
    28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 180, 8,
    108, 28, 28, 28, 28, 24, 24, 24, 24, 28, 28, 28,
    28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28,
    29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29,
    181, 9, 109, 29, 29, 29, 29, 29, 29, 29, 29, 29,
    29, 29, 29, 29, 181, 9, 109, 29, 29, 29, 29, 29,
    29, 29, 29, 29, 29, 29, 29, 29, 181, 9, 109, 29,
    29, 29, 29, 25, 25, 25, 25, 29, 29, 29, 29, 29,
    29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 30, 30,
    30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 182, 10,
    110, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30,
    30, 30, 182, 10, 110, 30, 30, 30, 30, 30, 30, 30,
    30, 30, 30, 30, 30, 30, 182, 10, 110, 30, 30, 30,
    30, 26, 26, 26, 26, 30, 30, 30, 30, 30, 30, 30,
    30, 30, 30, 30, 30, 30, 30, 30, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 183, 11, 111, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    183, 11, 111, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 183, 11, 111, 31, 31, 31, 31, 27,
    27, 27, 27, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 32, 32, 0, 32, 32, 32,
    32, 32, 32, 32, 32, 184, 12, 112, 0, 120, 32, 32,
    32, 32, 32, 32, 32, 32, 32, 32, 184, 12, 112, 0,
    120, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 184,
    12, 112, 0, 120, 32, 32, 32, 28, 28, 28, 28, 32,
    32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32,
    32, 32, 33, 33, 1, 33, 33, 33, 33, 33, 33, 33,
    33, 185, 13, 113, 1, 121, 33, 33, 33, 33, 33, 33,
    33, 33, 33, 33, 185, 13, 113, 1, 121, 33, 33, 33,
    33, 33, 33, 33, 33, 33, 33, 185, 13, 113, 1, 121,
    33, 33, 33, 29, 29, 29, 29, 33, 33, 33, 33, 33,
    33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 34, 34,
    2, 34, 34, 34, 34, 34, 34, 34, 34, 186, 14, 114,
    2, 122, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34,
    186, 14, 114, 2, 122, 34, 34, 34, 34, 34, 34, 34,
    34, 34, 34, 186, 14, 114, 2, 122, 34, 34, 34, 30,
    30, 30, 30, 34, 34, 34, 34, 34, 34, 34, 34, 34,
    34, 34, 34, 34, 34, 34, 35, 35, 3, 35, 35, 35,
    35, 35, 35, 35, 35, 187, 15, 115, 3, 123, 35, 35,
    35, 35, 35, 35, 35, 35, 35, 35, 187, 15, 115, 3,
    123, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 187,
    15, 115, 3, 123, 35, 35, 35, 31, 31, 31, 31, 35,
    35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
    35, 35, 36, 36, 4, 36, 36, 36, 36, 36, 36, 36,
    36, 188, 16, 116, 4, 124, 36, 36, 36, 36, 36, 36,
    36, 36, 36, 36, 188, 16, 116, 4, 124, 36, 36, 36,
    36, 36, 36, 36, 36, 36, 36, 188, 16, 116, 4, 124,
    36, 36, 36, 32, 32, 32, 32, 36, 36, 36, 36, 36,
    36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 37, 37,
    5, 37, 37, 37, 37, 37, 37, 37, 37, 189, 17, 117,
    5, 125, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37,
    189, 17, 117, 5, 125, 37, 37, 37, 37, 37, 37, 37,
    37, 37, 37, 189, 17, 117, 5, 125, 37, 37, 37, 33,
    33, 33, 33, 37, 37, 37, 37, 37, 37, 37, 37, 37,
    37, 37, 37, 37, 37, 37, 38, 38, 6, 38, 38, 38,
    38, 38, 38, 38, 38, 190, 18, 118, 6, 126, 38, 38,
    38, 38, 38, 38, 38, 38, 38, 38, 190, 18, 118, 6,
    126, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 190,
    18, 118, 6, 126, 38, 38, 38, 34, 34, 34, 34, 38,
    38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38,
    38, 38, 39, 39, 7, 39, 39, 39, 39, 39, 39, 39,
    39, 191, 19, 119, 7, 127, 39, 39, 39, 39, 39, 39,
    39, 39, 39, 39, 191, 19, 119, 7, 127, 39, 39, 39,
    39, 39, 39, 39, 39, 39, 39, 191, 19, 119, 7, 127,
    39, 39, 39, 35, 35, 35, 35, 39, 39, 39, 39, 39,
    39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 40, 40,
    8, 40, 40, 40, 40, 40, 40, 40, 192, 20, 8, 128,
    40, 40, 40, 40, 40, 40, 40, 40, 40, 192, 20, 8,
    128, 40, 40, 40, 40, 40, 40, 40, 40, 40, 192, 20,
    8, 128, 40, 40, 40, 36, 36, 36, 36, 40, 40, 40,
    40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40,
    41, 41, 9, 41, 41, 41, 41, 41, 41, 41, 193, 21,
    9, 129, 41, 41, 41, 41, 41, 41, 41, 41, 41, 193,
    21, 9, 129, 41, 41, 41, 41, 41, 41, 41, 41, 41,
    193, 21, 9, 129, 41, 41, 41, 37, 37, 37, 37, 41,
    41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41,
    41, 41, 42, 42, 10, 42, 42, 42, 42, 42, 42, 42,
    194, 22, 10, 130, 42, 42, 42, 42, 42, 42, 42, 42,
    42, 194, 22, 10, 130, 42, 42, 42, 42, 42, 42, 42,
    42, 42, 194, 22, 10, 130, 42, 42, 42, 38, 38, 38,
    38, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42,
    42, 42, 42, 42, 43, 43, 11, 43, 43, 43, 43, 43,
    43, 43, 195, 23, 11, 131, 43, 43, 43, 43, 43, 43,
    43, 43, 43, 195, 23, 11, 131, 43, 43, 43, 43, 43,
    43, 43, 43, 43, 195, 23, 11, 131, 43, 43, 43, 39,
    39, 39, 39, 43, 43, 43, 43, 43, 43, 43, 43, 43,
    43, 43, 43, 43, 43, 43, 44, 44, 12, 44, 44, 44,
    44, 44, 44, 44, 196, 24, 12, 132, 44, 44, 44, 44,
    44, 44, 44, 44, 44, 196, 24, 12, 132, 44, 44, 44,
    44, 44, 44, 44, 44, 44, 196, 24, 12, 132, 44, 44,
    44, 40, 40, 40, 40, 44, 44, 44, 44, 44, 44, 44,
    44, 44, 44, 44, 44, 44, 44, 44, 45, 45, 13, 45,
    45, 45, 45, 45, 45, 45, 197, 25, 13, 133, 45, 45,
    45, 45, 45, 45, 45, 45, 45, 197, 25, 13, 133, 45,
    45, 45, 45, 45, 45, 45, 45, 45, 197, 25, 13, 133,
    45, 45, 45, 41, 41, 41, 41, 45, 45, 45, 45, 45,
    45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 46, 46,
    14, 46, 46, 46, 46, 46, 46, 46, 198, 26, 14, 134,
    46, 46, 46, 46, 46, 46, 46, 46, 46, 198, 26, 14,
    134, 46, 46, 46, 46, 46, 46, 46, 46, 46, 198, 26,
    14, 134, 46, 46, 46, 42, 42, 42, 42, 46, 46, 46,
    46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46,
    47, 47, 15, 47, 47, 47, 47, 47, 47, 47, 199, 27,
    15, 135, 47, 47, 47, 47, 47, 47, 47, 47, 47, 199,
    27, 15, 135, 47, 47, 47, 47, 47, 47, 47, 47, 47,
    199, 27, 15, 135, 47, 47, 47, 43, 43, 43, 43, 47,
    47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47,
    47, 47, 48, 48, 16, 48, 48, 48, 48, 48, 48, 48,
    200, 28, 16, 136, 48, 48, 48, 48, 48, 48, 48, 48,
    48, 200, 28, 16, 136, 48, 48, 48, 48, 48, 48, 48,
    48, 48, 200, 28, 16, 136, 48, 48, 48, 44, 44, 44,
    44, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48,
    48, 48, 48, 48, 49, 49, 17, 49, 49, 49, 49, 49,
    49, 49, 201, 29, 17, 137, 49, 49, 49, 49, 49, 49,
    49, 49, 49, 201, 29, 17, 137, 49, 49, 49, 49, 49,
    49, 49, 49, 49, 201, 29, 17, 137, 49, 49, 49, 45,
    45, 45, 45, 49, 49, 49, 49, 49, 49, 49, 49, 49,
    49, 49, 49, 49, 49, 49, 50, 50, 18, 50, 50, 50,
    50, 50, 50, 50, 202, 30, 18, 138, 50, 50, 50, 50,
    50, 50, 50, 50, 50, 202, 30, 18, 138, 50, 50, 50,
    50, 50, 50, 50, 50, 50, 202, 30, 18, 138, 50, 50,
    50, 46, 46, 46, 46, 50, 50, 50, 50, 50, 50, 50,
    50, 50, 50, 50, 50, 50, 50, 50, 51, 51, 19, 51,
    51, 51, 51, 51, 51, 51, 203, 31, 19, 139, 51, 51,
    51, 51, 51, 51, 51, 51, 51, 203, 31, 19, 139, 51,
    51, 51, 51, 51, 51, 51, 51, 51, 203, 31, 19, 139,
    51, 51, 51, 47, 47, 47, 47, 51, 51, 51, 51, 51,
    51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 52, 52,
    20, 52, 52, 52, 52, 52, 52, 52, 204, 32, 20, 140,
    52, 52, 52, 52, 52, 52, 52, 52, 52, 204, 32, 20,
    140, 52, 52, 52, 52, 52, 52, 52, 52, 52, 204, 32,
    20, 140, 52, 52, 52, 48, 48, 48, 48, 52, 52, 52,
    52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52,
    53, 53, 21, 53, 53, 53, 53, 53, 53, 53, 205, 33,
    21, 141, 53, 53, 53, 53, 53, 53, 53, 53, 53, 205,
    33, 21, 141, 53, 53, 53, 53, 53, 53, 53, 53, 53,
    205, 33, 21, 141, 53, 53, 53, 49, 49, 49, 49, 53,
    53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53,
    53, 53, 54, 54, 22, 54, 54, 54, 54, 54, 54, 54,
    206, 34, 22, 142, 54, 54, 54, 54, 54, 54, 54, 54,
    54, 206, 34, 22, 142, 54, 54, 54, 54, 54, 54, 54,
    54, 54, 206, 34, 22, 142, 54, 54, 54, 50, 50, 50,
    50, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54,
    54, 54, 54, 54, 55, 55, 23, 55, 55, 55, 55, 55,
    55, 55, 207, 35, 23, 143, 55, 55, 55, 55, 55, 55,
    55, 55, 55, 207, 35, 23, 143, 55, 55, 55, 55, 55,
    55, 55, 55, 55, 207, 35, 23, 143, 55, 55, 55, 51,
    51, 51, 51, 55, 55, 55, 55, 55, 55, 55, 55, 55,
    55, 55, 55, 55, 55, 55, 56, 56, 24, 56, 56, 56,
    56, 56, 56, 56, 208, 36, 24, 144, 56, 56, 56, 56,
    56, 56, 56, 56, 56, 208, 36, 24, 144, 56, 56, 56,
    56, 56, 56, 56, 56, 56, 208, 36, 24, 144, 56, 56,
    56, 52, 52, 52, 52, 56, 56, 56, 56, 56, 56, 56,
    56, 56, 56, 56, 56, 56, 56, 56, 57, 57, 25, 57,
    57, 57, 57, 57, 57, 57, 209, 37, 25, 145, 57, 57,
    57, 57, 57, 57, 57, 57, 57, 209, 37, 25, 145, 57,
    57, 57, 57, 57, 57, 57, 57, 57, 209, 37, 25, 145,
    57, 57, 57, 53, 53, 53, 53, 57, 57, 57, 57, 57,
    57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 58, 58,
    26, 58, 58, 58, 58, 58, 58, 58, 210, 38, 26, 146,
    58, 58, 58, 58, 58, 58, 58, 58, 58, 210, 38, 26,
    146, 58, 58, 58, 58, 58, 58, 58, 58, 58, 210, 38,
    26, 146, 58, 58, 58, 54, 54, 54, 54, 58, 58, 58,
    58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58,
    59, 59, 27, 59, 59, 59, 59, 59, 59, 59, 211, 39,
    27, 147, 59, 59, 59, 59, 59, 59, 59, 59, 59, 211,
    39, 27, 147, 59, 59, 59, 59, 59, 59, 59, 59, 59,
    211, 39, 27, 147, 59, 59, 59, 55, 55, 55, 55, 59,
    59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59,
    59, 59, 60, 60, 28, 60, 60, 60, 60, 60, 60, 60,
    212, 40, 28, 148, 60, 60, 60, 60, 60, 60, 60, 60,
    60, 212, 40, 28, 148, 60, 60, 60, 60, 60, 60, 60,
    60, 60, 212, 40, 28, 148, 60, 60, 60, 56, 56, 56,
    56, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60,
    60, 60, 60, 60, 61, 61, 29, 61, 61, 61, 61, 61,
    61, 61, 213, 41, 29, 149, 61, 61, 61, 61, 61, 61,
    61, 61, 61, 213, 41, 29, 149, 61, 61, 61, 61, 61,
    61, 61, 61, 61, 213, 41, 29, 149, 61, 61, 61, 57,
    57, 57, 57, 61, 61, 61, 61, 61, 61, 61, 61, 61,
    61, 61, 61, 61, 61, 61, 62, 62, 30, 62, 62, 62,
    62, 62, 62, 62, 214, 42, 30, 150, 62, 62, 62, 62,
    62, 62, 62, 62, 62, 214, 42, 30, 150, 62, 62, 62,
    62, 62, 62, 62, 62, 62, 214, 42, 30, 150, 62, 62,
    62, 58, 58, 58, 58, 62, 62, 62, 62, 62, 62, 62,
    62, 62, 62, 62, 62, 62, 62, 62, 63, 63, 31, 63,
    63, 63, 63, 63, 63, 63, 215, 43, 31, 151, 63, 63,
    63, 63, 63, 63, 63, 63, 63, 215, 43, 31, 151, 63,
    63, 63, 63, 63, 63, 63, 63, 63, 215, 43, 31, 151,
    63, 63, 63, 59, 59, 59, 59, 63, 63, 63, 63, 63,
    63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 64, 64,
    64, 64, 64, 64, 64, 64, 64, 216, 44, 32, 152, 64,
    64, 64, 64, 64, 64, 64, 64, 64, 216, 44, 32, 152,
    64, 64, 64, 64, 64, 64, 64, 64, 64, 216, 44, 32,
    152, 64, 64, 64, 60, 60, 60, 60, 64, 64, 64, 64,
    64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 65,
    65, 65, 65, 65, 65, 65, 65, 65, 217, 45, 33, 153,
    65, 65, 65, 65, 65, 65, 65, 65, 65, 217, 45, 33,
    153, 65, 65, 65, 65, 65, 65, 65, 65, 65, 217, 45,
    33, 153, 65, 65, 65, 61, 61, 61, 61, 65, 65, 65,
    65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65,
    66, 66, 66, 66, 66, 66, 66, 66, 66, 218, 46, 34,
    154, 66, 66, 66, 66, 66, 66, 66, 66, 66, 218, 46,
    34, 154, 66, 66, 66, 66, 66, 66, 66, 66, 66, 218,
    46, 34, 154, 66, 66, 66, 62, 62, 62, 62, 66, 66,
    66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66,
    66, 67, 67, 67, 67, 67, 67, 67, 67, 67, 219, 47,
    35, 155, 67, 67, 67, 67, 67, 67, 67, 67, 67, 219,
    47, 35, 155, 67, 67, 67, 67, 67, 67, 67, 67, 67,
    219, 47, 35, 155, 67, 67, 67, 63, 63, 63, 63, 67,
    67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67,
    67, 67, 68, 68, 68, 68, 68, 68, 68, 68, 68, 220,
    48, 36, 156, 68, 68, 68, 68, 68, 68, 68, 68, 68,
    220, 48, 36, 156, 68, 68, 68, 68, 68, 68, 68, 68,
    68, 220, 48, 36, 156, 68, 68, 68, 64, 64, 64, 64,
    68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68,
    68, 68, 68, 69, 69, 69, 69, 69, 69, 69, 69, 69,
    221, 49, 37, 157, 69, 69, 69, 69, 69, 69, 69, 69,
    69, 221, 49, 37, 157, 69, 69, 69, 69, 69, 69, 69,
    69, 69, 221, 49, 37, 157, 69, 69, 69, 65, 65, 65,
    65, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69,
    69, 69, 69, 69, 70, 70, 70, 70, 70, 70, 70, 70,
    70, 222, 50, 38, 158, 70, 70, 70, 70, 70, 70, 70,
    70, 70, 222, 50, 38, 158, 70, 70, 70, 70, 70, 70,
    70, 70, 70, 222, 50, 38, 158, 70, 70, 70, 66, 66,
    66, 66, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70,
    70, 70, 70, 70, 70, 71, 71, 71, 71, 71, 71, 71,
    71, 71, 223, 51, 39, 159, 71, 71, 71, 71, 71, 71,
    71, 71, 71, 223, 51, 39, 159, 71, 71, 71, 71, 71,
    71, 71, 71, 71, 223, 51, 39, 159, 71, 71, 71, 67,
    67, 67, 67, 71, 71, 71, 71, 71, 71, 71, 71, 71,
    71, 71, 71, 71, 71, 71, 72, 72, 72, 72, 72, 72,
    72, 72, 72, 224, 52, 40, 160, 72, 72, 72, 72, 72,
    72, 72, 72, 72, 224, 52, 40, 160, 72, 72, 72, 72,
    72, 72, 72, 72, 72, 224, 52, 40, 160, 72, 72, 72,
    68, 68, 68, 68, 72, 72, 72, 72, 72, 72, 72, 72,
    72, 72, 72, 72, 72, 72, 72, 73, 73, 73, 73, 73,
    73, 73, 73, 73, 225, 53, 41, 161, 73, 73, 73, 73,
    73, 73, 73, 73, 73, 225, 53, 41, 161, 73, 73, 73,
    73, 73, 73, 73, 73, 73, 225, 53, 41, 161, 73, 73,
    73, 69, 69, 69, 69, 73, 73, 73, 73, 73, 73, 73,
    73, 73, 73, 73, 73, 73, 73, 73, 74, 74, 74, 74,
    74, 74, 74, 74, 74, 226, 54, 42, 162, 74, 74, 74,
    74, 74, 74, 74, 74, 74, 226, 54, 42, 162, 74, 74,
    74, 74, 74, 74, 74, 74, 74, 226, 54, 42, 162, 74,
    74, 74, 70, 70, 70, 70, 74, 74, 74, 74, 74, 74,
    74, 74, 74, 74, 74, 74, 74, 74, 74, 75, 75, 75,
    75, 75, 75, 75, 75, 75, 227, 55, 43, 163, 75, 75,
    75, 75, 75, 75, 75, 75, 75, 227, 55, 43, 163, 75,
    75, 75, 75, 75, 75, 75, 75, 75, 227, 55, 43, 163,
    75, 75, 75, 71, 71, 71, 71, 75, 75, 75, 75, 75,
    75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 76, 76,
    76, 76, 76, 76, 76, 76, 76, 228, 56, 44, 164, 76,
    76, 76, 76, 76, 76, 76, 76, 76, 228, 56, 44, 164,
    76, 76, 76, 76, 76, 76, 76, 76, 76, 228, 56, 44,
    164, 76, 76, 76, 72, 72, 72, 72, 76, 76, 76, 76,
    76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 77,
    77, 77, 77, 77, 77, 77, 77, 77, 229, 57, 45, 165,
    77, 77, 77, 77, 77, 77, 77, 77, 77, 229, 57, 45,
    165, 77, 77, 77, 77, 77, 77, 77, 77, 77, 229, 57,
    45, 165, 77, 77, 77, 73, 73, 73, 73, 77, 77, 77,
    77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77,
    78, 78, 78, 78, 78, 78, 78, 78, 78, 230, 58, 46,
    166, 78, 78, 78, 78, 78, 78, 78, 78, 78, 230, 58,
    46, 166, 78, 78, 78, 78, 78, 78, 78, 78, 78, 230,
    58, 46, 166, 78, 78, 78, 74, 74, 74, 74, 78, 78,
    78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78,
    78, 79, 79, 79, 79, 79, 79, 79, 79, 79, 231, 59,
    47, 167, 79, 79, 79, 79, 79, 79, 79, 79, 79, 231,
    59, 47, 167, 79, 79, 79, 79, 79, 79, 79, 79, 79,
    231, 59, 47, 167, 79, 79, 79, 75, 75, 75, 75, 79,
    79, 79, 79, 79, 79, 79, 79, 79, 79, 79, 79, 79,
    79, 79, 0, 72, 80, 80, 80, 80, 80, 80, 80, 80,
    232, 60, 48, 168, 80, 80, 80, 80, 80, 80, 80, 80,
    232, 60, 48, 168, 80, 80, 80, 80, 80, 80, 80, 80,
    232, 60, 48, 168, 80, 76, 76, 76, 76, 80, 80, 80,
    80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80,
    1, 73, 81, 81, 81, 81, 81, 81, 81, 81, 233, 61,
    49, 169, 81, 81, 81, 81, 81, 81, 81, 81, 233, 61,
    49, 169, 81, 81, 81, 81, 81, 81, 81, 81, 233, 61,
    49, 169, 81, 77, 77, 77, 77, 81, 81, 81, 81, 81,
    81, 81, 81, 81, 81, 81, 81, 81, 81, 81, 2, 74,
    82, 82, 82, 82, 82, 82, 82, 82, 234, 62, 50, 170,
    82, 82, 82, 82, 82, 82, 82, 82, 234, 62, 50, 170,
    82, 82, 82, 82, 82, 82, 82, 82, 234, 62, 50, 170,
    82, 78, 78, 78, 78, 82, 82, 82, 82, 82, 82, 82,
    82, 82, 82, 82, 82, 82, 82, 82, 3, 75, 83, 83,
    83, 83, 83, 83, 83, 83, 235, 63, 51, 171, 83, 83,
    83, 83, 83, 83, 83, 83, 235, 63, 51, 171, 83, 83,
    83, 83, 83, 83, 83, 83, 235, 63, 51, 171, 83, 79,
    79, 79, 79, 83, 83, 83, 83, 83, 83, 83, 83, 83,
    83, 83, 83, 83, 83, 83, 4, 76, 84, 84, 84, 84,
    84, 84, 84, 84, 236, 64, 52, 172, 84, 84, 84, 84,
    84, 84, 84, 84, 236, 64, 52, 172, 84, 84, 84, 84,
    84, 84, 84, 84, 236, 64, 52, 172, 84, 80, 80, 80,
    80, 84, 84, 84, 84, 84, 84, 84, 84, 84, 84, 84,
    84, 84, 84, 84, 5, 77, 85, 85, 85, 85, 85, 85,
    85, 85, 237, 65, 53, 173, 85, 85, 85, 85, 85, 85,
    85, 85, 237, 65, 53, 173, 85, 85, 85, 85, 85, 85,
    85, 85, 237, 65, 53, 173, 85, 81, 81, 81, 81, 85,
    85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85,
    85, 85, 6, 78, 86, 86, 86, 86, 86, 86, 86, 86,
    238, 66, 54, 174, 86, 86, 86, 86, 86, 86, 86, 86,
    238, 66, 54, 174, 86, 86, 86, 86, 86, 86, 86, 86,
    238, 66, 54, 174, 86, 82, 82, 82, 82, 86, 86, 86,
    86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86,
    7, 79, 87, 87, 87, 87, 87, 87, 87, 87, 239, 67,
    55, 175, 87, 87, 87, 87, 87, 87, 87, 87, 239, 67,
    55, 175, 87, 87, 87, 87, 87, 87, 87, 87, 239, 67,
    55, 175, 87, 83, 83, 83, 83, 87, 87, 87, 87, 87,
    87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 8, 80,
    88, 88, 88, 88, 88, 88, 88, 88, 0, 88, 208, 88,
    88, 88, 88, 88, 88, 88, 88, 0, 88, 208, 88, 88,
    88, 88, 88, 88, 88, 88, 0, 88, 208, 88, 84, 84,
    84, 84, 88, 88, 88, 88, 88, 88, 88, 88, 88, 88,
    88, 88, 88, 88, 88, 9, 81, 89, 89, 89, 89, 89,
    89, 89, 89, 1, 89, 209, 89, 89, 89, 89, 89, 89,
    89, 89, 1, 89, 209, 89, 89, 89, 89, 89, 89, 89,
    89, 1, 89, 209, 89, 85, 85, 85, 85, 89, 89, 89,
    89, 89, 89, 89, 89, 89, 89, 89, 89, 89, 89, 89,
    10, 82, 90, 90, 90, 90, 90, 90, 90, 90, 2, 90,
    210, 90, 90, 90, 90, 90, 90, 90, 90, 2, 90, 210,
    90, 90, 90, 90, 90, 90, 90, 90, 2, 90, 210, 90,
    86, 86, 86, 86, 90, 90, 90, 90, 90, 90, 90, 90,
    90, 90, 90, 90, 90, 90, 90, 11, 83, 91, 91, 91,
    91, 91, 91, 91, 91, 3, 91, 211, 91, 91, 91, 91,
    91, 91, 91, 91, 3, 91, 211, 91, 91, 91, 91, 91,
    91, 91, 91, 3, 91, 211, 91, 87, 87, 87, 87, 91,
    91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91,
    91, 91, 12, 84, 92, 92, 92, 92, 92, 92, 92, 92,
    4, 92, 212, 92, 92, 92, 92, 92, 92, 92, 92, 4,
    92, 212, 92, 92, 92, 92, 92, 92, 92, 92, 4, 92,
    212, 92, 88, 88, 88, 88, 92, 92, 92, 92, 92, 92,
    92, 92, 92, 92, 92, 92, 92, 92, 92, 13, 85, 93,
    93, 93, 93, 93, 93, 93, 93, 5, 93, 213, 93, 93,
    93, 93, 93, 93, 93, 93, 5, 93, 213, 93, 93, 93,
    93, 93, 93, 93, 93, 5, 93, 213, 93, 89, 89, 89,
    89, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93,
    93, 93, 93, 93, 14, 86, 94, 94, 94, 94, 94, 94,
    94, 94, 6, 94, 214, 94, 94, 94, 94, 94, 94, 94,
    94, 6, 94, 214, 94, 94, 94, 94, 94, 94, 94, 94,
    6, 94, 214, 94, 90, 90, 90, 90, 94, 94, 94, 94,
    94, 94, 94, 94, 94, 94, 94, 94, 94, 94, 94, 15,
    87, 95, 95, 95, 95, 95, 95, 95, 95, 7, 95, 215,
    95, 95, 95, 95, 95, 95, 95, 95, 7, 95, 215, 95,
    95, 95, 95, 95, 95, 95, 95, 7, 95, 215, 95, 91,
    91, 91, 91, 95, 95, 95, 95, 95, 95, 95, 95, 95,
    95, 95, 95, 95, 95, 95, 16, 88, 96, 96, 96, 96,
    96, 96, 96, 96, 8, 96, 216, 96, 96, 96, 96, 96,
    96, 96, 96, 8, 96, 216, 96, 96, 96, 96, 96, 96,
    96, 96, 8, 96, 216, 96, 92, 92, 92, 92, 96, 96,
    96, 96, 96, 96, 96, 96, 96, 96, 96, 96, 96, 96,
    96, 17, 89, 97, 97, 97, 97, 97, 97, 97, 97, 9,
    97, 217, 97, 97, 97, 97, 97, 97, 97, 97, 9, 97,
    217, 97, 97, 97, 97, 97, 97, 97, 97, 9, 97, 217,
    97, 93, 93, 93, 93, 97, 97, 97, 97, 97, 97, 97,
    97, 97, 97, 97, 97, 97, 97, 97, 18, 90, 98, 98,
    98, 98, 98, 98, 98, 98, 10, 98, 218, 98, 98, 98,
    98, 98, 98, 98, 98, 10, 98, 218, 98, 98, 98, 98,
    98, 98, 98, 98, 10, 98, 218, 98, 94, 94, 94, 94,
    98, 98, 98, 98, 98, 98, 98, 98, 98, 98, 98, 98,
    98, 98, 98, 19, 91, 99, 99, 99, 99, 99, 99, 99,
    99, 11, 99, 219, 99, 99, 99, 99, 99, 99, 99, 99,
    11, 99, 219, 99, 99, 99, 99, 99, 99, 99, 99, 11,
    99, 219, 99, 95, 95, 95, 95, 99, 99, 99, 99, 99,
    99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 20, 92,
    100, 100, 100, 100, 100, 100, 100, 100, 12, 100, 220, 100,
    100, 100, 100, 100, 100, 100, 100, 12, 100, 220, 100, 100,
    100, 100, 100, 100, 100, 100, 12, 100, 220, 100, 96, 96,
    96, 96, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
    100, 100, 100, 100, 100, 21, 93, 101, 101, 101, 101, 101,
    101, 101, 101, 13, 101, 221, 101, 101, 101, 101, 101, 101,
    101, 101, 13, 101, 221, 101, 101, 101, 101, 101, 101, 101,
    101, 13, 101, 221, 101, 97, 97, 97, 97, 101, 101, 101,
    101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101,
    22, 94, 102, 102, 102, 102, 102, 102, 102, 102, 14, 102,
    222, 102, 102, 102, 102, 102, 102, 102, 102, 14, 102, 222,
    102, 102, 102, 102, 102, 102, 102, 102, 14, 102, 222, 102,
    98, 98, 98, 98, 102, 102, 102, 102, 102, 102, 102, 102,
    102, 102, 102, 102, 102, 102, 102, 23, 95, 103, 103, 103,
    103, 103, 103, 103, 103, 15, 103, 223, 103, 103, 103, 103,
    103, 103, 103, 103, 15, 103, 223, 103, 103, 103, 103, 103,
    103, 103, 103, 15, 103, 223, 103, 99, 99, 99, 99, 103,
    103, 103, 103, 103, 103, 103, 103, 103, 103, 103, 103, 103,
    103, 103, 24, 104, 104, 104, 104, 104, 104, 104, 104, 16,
    104, 224, 104, 104, 104, 104, 104, 104, 104, 104, 16, 104,
    224, 104, 104, 104, 104, 104, 104, 104, 104, 16, 104, 224,
    104, 100, 100, 100, 100, 104, 104, 104, 104, 104, 104, 104,
    104, 104, 104, 104, 104, 104, 104, 104, 25, 105, 105, 105,
    105, 105, 105, 105, 105, 17, 105, 225, 105, 105, 105, 105,
    105, 105, 105, 105, 17, 105, 225, 105, 105, 105, 105, 105,
    105, 105, 105, 17, 105, 225, 105, 101, 101, 101, 101, 105,
    105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105,
    105, 105, 26, 106, 106, 106, 106, 106, 106, 106, 106, 18,
    106, 226, 106, 106, 106, 106, 106, 106, 106, 106, 18, 106,
    226, 106, 106, 106, 106, 106, 106, 106, 106, 18, 106, 226,
    106, 102, 102, 102, 102, 106, 106, 106, 106, 106, 106, 106,
    106, 106, 106, 106, 106, 106, 106, 106, 27, 107, 107, 107,
    107, 107, 19, 107, 227, 107, 107, 107, 107, 107, 19, 107,
    227, 107, 107, 107, 107, 107, 19, 107, 227, 107, 103, 103,
    103, 103, 107, 107, 107, 107, 107, 107, 107, 107, 107, 107,
    107, 107, 107, 107, 107, 28, 108, 108, 108, 108, 108, 20,
    108, 228, 108, 108, 108, 108, 108, 20, 108, 228, 108, 108,
    108, 108, 108, 20, 108, 228, 108, 104, 104, 104, 104, 108,
    108, 108, 108, 108, 108, 108, 108, 108, 108, 108, 108, 108,
    108, 108, 29, 109, 109, 109, 109, 109, 21, 109, 229, 109,
    109, 109, 109, 109, 21, 109, 229, 109, 109, 109, 109, 109,
    21, 109, 229, 109, 105, 105, 105, 105, 109, 109, 109, 109,
    109, 109, 109, 109, 109, 109, 109, 109, 109, 109, 109, 30,
    110, 110, 110, 110, 110, 22, 110, 230, 110, 110, 110, 110,
    110, 22, 110, 230, 110, 110, 110, 110, 110, 22, 110, 230,
    110, 106, 106, 106, 106, 110, 110, 110, 110, 110, 110, 110,
    110, 110, 110, 110, 110, 110, 110, 110, 31, 111, 111, 111,
    111, 111, 23, 111, 231, 111, 111, 111, 111, 111, 23, 111,
    231, 111, 111, 111, 111, 111, 23, 111, 231, 111, 107, 107,
    107, 107, 111, 111, 111, 111, 111, 111, 111, 111, 111, 111,
    111, 111, 111, 111, 111, 32, 112, 112, 112, 112, 112, 24,
    112, 232, 112, 112, 112, 112, 112, 24, 112, 232, 112, 112,
    112, 112, 112, 24, 112, 232, 112, 108, 108, 108, 108, 112,
    112, 112, 112, 112, 112, 112, 112, 112, 112, 112, 112, 112,
    112, 112, 33, 113, 113, 113, 113, 113, 25, 113, 233, 113,
    113, 113, 113, 113, 25, 113, 233, 113, 113, 113, 113, 113,
    25, 113, 233, 113, 109, 109, 109, 109, 113, 113, 113, 113,
    113, 113, 113, 113, 113, 113, 113, 113, 113, 113, 113, 34,
    114, 114, 114, 114, 114, 26, 114, 234, 114, 114, 114, 114,
    114, 26, 114, 234, 114, 114, 114, 114, 114, 26, 114, 234,
    114, 110, 110, 110, 110, 114, 114, 114, 114, 114, 114, 114,
    114, 114, 114, 114, 114, 114, 114, 114, 35, 115, 115, 115,
    115, 115, 27, 115, 235, 115, 115, 115, 115, 115, 27, 115,
    235, 115, 115, 115, 115, 115, 27, 115, 235, 115, 111, 111,
    111, 111, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115,
    115, 115, 115, 115, 115, 36, 116, 116, 116, 116, 116, 28,
    116, 236, 116, 116, 116, 116, 116, 28, 116, 236, 116, 116,
    116, 116, 116, 28, 116, 236, 116, 112, 112, 112, 112, 116,
    116, 116, 116, 116, 116, 116, 116, 116, 116, 116, 116, 116,
    116, 116, 37, 117, 117, 117, 117, 117, 29, 117, 237, 117,
    117, 117, 117, 117, 29, 117, 237, 117, 117, 117, 117, 117,
    29, 117, 237, 117, 113, 113, 113, 113, 117, 117, 117, 117,
    117, 117, 117, 117, 117, 117, 117, 117, 117, 117, 117, 38,
    118, 118, 118, 118, 118, 30, 118, 238, 118, 118, 118, 118,
    118, 30, 118, 238, 118, 118, 118, 118, 118, 30, 118, 238,
    118, 114, 114, 114, 114, 118, 118, 118, 118, 118, 118, 118,
    118, 118, 118, 118, 118, 118, 118, 118, 39, 119, 119, 119,
    119, 119, 31, 119, 239, 119, 119, 119, 119, 119, 31, 119,
    239, 119, 119, 119, 119, 119, 31, 119, 239, 119, 115, 115,
    115, 115, 119, 119, 119, 119, 119, 119, 119, 119, 119, 119,
    119, 119, 119, 119, 119, 40, 120, 120, 120, 120, 68, 56,
    176, 120, 120, 120, 68, 56, 176, 120, 120, 120, 68, 56,
    176, 120, 116, 116, 116, 116, 120, 120, 120, 120, 120, 120,
    120, 120, 120, 120, 120, 120, 120, 120, 120, 41, 121, 121,
    121, 121, 69, 57, 177, 121, 121, 121, 69, 57, 177, 121,
    121, 121, 69, 57, 177, 121, 117, 117, 117, 117, 121, 121,
    121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121,
    121, 42, 122, 122, 122, 122, 70, 58, 178, 122, 122, 122,
    70, 58, 178, 122, 122, 122, 70, 58, 178, 122, 118, 118,
    118, 118, 122, 122, 122, 122, 122, 122, 122, 122, 122, 122,
    122, 122, 122, 122, 122, 43, 123, 123, 123, 123, 71, 59,
    179, 123, 123, 123, 71, 59, 179, 123, 123, 123, 71, 59,
    179, 123, 119, 119, 119, 119, 123, 123, 123, 123, 123, 123,
    123, 123, 123, 123, 123, 123, 123, 123, 123, 44, 124, 124,
    124, 124, 72, 60, 180, 124, 124, 124, 72, 60, 180, 124,
    124, 124, 72, 60, 180, 124, 120, 120, 120, 120, 124, 124,
    124, 124, 124, 124, 124, 124, 124, 124, 124, 124, 124, 124,
    124, 45, 125, 125, 125, 125, 73, 61, 181, 125, 125, 125,
    73, 61, 181, 125, 125, 125, 73, 61, 181, 125, 121, 121,
    121, 121, 125, 125, 125, 125, 125, 125, 125, 125, 125, 125,
    125, 125, 125, 125, 125, 46, 126, 126, 126, 126, 74, 62,
    182, 126, 126, 126, 74, 62, 182, 126, 126, 126, 74, 62,
    182, 126, 122, 122, 122, 122, 126, 126, 126, 126, 126, 126,
    126, 126, 126, 126, 126, 126, 126, 126, 126, 47, 127, 127,
    127, 127, 75, 63, 183, 127, 127, 127, 75, 63, 183, 127,
    127, 127, 75, 63, 183, 127, 123, 123, 123, 123, 127, 127,
    127, 48, 0, 24, 48, 72, 96, 0, 0, 0, 128, 76,
    64, 184, 0, 0, 0, 128, 76, 64, 184, 0, 0, 0,
    128, 76, 64, 184, 128, 124, 124, 124, 124, 128, 128, 128,
    49, 1, 25, 49, 73, 97, 1, 1, 129, 77, 65, 185,
    1, 1, 1, 129, 77, 65, 185, 1, 1, 1, 129, 77,
    65, 185, 129, 125, 125, 125, 125, 129, 129, 129, 50, 2,
    26, 50, 74, 98, 2, 2, 130, 78, 66, 186, 2, 2,
    2, 130, 78, 66, 186, 2, 2, 2, 130, 78, 66, 186,
    130, 126, 126, 126, 126, 130, 130, 130, 51, 3, 27, 51,
    75, 99, 3, 3, 131, 79, 67, 187, 3, 3, 3, 131,
    79, 67, 187, 3, 3, 3, 131, 79, 67, 187, 131, 127,
    131, 131, 131, 52, 4, 28, 52, 76, 100, 4, 4, 132,
    80, 68, 188, 4, 4, 4, 132, 80, 68, 188, 4, 4,
    4, 132, 80, 68, 188, 132, 128, 132, 132, 132, 53, 5,
    29, 53, 77, 101, 5, 133, 81, 69, 189, 5, 5, 133,
    81, 69, 189, 5, 5, 133, 81, 69, 189, 133, 129, 133,
    133, 133, 54, 6, 30, 54, 78, 102, 6, 134, 82, 70,
    190, 6, 6, 134, 82, 70, 190, 6, 6, 134, 82, 70,
    190, 134, 130, 134, 134, 134, 55, 7, 31, 55, 79, 103,
    7, 135, 83, 71, 191, 7, 7, 135, 83, 71, 191, 7,
    7, 135, 83, 71, 191, 135, 131, 135, 135, 135, 56, 8,
    32, 56, 80, 104, 8, 136, 84, 72, 192, 8, 8, 136,
    84, 72, 192, 8, 8, 136, 84, 72, 192, 136, 132, 136,
    136, 136, 57, 9, 33, 57, 81, 105, 9, 137, 85, 73,
    193, 9, 9, 137, 85, 73, 193, 9, 9, 137, 85, 73,
    193, 137, 133, 137, 137, 137, 58, 10, 34, 58, 82, 106,
    10, 138, 86, 74, 194, 10, 10, 138, 86, 74, 194, 10,
    10, 138, 86, 74, 194, 138, 134, 138, 138, 138, 59, 11,
    35, 59, 83, 107, 11, 139, 87, 75, 195, 11, 11, 139,
    87, 75, 195, 11, 11, 139, 87, 75, 195, 139, 135, 139,
    139, 139, 60, 12, 36, 60, 84, 108, 12, 140, 88, 76,
    196, 12, 12, 140, 88, 76, 196, 12, 12, 140, 88, 76,
    196, 140, 136, 140, 140, 140, 61, 13, 37, 61, 85, 109,
    13, 141, 89, 77, 197, 13, 13, 141, 89, 77, 197, 13,
    13, 141, 89, 77, 197, 141, 137, 141, 141, 141, 62, 14,
    38, 62, 86, 110, 14, 142, 90, 78, 198, 14, 14, 142,
    90, 78, 198, 14, 14, 142, 90, 78, 198, 142, 138, 142,
    142, 142, 63, 15, 39, 63, 87, 111, 15, 143, 91, 79,
    199, 15, 15, 143, 91, 79, 199, 15, 15, 143, 91, 79,
    199, 143, 139, 143, 143, 143, 64, 16, 40, 64, 88, 112,
    0, 8, 0, 144, 92, 80, 200, 0, 144, 92, 80, 200,
    0, 144, 92, 80, 200, 144, 140, 144, 144, 144, 65, 17,
    41, 65, 89, 113, 1, 9, 1, 145, 93, 81, 201, 145,
    93, 81, 201, 145, 93, 81, 201, 0, 0, 7, 14, 21,
    28, 35, 42, 49, 56, 63, 70, 77, 84, 91, 98, 105,
    112, 119, 141, 0, 0, 0, 0, 66, 18, 42, 66, 90,
    114, 2, 10, 2, 146, 94, 82, 202, 146, 94, 82, 202,
    146, 94, 82, 202, 1, 8, 15, 22, 29, 36, 43, 50,
    57, 64, 71, 78, 85, 92, 99, 106, 113, 120, 142, 1,
    67, 19, 43, 67, 91, 115, 3, 11, 3, 147, 95, 83,
    203, 147, 95, 83, 203, 147, 95, 83, 203, 2, 9, 16,
    23, 30, 37, 44, 51, 58, 65, 72, 79, 86, 93, 100,
    107, 114, 121, 143, 2, 68, 20, 44, 68, 92, 116, 4,
    12, 4, 148, 96, 84, 204, 148, 96, 84, 204, 148, 96,
    84, 204, 3, 10, 17, 24, 31, 38, 45, 52, 59, 66,
    73, 80, 87, 94, 101, 108, 115, 122, 144, 3, 69, 21,
    45, 69, 93, 117, 5, 13, 149, 97, 85, 205, 149, 97,
    85, 205, 149, 97, 85, 205, 4, 11, 18, 25, 32, 39,
    46, 53, 60, 67, 74, 81, 88, 95, 102, 109, 116, 123,
    0, 0, 4, 70, 22, 46, 70, 94, 118, 6, 14, 150,
    98, 86, 206, 150, 98, 86, 206, 150, 98, 86, 206, 5,
    12, 19, 26, 33, 40, 47, 54, 61, 68, 75, 82, 89,
    96, 103, 110, 117, 124, 71, 23, 47, 71, 95, 119, 7,
    15, 151, 99, 87, 207, 151, 99, 87, 207, 151, 99, 87,
    207, 6, 13, 20, 27, 34, 41, 48, 55, 62, 69, 76,
    83, 90, 97, 104, 111, 118, 125,
};

static __device__ __constant__ uint8_t kDependencyCounts[130] = {
    0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1, 1,
    2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1,
    1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3,
    1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 3, 1, 1, 1, 1, 1, 1, 0, 2, 1,
    2, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1,
    2, 1, 2, 1, 1, 1, 1, 2, 1, 2, 1, 1,
    1, 1, 2, 1, 2, 1, 1, 1, 5, 2,
};

static __device__ __constant__ uint8_t kRoleMasks[130] = {
    9, 15, 9, 9, 11, 9, 15, 9, 15, 9, 15, 9,
    15, 9, 9, 15, 9, 15, 15, 9, 9, 15, 15, 15,
    9, 15, 9, 9, 15, 9, 15, 9, 15, 15, 9, 15,
    9, 15, 9, 9, 15, 9, 15, 15, 9, 9, 15, 15,
    15, 9, 15, 9, 9, 15, 9, 15, 9, 15, 15, 9,
    15, 9, 15, 9, 9, 15, 9, 15, 15, 9, 9, 15,
    15, 15, 9, 15, 9, 9, 15, 9, 15, 9, 15, 15,
    9, 15, 9, 9, 15, 15, 15, 15, 15, 11, 15, 15,
    9, 9, 9, 9, 11, 15, 15, 9, 9, 9, 9, 11,
    15, 15, 9, 9, 9, 9, 11, 15, 15, 9, 9, 9,
    9, 11, 15, 15, 9, 9, 9, 9, 1, 1,
};

static __device__ __constant__ uint16_t kSuccessorOffsets[131] = {
    0, 1, 2, 3, 4, 5, 8, 9, 10, 11, 12, 13,
    14, 15, 17, 19, 20, 21, 22, 23, 24, 25, 26, 27,
    28, 29, 30, 32, 34, 35, 36, 37, 38, 39, 40, 41,
    42, 43, 44, 46, 48, 49, 50, 51, 52, 53, 54, 55,
    56, 57, 58, 59, 61, 63, 64, 65, 66, 67, 68, 69,
    70, 71, 72, 73, 75, 77, 78, 79, 80, 81, 82, 83,
    84, 85, 86, 87, 88, 90, 92, 93, 94, 95, 96, 97,
    98, 99, 100, 101, 107, 112, 113, 114, 115, 116, 118, 119,
    120, 121, 122, 123, 124, 126, 127, 128, 129, 130, 131, 132,
    134, 135, 136, 137, 138, 139, 140, 142, 143, 144, 145, 146,
    147, 148, 150, 151, 152, 153, 154, 155, 156, 157, 157,
};

static __device__ __constant__ uint16_t kSuccessors[157] = {
    1, 2, 3, 5, 12, 6, 8, 10, 7, 21, 9, 46,
    11, 71, 13, 14, 24, 15, 18, 16, 17, 19, 20, 21,
    21, 22, 23, 24, 25, 26, 27, 36, 28, 33, 29, 30,
    31, 32, 36, 34, 35, 36, 37, 38, 39, 49, 40, 43,
    41, 42, 44, 45, 46, 46, 47, 48, 49, 50, 51, 52,
    61, 53, 58, 54, 55, 56, 57, 61, 59, 60, 61, 62,
    63, 64, 74, 65, 68, 66, 67, 69, 70, 71, 71, 72,
    73, 74, 75, 76, 77, 86, 78, 83, 79, 80, 81, 82,
    86, 84, 85, 86, 87, 88, 94, 101, 108, 115, 122, 89,
    90, 91, 92, 96, 103, 110, 117, 124, 94, 95, 128, 96,
    97, 98, 99, 100, 101, 102, 128, 103, 104, 105, 106, 107,
    108, 109, 128, 110, 111, 112, 113, 114, 115, 116, 128, 117,
    118, 119, 120, 121, 122, 123, 128, 124, 125, 126, 127, 129,
    129,
};

}  // namespace deepspec::v4_generated
